### ISSUE TITLE
Add a "clear queue" or "add and replace" button in Browse tab

### ISSUE THREAD

**Issue by archphile** [jcorporation/myMPD#10]
This is definitely  not a bug, but a feature I believe that will make myMPD use easier.

Le's say that I have some files loaded in queue and while browsing in order to add some new stuff, I want to get rid of the current queue and then load the new tracks.

With current myMPD implementation, I need to go back to **Queue** (and lose the last Browse state), press the "clear queue" button and then go back to **Browse** to add the files.

What I suggest is either:

- add a "clear queue" button in **Browse** mode, so that the user clears queue before loading new stuff
or
- add a button next to the existing that add the tracks that will "add and replace" to the queue. This way the user does what he wants with one click.

or

to implement both.

Greetings,
Mike

**Comment by jcorporation** [comment]
Thanks for that feature request. I do not think that a "clear queue" button in Browse mode is user friendly. Your second suggestion is better. I plan further actions on songs, to which the suggestion fits. I must evaluate the design for these advanced actions.

To save and restore states of the tabs has more priority and weakens this feature.

**Comment by archphile** [comment]
Thank you very much for your reply. Indeed the second suggestion is better.

One of my favorite Android clients (named MPD Remote) offers some interesting options:

- Add --> adds the desired file(s) at the end of the existing queue
- Enqueue --> adds the desired file(s) just right after the track is currently played
- Clear and Add --> clears queue and adds the new file(s)
- Clear, ddd and Play --> clears queue, adds the new file(s) and plays **(this is what I always use)**
- Add to stored playlist --> I have never tested it as I don't use MPD playlists, but I assume it does what it says

I just mentioned the above to give you some ideas on actions.

Greetings,
Mike

**Comment by jcorporation** [comment]
Exactly in this manner the advanced actions should work. Many thanks for your ideas.

**Comment by jcorporation** [comment]
The first advanced actions are now in master

**Comment by archphile** [comment]
Many thanks for that. Unfortunately I can't test because after building from latest master I am unable to add anything in queue both from filesystem and database.

Regards,
Mike

**Comment by Emilot** [comment]
From webradio folder you can "Append to queue" and "Replace queue" any .pls file(from the little sign on the right). From any other folder not. No errors at console.

**Comment by archphile** [comment]
I have the same experience with Emilot. I can only add pls files and nothing else. 

Should I open a separate bug report?

Regards,
Mike

**Comment by jcorporation** [comment]
I tested it again localy and I can't reproduce your issue. A seperate bug report would be good.
