### ISSUE TITLE
[UI Improvement]-Replace "root" in filebrowser

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPD#100]
I keep getting bugged by the "Root" in the file browser.

Maybe it could be replaced with an icon, like a folder or a home :

https://fontawesome.com/icons/folder?style=solid
https://fontawesome.com/icons/home?style=solid

Thanks

**Comment by jcorporation** [comment]
Is now replaced in devel. myMPD uses the material-icons font for symbols: https://material.io/tools/icons/
