### ISSUE TITLE
Feat: Add the possibility to select multiple songs and add actions for the selections

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#1001]
Discussed in https://github.com/jcorporation/myMPD/discussions/997

Add the possibility to select multiple songs and add actions for the selections.

## Refactor APIs

**Playlists**
- [x] Remove selection from playlist (MYMPD_API_PLAYLIST_CONTENT_RM_POSITIONS)
- [x] Move entries between playlists (MYMPD_API_PLAYLIST_CONTENT_MOVE_TO_PLAYLIST)
- Add selection to playlist
  - [x] MYMPD_API_PLAYLIST_CONTENT_APPEND_URIS
  - [x] MYMPD_API_PLAYLIST_CONTENT_INSERT_URIS
  - [x] MYMPD_API_PLAYLIST_CONTENT_REPLACE_URIS
  - [x] MYMPD_API_PLAYLIST_CONTENT_APPEND_ALBUMS
  - [x] MYMPD_API_PLAYLIST_CONTENT_INSERT_ALBUMS
  - [x] MYMPD_API_PLAYLIST_CONTENT_REPLACE_ALBUMS
  - [x] MYMPD_API_PLAYLIST_CONTENT_APPEND_ALBUM_DISC
  - [x] MYMPD_API_PLAYLIST_CONTENT_INSERT_ALBUM_DISC
  - [x] MYMPD_API_PLAYLIST_CONTENT_REPLACE_ALBUM_DISC
- [x] Remove playlists (MYMPD_API_PLAYLIST_RM)
- [x] Copy/Merge/Move playlists (MYMPD_API_PLAYLIST_COPY)

**Queue**
- [x] Remove selection from queue (MYMPD_API_QUEUE_RM_IDS)
- [x] Remove selection from jukebox queue (MYMPD_API_JUKEBOX_RM)
- Add selection to queue
  - [x] MYMPD_API_QUEUE_APPEND_URIS
  - [x] MYMPD_API_QUEUE_INSERT_URIS
  - [x] MYMPD_API_QUEUE_REPLACE_URIS
- Add multiple playlists to the queue
  - [x] MYMPD_API_QUEUE_APPEND_PLAYLISTS
  - [x] MYMPD_API_QUEUE_INSERT_PLAYLISTS
  - [x] MYMPD_API_QUEUE_REPLACE_PLAYLISTS
- Add multiple albums to the queue
  - [x] MYMPD_API_QUEUE_APPEND_ALBUMS
  - [x] MYMPD_API_QUEUE_INSERT_ALBUMS
  - [x] MYMPD_API_QUEUE_REPLACE_ALBUMS
  - [x] MYMPD_API_QUEUE_APPEND_ALBUM_DISC
  - [x] MYMPD_API_QUEUE_INSERT_ALBUM_DISC
  - [x] MYMPD_API_QUEUE_REPLACE_ALBUM_DISC
- Play selection after current song
  - [x] MYMPD_API_QUEUE_PRIO_SET
  - [x] MYMPD_API_QUEUE_PRIO_SET_HIGHEST
  - [x] MYMPD_API_QUEUE_MOVE_RELATIVE
- Webradio Favorites
  - [x] MYMPD_API_WEBRADIO_FAVORITE_RM

## Add multiple select action to views

- [x] Current queue
- [x] Jukebox queue
- [x] Playlists
- [x] Playlist detail
- [x] Search
- [x] Albums
- [x] Album detail
- [x] Filesystem
- [x] Radio favorites 
- [x] WebradioDB
- [x] Radiobrowser

**Comment by tobiasjakobi** [comment]
I would be very much interested in this feature. Currently playlist management in any of the MusicPD webclients I tried is less than optimal. Sending a selection of the playqueue to a new or existing playlist is something I use very often. Sadly only the abandoned Gnome client (GMPC) lets me do this efficiently.
