### ISSUE TITLE
choose ligature - ligatures to choose from are not visible

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1007]
myMPD version: 10.2.6

E.g.: Edit home icon -> choose Ligature
A ligatures is only visible under the mouse pointer (when hovering over it with the mouse), others appear to be shown in the the same colour as the background (not visible).
![ligatures_invisible](https://user-images.githubusercontent.com/75694230/227713001-782795dd-333e-4cf2-a023-c01a2b75e5f5.jpg)

**Comment by jcorporation** [comment]
Fixed in devel and ini the v10.3.0 branch.
