### ISSUE TITLE
Home icon added from webradios not editable

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1016]
myMPD version: 10.3.0 (12 Apr 2023)

When I add e.g. a playlist or a view of a album list as an icon to the home screen and then click on its name I can edit, duplicate or delete it (panel to the right pops out).
When I add a stream from webradios (or an album from the albumview) as home icon and do the same (click on its name) nothing happens (no panel, no possibility to edit).

Steps to reproduce:
1. Go to Browse/Webradios
2. Click on a stream on the right and "Add to homescreen"
3. Change to Home and click on the Name to edit the icon
4. No edit possible

Expected behavior:
Homeicon added from webradios or albums is editable like any other.

Server:
 - OS: Linux
 - OS version EL 8.7
 - Plattform: x86_64
 - MPD version: 0.23.12

Client:
 - Device: Laptop]
 - OS: Windows 10
 - Browser Firefox
 - Browser version 111.0.1 and 112.0 (64bit)
 - Browser Edge
 - Browser version 112.0.1722.39 (Official build) (64-bit)

**Comment by jcorporation** [comment]
Fixed, thanks for testing devel!
