### ISSUE TITLE
Queue list drag & drop: song disappears if drop on itself

### ISSUE THREAD

**Issue by Ezka77** [jcorporation/myMPD#1026]
myMPD version: devel bee1368

drag & drop an item on itself in the queue list make it disappears

before there is 12 songs in queue:

![image](https://github.com/jcorporation/myMPD/assets/1818604/1f3271c9-6dd7-4ba9-9bbe-10ac2809fa25)

next, after drag & drop the n°12 over itself:

![image](https://github.com/jcorporation/myMPD/assets/1818604/95174f5c-c512-445b-8bdc-0a3a08dc445a)

11 songs but the queue says 12, refresh the page and it comes back to 12.

**Server platform:**
- OS: alpine linux
- OS version: stable
- Platform: x86_64
- MPD version: 23.13

**Client platform:**
- Device: PC
- OS: Windows 10
- Browser: firefox
- Browser version: 113.0.1

**Comment by jcorporation** [comment]
Fixed also for table headers.
