### ISSUE TITLE
WebRadio function is not working

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#1031]
myMPD version: 10.3.3

**Describe the bug**

When i choose the Webradio option, it throws an error (see below)

**To Reproduce**

1. Go to webRadio option
2. Click on the Heart icon
3. See error

**Screenshots**

![mympd](https://github.com/jcorporation/myMPD/assets/18086896/04a5cd60-dfd8-4620-98e3-dc4a8dbc7675)

Thank you

**Comment by jcorporation** [comment]
Please add exact version to the bug report and the myMPD debug log.

**Comment by Emilot** [comment]
myMPD 10.3.3 (it happens also to previous version)

![mympd 2](https://github.com/jcorporation/myMPD/assets/18086896/9ecb51d5-00e3-4c09-b92e-7f857d2905d3)

p.s Second errors happen when i choose webradio option

**Comment by jcorporation** [comment]
Please set loglevel to debug and post new logs. Sure myMPD can access the internet and dns resolution works?

**Comment by Emilot** [comment]
![mympd 3](https://github.com/jcorporation/myMPD/assets/18086896/76346176-ac76-495e-a81c-bc4278ab1533)

i can ping anything from the Rpi i use...

**Comment by Emilot** [comment]
TLS is not enabled ?

**Comment by jcorporation** [comment]
Did you compile myMPD without ssl support?

**Comment by Emilot** [comment]
> Did you compile myMPD without ssl support?

Yes. I do not need ssl to my home network.

**Comment by jcorporation** [comment]
Ok, this is the issue. Next major release enforces compiled in ssl support. For the server it could be disabled. I forgot the requirement for clientside.

**Comment by Emilot** [comment]
Thank you JC!
