### ISSUE TITLE
Streaming works on desktop, fails on iPhone

### ISSUE THREAD

**Issue by toddfoster** [jcorporation/myMPD#1036]
myMPD version: 10.3.3 (built from source)

Streaming music via httpd is the stand-out feature I was looking for. It works great on my desktop client. On ios 15.7.6, using either Brave or Safari, the "Local playback" dialog reports "Error loading stream" when I hit play.

1. Go to 'http://myhost.local:port' (with myhost and port changed appropriately)
2. Start some music playing
3. Turn phone sideways to reveal "Local playback" button & hit it
4. Hit "play"

**Expected behavior**
Music playback through phone speaker/headset/etc.

**Server platform:**
 - OS: Ubuntu
 - OS version 22.05
 - Plattform: x86_64
 - MPD version: 10.3.3

**Client platform:**
 - Device: iPhone SE (old!)
 - OS: iOS 15.7.6
 - Browser: safari 
 - Browser version: (current version to iOS 15.7.6)

**Debug logs**
Don't know if they're useful, but I got several of these messages :
> 09:01:42 ERROR    webserver HTTP connection "85" failed

**Configuration**
I customized the port for mympd, but otherwise I believe the configuration is all default.

mpd.conf is very default as well, just added outputs for pulseaudio and httpd, according to https://help.ubuntu.com/community/MPD

**Additional context**
Streaming works as expected on desktop client running Brave.

**Comment by jcorporation** [comment]
You have read this: https://jcorporation.github.io/myMPD/references/local-playback

**Comment by toddfoster** [comment]
Argh, I totally missed that. You documented exactly my issue:
>     encoder     "lame" #to support safari on ios

Thank you!
