### ISSUE TITLE
Support separators in syscmds

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#104]
It would be great to support horizontal separators in syscmds!

**Comment by jcorporation** [comment]
You mean a simple horizontal line between two syscmd entries in the main menu?

**Comment by parkmino** [comment]
yeah, when I want to separatethe the streamimg urls and system commands such as reboot or shutdown.

**Comment by jcorporation** [comment]
That was easy to implement. Feature is now in devel. Create a file with name `HR` to insert a divider. I updated the wiki.
