### ISSUE TITLE
Run syscmds even when not connected

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#105]
It would be good to run syscmds when MPD is not avaiable.
Then users are still able to run syscmds e.g. shut down

**Comment by jcorporation** [comment]
Feature is now in devel.

**Comment by parkmino** [comment]
Thansk for implementing this feature.
However myMPD does not start without running mpd.
It is stuck at "Fetch MPD settings".
Anything to check on my side?

**Comment by jcorporation** [comment]
It could stuck 3 seconds or so.

**Comment by parkmino** [comment]
More than that and myMPD does not start.
What is your result "sudo mympd" without mpd, is it specific only for me?

**Comment by jcorporation** [comment]
It works for me with a inaccessible mpd socket, but I found a bug that can cause a issue, if myMPD connects over ip to mpd.

I fixed it in master. Can you give it another try?

If it doesn't work, output of myMPD in debug mode is usefull. Also check, if some javascript errors are displayed in the web console of your browser

**Comment by parkmino** [comment]
Yeah, it starts now without mpd.
Thanks!
