### ISSUE TITLE
Version 11.0.0 not running on Debian 12

### ISSUE THREAD

**Issue by avalx** [jcorporation/myMPD#1050]
myMPD version: [e.g. 11.0.0]

After updating the server from Debian 11 to 12 and compiling myMPD from sources it does nor run properly anymore. Compilation is successful and mympd service is running but when accessed via browser all I get is the splash screen and nothing more. On Debian 11 it was working OK and I was using it daily. Also the development version 10.3.3 runs fine on Debian 11 and 12.

**To Reproduce**

1. ./build.sh pkgdebian
2. dpkg -i ./package/mympd_11.0.0-1_amd64.deb
3.  systemctl daemon-reload
4.  sc restart mympd
5.  Access mympd via browser (http)
6. Splash screen is displayed and nothig more

**Expected behavior**

Getting the normal interface for myMPD

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: Debian
 - OS version 12
 - Plattform: [e.g. x86_64]
 - MPD version: 0.23.12

**Client plattform (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Browser version [e.g. 22]

**Debug logs (please attach if it can be useful)**

Look at https://jcorporation.github.io/myMPD/debug

root@jug:/var/lib/mympd# journalctl -fu mympd
Jun 27 14:56:39 jug mympd[289068]: INFO     mpdworker Update of smart playlist myMPDsmart-Genre-Funk skipped, already up to date
Jun 27 14:56:39 jug mympd[289068]: DEBUG    mpdworker Playlist myMPDsmart-Genre-Instrumental: playlist mtime 1687184902, smartpls mtime 1673347361
Jun 27 14:56:39 jug mympd[289068]: INFO     mpdworker Update of smart playlist myMPDsmart-Genre-Instrumental skipped, already up to date
Jun 27 14:56:39 jug mympd[289068]: NOTICE   mpdworker 0 smart playlists updated, 21 already up-to-date
Jun 27 14:56:39 jug mympd[289068]: DEBUG    mpdworker "!all!": Push websocket notify to queue: "{"jsonrpc":"2.0","method":"notify","params":{"facility":"playlist","severity":"info","message":"Smart playlists updated","data":{}}}"
Jun 27 14:56:39 jug mympd[289068]: INFO     mpdworker "default": Disconnecting from mpd
Jun 27 14:56:39 jug mympd[289068]: NOTICE   mpdworker Stopping mpd_worker thread
Jun 27 14:56:39 jug mympd[289068]: DEBUG    mpdworker Sticker cache is NULL not freeing anything
Jun 27 14:56:39 jug mympd[289068]: DEBUG    mpdworker Album cache is NULL not freeing anything
Jun 27 14:56:39 jug mympd[289068]: DEBUG    webserver No websocket client connected, discarding message: {"jsonrpc":"2.0","method":"notify","params":{"facility":"playlist","severity":"info","message":"Smart playlists updated","data":{}}}
Jun 27 14:56:51 jug mympd[289068]: DEBUG    webserver New connection id "2" from 10.55.66.111, connections: 2
Jun 27 14:56:51 jug mympd[289068]: INFO     webserver HTTP request (2): GET /ws/default
Jun 27 14:56:51 jug mympd[289068]: INFO     webserver "default": New Websocket connection established (2)
Jun 27 14:57:04 jug mympd[289068]: DEBUG    webserver New connection id "3" from 10.55.66.111, connections: 3
Jun 27 14:57:04 jug mympd[289068]: INFO     webserver HTTP request (3): GET /
Jun 27 14:57:04 jug mympd[289068]: INFO     webserver HTTP request (3): GET /css/combined.css
Jun 27 14:57:04 jug mympd[289068]: INFO     webserver HTTP request (3): GET /js/combined.js
Jun 27 14:57:04 jug mympd[289068]: DEBUG    webserver New connection id "4" from 10.55.66.111, connections: 4
Jun 27 14:57:04 jug mympd[289068]: INFO     webserver HTTP request (4): GET /assets/coverimage-mympd
Jun 27 14:57:04 jug mympd[289068]: DEBUG    webserver Sending 302 Found "/assets/coverimage-mympd.svg" to 4
Jun 27 14:57:07 jug mympd[289068]: INFO     webserver HTTP request (3): GET /
Jun 27 14:57:08 jug mympd[289068]: INFO     webserver HTTP request (4): GET /js/combined.js
Jun 27 14:57:08 jug mympd[289068]: INFO     webserver HTTP request (3): GET /css/combined.css
Jun 27 14:57:08 jug mympd[289068]: INFO     webserver HTTP request (3): GET /assets/coverimage-mympd
Jun 27 14:57:08 jug mympd[289068]: DEBUG    webserver Sending 302 Found "/assets/coverimage-mympd.svg" to 3
Jun 27 14:57:09 jug mympd[289068]: DEBUG    mympdapi  Timer with id 1 triggered
Jun 27 14:57:09 jug mympd[289068]: INFO     mympdapi  Start timer_handler_covercache_crop
Jun 27 14:57:09 jug mympd[289068]: DEBUG    mympdapi  "default": Leaving mpd idle mode
Jun 27 14:57:09 jug mympd[289068]: DEBUG    mympdapi  "default": Handle API request "MYMPD_API_COVERCACHE_CROP"
Jun 27 14:57:09 jug mympd[289068]: DEBUG    mympdapi  "default": MYMPD API request (-1)(0) MYMPD_API_COVERCACHE_CROP: {"jsonrpc":"2.0","id":0,"method":"MYMPD_API_COVERCACHE_CROP","params":{}}
Jun 27 14:57:09 jug mympd[289068]: NOTICE   mympdapi  Cleaning covercache "/var/cache/mympd/covercache"
Jun 27 14:57:09 jug mympd[289068]: DEBUG    mympdapi  Remove files older than 1685192229 sec
Jun 27 14:57:09 jug mympd[289068]: NOTICE   mympdapi  Deleted 0 files from covercache
Jun 27 14:57:09 jug mympd[289068]: DEBUG    mympdapi  "default": Entering mpd idle mode
Jun 27 14:57:16 jug mympd[289068]: DEBUG    webserver "default": Websocket message (2): ping

Firefox console:

Content Security Policy: Couldn’t process unknown directive ‘require-trusted-types-for’ jug.lan:88
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”). content.js:59:340
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:59:206
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:59:421
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. 3 jug.lan:88
Uncaught SyntaxError: unexpected token: identifier combined.js:13:346381
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:33:9

 
**Configuration (please attach if it can be useful)**

[myMPD.zip](https://github.com/jcorporation/myMPD/files/11882485/myMPD.zip)

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 

**Additional context**

The version 11.0.0 compiles and runs OK on Fedora 38!

**Comment by jcorporation** [comment]
I do not think this is a debian issue. Version 11.0.0 is very unstable at the moment.

Have you compiled the exact same snapshot of the codebase?

It seems to be a javascript error. Please look at combined.js line 13, column 346381 and paste it with some context here, a function block will be the best.

**Comment by jcorporation** [comment]
> Sorry, but I don't know where to find named file and how to do this?!

You can grab the content of this file with the help of the web developer tools. In the debugger you should se the combined.js file.

**Comment by avalx** [comment]
> > Sorry, but I don't know where to find named file and how to do this?!
> 
> You can grab the content of this file with the help of the web developer tools. In the debugger you should se the combined.js file.

I'll try to do that, but I'm not very familiar with web developer tools. And now I'm back to v10 of myMPD so I'll have to compile v11 again one of these days. I'll let you know how it goes.

**Comment by avalx** [comment]
I'm not sure if this is what might help here, but that's all I managed to do. If I try to see source in debugger new browser tab is opened with this content as in attachment (the last line is highlighted).


[a.zip](https://github.com/jcorporation/myMPD/files/11894098/a.zip)

**Comment by jcorporation** [comment]
There were missing semicolons. This type of bug is occurring only for minified release builds and release builds are not tested in the early stage of developing a new release. You should stick with latest stable version or at least the devel branch. Feature branches are always extremely unstable.

**Comment by avalx** [comment]
Great, thanks for quick fix.

Just out of curiosity, I'm wondering why was that not a problem on Fedora 38? Even without this fix, myMPD is working fine - as much as I can tell.
