### ISSUE TITLE
Support syscmds with arguments

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#106]
Is it possible to support user specified arguments in syscmds?
If I have gone too far, just forget about this ;-)

**Comment by jcorporation** [comment]
What is the usage szenario?

**Comment by parkmino** [comment]
It might be my crazy idead, anyway

1. In syscmds
"Input 1st argument"
"Input 2nd argument"
/path/command

2. Run the syscmd in myMPD and open the query window.
--------------------------
Input 1st argument
[                            ]
Input 2nd argument
[                            ]
[OK]          [Cancel]
--------------------------

3. Result - Run command
/path/command "1st arg" "2nd arg"

Please close this issue, if it does not make sense.

**Comment by jcorporation** [comment]
That could be possible, but what is your use case? I want to keep the syscmds implementation rather simple.

**Comment by parkmino** [comment]
I would like to have arguments for username and password e.g. wifi connection, spotify or something like this.
Without arguments, syscmds usage will remain the same.
It is upto you whether to implement this or not as always.

**Comment by jcorporation** [comment]
I close this issue now. I won't work on this feature in the near future. myMPD is a mpd client, not a system configuration utility. But thanks for using myMPD and your feedback.
