### ISSUE TITLE
Jukbox doesn't respect "Last played older than" correctly

### ISSUE THREAD

**Issue by kp-org** [jcorporation/myMPD#1063]
myMPD version: 10.3.3

The Jukebox mode doesn't respect the option "Last played older than" with value of 24 hours reliable. It is the same for Artist or Album selection. Maybe offer combinations are effected as well.

Set locale to en-US and enable the Jukebox.

**Expected behavior**

Don't repeat an artist (/album) within 24 hours. And yes, there are enough artists (190 right now).

**Screenshots**
Jukebox settings:
![image](https://github.com/jcorporation/myMPD/assets/13482381/9b20ab5d-953d-482b-af8c-d49cb44e559e)

Here an example with my preferred en-US locale setting:
![image](https://github.com/jcorporation/myMPD/assets/13482381/46fb48a2-af9e-4282-968d-efaf23a1106f)
The same dates with de-DE locale:
![image](https://github.com/jcorporation/myMPD/assets/13482381/accf1bb4-0146-43ab-8fee-1244e48c52af)

**Server plattform (please complete the following information):**
 - OS: Linux
 - Plattform: x86_64
 - MPD version: 10.3.3 (and earlier)

**Comment by jcorporation** [comment]
"Enforce uniqueness" and "Last played older than" is not designed to work as you expect.

- "Enforce uniqueness" is only enforced within a range of the last 50 songs played
- "Last played older than" is a constraint for a single song.

**Comment by kp-org** [comment]
Thanks for your clarification, lets look forward to the 1.11 release.
