### ISSUE TITLE
Show ip address of myMPD server connection

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#107]
It will be helpful sometimes e.g. avahi

**Comment by jcorporation** [comment]
You mean the ip myMPD is lissening? Or the ip/ socket myMPD is connecting to mpd?

**Comment by parkmino** [comment]
The former

**Comment by jcorporation** [comment]
I found no easy and fast way to implement this and because it is maximal a nice to have, I would not implement this feature request.

**Comment by jcorporation** [comment]
Issue reopend. It seems this feature is more important than I expected
