### ISSUE TITLE
Play View - some tags not displayed since 10.0.1

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1076]
Since 11.0.2 (likely 10.0.1 too) tags like Conductor, Filetype and Date (probably others as well, not tested) are not displayed in the play view.

Screenshots

11.0.2:
![mympd-11 0 2](https://github.com/jcorporation/myMPD/assets/75694230/a910e71f-5ae3-43d9-9324-f71bfa8f3291)

11.1.0:
![mympd-11 1 0](https://github.com/jcorporation/myMPD/assets/75694230/13fb71c5-dbdd-4a77-aae3-fb2b098e4e5b)

10.3.3 (here they are displayed):
![mympd-10 3 3](https://github.com/jcorporation/myMPD/assets/75694230/3780c115-eeeb-4c41-a986-c854236e4c9b)

**Comment by jcorporation** [comment]
Thanks for reporting this bug. All tags that are not enabled for the browse view are not displayed. Should be fixed in the devel and in the v11.1.0 branches.
