### ISSUE TITLE
Support locale and multi language

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#108]
I would like to contribute Korean translation.

**Comment by jcorporation** [comment]
This feature is on the roadmap.

**Comment by parkmino** [comment]
It would be good to have the option to choose a language.

**Comment by koflesinge** [comment]
I would like to do the french translation

**Comment by jcorporation** [comment]
I am working in the locale branch on this feature. The general i18n functions are working and the frontend is translated to german. Now I am working on the backend to emit translatable messages to the frontend.

For each language there are now separate text files with a simple syntax in the directory src/i18n/. A perl script creates a javascipt / json file from this files (called by mkdebug.sh and mkrelease.sh).

The syntax of this translation files is described in the wiki: https://github.com/jcorporation/myMPD/wiki/Translating

**Comment by parkmino** [comment]
Thanks a lot for your effort! ;-)

Yeah, I have been checking the locale branch from time to time.
Please let me know when it is ready to add Korean translation.
A couple of days would be enough for me to translate and I am considering to opening another issue to attached ko-KR.txt file.
PR seems too much for me only to upload the translated file.

**Comment by jcorporation** [comment]
My german translation is now finished. You can use the de-DE.txt file to translate myMPD in your language. Attaching a ko-KR.txt file is good enough, I can add it to the repository.

**Comment by parkmino** [comment]
OK and I will statrt the translation.

**Comment by parkmino** [comment]
Hmm... I translated the Korean and tried to test,
however the following error message shows up in build.

```
[ 20%] Building C object CMakeFiles/mympd.dir/src/mpd_client.c.o
/home/parkmino/Downloads/mpd/mympd/myMPD-master/src/mpd_client.c: In function ‘mpd_client_search_adv’:
/home/parkmino/Downloads/mpd/mympd/myMPD-master/src/mpd_client.c:3141:12: error: invalid type argument of unary ‘*’ (have ‘int’)
     (void) *sortdesc;
            ^~~~~~~~~
/home/parkmino/Downloads/mpd/mympd/myMPD-master/src/mpd_client.c:3144:12: error: invalid type argument of unary ‘*’ (have ‘unsigned int’)
     (void) *offset;
            ^~~~~~~
CMakeFiles/mympd.dir/build.make:110: recipe for target 'CMakeFiles/mympd.dir/src/mpd_client.c.o' failed
make[2]: *** [CMakeFiles/mympd.dir/src/mpd_client.c.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mympd.dir/all' failed
make[1]: *** [CMakeFiles/mympd.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jcorporation** [comment]
This error should now be fixed.

**Comment by parkmino** [comment]
I put the translated ko-KR.txt file into i18n, however it is not listed in locale.
Is there anything to check on myside?

**Comment by jcorporation** [comment]
The translation files must be added manually to the select in index.html. Automatic inclusion of translation files in the compile step comes in the next days.

**Comment by jcorporation** [comment]
Should now work, put your file in the i18n folder before calling ./mkrelease.sh. Please note that you must the write the friendly language name in the first line of the translatation file.

**Comment by parkmino** [comment]
I do not see Korean still.
I separately run tojson.pl and put it in /usr/share/mympd/htdocs/js/i18n.min, then it woks.

**Comment by jcorporation** [comment]
mkrelease.sh now runs tojson.pl at build time.

**Comment by parkmino** [comment]
Finally it works!
Some translations seem missing as attached.

![2019-06-21-003024_1600x900_scrot](https://user-images.githubusercontent.com/12131158/59862409-b23db000-93bd-11e9-9419-e9d9936d2696.png)
![2019-06-21-003053_1600x900_scrot](https://user-images.githubusercontent.com/12131158/59862410-b23db000-93bd-11e9-9b2e-67f70ed431b5.png)
![2019-06-21-003159_1600x900_scrot](https://user-images.githubusercontent.com/12131158/59862411-b2d64680-93bd-11e9-9090-57237ef15629.png)

**Comment by jcorporation** [comment]
I added the missing hooks in source and the phrases to de-DE.txt.
Commits: 76a2ab640317a21db35d83e2ce74488149186ba8, bd05722221e3bf284cbc24751a5264628f67c036

**Comment by parkmino** [comment]
days/hours/minutes/seconds seems not to change properly according to the locale.

**Comment by parkmino** [comment]
One more missing translation found.

![2019-06-21-072921_1600x900_scrot](https://user-images.githubusercontent.com/12131158/59885518-838ffb80-93f6-11e9-8346-308dce2d4fbd.png)

**Comment by parkmino** [comment]
> days/hours/minutes/seconds translation seems not to change properly according to the locale.

Those should be appended to the relevant translation.
I added the days/hours/minutes/seconds translation to ko-KR.txt, it shows OK.

**Comment by jcorporation** [comment]
Error on my side. Last commit added: Days, Hours, Minutes, Seconds and Background phrases to translation framework.

**Comment by parkmino** [comment]
Thanks for your effort.
Please find the attached file for the Korean translation.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/3317681/ko-KR.txt)

I will close this issue at once, and open new one when any update is needed.

**Comment by jcorporation** [comment]
Your translation is now integrated in the repository. Thanks for your effort.
