### ISSUE TITLE
Error when adding a playlist to the queue while listing its contents

### ISSUE THREAD

**Issue by mgonzalezm** [jcorporation/myMPD#1087]
myMPD version: 11.0.3

When I'm browsing the contents of a playlists and try to append/insert/replace the queue with such playlist (using the drop down menu) I get the following error:

```
INFO     webserver HTTP request (78): POST /api/default
INFO     webserver "default": API request (78): MYMPD_API_QUEUE_REPLACE_PLAYLISTS
WARN     mympdapi  Invalid json object type for JSON path "$.params.plists": MJSON_TOK_STRING
ERROR    mympdapi  "default": Error processing method "MYMPD_API_QUEUE_REPLACE_PLAYLISTS"
```
![add-playlist-to-queue](https://github.com/jcorporation/myMPD/assets/11181196/d6576dae-dd38-4554-a516-ab619df1f45c)

But if you are one level up, browsing the list of playlists, then there is no problem and I can add the playlist ( and any other ) to the queue.

**Comment by jcorporation** [comment]
Regression of  #1001. Is now fixed in devel and 12.0.0 branch.

**Comment by mgonzalezm** [comment]
Hi, Sorry to bother

The same error is happening when trying to add any of the predefined smart playlists.

![smart-playlist](https://github.com/jcorporation/myMPD/assets/11181196/dde4ba8c-8270-4427-a935-e6bdf168decd)


Do you need me to create a new issue ?

**Comment by jcorporation** [comment]
New error -> new issue
