### ISSUE TITLE
Stream not filled in "add to playlist" pop up

### ISSUE THREAD

**Issue by matthiakl** [jcorporation/myMPD#1095]
myMPD version: 11.0.3

**Describe the bug**

In the "Add to playlist" window, the stream URL of the selected stream is not filled into the input field.
Also the "Add to" buttons do not wrap on small screens and overflow the pop up

**To Reproduce**

1. Play a stream
2. Right click the stream in the current playlist view
3. Select "Add to playlist"
4. Stream URL field is empty

**Expected behavior**

The Stream URL field should contain the URL of the selected stream

**Screenshots**

![Bildschirmfoto vom 2023-08-23 21-16-51](https://github.com/jcorporation/myMPD/assets/23122583/452e3158-d2d4-4a96-a3ca-d31c5d2edc41)

**Server plattform (please complete the following information):**
 - OS: Buildroot
 - OS version 2023.02
 - Plattform: Raspberry Pi 3
 - MPD version: 0.23.13

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Arch Linux
 - Browser Firefox
 - Browser version 116.0.2

**Comment by jcorporation** [comment]
It seems the modal is not populated correctly. Does it work for normal songs?

**Comment by matthiakl** [comment]
For normal songs there is no field showing the select song, but yes for them it works as expected.
Also when selecting "Add to homescreen" on a stream the URL is filled in.

**Comment by matthiakl** [comment]
I just noticed that in the picture the radio buttons do not respect the custom blue highlight color...

**Comment by jcorporation** [comment]
The color is fixed. I can not reproduce the primary issue. I tested with 11.0.4. Please test with this version again.

**Comment by matthiakl** [comment]
With v11.0.4 the stream URL is still empty.

**Comment by jcorporation** [comment]
Fixed in devel.
