### ISSUE TITLE
Trying to move a track from the context menu fails (Invalid API request)

### ISSUE THREAD

**Issue by animaldaydream** [jcorporation/myMPD#1101]
myMPD version: 11.0.5

**Describe the bug**

When using the contextual menu's option to move tracks through the queue, nothing happens and an error "Invalid API request" appears instead.

**To Reproduce**

1. Make a queue
2. Right click a song and hit "Move song"
3. Input a position and press "Move"
4. Error appears on the _Move song_ dialog.

**Expected behavior**

Song should be moved to position specified.

**Screenshots**
![imagen](https://github.com/jcorporation/myMPD/assets/78395839/5a99edc4-6bc6-40c6-85ac-71355814aec3)

**Server plattform (please complete the following information):**
 - OS: EndeavourOS
 - OS version: (This is a rolling release. Here's the output of `uname -a`.)
   - `Linux bqbqbq 6.4.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:37:46 +0000 x86_64 GNU/Linux`
 - Plattform: x86_64
 - MPD version: 0.23.13-3

**Client plattform (please complete the following information):**
 - Device:
   1. The same PC used as server
   2. Redmi Note 9 Pro
 - OS:
   1. Server's OS install
   2. Custom ROM; Paranoid Android 13
 - Browser:
   1. Firefox 117.0, and Brave 1.57.57 (64 bits, official build as this is a binary package)
   2. Brave (for Android) 1.57.57
 
**Debug logs (please attach if it can be useful)**
I don't believe the MPD logs show anything in them, but perhaps I failed at changing the loglevel.
Attention, however: I tried snooping on the socket connection as per instructions, but there was no data sent when I tried to move the track.
Finally: I'm so sorry, I had to remove audio filenames from the state directory's tarball. I can make a test MPD+myMPD setup later if this is a problem.

[mympd_move.log](https://github.com/jcorporation/myMPD/files/12519731/mympd_move.log)
[mpd_move.log](https://github.com/jcorporation/myMPD/files/12520035/mpd_move.log)
[mympd-browserconsole_move.log](https://github.com/jcorporation/myMPD/files/12520060/mympd-browserconsole_move.log)
[mympd-browsernetwork_move.log](https://github.com/jcorporation/myMPD/files/12520308/mympd-browsernetwork_move.log)

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
**Configuration (please attach if it can be useful)**

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf`
 
Apparently GitHub doesn't accept attachments of files with extensions `.conf` or `.tar`, so tarballs must be compressed with gzip and I had to rename `mpd.conf`

[mympd_config.tar.gz](https://github.com/jcorporation/myMPD/files/12520633/mympd_config.tar.gz)
[mympd_state.tar.gz](https://github.com/jcorporation/myMPD/files/12520634/mympd_state.tar.gz)
[mpd.txt](https://github.com/jcorporation/myMPD/files/12520638/mpd.txt)

---

### Discussed in https://github.com/jcorporation/myMPD/discussions/997

I think this feature rolled out in release v11.0.0 back in July, but I thought me having a Podman setup (using the Docker image) might have introduced more problems, so I didn't do anything until now. Now I hit a different bug which I had to troubleshoot, and decided to figure this one out too.

Anyway, this feature never worked for me.

I don't know how to troubleshoot this. But here's what I tried:

- I installed myMPD on the host instead. I'm using the Arch Linux package.
- I moved my music folders to a place myMPD could reach (which also didn't compromise my home folder's permissions).
  - It's under `/var/lib` and I made sure a shell from the `mympd` user could `cd`  onto it and list contents. I changed permissions recursively on my library for this.
- I only connect through a socket because the clients I need all support it, so I checked if that was the problem, but connecting through an IP address makes no difference.

**Comment by animaldaydream** [comment]
I just realized I didn't fill out the fields. I'll do that now.

**Comment by jcorporation** [comment]
The context menu action uses a not implemented api endpoint. Will be fixed for the upcoming v12.0.0 release.
