### ISSUE TITLE
sbuild does not update embedded assets?

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#1108]
nb: when I pull a new version, I usually do

```
git pull
./build.sh createassets
./build.sh sbuild_build
```

but it seems doing so in this case resulted in the incorrect js file being packaged in the resulting .deb package... 
should I do a `./build cleanup` beforehand ?

_Originally posted by @tsunulukai in https://github.com/jcorporation/myMPD/issues/1106#issuecomment-1722298329_

**Comment by jcorporation** [comment]
Running `./build cleanup` should not be a requirement. But it could be your issue. I do not use the sbuild_* function regularly.

Also `./build.sh createassets` must not be called manually. In current versions of myMPD cmake creates the assets and removes the object files with the embedded assets.

On each rebuild following both object files should be recompiled:
- src/CMakeFiles/mympd.dir/mympd_api/scripts.c.o
- src/CMakeFiles/mympd.dir/web_server/utility.c.o

**Comment by tsunulukai** [comment]
To ease the investigation, here's the complete script I use to compile dev builds for testing purposes:

```
#!/bin/bash

# Configure Build variables
export WORKDIR="/srv/WorkDir/builder/"
export DISTROS="bookworm"
export TARGETS="amd64"
export DEBIAN_MIRROR="http://ftp.de.debian.org/debian"

cd $WORKDIR

# Synchronize & cleanup myMPD repository with origin 
[ -d myMPD ] || git clone https://github.com/jcorporation/myMPD
cd myMPD
git checkout devel
git fetch origin
git reset --hard origin/devel
git clean -f

# Display build paramaters
VERSION=$(grep "  VERSION" CMakeLists.txt | sed 's/  VERSION //')
echo WorkDir: $WORKDIR
echo myMPD Version ${VERSION}
echo git commit $(git rev-parse HEAD)
echo ${DISTROS}-${TARGETS}/mympd_$VERSION-1_${TARGETS}.deb
#exit 1

# Build package
# ./build.sh createassets # Should not be required https://github.com/jcorporation/myMPD/issues/1108#issuecomment-1722302443
./build.sh sbuild_build

# Install package
dpkg -i builds/${DISTROS}-${TARGETS}/mympd_$VERSION-1_${TARGETS}.deb
systemctl daemon-reload
systemctl restart mympd

# Display build parameters
echo myMPD Version ${VERSION}
echo git commit $(git rev-parse HEAD)
echo ${DISTROS}-${TARGETS}/mympd_$VERSION-1_${TARGETS}.deb
```

**Comment by jcorporation** [comment]
Looks good for me. I see no reason why old assets are should be embedded. 

Does dpkg really upgrade the package, if the version does not change? I am not sure.

**Comment by tsunulukai** [comment]
When I initially tried, I only did a 'git pull' instead of the git checkout/fetch/reset/clean commands in the script, so it could be why I had the issue.

Is it expected for the myMPD repository to be entirely cleand up before trying a new build ? Or would you expect sbuild_build  to work without issue even if previous builds are possibly left artifacts behind?

**Comment by jcorporation** [comment]
sbuild_build does the cleanup itself. It calls the same function as cleanup.

**Comment by jcorporation** [comment]
I could not reproduce your issue, can I close it, or will you investigate further?

**Comment by tsunulukai** [comment]
Would it be possible for the embedded assets to display the built-time git commit# next to the version# in the about view ?
This way I could have a reliable way to check which version of the assets are compiled with the sbuild command... 
Otherwise, it's difficult to confirm a potential issue (last time I had a interface breaking bug that made it obvious, but it's currently not the case anymore....)

**Comment by jcorporation** [comment]
Not in the build process, because it is not guaranteed that git is installed or the git history is available. I can add the commit id in the `setversion` function, that updates the version number and the release date. I execute this always before a new release is published.

**Comment by jcorporation** [comment]
The displayed commit id will be always one commit behind the actual commit, because I must commit the file with the integrated commit id.
