### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#1117]
Thanks,

for the update I have added the FreeBSD build files and the rc script.

And I can confirm that the change you suggested for TIMER_ID_CACHES_CREATE works. I have added it to the commit with timerfd change. 
The albums are now correctly listed.

I have a couple of TODOs:

- [x] 1. add the documentation for FreeBSD build and some specific setup notes
- [x] 2. remove gettid usage in script thread, commit 39fe9ae
- [x] 3. create a header file and probably a macro with linux threadname to centralize that, commit 25eaf4c
- [x] 4. test if the __FreeBSD__ ifdefs are really needed in the socket.h headers.
- [x] 5. disable timers in user interface for FreeBSD <14, commit 9fc09d7

_Originally posted by @robertek in https://github.com/jcorporation/myMPD/issues/1114#issuecomment-1733117545_

**Comment by robertek** [comment]
The 3) and 4) are done. I will post another PR.

For the 2), I have found it uses gettid(2) syscall, which is Linux specific. And it is kernel wide unique value and I don't think there is a FreeBSD equivalent. The pthread_self() is not.
So it highly depends on what the id in the create_request() represents and if something else can be used.

https://github.com/jcorporation/myMPD/blob/9671a241d6e1f325dc5ab89c11e43e9423ab2334/src/mympd_api/scripts.c#L706

**Comment by robertek** [comment]
And adding an another item to the TODO list:

5) disable timers in user interface for FreeBSD <14

I will try to copy the way it is done for LUA.

**Comment by jcorporation** [comment]
The threadid is used to get the response from the async request.

**Comment by jcorporation** [comment]
I rebased the freebsd branch to current master (myMPD v12.1.0).

**Comment by robertek** [comment]
Sorry for my delays. I was tight on my time for few weeks recently. 

For the LUA support, I will not fix that now. It will need a deeper understanding of that and it may be easily disabled during the build process. I want to postpone it to the later phase.

What I think is the only thing that is missing before the merge to the master is the task 5, to disable the timers in UI.

**Comment by jcorporation** [comment]
> For the 2), I have found it uses gettid(2) syscall, which is Linux specific. And it is kernel wide unique value and I don't think there is a FreeBSD equivalent. The pthread_self() is not. So it highly depends on what the id in the create_request() represents and if something else can be used.
> 
> https://github.com/jcorporation/myMPD/blob/9671a241d6e1f325dc5ab89c11e43e9423ab2334/src/mympd_api/scripts.c#L706

This must be only an uniq identifier. I do not use pthread_self, because the pthread_t is an opaque type. For freebsd there is a [pthread_getthreadid_np](https://man.freebsd.org/cgi/man.cgi?query=pthread_getthreadid_np&sektion=3&format=html). This will do the job.

Add a central function to get the thread id.

**Comment by jcorporation** [comment]
I fixed 2) and 3) in the devel branch and rebased the freebsd branch to devel.

**Comment by robertek** [comment]
You were much faster than me :). I had some of the fixes in the queue but forget to PR. But when I looked in your fixes, I see yours are much better then my :). 

I will update the FreeBSD's Makefile to include the LUA for building. I have tested this couple days ago and it is working ok.

**Comment by jcorporation** [comment]
I will merge the freebsd into devel soon.

**Comment by robertek** [comment]
Yes, I agree. It is working very well now and I have nothing else to push.
