### ISSUE TITLE
myMPD refuses to start with IPv4 disabled

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1118]
myMPD version: 12.0.2

To Reproduce
IPv6 disabled (GRUB_CMDLINE_LINUX="... ipv6.disable=1"

myMPD fails at start with:

Sep 29 10:04:43 mpd8.hal9000.at mympd[2385]: NOTICE   mympd     Setting loglevel to ERROR
Sep 29 10:04:43 mpd8.hal9000.at mympd[2385]: 27cee  1 mongoose.c:4664:mg_open_listen socket: 97
Sep 29 10:04:43 mpd8.hal9000.at mympd[2385]: 27cee  1 mongoose.c:3713:mg_listen      Failed: http://[::]:80, errno 97
Sep 29 10:04:43 mpd8.hal9000.at mympd[2385]: EMERG    mympd     Can't bind to http://[::]:80
Sep 29 10:04:43 mpd8.hal9000.at mympd[2385]: Exiting erroneous, thank you for using myMPD
Sep 29 10:04:43 mpd8.hal9000.at systemd[1]: mympd.service: Main process exited, code=exited, status=1/FAILURE
Sep 29 10:04:43 mpd8.hal9000.at systemd[1]: mympd.service: Failed with result 'exit-code'.

(with IPv6 enabled it works flawless with it´s IPv4 address)

Expected behavior:

myMPD should use and require IPv4 only, if IPv6 is not available.
Currently it requires IPv6 at start even if later only IPv4 is used.

**Comment by GK-774** [comment]
I just read #1066 which might be connected to the issue.

With 12.0.2 now both wget commands give me the correct output ("<!DOCTYPE html><!--myMPD (c) 2018-2023 Juergen Mang <mail@jcgames.de>" if I have IPv6 enabled.

So the current status is:
IPv6 only works
IPv6 and IPv4 works
IPv4 only does not work (Can't start).

**Comment by jcorporation** [comment]
myMPD listens in its default configuration to [::]. Thats why IPv4 does not work. Simply run  ` echo "0.0.0.0" > /var/lib/mympd/config/http_host` to change this.
