### ISSUE TITLE
Honoring CMake Build Type

### ISSUE THREAD

**Issue by comburent** [jcorporation/myMPD#1119]
myMPD version: 12.0.2

**Describe the bug**

The option `MYMPD_STRIP_BINARY` is applied even when `RelWithDebInfo` is specified.
This is incorrect and technically this option is redundant as this should be the responsibility of `Release` or `MinSizeRel` build types.

**Comment by comburent** [comment]
Similarly, `MYMPD_DEBUG` is redundant as this can be covered by using the `Debug` build type.

Of tangential interest is the existence of `MYMPD_BUILD_TESTING`, IMO the tests should always be built as AFAIK they don't add any additional dependencies and building them is harmless as they're not executed as part of a release build.

The advantages in having them built automatically is that distributions that have _testing_ as part of their procedures will get legitimate results instead of the “dummy” test that always succeeds.
It might be worth mentioning which of the tests assume network connectivity and can be reasonably excluded by the packagers.
As a suggestion, the command `ctest --exclude-regex test_http_client` is used in Guix to skip this kind of check.

**Comment by jcorporation** [comment]
Using standard cmake build types is the way to go. I have not yet dealt with it in this way

myMPD v13 will respect this cmake build types. Is this feasible for you?

Menitioning @dvzrv as he is packaging myMPD for Arch.

- **Release, MinSizeRel**
  - Uses predefined compile and link options for a release build
  - Embed assets in binary
  - Strips binary
- **RelWithDebInfo**
  - Uses predefined compile and link options for a release build
  - Embed assets in binary
  - No debug output
- **Debug**
  - Uses predefined compile and link options for a debug build
  - Assets are served from the `htdocs` folder in the source directory
  - Debug output
- **None**
  - Use this option to set your own compile and link options

**Comment by comburent** [comment]
>     * **RelWithDebInfo**
>       
>       * Uses predefined compile and link options for a release build
>       * Embed assets in binary
>       * No debug output

By _debug output_ you're referring to the extra verbose logging messages right?

**Comment by jcorporation** [comment]
> By debug output you're referring to the extra verbose logging messages right?

correct

**Comment by comburent** [comment]
> > By debug output you're referring to the extra verbose logging messages right?
> 
> correct

I wonder, couldn't you use the syslog `debug` level instead? It should be easier to maintain than doing conditional compilation I think.

I also see that the _Debug_ build also does the asset part differently.
IMO I think myMPD shouldn't be embedding the assets in the binary by default (i.e. should be defaulting `MYMPD_EMBEDDED_ASSETS` to `OFF`) since this makes the daemon consume more memory needlessly.
I can see the value for embedding assets when building packages with less “clutter” is desired (for distributing self contained binaries) though any platform with a sane package manager shouldn't have trouble handling multiple files.

**Comment by jcorporation** [comment]
1) Most of the debug messages are enabled through the configureable debug level at runtime. 

2) Not embedding assets is designed only for development of myMPD. I like the design of a single binary. myMPD and the assets are small enough that the memory footprint does not matter.

**Comment by jcorporation** [comment]
I think the bug is fixed with above commit, closing this issue now.
