### ISSUE TITLE
Validation of value "" has failed

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#1123]
myMPD version: Noticed on 12.0.2, still an issue on the devel branch.

Clicking the "+" (right of the search field) and choosing "add to queue" (with or without "play") or "replace queue" (with or without "play) yields the above notification. Right clicking any file or folder, and picking either option works fine - only the plus button function fails.

I also get a "JavaScript error: TypeError: can't access property "classList", el is undefined (http://tonberry.local:8080/js/combined.js: 10932:9)" somewhere in there.

OS: Debian trixie/sid kernel 6.5.3-1
MPD: 0.23.12

Same behaviour on anything from Firefox for Linux to Chrome for Android.

Yellow stuff from debug log:

02:07:31 WARN     mympdapi  $.params.uris: Validation of value "" has failed
02:07:31 WARN     mympdapi  Iteration callback for path "$.params.uris" has failed
02:07:31 DEBUG    mympdapi  Push response to queue for connection 3: {"jsonrpc":"2.0","id":614417007,"error":{"method":"MYMPD_API_QUEUE_REPLACE_URIS","facility":"general","severity":"error","message":"Validation of value \"\" has failed","data":{"path":"$.params.uris"}}}

Can of course feed you more logs and info if necessary, but since the same functions work in other places, i bet you know what could be wrong.

All the best!

**Comment by jcorporation** [comment]
In which view occurs this?

**Comment by therion23** [comment]
Oops, sorry, forgot that: Browse -> Filesystem.

**Comment by jcorporation** [comment]
This bug reveals further issues with the "Add all" functionality for the filesystem view. Thanks for reporting this.

It should be resolved with 00bc132. This commit adds some new functionality, that will be released with myMPD v12.1.0 (current devel branch).

**Comment by jcorporation** [comment]
Thanks, this was an copy & paste error.

**Comment by therion23** [comment]
That works a lot better. Thank you, really seems all fixed now!
