### ISSUE TITLE
The version 12.0.4 doesn't show anymore the album cover larger than a limit whose value I'm still investigating

### ISSUE THREAD

**Issue by DoDiesis** [jcorporation/myMPD#1125]
myMPD version:12.0.4

**Describe the bug**
The version 12.0.4 doesn't show anymore the album cover in PNG format, while the JPEG covers are still correctly shown.
The cover image is neither shown in the Browse, nor in Playback section. 
Other MPD clients, freshly installed on my phone, show the cover.png images, as myMPD did before.

**To Reproduce**
Use whatever cover.png image file you prefer.

n.a.

**Expected behavior**
The image should be shown.
on of what you expected to happen.
The old versions showed the PNG cover images, too.

**Screenshots**
![image](https://github.com/jcorporation/myMPD/assets/76726999/b16f6f51-761f-4a6b-af6d-1c8d14de597c)
![image](https://github.com/jcorporation/myMPD/assets/76726999/a7ab4be3-8418-49a8-a54d-2f4114dff70e)

**Server plattform (please complete the following information):**
 - OS: Archlinux
 - OS version: 6.5.6
 - Plattform: x86_64]
 - MPD version: [e.g. 0.21.16]

**Client plattform (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS, Windows 10, Ubuntu Linux 19.10]
 - Browser: Firefox 118.0.1 and Chromium 118.0.5993.54
 - Browser version: 118.0.1/118.0.5993.54

** debug log **
[root@dodiesisx ~]# journalctl -fu mympd
Oct 09 20:30:06 dodiesisx mympd[629]: INFO     webserver "default": API request (37): MYMPD_API_DATABASE_ALBUM_LIST
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    mympdapi  "default": Leaving mpd idle mode
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    mympdapi  "default": Handle API request "MYMPD_API_DATABASE_ALBUM_LIST"
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    mympdapi  "default": MYMPD API request (37)(107801008) MYMPD_API_DATABASE_ALBUM_LIST: {"jsonrpc":"2.0","id":107801008,"method":"MYMPD_API_DATABASE_ALBUM_LIST","params":{"offset":0,"limit":100,"expression":"","sort":"AlbumArtist","sortdesc":false,"cols":["Artist","Album","AlbumArtist"]}}
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    mympdapi  Push response to queue for connection 37: {"jsonrpc":"2.0","id":107801008,"result":{"method":"MYMPD_API_DATABASE_ALBUM_LIST","data":[{"Type": "album","Artist":["Abalone Dots"],"Album":"Traveler","AlbumArtist":["Abalone Dots"],"AlbumId":"42dff4cf7ce122b1786ae3a7a7ee1b363f1ee8c5","Duration":2475,"LastModified":1609250320,"uri":"internal/gen/Abalone_Dots/Abalone_Dots-Traveler/01_Craighead_County_Sky.flac","Discs":1,"SongCount":11,"FirstSongUri":"internal/gen/Abalone_Dots/Abalone_Dots-Traveler/01_Craighead_County_Sky.flac"},{"Type": "album","Artist":["ABBA"],"Album":"Gold - Greatest Hits","AlbumArtist":["ABBA"],"AlbumId":"05aada02ea57f57820acd27fe5a05e27e7161416","Duration":4626,"LastModified":1609234491,"uri":"internal/gen/ABBA/ABBA-Gold_Greatest_Hits/01_Dancing_Queen.flac","Discs":1,"SongCount":19,"FirstSongUri":"internal/gen/ABBA/ABBA-Gold_Greatest_Hits/01_Dancing_Queen.flac"},{"Type": "album","Artist":["ABBA"],"Album":"More Gold - More ABBA Hits","AlbumArtist":["ABBA"],"AlbumId":"fc5316c...
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    mympdapi  "default": Entering mpd idle mode
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    webserver "default": Got API response for id "37"
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    webserver "default": Sending response to conn_id 37 (length: 50730): {"jsonrpc":"2.0","id":107801008,"result":{"method":"MYMPD_API_DATABASE_ALBUM_LIST","data":[{"Type": "album","Artist":["Abalone Dots"],"Album":"Traveler","AlbumArtist":["Abalone Dots"],"AlbumId":"42dff4cf7ce122b1786ae3a7a7ee1b363f1ee8c5","Duration":2475,"LastModified":1609250320,"uri":"internal/gen/Abalone_Dots/Abalone_Dots-Traveler/01_Craighead_County_Sky.flac","Discs":1,"SongCount":11,"FirstSongUri":"internal/gen/Abalone_Dots/Abalone_Dots-Traveler/01_Craighead_County_Sky.flac"},{"Type": "album","Artist":["ABBA"],"Album":"Gold - Greatest Hits","AlbumArtist":["ABBA"],"AlbumId":"05aada02ea57f57820acd27fe5a05e27e7161416","Duration":4626,"LastModified":1609234491,"uri":"internal/gen/ABBA/ABBA-Gold_Greatest_Hits/01_Dancing_Queen.flac","Discs":1,"SongCount":19,"FirstSongUri":"internal/gen/ABBA/ABBA-Gold_Greatest_Hits/01_Dancing_Queen.flac"},{"Type": "album","Artist":["ABBA"],"Album":"More Gold - More ABBA Hits","AlbumArtist":["ABBA"],"...
Oct 09 20:30:06 dodiesisx mympd[629]: DEBUG    webserver Sending 50730 bytes to 37
Oct 09 20:30:27 dodiesisx mympd[629]: DEBUG    webserver "default": Websocket message (32): ping
Oct 09 20:30:52 dodiesisx mympd[629]: DEBUG    webserver "default": Websocket message (32): ping

**Additional context**

Other MPD clients, freshly installed on my phone, show the cover.png images, as myMPD did before.

**Comment by jcorporation** [comment]
Your log shows not the relevant parts. Interessting snippet is:
```
20:48:00 INFO     webserver /myMPD/src/web_server/web_server.c:532: HTTP request (157): GET /albumart?offset=0&uri=Testfiles%2Fsylt%2FBuddy.mp3
20:48:00 DEBUG    webserver /myMPD/src/web_server/albumart.c:162: Handle albumart for uri "Testfiles/sylt/Buddy.mp3", offset 0
20:48:00 DEBUG    webserver /myMPD/src/web_server/utility.c:161: Searching image file for basename "/var/cache/mympd/covercache/6a91ecd32cd829730e79ab6b9e6f4302a969694e-0"
20:48:00 DEBUG    webserver /myMPD/src/web_server/utility.c:141: No covercache file found
20:48:00 DEBUG    webserver /myMPD/src/web_server/albumart.c:234: Absolut media_file: /home/juergen/musik/Testfiles/sylt/Buddy.mp3
20:48:00 DEBUG    webserver /myMPD/src/web_server/utility.c:161: Searching image file for basename "/home/juergen/musik/Testfiles/sylt/cover"
20:48:00 DEBUG    webserver /myMPD/src/web_server/utility.c:161: Searching image file for basename "/home/juergen/musik/Testfiles/sylt/folder"
20:48:00 DEBUG    webserver /myMPD/src/web_server/albumart.c:284: Serving file /home/juergen/musik/Testfiles/sylt/folder.png (image/png)
```

**Comment by DoDiesis** [comment]
Here is a log taken when loading the cover images. 
[root@dodiesisx ~]# journalctl -fu mympd
Oct 09 20:57:56 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:57:56 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:57:56 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:57:56 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:57:56 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:57:56 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:57:57 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:57:57 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:58:12 dodiesisx mympd[2033]: NOTICE   mympdapi  Cleaning covercache "/var/cache/mympd/covercache"
Oct 09 20:58:12 dodiesisx mympd[2033]: NOTICE   mympdapi  Deleted 0 files from covercache
Oct 09 20:58:36 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:58:41 dodiesisx mympd[2033]: NOTICE   mympdapi  Starting mpd_worker thread for MYMPD_API_CACHES_CREATE
Oct 09 20:58:41 dodiesisx mympd[2033]: NOTICE   mpdworker "default": Connecting to "localhost:6600"
Oct 09 20:58:41 dodiesisx mympd[2033]: NOTICE   mpdworker "default": Connected to MPD
Oct 09 20:58:41 dodiesisx mympd[2033]: WARN     mpdworker Can not create albumkey for uri "internal/noise/audiocheck.net_pink_96k_-3dBFS.wav", tags AlbumArtist and Artist are empty
Oct 09 20:58:41 dodiesisx mympd[2033]: WARN     mpdworker Can not create albumkey for uri "internal/noise/audiocheck.net_white_96k_-3dBFS.wav", tags AlbumArtist and Artist are empty
Oct 09 20:58:41 dodiesisx mympd[2033]: WARN     mpdworker "default": Skipped 2 songs for album cache
Oct 09 20:58:41 dodiesisx mympd[2033]: NOTICE   mpdworker Stopping mpd_worker thread
Oct 09 20:58:55 dodiesisx mympd[2033]: NOTICE   mympdapi  Cleaning covercache "/var/cache/mympd/covercache"
Oct 09 20:58:55 dodiesisx mympd[2033]: NOTICE   mympdapi  Deleted 0 files from covercache
Oct 09 20:58:59 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:01 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:02 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:02 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:02 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:02 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:02 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:02 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:03 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:03 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:03 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:03 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:03 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:03 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:04 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:04 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:04 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:25 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:26 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:27 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:29 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:29 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:29 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:29 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:30 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:31 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:31 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:31 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:33 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:34 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 20:59:34 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  "default": MPD protocol version: 0.23.5
Oct 09 21:00:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Disabling library feature, music directory not defined
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  "default": MPD supported tags: Artist Album AlbumArtist Title Track Name Genre Date Composer Performer Comment Disc
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  Enabled tag_list: Artist Album AlbumArtist Title Track Name Genre Composer Performer Disc
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  "default": Enabled tag_list_album: Artist Album AlbumArtist Genre Composer Performer
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  Enabled tag_list_search: Album AlbumArtist Artist Composer Genre Performer Title
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  Enabled tag_list_browse: Album AlbumArtist Artist Composer Genre Performer
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  Enabled smartpls_generate_tag_list: Genre
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  "default": Enabling partitions feature
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  "default": Enabling binarylimit feature
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  "default": Enabling delete playlist range feature
Oct 09 21:00:32 dodiesisx mympd[2033]: NOTICE   mympdapi  "default": Enabling position whence feature
Oct 09 21:00:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Disabling advanced queue feature, depends on mpd >= 0.24.0
Oct 09 21:00:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Disabling consume oneshot feature, depends on mpd >= 0.24.0
Oct 09 21:00:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Disabling playlist directory autoconfiguration feature, depends on mpd >= 0.24.0
Oct 09 21:00:32 dodiesisx mympd[2033]: WARN     mympdapi  "default": Disabling starts_with filter expression feature, depends on mpd >= 0.24.0
Oct 09 21:00:57 dodiesisx mympd[2033]: C0062BF0197F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:303:
Oct 09 21:00:57 dodiesisx mympd[2033]: ERROR    webserver 20009c 1 mongoose.c:403:mg_error        13 0x8 tls hs: rc -1, err 1
Oct 09 21:00:57 dodiesisx mympd[2033]: C0062BF0197F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:303:
Oct 09 21:00:57 dodiesisx mympd[2033]: ERROR    webserver 2000a9 1 mongoose.c:403:mg_error        15 0xb tls hs: rc -1, err 1
Oct 09 21:00:57 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:57 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:57 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:57 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:58 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:58 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:58 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:58 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:58 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:58 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:58 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:59 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:59 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:59 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:59 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:59 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding
Oct 09 21:00:59 dodiesisx mympd[2033]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding

**Comment by DoDiesis** [comment]
I further investigated.
The issue is related to the size of an image file being too big.
So it is not a matter of the file type, but of its size.
FOr example, a file 489960 byte long is too big.
But in the previous releases it was shown.

**Comment by DoDiesis** [comment]
I set the Binary limit to the maximum, but with no result:
![image](https://github.com/jcorporation/myMPD/assets/76726999/9950d528-fef2-468d-a1cc-e234d3293af3)

**Comment by DoDiesis** [comment]
A cover image 86548 bytes large is ok.
A cover image 307235 bytes large is not shown and the line

mympd[2094]: WARN     mympdapi  "default": Retrieved binary data is too large, discarding

is logged.

**Comment by jcorporation** [comment]
Yes, there is a limit of the max binary size myMPD accepts from MPD. The binary limit in the connection dialog is the setting for the chunk size and not for the maximum size myMPD accepts.

Commit d057047edc18ce9ca27a7afd4322e225a28b746e changes the maximum size erroneously from 5 MB to 256 kb.

**Comment by jcorporation** [comment]
Fix is in devel. Can you test?

**Comment by DoDiesis** [comment]
Tested.
Great!
It works.
