### ISSUE TITLE
Show control row to add the first disc of a multi-disc album

### ISSUE THREAD

**Issue by ThecaTTony** [jcorporation/myMPD#1126]
myMPD version: 12.0.4-1

**Describe the bug**

In multi-disc albums, the control row for adding the first disc is not shown, but the control rows for adding the second, third and so on are shown.

**To Reproduce**

1. Browse a multi-disc album
2. There is no control row to add the first disk

**Expected behavior**

The same control row should be displayed to add only the first disc of an album.

**Screenshots**

![Screenshot_2023-10-09-19-51-37-079_com vivaldi browser](https://github.com/jcorporation/myMPD/assets/6334401/05f116b0-39d6-40db-bb93-a7cef89d1075)
![Screenshot_2023-10-09-19-51-50-165_com vivaldi browser](https://github.com/jcorporation/myMPD/assets/6334401/4f6f7b44-08dd-4802-8527-3dba4058c39e)
![Screenshot_2023-10-09-19-51-50-165_com vivaldi browser](https://github.com/jcorporation/myMPD/assets/6334401/6af2a47f-fa30-4b9b-9f2c-95b36008bd1a)

**Server plattform:**
 - OS: ArchlinuxArm
 - OS version Rolling release
 - Plattform: armv7h
 - MPD version: 0.23.13-3

**Client plattform:**
 - Device: Android phone and PC
 - OS: Android 12 / Archlinux (x86_64)
 - Browser Vivaldi
 - Browser version 6.2.3110.143 / 6.2.3105.54

**Comment by jcorporation** [comment]
I can not reproduce this behavior. In my environment the first disc is displayed. Please grab the response for the MYMPD_API_DATABASE_ALBUM_DETAIL call via the webdeveloper tools and post it here.

**Comment by ThecaTTony** [comment]
Hi, I just want to clarify that the songs of disc 1 of a multi-disc album are listed, what is missing is the control row for that disc, which is highlighted in red for disc 2 of the example album.

![mympd_disc1_bug](https://github.com/jcorporation/myMPD/assets/6334401/1bf9ed02-cc95-4ff5-b441-484b8b52e58f)

[album_detail.json](https://github.com/jcorporation/myMPD/files/12864547/album_detail.json)

**Comment by jcorporation** [comment]
The discs tag in the response has the value 1. This is the reason, why the table does not start with a disc row. The discs are counted by the album cache creation process. Please force an update of the caches and check again. This issue can occur if the disc tag was not enabled at album cache creation time (a bug in former releases).

**Comment by ThecaTTony** [comment]
Thanks, just as you said, the forced cache update fixed it.

![mympd_disc1_bug_fixed](https://github.com/jcorporation/myMPD/assets/6334401/b14d2ab7-9a2c-4d3a-9646-2559651dae83)
