### ISSUE TITLE
Increase LINE_LENGTH_MAX

### ISSUE THREAD

**Issue by loop333** [jcorporation/myMPD#1129]
myMPD version: 12.0.4

**Describe the bug**

Error reading album_cache.json lines for 2 albums:

https://www.discogs.com/release/6368618-Various-Touched-Two

https://www.discogs.com/release/12945348-Various-Touched-3

which have line length 4044 and 6292 respectively 

**Expected behavior**

Increase LINE_LENGTH_MAX 8192

**Comment by jcorporation** [comment]
Fixed in devel. v13 saves the album cache in mpack format and does not have this issue.
