### ISSUE TITLE
Ubuntu package does not start

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#113]
I downloaded the new ubuntu package at https://download.opensuse.org/repositories/home:/jcorporation/xUbuntu_18.04/amd64/mympd_5.3.0-1_amd64.deb
It does not start showing the message "ERROR    Can't load plugin /usr/share/mympd/lib/libmympd_coverextract.so: /usr/share/mympd/lib/libmympd_coverextract.so: cannot open shared object file: No such file or directory"

No problem with the 5.3.0 release manually built.

**Comment by jcorporation** [comment]
It seems the debian packaging is broken. I will fix it as soon as possible.
