### ISSUE TITLE
replace special symbols in picture file names

### ISSUE THREAD

**Issue by loop333** [jcorporation/myMPD#1130]
myMPD version: 12.0.4

**Describe the bug**

Can’t show label picture for labels with special symbols, such as

Fax +49-69/450464

**Expected behavior**

replace / and others dangerous symbols to underscore, when searching for picture file

**Comment by jcorporation** [comment]
What do you mean with label pictures? tagart?

**Comment by loop333** [comment]
— begin quote
Pictures for other tags
The “Browse Database” grid view can display pictures for other tags than album also. To enable this simply create a directory with the tagname in the /var/lib/mympd/pics directory and put pictures with filename equal the tag value in this directory.
— end quote

**Comment by loop333** [comment]
mediafile = webserver_find_image_file(mediafile);

**Comment by jcorporation** [comment]
myMPD should replace the chars that the filename validation function rejects: `\a\b\f\n\r\t\v/\\`

**Comment by jcorporation** [comment]
Fix is in devel, can you test?

**Comment by loop333** [comment]
Yes, it works ) 

00:52:57 INFO     webserver HTTP request (8): GET /tagart?tag=Label&value=Fax%20%2B49-69%2F450464
00:52:57 DEBUG    webserver Handle tagart for "Label": "Fax +49-69_450464"
00:52:57 DEBUG    webserver Absolut media_file: /home/ha/PRG/mympd/workdir/pics/Label/Fax +49-69_450464
00:52:57 DEBUG    webserver Searching image file for basename "/home/ha/PRG/mympd/workdir/pics/Label/Fax +49-69_450464"
00:52:57 DEBUG    webserver Serving file /home/ha/PRG/mympd/workdir/pics/Label/Fax +49-69_450464.jpg (image/jpeg)

**Comment by jcorporation** [comment]
Great!

**Comment by loop333** [comment]
and for AlbumArtist:

00:54:48 INFO     webserver HTTP request (8): GET /tagart?tag=AlbumArtist&value=AC%2FDC
00:54:48 DEBUG    webserver Handle tagart for "AlbumArtist": "AC_DC"
00:54:48 DEBUG    webserver Absolut media_file: /home/ha/PRG/mympd/workdir/pics/AlbumArtist/AC_DC
00:54:48 DEBUG    webserver Searching image file for basename "/home/ha/PRG/mympd/workdir/pics/AlbumArtist/AC_DC"
00:54:48 DEBUG    webserver Serving file /home/ha/PRG/mympd/workdir/pics/AlbumArtist/AC_DC.jpg (image/jpeg)
