### ISSUE TITLE
can’t disable massive smartplaylist autogeneration

### ISSUE THREAD

**Issue by loop333** [jcorporation/myMPD#1131]
myMPD version: 12.0.4

**Describe the bug**

Can’t disable autogeneration of smart playlists for tag Genre

**To Reproduce**

1. Go to Setting / General / Smart playlists
2. Clear Genre in list of tags (clear all tags)
3. Restart myMPD
5. See that tag Genre is automatically checked again

**Expected behavior**

i want to disable massive smart playlists generation, but be able to periodically generate custom smart playlists

**Comment by jcorporation** [comment]
Setting the default to an empty list was scheduled for the v13 release. I cherry picked the commit into devel.
