### ISSUE TITLE
Pictures with "dangerous symbols" like dot, ampersand, slash ...

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#1136]
### Discussed in https://github.com/jcorporation/myMPD/discussions/1135

<div type='discussions-op-text'>

<sup>Originally posted by **kp-org** October 18, 2023</sup>
I'm using myMPD for a while now and it is the best I have found to fit my needs. Great work.

Unfortunately it seems #1130 breaks to read pictures which have the correct spelling. This is a bit annoying.

Until myMPD 12.0.4 all was fine for me so far, except that I have had one filename with a single quote which wasn't recognized correctly, beside other filenames of pictures with one ore more single quotes were displayed correctly. Not really sure why but I assume it's the length of the filename.

Right now a lot of (Album)Artist arts will no longer displayed. Using underscores in filenames isn't best practice and not really an option. There are better ways to deal with dots, slashes etc. in filenames. And what should be the definition of "dangerous symbols"? Dots, ampersand and many more are valid characters in filenames - even in the Windows world. 

Now, as #1130 was especially for replacing a slash: for AC/DC create  a directory AC and inside that a file DC.jpg. Or replace the slash with use an UTF-8 char (how about U+0B75). 

Please revert this change or make it at least configurable.

Beside that, having GitHub as communication channel only limits potential feedback to GitHub users ... just IMHO.
</div>

**Comment by jcorporation** [comment]
This is a bug. Only slashes should be replaced with underscores.

**Comment by jcorporation** [comment]
Fixed in devel.

**Comment by kp-org** [comment]
With 12.1.1 it seems that all works fine again. Beside pictures with a slash, but that's ok for me as I have only one artist here. Thanks for the quick fix.

**Comment by jcorporation** [comment]
Replacing the slash with an underscore should work. If not it is a bug. Feel free to open a new issue.
