### ISSUE TITLE
Jukebox not random after 30-40 songs

### ISSUE THREAD

**Issue by thaihugo** [jcorporation/myMPD#1142]
myMPD version: 13.0

Hi,

The jukebox function seems to revert to a set list of music (probably the alphabetic order in the database) after 40-50 songs. Playlist needs to be cleanup to restart a random set of 30 songs.

The number of tracks for the jukebox mode does not influence the fact that it acts weird after 40-50 songs

**To Reproduce**

The jukebox was setup and working normaly for the previous versions.
Jukebox set to song
Playlist: database
Keep queue length: 40 (20 will seems normal then display the bug after 20 songs)
Enforce uniqueness: song (you cannot set album, it goes back to song, another small bug I thing)
Song was played last:24
Ignore hated song on
no other setting.

The playlist last songs will soon become the same

It should be random of course even after 3 hours of play.

 - OS: Dietpi
 - OS version latest as of 31 october 2023
 - Plattform: raspberry pi 4
 - MPD version: 13.0

Please tell me if you need logs

Thanks

**Comment by thaihugo** [comment]
Also, It seems that to get a new track list, and not a grouped set of songs from alphabetical list, you need to respect certain conditions like changing one parameter in jukebox and saving, or clicking on clear queue in the arrow menu and not on the main button in the playlist view.

**Comment by jcorporation** [comment]
Thanks for reporting this. Both bugs should be fixed in devel. Can you test?

**Comment by thaihugo** [comment]
The devel branch is indeed solving the 2 bugs. A first try to 80 songs didn't display the unwanted behavior.
I can also see my selection for the unicity parameter.
Thanks a lot for this!
