### ISSUE TITLE
Feat: Add a maximum song duration for the jukebox

### ISSUE THREAD

**Issue by thaihugo** [jcorporation/myMPD#1146]
Hello,

As the minimum song duration is a well thought added function to the jukebox selection, may I ask for a maximum duration too, to filter those pesky one hour-one file mp3 albums that would get caught by the random process sometimes? 

Maybe it can be solved by an Exclude Expression, but I though it would make sense to have max if we have min duration.

Thanks for your consideration.

**Comment by jcorporation** [comment]
Implemented in the v13.1.0 branch.
