### ISSUE TITLE
Ubuntu 16.04.6 arm64 cannot build debian package

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#115]
Ubuntu 16.04.6 does not build showing the following error message.
Could you please advise me?

[ 66%] Building C object CMakeFiles/mympd.dir/dist/src/inih/ini.c.o
[ 73%] Linking C executable mympd
make[3]: Leaving directory '/root/myMPD-5.3.1/release'
[ 73%] Built target mympd
make[3]: Entering directory '/root/myMPD-5.3.1/release'
Scanning dependencies of target mympd_coverextract
make[3]: Leaving directory '/root/myMPD-5.3.1/release'
make[3]: Entering directory '/root/myMPD-5.3.1/release'
[ 80%] Building CXX object CMakeFiles/mympd_coverextract.dir/src/plugins/mympd_coverextract.cpp.o
/root/myMPD-5.3.1/src/plugins/mympd_coverextract.cpp: In function ‘bool write_base64_decoded(const string&, const string&)’:
/root/myMPD-5.3.1/src/plugins/mympd_coverextract.cpp:67:47: error: no matching function for call to ‘std::basic_ofstream<char>::open(const string&, const openmode&)’
     myfile.open(abs_tmp_file, ofstream::binary);
                                               ^
In file included from /root/myMPD-5.3.1/src/plugins/mympd_coverextract.cpp:20:0:
/usr/include/c++/5/fstream:799:7: note: candidate: void std::basic_ofstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       open(const char* __s,
       ^
/usr/include/c++/5/fstream:799:7: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’
CMakeFiles/mympd_coverextract.dir/build.make:62: recipe for target 'CMakeFiles/mympd_coverextract.dir/src/plugins/mympd_coverextract.cpp.o' failed
make[3]: *** [CMakeFiles/mympd_coverextract.dir/src/plugins/mympd_coverextract.cpp.o] Error 1
make[3]: Leaving directory '/root/myMPD-5.3.1/release'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mympd_coverextract.dir/all' failed
make[2]: *** [CMakeFiles/mympd_coverextract.dir/all] Error 2
make[2]: Leaving directory '/root/myMPD-5.3.1/release'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/myMPD-5.3.1/release'
debian/rules:7: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by jcorporation** [comment]
It is a problem with the c++ version that is installed on ubuntu 16.06.
Change line 67 in ```src/plugins/mympd_coverextract.cpp```
from
```
myfile.open(abs_tmp_file, ofstream::binary);
```
to
```
myfile.open(abs_tmp_file.c_str(), ofstream::binary);
```
should do the trick. 
If it works I include this patch in the next release.

**Comment by parkmino** [comment]
Yeah, your patch resolves this issue!
Please implement this in the next releases.
