### ISSUE TITLE
Linux build: debian postinst file does not fully handle the sysvinit script

### ISSUE THREAD

**Issue by nousernouser** [jcorporation/myMPD#1156]
myMPD version: [13.0.1]

**Describe the bug**

Building myMPD under Linux, the Debian postinst file (`DEBIAN/postinst`) does not fully handle the sysvinit script:
- `/etc/init.d/mympd` should have 755 permissions (running `chmod +x /etc/init.d/mympd`)
- the mympd init daemon should be "enabled" (running `/etc/update.rc.d` -f mympd defaults)

As a result, the mympd sysvinit daemon is neither recognized nor startable (being not executable).

**To Reproduce**

1. Install the myMPD deb package in a system which sysvinit is in use
2. Run `ls -la /etc/init.d/mympd`; no x permissions
3. Run `sudo service mympd start`: the daemon is unknown

**Expected behavior**
The mympd sysvinit daemon is succesful started after package installation and/or running  `sudo service mympd start`

**Additional context**

The Debian postinst file (`DEBIAN/postinst`)  should be similar to:

    #!/bin/sh
    set -e
    
    if ! command -v systemctl > /dev/null
    then
        # Add mympd user only for none-systemd installations
        echo "Checking status of mympd system user and group"
        getent group mympd > /dev/null || groupadd -r mympd
        getent passwd mympd > /dev/null || useradd -r -g mympd -s /bin/false -d /var/lib/mympd mympd
    else
        ! systemctl -q is-active mympd || systemctl stop mympd
        echo "Removing obsolet mympd user and group"
        ! getent passwd mympd > /dev/null || userdel mympd
        ! getent group mympd > /dev/null || groupdel mympd
    fi
    
    # Handle sysvinit daemon
    if [ -f /etc/init.d/mympd ]
    then
        chmod +x /etc/init.d/mympd
        update-rc.d -f mympd defaults
    fi
    
    exit 0

**Comment by jcorporation** [comment]
The x-bit should be better set in the packaging prozess.

Enabling the daemon at default was intentionally left out.

**Comment by jcorporation** [comment]
Strange: the cmake install script sets the x-bit.

**Comment by nousernouser** [comment]
In fact, that's as you pointed out. 

I redid a build from scratch, and the x-bit is present, then I regenerated the deb package and the x-bit is ok. 

It might have been some mistake on my part (although I can't figure out how) doing the test build I did before...     
Anyway it's ok. I humbly apologize. 

Just out of curiosity: you say that enabling the daemon at default was intentionally left out. Can I ask the reason for this choice? Thank you. Sorry again

PS: 

Another thing. I thought it would be a great improvement if `<workingdir>` and `<cachedir>` could be specified as build parameters (rather than being hardcoded), to allow installation in locations other than `/var/lib/mympd` and `/var/cache/mympd` -- e.g. `/opt/mympd` and `/opt/cache/mympd` or also `~/.mympd` and `~/.cache/mympd`. 

What do you think?

**Comment by jcorporation** [comment]
> Just out of curiosity: you say that enabling the daemon at default was intentionally left out. Can I ask the reason for this choice?

This is only my personal taste.

> Install location

You can use the standard `-DCMAKE_INSTALL_PREFIX=` option or use the myMPD command line options.

- https://jcorporation.github.io/myMPD/installation/compiling/cmake
- https://jcorporation.github.io/myMPD/configuration/command-line-options

Closing this issue now as invalid.
