### ISSUE TITLE
Value length for JSON path "$.params.albumid" is too short

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#1167]
myMPD 11.0.3, Debian trixie/sid x86_64, tested with Firefox on Debian and Edge on Win 11.

- Right click any song in your playback queue and pick "Song details".
- Left click on the album title.

Also happens in filesystem view, but not the database view. On rare occasions it jumps to the previous album looked at in database view mode instead of throwing the error.

Let me know if you need debug logs.

**Comment by jcorporation** [comment]
Fixed in devel, can you test?

**Comment by therion23** [comment]
Yup, that did the trick - at least i cannot reproduce any of the above anymore. Thanks once again!
