### ISSUE TITLE
Error when accessing myMPD in browser

### ISSUE THREAD

**Issue by padertux** [jcorporation/myMPD#1179]
I did compile the latest version 13.0.5 of myMPD. When I try to access it in the browser I do get following messages in the log: 

23:11:10 INFO     webserver HTTP request (3): GET /assets/i18n/en-US.json
23:11:10 ERROR    webserver HTTP 404: Embedded asset "/assets/i18n/en-US.json" not found
23:11:11 INFO     webserver HTTP request (4): GET /sw.js
23:11:11 INFO     webserver HTTP request (3): GET /sw.js
23:11:29 DEBUG    mympdapi  Timer with id 1 triggered
23:11:29 INFO     mympdapi  Start timer_handler_covercache_crop
23:11:29 DEBUG    mympdapi  "default": Leaving mpd idle mode
23:11:29 DEBUG    mympdapi  "default": Handle API request "MYMPD_API_COVERCACHE_CROP"
23:11:29 DEBUG    mympdapi  "default": MYMPD API request (-1)(0) MYMPD_API_COVERCACHE_CROP: {"jsonrpc":"2.0","id":0,"method":"MYMPD_API_COVERCACHE_CROP","params":{}}
23:11:29 NOTICE   mympdapi  Cleaning covercache "/var/cache/mympd/covercache"
23:11:29 DEBUG    mympdapi  Remove files older than 1698016289 sec
23:11:29 ERROR    mympdapi  Error opening directory "/var/cache/mympd/covercache"
23:11:29 ERROR    mympdapi  Permission denied
23:11:29 DEBUG    mympdapi  "default": Entering mpd idle mode
23:13:08 INFO     webserver HTTP connection 5 closed
23:13:08 INFO     webserver HTTP connection 4 closed
23:13:08 INFO     webserver HTTP connection 3 closed

In the browser I do get following error message:

![image](https://github.com/jcorporation/myMPD/assets/18649312/32ec6a19-6b37-40b9-860b-e5bccf727473)

How can I fix this problem?

**Comment by jcorporation** [comment]
Please provide information how you compiled myMPD and the compile log.

**Comment by padertux** [comment]
Hi. The issue can be closed. I am using buildroot to build mympd and buildroot does build in source by default. Instructing buildroot to do an out of source build did solve the problem.
