### ISSUE TITLE
Hate/Love buttons disappeared in Playback view

### ISSUE THREAD

**Issue by loop333** [jcorporation/myMPD#1186]
myMPD version: 13.0.5

**Describe the bug**

Hate/Love buttons disappeared in Playback view

**To Reproduce**

1. Go to Playback View

**Expected behavior**

Hate and Love buttons are visible in Playback view

**Screenshots**

![Screenshot_20231211_000739](https://github.com/jcorporation/myMPD/assets/37012903/69dd6db3-cca8-4b14-90bd-8a553d7e401a)

**Server plattform (please complete the following information):**
 - OS: Debian
 - OS version Trixie
 - Plattform: x86_64
 - MPD version: 0.23.14

**Client platform (please complete the following information):**
 - Device: PC
 - OS: Debian Trixie
 - Browser Chrome, Thorium, Firefox ESR
 - Browser version 120.0.6099.71, 117.0.5938.157, 115.5.0esr

**Comment by jcorporation** [comment]
I can not reproduce your issue. In my setup with myMPD v13.0.5 the hate/love appears as designed. Check if the MPD sticker support is enabled. Please post also logs of the startup of myMPD with debug logging enabled.

**Comment by loop333** [comment]
Dec 11 23:52:07 minipc mympd[240913]: DEBUG    mympdapi  "stickerdb": Can not open file "/home/ha/PRG/mympd/workdir/state/stickerdb/preset_list"

**Comment by loop333** [comment]
i have created dir workdir/stickerdb and after restart i can see hate/love buttons

**Comment by jcorporation** [comment]
That is strange, this directory should not be needed. Please attach your configuration and the complete log.

**Comment by loop333** [comment]
after deleting dir workdir/state/stickerdb buttons are still visible, so i have attached old logs
[mympd.log](https://github.com/jcorporation/myMPD/files/13644882/mympd.log)
[config.zip](https://github.com/jcorporation/myMPD/files/13644891/config.zip)

**Comment by jcorporation** [comment]
> Dec 11 23:52:07 minipc mympd[240913]: DEBUG mympdapi "stickerdb": Can not open file "/home/ha/PRG/mympd/workdir/state/stickerdb/preset_list"

This is a normal, but irritating debug message. This is already fixed for the upcoming major version 14.0.0.
