### ISSUE TITLE
No coverimage for devel build

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#119]
No coverimage and sometimes with the following error message.
`ERROR    Error extracting coverimage, invalid music_directory`

I have no idea why the local downloaded src files from github are engaged here, is it my fault?

Ubuntu 18.04.2 X86_64

[mympd.conf.txt](https://github.com/jcorporation/myMPD/files/3200725/mympd.conf.txt)

[log.txt](https://github.com/jcorporation/myMPD/files/3200726/log.txt)

**Comment by jcorporation** [comment]
You use embedded coverimages? I don't see the error in your provided logs.

**Comment by parkmino** [comment]
Yeah, embedded covers does not show in devel while external ones are fine.

**Comment by parkmino** [comment]
There might have been some changes and now I see most of all cover however not all.
I will look into it more.

**Comment by jcorporation** [comment]
Devel code is in flow ;) today i am worked on making the music directory configurable in the gui.

**Comment by parkmino** [comment]
Is there any way to resove the following error?
I cannot change the mpd connection in gui.

```
ERROR    MPD connection: incorrect password
ERROR    MPD connection failed
```

**Comment by parkmino** [comment]
I removed /var/lib/mympd/state/mpd_pass and it works again.
I will look into it.

**Comment by parkmino** [comment]
I am confused... all covers are not shown and just showing 'not playing'

**Comment by parkmino** [comment]
New error
There's no sticker setting in mympd.conf

```
ERROR    MPD error: unknown command "sticker"
ERROR    MPD error mpd_send_sticker_set: unknown command "sticker"
ERROR    MPD error mpd_run_sticker_set: unknown command "sticker"
```

**Comment by parkmino** [comment]
Is it related to the latest commit?
https://github.com/jcorporation/myMPD/commit/4d2bacc652a7178e15940a7406ee9d51694ae34d

**Comment by jcorporation** [comment]
No, but the sticker feature detection was broken. I fixed it with commit 0d3021d3d6eb4986ffcac62cf4c2a1ee2742df26
Stickers can be also disabled in settings in the gui

**Comment by parkmino** [comment]
With the latest devel, most of embedded cover shows except the attached one.
Could you please check this on your side?

[이진아 - Always with us (Inspired by `파랑`).mp3.zip](https://github.com/jcorporation/myMPD/files/3214474/-.Always.with.us.Inspired.by.mp3.zip)

**Comment by parkmino** [comment]
The album cover is in /var/lib/mympd/covercache/, however no show.

**Comment by jcorporation** [comment]
I tested it with recent devel and I see the cover.

**Comment by parkmino** [comment]
It is stange that I see the cover at this time, close this issue then.
