### ISSUE TITLE
Next song icon is greyed out when a new song is appended in devel.

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#120]
**Describe the bug**
Next song icon is greyed out even when a new song is appeneded.

**To Reproduce**
1. Play a song
2. Append a song with "Append the queue"
3. Next icon is still greyed out (>|)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Browser: Firefox
 - Version: 66.0.5

**Comment by jcorporation** [comment]
Is now fixed in devel.
