### ISSUE TITLE
Album for key  not found in cache

### ISSUE THREAD

**Issue by mgonzalezm** [jcorporation/myMPD#1215]
myMPD version: 14.0.1

When browsing an album's contents and try to add the album to the queue from the contextual menu that appears from any of  the songs, nothing is added and got an error like this in the log:

```
INFO     webserver "default": API request (5): MYMPD_API_QUEUE_REPLACE_ALBUMS
ERROR    mympdapi  Album for key "d8a207df-ccb3-44fe-8e40-5c875d98aabf" not found in cache
--
INFO     webserver "default": API request (34): MYMPD_API_QUEUE_APPEND_ALBUMS
ERROR    mympdapi  Album for key "d8a207df-ccb3-44fe-8e40-5c875d98aabf" not found in cache
```
![mympd](https://github.com/jcorporation/myMPD/assets/11181196/0bfee9a2-84ca-4c53-9940-963f357b865e)

But if I use the button on the upper left instead, then the album is added without a problem.

![mympd2](https://github.com/jcorporation/myMPD/assets/11181196/3a9adf55-4e47-4fee-982a-a6249d4fecd1)

Server plattform

    OS: DietPi v9.0.2
    Device model : Sparky SBC (armv7l)
    MPD version: Music Player Daemon 0.24

Client plattform

    Device: PC
    OS: Arch-Linux
    Browser: Firefox 121.0.1

Edit to add: The same thing occurs when selecting a song from a search result list and try to add the whole album.

**Comment by jcorporation** [comment]
Please post the complete Leute debug log from start, success and failure.

**Comment by mgonzalezm** [comment]
[error.log](https://github.com/jcorporation/myMPD/files/14230691/error.log)
[ok.log](https://github.com/jcorporation/myMPD/files/14230693/ok.log)

**Comment by jcorporation** [comment]
You have enabled the musicbrainz_albumid in MPD but not in myMPD? Then the above commit should fix the issue.

**Comment by mgonzalezm** [comment]
> You have enabled the musicbrainz_albumid in MPD but not in myMPD

yes that's right, I did it because I have some multi-album set like this [musicbrainz](https://musicbrainz.org/release/d25017c5-01c2-4a49-b372-3186e3e2085a) but still wanted to see them separated.

It seems to be working now.

Thank you for this amazing piece of software.
