### ISSUE TITLE
gentoo ebuild fails at installl phase

### ISSUE THREAD

**Issue by kp-org** [jcorporation/myMPD#1219]
myMPD version: 14.0.2

Unfortunately there is another issue with the ebuild. It fails at install phase with

`!!! dobin: bin/mympd-config does not exist`

The file mympd-config exists in dir `cli_tools` after compilation.

**Comment by jcorporation** [comment]
Changed to `dobin ../cli_tools/mympd-config/mympd-config`. I hope this is correct. I am not familiar with gentoo.
