### ISSUE TITLE
Progress bar is not visible under Firefox

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#122]
**Describe the bug**
Progress bar is not visible under Firefox while Google Chrome has no problem.

**Screenshots**

![2019-05-24-114515_1600x900_scrot](https://user-images.githubusercontent.com/12131158/58299306-ca9bc880-7e19-11e9-85d6-1722106b298b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Browser: Firefox
 - Version: 67.0

**Comment by jcorporation** [comment]
I am using the same firefox version and I see the progress bar. I am using Ubuntu 19.04. Is the progress bar visible with current master?

**Comment by parkmino** [comment]
No, I don't see the progress bar with master.

**Comment by jcorporation** [comment]
Very odd. Do you see the range slider in the volume menu?

**Comment by parkmino** [comment]
Volumecontrol is disabled and any other thing to check?

**Comment by parkmino** [comment]
I enabled volumecontrol to check this and no slider either.
Where is the location of mympd.css?
I see mympd.css in github, however there are bootstrap.min.css and mympd.min.css in my /usr/share/mympd/htdocs/css.

**Comment by parkmino** [comment]
Should I remove the previous deb package and install the devel again?

**Comment by jcorporation** [comment]
Ok, then it is no problem with the background color. Have you enabled firefox plugins that can cause this issue?

**Comment by parkmino** [comment]
Hmm... I remove the old mympd deb package, modified mympd.css, rebuilt it.
No slider still.
I disabled the only one plugin and still no difference.

**Comment by jcorporation** [comment]
Since what version of myMPD you have no slider?

**Comment by parkmino** [comment]
Since the first time with firefox.

2019년 5월 28일 (화) 오전 1:58, Jürgen Mang <notifications@github.com>님이 작성:

**Comment by jcorporation** [comment]
The slider is a standard ``<input type="range">`` element with no special css applied to it.

Does this slider in the bootstrap example appear?
https://getbootstrap.com/docs/4.3/components/forms/#range-inputs

**Comment by parkmino** [comment]
No slider in range-inputs while range looks fine.
Close this issue if it is my own problem with firefox.
