### ISSUE TITLE
Album Filtering - Android (Firefox, Chrome)

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1220]
myMPD 14.0.3

In the album view (Browse/Album) one can type a search term and the view gets immidiatly filtered as you type and/or one may hit Enter and add the next search term. This works with all desktop browsers I have tried (Firefox, Edge), it works on an Ipad (Firefox, Safari) and iPhone (Safari).

For some reason it does not work on three Android devices (one tablet, two phones) I tried:
With Firefox I do not get "search/filter" as you type but get some result when I add a blank at the end.
With Chrome there is no search or filter function at all.

**Comment by jcorporation** [comment]
It seems to be a chrome bug: https://stackoverflow.com/questions/17974021/keyup-not-working-on-chrome-on-android

Pressing enter works?

**Comment by john-** [comment]
Looks like I see the same behavior.  Pressing enter to add the search term adds the term but does not execute the search.  I need to press enter by itself in the search box in order for the results to be filtered.

**Comment by GK-774** [comment]
Enter works in the sense that it moves the search term to the area below but no filtering action takes place.

**Comment by GK-774** [comment]
It looks like the android/chrome bug, yes, more android though, because with Firefox on Android behaviour is the same. Is there a browser for Android one could try?

**Comment by Emilot** [comment]
It happens to Firefox too. No search...

**Comment by john-** [comment]
In my experience on Android:

- Filter as you type is not not working
- Submitting a search term does not trigger the filtering

However, if you hit enter in the search box after submitting a search term the filtered results appear.

**Comment by john-** [comment]
For basic test I typed only the letter `s` in each case.

Firefox on linux laptop
```
Key "s" pressed [event: keydown]
Key "s" about to be input [event: beforeinput]
Key "s" input [event: input]
Key "s" released [event: keyup]
```
Android 13 phone using Chrome:
```
Key "Unidentified" pressed [event: keydown]
Key "s" about to be input [event: beforeinput]
Key "s" input [event: input]
Key "Unidentified" released [event: keyup] 
```

That seems pretty messed up so it would be good if someone else can verify.

**Comment by GK-774** [comment]
I can confirm the results that John got. Firefox on iPad same result as Firefox on linux laptop, DuckDuckGo, Edge and Chrome on LineageOS 20 (Android 13) same result as Android 13 phone using Chrome.

**Comment by jcorporation** [comment]
Please test the Enter key also.

**Comment by john-** [comment]
`Enter` key...

Firefox on Linux:
```
Key "Enter" pressed [event: keydown]
Key "null" about to be input [event: beforeinput]
Key "null" input [event: input]
Key "Enter" released [event: keyup]
```
Android 13 phone using Chrome:
```
Key "Unidentified" pressed [event: keydown]
Key "Unidentified" released [event: keyup]
Key "Enter" pressed [event: keydown]
Key "null" about to be input [event: beforeinput]
Key "null" input [event: input]
Key "Enter" released [event: keyup] 
```

**Comment by jcorporation** [comment]
Thanks. Search on type could not work, but pressing enter for search should work with some adjustments.

**Comment by john-** [comment]
I tested on Firefox/Linux and Chrome/Android.  Firefox/linux continues to work as expected (no regression)

With Chrome, adding search terms works as expected (no search on type, enter key adds search term and filters the results).

However, when removing a search term with the `x` the search results do not update to show no filtering.  Furthermore, the removed search term pops back into the search box.   Selecting the `x` to the right of the search box clears the text.

I can provide a screen shot if that helps.

On desktop, removal continues to work as expected.

**Comment by jcorporation** [comment]
- Selecting the `x` to the right of the search box uses now the keydown and Enter event. Keyup is disabled for Android.
- It seems Android does not catch the click event of a span inside a button, replaced it with generic div elements.

Pleas test again.

**Comment by john-** [comment]
I am getting inconsistent results and trying to rule out caching or some kind of user error.  I say this because some times removal works as expected (removes search term and updates results) and other times it does not (pops the search term back to the search box and does not update the search results).

I have not figured out a pattern and need to step away from the computer.  Hopefully others can look at this otherwise I will try later.

**Comment by GK-774** [comment]
I can confirm normal operation on an Laptop (Firefox and Edge), I will test on two Android devices this evening and report back.

**Comment by GK-774** [comment]
Yes, :-) looks good. With Android Phone and Tablet I get the correct filtering action after Enter, clearing it with the „x“ button returns to the view before. I would say, it’s resolved.
