### ISSUE TITLE
Can syscmds have sub-menu same as "> Update"

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#123]
It would be good for syscmds to have sub-menu to reduce main-menu lines.

**Comment by jcorporation** [comment]
I think a sub-menu is only useful, if more than 5 entries are present.

**Comment by parkmino** [comment]
Yeah, I've got 13 now.

**Comment by jcorporation** [comment]
Is now implemented in devel. The submenu is added, if more than 4 system commands are configured.

**Comment by parkmino** [comment]
It would be good to translate "System commands".

**Comment by jcorporation** [comment]
Translation files for germyn and korean are updated.
