### ISSUE TITLE
Some assets fail to load behind NGINX reverse proxy

### ISSUE THREAD

**Issue by cbrenberg** [jcorporation/myMPD#1231]
myMPD version: 14.0.3

**Describe the bug**

The file located at 'assets/coverimage-notavailable.svg' fails to load when accessing myMPD through an NGINX reverse proxy. I believe this is because the location of this SVG file is defined as a relative path in CSS, which becomes incorrect when accessed through the proxy URL.

**To Reproduce**

1. Set up nginx reverse proxy using the example on the documentation site: https://jcorporation.github.io/myMPD/additional-topics/behind-a-reverse-proxy
2. Load the proxy URL in a browser (
3. Inspect the network requests from the browser's dev tools while loading an album cover art view
4. All requests for 'assets/coverimage-notavailable.svg' fail to load

**Expected behavior**

All assets load successfully. Here are three options to consider for a solution:
1. the documentation should be updated with a working example of a nginx reverse proxy configuration
2. the nginx example should be removed from the reverse proxy documentation since it doesn't work
3. the path to the affected SVG file in the CSS files should be changed from a relative path to the fully qualified path (or some other solution that results in successfully loading the cover not available SVG file regardless of the URL at which myMPD is accessed)

**Server platform (please complete the following information):**
 - OS: DietPi
 - OS version: 9.1
 - Platform: Raspberry Pi 3

**Client platform (please complete the following information):**
 - Device: Windows 10 laptop with Chrome browser, iPhone with Safari browser. This issue most likely impacts all devices and browsers

**Additional context**

I also had issues with the websocket connection when hosted behind an NGINX reverse proxy, so if the docs need updating, it might be worth looking into that also.

**Comment by jcorporation** [comment]
Please provide myMPD debug logs and nginx access logs.

**Comment by cbrenberg** [comment]
I just confirmed that adding the second line `proxy_redirect / /mympd/` to my nginx configuration resolves this issue. Thanks for looking into it!
