### ISSUE TITLE
Filesystem do not return to previous position state (same as #754)

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#1234]
Describe the bug

When i am at the third page for example and open a folder at the bottom of the page, when i press "Back" will go to the top page and not on the folder i was (it will reset the position).

To Reproduce

    Go to Filesystem
    Click on a folder
    Go back(back mouse button)
    Go to the top of the page and not to the folder you where

Expected behavior

To go to the folder i was last

PS.Can you bring back the three dots ".." in the path because i can only go to the root directory without them ?

**Comment by jcorporation** [comment]
> PS.Can you bring back the three dots ".." in the path because i can only go to the root directory without them ?

There are breadcrumbs to go back to a specific parent folder. The threee dots "..." was redundant.

**Comment by Emilot** [comment]
> > PS.Can you bring back the three dots ".." in the path because i can only go to the root directory without them ?
> 
> There are breadcrumbs to go back to a specific parent folder. The threee dots "..." was redundant.

Hmm...

I have a folder "Music" with all my music album-folders in it.

I open an album-folder on the 6th page.

breadcrumbs show me the "Music" parent folder. Nothing else. When i click it i go back to Page 1.

**Comment by jcorporation** [comment]
That is the correct behavior. The three dots had behaved also that way. To go a page back, you should use the pagination.

That has nothing to do with your described bug. The state of the folders are indeed not saved.

**Comment by Emilot** [comment]
> That is the correct behavior. The three dots had behaved also that way. To go a page back, you should use the pagination.
> 
> That has nothing to do with your described bug. The state of the folders are indeed not saved.

Ok! I got confused with the "breadcrumbs" you said earlier. Thanx for the clarification.

**Comment by Emilot** [comment]
Thank you for the quick fix!

**Comment by jcorporation** [comment]
It was a regression caused by 745ac77.
