### ISSUE TITLE
"Disconnected from myMPD" when not using avahi announced address (iOS only)

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1238]
myMPD version: 14.1.0 (same result with 14.0.4)

myMPDs IP address should be accessible by all browsers and OS versions directly by IP and with avahi (zeroconf, bonjour) on the operating systems that support it.
This works with all browsers tested (Firefox, Safari and Edge) except on iOS devices (iPhone and iPad tested) where I immidiately get "Disconnected from myMPD" and can´t reconnect. Connecting to the avahi provided name (e.g. "mympd.local") works normally, though. If I start a webserver (apache) on port 80 instead of myMPD iOS devices can connect by IP.

I have used 14.0.4 since it was released and do not recall this effect so this appears to be some myMPD (mongoose?) - iOS incompatibility since the iOS update to 17.4 two days ago. It is browser independend.

Server plattform
 - OS: Springdale Open Enterprise Linux (RHEL9 compatible)
 - OS version release 9.2
 - Plattform: x86_64
 - MPD version: 0.23.15

Client plattform
 - Device: iPhone6, iPad pro
 - OS: iOS 17.4
 - Browser Firefox 123.3, Safari and Edge (latest versions)

myMPD debug log attached. (Actions were connecting to 192.168.0.17, try the reload in the red disconnected field two times and browser page reload two times).
[debug.txt](https://github.com/jcorporation/myMPD/files/14590124/debug.txt)

**Comment by jcorporation** [comment]
This error appears if the browser can not establish a websocket connection. I see no websocket messages in the attached debug log. It seems to be a client problem. I tried to replicate the issue with my iPhone (same OS release as yours), but in my environment it works without problems. Any chance to get the logs from the browser?

Your test with apache is not helpful, because simple http requests are working with myMPD also.

**Comment by GK-774** [comment]
Firefox (iOS) log attached.
[Firefox.log](https://github.com/jcorporation/myMPD/files/14593343/Firefox.log)

**Comment by GK-774** [comment]
Well, sorry to have bothered you with this. I have a Privoxy proxy running and just found if I disable the proxy on iOS everything works as advertised. Strange still that this only interferes with iOS devices, but anyway it´s not a myMPD issue.
Sorry for having wasted your time, the bug report is "invalid".
