### ISSUE TITLE
Album List View — ** no covers **

### ISSUE THREAD

**Issue by iconoclasthero** [jcorporation/myMPD#1246]
I love how I can't edit in a picture in github.  wtf is that locked out for?  Thanks again gighub.

**Comment by jcorporation** [comment]
Not a bug report

**Comment by iconoclasthero** [comment]
I'd like to see this as a list.  The pictures make me very, very 😠

**Comment by iconoclasthero** [comment]
This isn't a bug it's a feature request.  where do they go then?

**Comment by iconoclasthero** [comment]
Also, is there like a discord or something where i can just ask a few questions?

**Comment by jcorporation** [comment]
The https://github.com/jcorporation/myMPD/discussions are the the right place for feature request and questions.
