### ISSUE TITLE
myMPD Web Interface keeps timing out

### ISSUE THREAD

**Issue by Kornelius777** [jcorporation/myMPD#1252]
myMPD version: 14.1.0

**Describe the bug**

Running on a Raspberry Pi. Accessible via hostname, fixed IP Address.
SSL disabled.
Every once in a while - multiple times a day - the myMPD web interface is no longer available.

Today, to enhance the situation, I installed nginx and made it a reverse proxy to myMPD. Now, the timeout occurred again: Here is the error log:

```
2024/04/06 15:01:34 [info] 20006#20006: *89 upstream timed out (110: Connection timed out) while proxying upgraded connection, client: 10.10.8.116, server: radio.xxx.yyy.de, request: "GET /ws/default HTTP/1.1", upstream: "http://127.0.0.1:80/ws/default", host: "radio.xxx.yyy.de"
```

**To Reproduce**

*Shrug* - No Idea

**Expected behavior**

Stay available via web interface 

**Screenshots**

None

**Server plattform (please complete the following information):**
 - OS: Raspberry Pi OS
 - OS Version: cat /etc/debian_version - 12.5
 - Plattform: Raspberry Pi Arm
 - MPD version: 14.1.0

**Client plattform (please complete the following information):**
 - Device: Android (Firefox)
 - OS: Android 
 - Browser Firefox 
 - Browser version 124.0

**Debug logs (please attach if it can be useful)**

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
**Configuration (please attach if it can be useful)**

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 

**Additional context**

**Comment by jcorporation** [comment]
Where are the debug logs from myMP?

**Comment by Kornelius777** [comment]
Closed.
