### ISSUE TITLE
Iphone 15 Pro: can't reach volume controller, too far on the right

### ISSUE THREAD

**Issue by roizcorp** [jcorporation/myMPD#1253]
myMPD version: 14.1.1.0

**Describe the bug**
On iPhone 15 Pro, trying to change the volume level on portrait mode, can't reach the volume controller (bottom right).

**Comment by jcorporation** [comment]
Please post a screenshot.

**Comment by roizcorp** [comment]
![123](https://github.com/jcorporation/myMPD/assets/8208464/ec3d5d7e-0cc6-47b4-a5ed-e64a8da84f53)
![456](https://github.com/jcorporation/myMPD/assets/8208464/2763c51a-3915-446c-a21f-d598759761de)

hit and miss as you can see

**Comment by jcorporation** [comment]
You have enabled to many footer elements, simply disable some.

**Comment by roizcorp** [comment]
Thank you
