### ISSUE TITLE
Output attributes show wrong "state Disabled"

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1254]
myMPD Version: 14.1.1 shows in Output attributes always "Disabled" no matter if it is currently enabled. Enabling and disabling output works normally, they are coloured if active and they play of course if enabled, it´s just the text in "Show attributes" that never changes.

mpc outputs shows:
Output 1 (USB) is enabled
        allowed_formats=""
        dop="0"
Output 2 (Analog) is disabled
        allowed_formats=""
        dop="0"
Output 3 (SPDIF) is disabled
        allowed_formats=""
        dop="0"

In /var/lib/mpd/mpdstate I have:
audio_device_state:1:USB
audio_device_state:0:Analog
audio_device_state:0:SPDIF

**Comment by jcorporation** [comment]
Fixed in devel.
