### ISSUE TITLE
Have to have a  Stream Port although not required

### ISSUE THREAD

**Issue by stratosgear** [jcorporation/myMPD#1255]
myMPD version: : 14.1.1

I have set up a remote mpd with streaming output on port 64223.  But at the same time I have proxied, with traefik, to use a custom url of https://stream.my.domain.name, so it looks neater.

Now when on the mympd client try to  setup the Settings / Features / Local Playback section I can provide for:

```
Stream URI: https://stream.my.domain.name
Stream port: FORCES a value here!!!
```

It forces me to use a value between 1024 and 65535!
 
Using any value (I used 1024, for example) allows me to save the settings.

Streaming is working correctly afterwards

**Expected behavior**

The Stream port should NOT be a requirement.

**Server platform (please complete the following information):**
 - OS: nixos unstable
 - Platform: x86_64
 - MPD version: latest

**Client platform (please complete the following information):**
 - Device: Desktop
 - OS: nixos unstable
 - Browser firefox latest

**Comment by jcorporation** [comment]
Use any port above 1024. It is ignored if a stream uri is defined. Above commit set's the default value automatically on save.
