### ISSUE TITLE
Error when running ./build.sh 

### ISSUE THREAD

**Issue by Lukecell** [jcorporation/myMPD#1271]
myMPD version: v15.1.0 (most recent release from GitHub)

**Describe the bug**

When running

./build.sh releaseinstall

The script produces an error:

./build.sh: 304: 1: parameter not set

**To Reproduce**

1. Go to some directory in your terminal emulator
2. git clone https://github.com/jcorporation/myMPD.git
3. cd myMPD
4. git pull origin v15.1.0
5. git checkout v15.1.0
6. sudo ./build.sh installdeps
7. sudo ./build.sh releaseinstall

**Expected behavior**

To compile myMPD, and install it to the correct folders as is done by the release and install options

**Screenshots**

![errorMessage](https://github.com/jcorporation/myMPD/assets/19983728/8a447a9a-ba5f-4567-bf01-c34d70c62cdb)

**Server platform (please complete the following information):**
 - OS: Linux Mint (X-Cinnamon)
 - OS version: 21.2
 - Platform: x86_64
 - MPD version: 0.23.5

**Client platform (please complete the following information):**
 - Device: Laptop (Dell Precision M4800, heavily modified)
 - OS: Linux Mint 21.2 (X-Cinnamon)
 - Browser: Firefox
 - Browser version: 125.0.2 (64-bit)
 - Shell: Zsh

**Debug logs (please attach if it can be useful)**

As far as I am aware none are generated
 
**Configuration (please attach if it can be useful)**

I don't believe this would be useful, considering this prevents configuration files from being generated

**Additional context**

You can go around this bug by simply running

./build.sh release
sudo ./build.sh install

I believe this is the source of the bug (line 1440 in build.sh)

![code](https://github.com/jcorporation/myMPD/assets/19983728/76009c12-f894-43c8-a32e-0362e034408b)

**Comment by jcorporation** [comment]
> I believe this is the source of the bug (line 1440 in build.sh)

Correct, the parameter for buildrelease is missing.
