### ISSUE TITLE
Show backgound coverimage as much as possible

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#128]
It is good to show the background coverimage, however it seems too small and not seamless.
Is it possible to show more coverimage? e.g. transparent coverimage in content area.

**Comment by jcorporation** [comment]
Too small? The background image should be full the whole browser window. The size of the coverimage in the playback card can be adjusted through settings, default 240px.

**Comment by parkmino** [comment]
Visible area is too small since the content hide the background cover.
That's why I suggest transparent coverinamge in content area if possible.

**Comment by jcorporation** [comment]
Eventually slight transparent cards, can be a option.

**Comment by parkmino** [comment]
Yeah, it would be a good option.

**Comment by jcorporation** [comment]
I am tested it setting 
```
.card {
  background-color: rgba(255,255,255,0.9);
}
```
It doesn't looks good for me. The ui looks with that to unclean for me.

**Comment by parkmino** [comment]
Thanks for your test and I will close this issue then.
Please refer to the following link for further ui improvement.
https://moodeaudio.org/#features
