### ISSUE TITLE
Turning off SSL seems to break myMPD

### ISSUE THREAD

**Issue by Fluffkin** [jcorporation/myMPD#1287]
myMPD version: 15.0.1

Follow the instructions at https://jcorporation.github.io/myMPD/configuration/ssl to turn off SSL and simply use http:80 access.
"set /var/lib/mympd/config/ssl to false"
Restart the mympd service.
Now myMPD is inaccessible at the same address that worked (with certificate errors) before.

Edit: I think it might still be redirecting to 443 even though that doesn't exist any more?

**Expected behavior**
mympd should allow access to mympd without needing SSL.

**Server platform (please complete the following information):**
 - OS: Rasbian
 - OS version: Debian 12.2.0
 - Platform: arm64
 - MPD version: 0.23.12

**Client platform (please complete the following information):**
 - Device: Desktop
 - OS: MX Linux
 - Browser: Any
 - Browser version: N/A

**Comment by jcorporation** [comment]
Where are the debug logs?

**Comment by Fluffkin** [comment]
If you change one word in a one word file and restart myMPD you can make as many debug logs as you like.

**Comment by jcorporation** [comment]
In the bug report template I ask for the debug logs. You have ignored that. Why I should I verify that it works? Show me the logs that says it does not work.

It is very unlikely that this does not work as it is a common setup.
