### ISSUE TITLE
Material Design Icons do not show in chromium

### ISSUE THREAD

**Issue by CultofRobots** [jcorporation/myMPD#13]
Material Design Icons do not show in chromium

![screenshot from 2018-06-07 11-19-27](https://user-images.githubusercontent.com/35628488/41109300-b1115c98-6a44-11e8-9be1-273c9eee00cb.png)

**Desktop:**
Arch Linux 
Chromium - 67.0.3396.79

Closing off line 95 and adding an additional "src:" on line 96 in mpd.css corrects the problem:

94   src: local('Material Icons'),
**95**           local('MaterialIcons-Regular')**;**
**96   src\:** url(/assets/MaterialIcons-Regular.woff2) format('woff2'),

**Comment by jcorporation** [comment]
Strange, in Chromium 66 it works, however I fixed it in master
