### ISSUE TITLE
songs are displayed and played in the wrong order in play queue

### ISSUE THREAD

**Issue by payonq** [jcorporation/myMPD#130]
myMPD is client of MPD on Snakeoil.

After choosing album and adding to queue songs are displayed and played in the wrong order, not like on the album. each time in the same, wrong order. For each album. 

**Expected behavior**
To display and play in order same as on original album.

**Desktop (please complete the following information):**
Win 10
Firefox
67.0.1

**Comment by jcorporation** [comment]
I think this is a behaviour of mpd itself.
But for sure:
In which view you add the album? Please add a screenshot of albumview and queue view.

**Comment by jcorporation** [comment]
No response? I close this issue now. Don‘t hestitate to reopen it with the the requested informations.
