### ISSUE TITLE
cache_cover_keep_days & mympd-config

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1312]
myMPD version 16.0.0 from today (11:56:51 AM CEST)

I have set /var/lib/mympd/config/cache_cover_keep_days to -1 to disable pruning of the cache. If I start mympd-config it shows me 31 days instead of -1, if I try to set it to -1 I get:

[root@mpd9 ~]# mympd-config
/usr/bin/mympd-config: line 76: read: `MYMPD_CACHE_COVER_KEEP_DAYS=31': not a valid identifier
/usr/bin/mympd-config: line 77: read: `MYMPD_CACHE_LYRICS_KEEP_DAYS=31': not a valid identifier
/usr/bin/mympd-config: line 78: read: `MYMPD_CACHE_MISC_KEEP_DAYS=31': not a valid identifier
/usr/bin/mympd-config: line 79: read: `MYMPD_CACHE_THUMBS_KEEP_DAYS=31': not a valid identifier

**Comment by GK-774** [comment]
Additional question: With a mympd restart the cache gets pruned despite having "-1" in cache_cover_keep_days ?
I had populated the cache with the CovercachePrepopulate which resulted in du -hs /var/cache/mympd/cover
389M    /var/cache/mympd/cover some time after a restart I get: du -hs /var/cache/mympd/cover
0       /var/cache/mympd/cover

**Comment by jcorporation** [comment]
Both are bugs, thanks for reporting

**Comment by GK-774** [comment]
Just did an update, and the cover cache still filled (looks ok), but mympd-config gives me now:
[root@mpd9 ~]# mympd-config
/usr/bin/mympd-config: line 78: read: `MYMPD_CACHE_MISC_KEEP_DAYS < /var/lib/mympd/config/cache_misc_keep_days
    [ -f /var/lib/mympd/config/cache_thumbs_keep_days ] && read -r MYMPD_CACHE_THUMBS_KEEP_DAYS': not a valid identifier
Segmentation fault (core dumped)

**Comment by GK-774** [comment]
The error is immideatly after selecting "Misc".

**Comment by jcorporation** [comment]
Orphan quotes from last fix..should now been fixed

**Comment by GK-774** [comment]
Still opening "Misc" does not work for me. The Mask dissapears and mympd-config first hangs on the promt and after a few seconds crahes: [root@mpd9 ~]# mympd-config
Segmentation fault (core dumped)

**Comment by GK-774** [comment]
If I first set anynthing to "Reset to default" it works normally.

**Comment by GK-774** [comment]
Well, until I configure the cover cache to -1 with mympd-config. Then it crashes and core dumped.

**Comment by GK-774** [comment]
Ok, just tested, yes this is the only difference. cache_cover_keep_days at 31 -> works, cache_cover_keep_days at -1 -> does not.

**Comment by GK-774** [comment]
And, sorry to say, the cache gets pruned as well although it´s now set to 31 days, it´s empty again.

**Comment by jcorporation** [comment]
Ah, whiptail interprets -1 as an option and not as value - fixed, bad that it crashes and not reporting an error.

I switched some settings between clear and crop internally. It should work now.

**Comment by GK-774** [comment]
No more crash of mympd-config, but if cache_cover_keep_days is already set at -1 it refuses to set it to another value (jumps to the first item). If I have 31 in cache_cover_keep_days it accepts editing but after Exit says "/usr/bin/mympd-config: line 157: -c: command not found" and the value is unchanged at 31.

**Comment by GK-774** [comment]
If I explicitely state the path to mympd I get after editing:
 mympd-config -b /usr/bin/mympd
/usr/bin/mympd-config: line 107:  6124 Segmentation fault      (core dumped) $MYMPD_BIN -c

**Comment by jcorporation** [comment]
I should really test my code better. The path for mympd executable is now determinded automatically if not defined explicitly.

It seems in your environment `mympd -c` segfaults. I can not reproduce it in my environment. Please run the mympd debug build with valgrind.

```
build.sh debug
```

If you run mympd with the default systemd unit from mympd:

```
systemd-run -u mympd -p DynamicUser=yes -p StateDirectory=mympd -p CacheDirectory=mympd -E MYMPD_CACHE_COVER_KEEP_DAYS=-1 valgrind debug/bin/mympd -c
```

If not:

```
export MYMPD_CACHE_COVER_KEEP_DAYS=-1
valgrind debug/bin/mympd -c
```

**Comment by GK-774** [comment]
Ok, did:
git clone --single-branch --branch v16.0.0 https://github.com/jcorporation/myMPD.git
cd myMPD/
./build.sh debug
export MYMPD_CACHE_COVER_KEEP_DAYS=-1

sudo valgrind debug/bin/mympd -c
output: valgrind_1.txt

and

sudo valgrind --leak-check=full --show-leak-kinds=all debug/bin/mympd -c
output: valgrind_2.txt

[valgrind_1.zip](https://github.com/user-attachments/files/15863018/valgrind_1.zip)
[valgrind_2.zip](https://github.com/user-attachments/files/15863021/valgrind_2.zip)

**Comment by jcorporation** [comment]
You must use sudo -E to preserve the exporter environment variable. In the provided logs there are no errors.

**Comment by GK-774** [comment]
With the mympd binary I never experienced any crashes/core dumps, it was mympd-config with which I had a problem. So I wanted to repeat it today with "sudo -E" but did a new check out of the devel branch before testing it. And now mympd-config works as expected, no issues. So I think it´s resolved.
