### ISSUE TITLE
Build fails without luac

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#1317]
MyMPD 16.0.0, just pulled.

cmake -B build -DMYMPD_ENABLE_LUA=off (and a lot of other stuff).

I get this twice, after which it fails and stops, even though it fully acknowledges that "Lua is disabled by user":
```
Compiling lua libraries
ERROR: luac not found
CMake Error at CMakeLists.txt:194 (message):
  Creating assets failed


-- Configuring incomplete, errors occurred!
```
Probably something very trivial. Thank you in advance.

**Comment by jcorporation** [comment]
Fixed in devel. Please test.

**Comment by therion23** [comment]
Builds cleanly, thanks!

Simply never had any use for myMPD scripting (or lua outside of that for that matter), and until this version, myMPD built just fine without even disabling lua.
