### ISSUE TITLE
Browse by Composer->Album Empty List

### ISSUE THREAD

**Issue by mayanez** [jcorporation/myMPD#1330]
myMPD version: 16.0.1
**Describe the bug**

When trying to browse by the `Composer` tag and then selecting associated albums, the result is empty.

**To Reproduce**

1. Go to 'Browse'
2. Click on 'Select View'
3. Select 'Composer'
4. Click on 'Album' icon
![image](https://github.com/user-attachments/assets/cbbd34d6-59cb-4444-a2db-5ce96947129c)

**Expected behavior**

Albums associated with the specified composer should be listed.

**Screenshots**

![image](https://github.com/user-attachments/assets/11048bb7-15dc-4b78-9e74-24f67c793123)

![image](https://github.com/user-attachments/assets/72c0e534-604b-498b-b4f8-f16bb816cdf4)

**Server platform (please complete the following information):**
 - OS: Docker Image
 - Platform: x86_64
 - MPD version: 0.23.15

**Client platform (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser: Any
 - Browser version: Any

**Debug logs**

```
mympd  | DEBUG    mympdapi        "default": Handle API request "MYMPD_API_DATABASE_ALBUM_LIST"
mympd  | DEBUG    mympdapi        "default": MYMPD API request (38)(827986010) MYMPD_API_DATABASE_ALBUM_LIST: {"jsonrpc":"2.0","id":827986010,"method":"MYMPD_API_DATABASE_ALBUM_LIST","params":{"offset":0,"limit":100,"expression":"((Composer == 'Antonín Dvořák'))","sort":"AlbumArtist","sortdesc":false,"fields":["Album","AlbumArtist","Thumbnail","Work","Composer"]}}
mympd  | DEBUG    mympdapi        Parsed expression tag: "Composer", op: "==", value:"Antonín Dvořák"
mympd  | DEBUG    mympdapi        Push response to webserver queue for connection 38: {"jsonrpc":"2.0","id":827986010,"result":{"method":"MYMPD_API_DATABASE_ALBUM_LIST","data":[],"totalEntities":0,"returnedEntities":0,"offset":0,"expression":"((Composer == 'Antonín Dvořák'))","sort":"AlbumArtist","sortdesc":false,"tag":"Album"}}
```

**Additional context**

The song/tracks view works correctly. This makes sense since the `Composer` tag is associated with a specific track. Other clients (such as MAFA on Android) seem to be able to do `Composer`->`Album`. I'm not sure if this is already available in the MPD database or if it requires additional bookkeeping by `myMPD`.

**Comment by jcorporation** [comment]
This should work. Have you enabled the composer tag for myMPD browse tags and forced a refresh of the album cache?

**Comment by mayanez** [comment]
Thanks for getting back so quickly!
Yes, I did enable them. Refreshing the cache seems to have done the trick! I apologize for the false report. 

Perhaps, if it's not done already,  a cache invalidation when new tags are enabled would be handy.
