### ISSUE TITLE
Actions Menu Uncaught Type Error in v18.0.0

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#1356]
### Discussed in https://github.com/jcorporation/myMPD/discussions/1355

<div type='discussions-op-text'>

<sup>Originally posted by **MickMorley** October  8, 2024</sup>
In the latest version, the Actions button causes an error `Uncaught TypeError: Cannot read properties of undefined (reading 'substr')` in the UI.  This occurs under the `Search` menu and `Browse` menu.  It only happens on individual songs, if you select the Actions button on an Album, it works.  The side pane displays.

I believe this issue started last week which is when 18.0.0 was released.  There was a container update today that I tried as well, but same issue.

Edit: Just tried a new installation (with a fresh work and cache directory) and the same issue persists.

![image](https://github.com/user-attachments/assets/2ff25493-704e-482f-9814-156379187ec1)</div>

**Comment by jcorporation** [comment]
Fix is in devel. Can you test?

**Comment by MickMorley** [comment]
> Fix is in devel. Can you test?

I have confirmed that the Actions button is working in `mympd-devel:devel`

![image](https://github.com/user-attachments/assets/71807827-ca1f-424e-91bf-97937a1d8774)
