### ISSUE TITLE
Album details - no track information

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1359]
[mympd.log.gz](https://github.com/user-attachments/files/17325456/mympd.log.gz)
myMPD version: 18.1.2 (checkout today)

Since version 18.x in "Album details" the track information no longer gets displayed (Screenshot 18.png), downgrading to 17.0.4 immediately solves the issue (Screenshot 17.png).
Logfile (18.1.2 with loglevel 7) is attached. mpd version is 0.23.15.
![Screenshot 18](https://github.com/user-attachments/assets/fd975ca8-65fb-4c59-a87b-a7636e1137de)
[mympd.log.gz](https://github.com/user-attachments/files/17325430/mympd.log.gz)
![Screenshot 17](https://github.com/user-attachments/assets/2c8986be-8a01-471e-8b43-f8a0a6123522)

**Comment by GK-774** [comment]
Browser Console output 
[firefox_browser_console.zip](https://github.com/user-attachments/files/17339555/firefox_browser_console.zip)

**Comment by jcorporation** [comment]
I think I found the issue. You have not enabled stickers in MPD or disabled stickers in myMPD?

**Comment by tsunulukai** [comment]
Using devel ceb726366b744984008d99b43ceff9243459bff5, album details are shown as expected on my system.
