### ISSUE TITLE
Mute pressing speaker button not working

### ISSUE THREAD

**Issue by Toets** [jcorporation/myMPD#1360]
myMPD version: [e.g. 8.1.0]

**Describe the bug**

Not able to mute by clicking the speaker icon in the bottom right. Clicking the icon opens the sound output / volume pop-up. Same behaviour as clicking the ^ icon on the right hand side of the speaker icon

**To Reproduce**

Just click :)

**Expected behavior**

Clicking the speaker icons hsould mute output

**Screenshots**

![image](https://github.com/user-attachments/assets/6df964eb-8cb9-4dbd-9c73-73a16d8c6a14)

**Server platform (please complete the following information):**
MyMPD Version: 18.1.2

**Client platform (please complete the following information):**
 - Device: laptop
 - OS: Fedore Linux 40
 - Browser Firefox, Chromium
 - Browser version Latest

**Debug logs**

Look at https://jcorporation.github.io/myMPD/debug

No corresponding logs
**Configuration (please attach if it can be useful)**
**Additional context**

**Comment by jcorporation** [comment]
There is no mute function Provider by MPD. You can only enable/disable outputs.
