### ISSUE TITLE
Album details - no track information

### ISSUE THREAD

**Issue by Floppe** [jcorporation/myMPD#1361]
myMPD version: 18.1.2

**Describe the bug**

No tracks shown. Last version it worked on was myMPD 14.

**Server platform (please complete the following information):**
 - OS: Alpine
 - Platform: x86_64
 - MPD version: 0.23.5

**Client platform (please complete the following information):**
 - Device: Laptop
 - OS: Win 11
 - Browser: Chrome
 - Browser version: 130

**Debug logs**

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log -> Nothing except DB updates
 - Browser error console -> No errors
 - Browser network console
 
**Additional context**

I deleted state folder and reconfigured mpd connection, did not help.
I guess there is a config issue when working with MPD 0.23.5?

If I could find MPD 0.24 for Alpine then I could test that.

[mympd-debug.txt](https://github.com/user-attachments/files/17521470/mympd-debug.txt)

**Comment by jcorporation** [comment]
Response from backend looks correct. Are you really sure there is no error in the browser console?

**Comment by Floppe** [comment]
Tested on Edge and Android and there it works. But not in Chrome desktop. I've disabled all extensions, cleared all site settings. CTRL+F5 to reload. Nothing helps.  No errors in JS console either.

![image](https://github.com/user-attachments/assets/8dc08966-ad02-4cdc-8362-a62a82754563)

Scrolled max down in above screenshot.

**Comment by jcorporation** [comment]
I tested it in my setup with chromium on linux and had no issues.  Appears this issue with all albums or only with a specific album?

Please create a HAR file: https://developer.chrome.com/docs/devtools/network/reference/#save-as-har

**Comment by Floppe** [comment]
All albums.
[mympd.zip](https://github.com/user-attachments/files/17532062/mympd.zip)

**Comment by jcorporation** [comment]
I did not find anything pointing to an error in the har file. It looks all as it should. As I understand it works in all browsers but chrome? Can you test a debug build? At best the current devel branch.

**Comment by Floppe** [comment]
Hah. I found the issue. I have a 34 inch WQHD monitor with 3440x1440 resolution and when Chrome is in fullscreen then the tracks are hidden.

So something with the scrollbars on large screens.

**Comment by jcorporation** [comment]
The coversize is now limited to 27rem this should fix your issue. Please test devel if possible.

**Comment by Floppe** [comment]
Yes, now it works. Thank you!
