### ISSUE TITLE
Fedora RPM package requires `whiptail`, which nothing provides

### ISSUE THREAD

**Issue by Crawron** [jcorporation/myMPD#1381]
myMPD version: 18.2.2

**Describe the bug**

When installing from the openSUSE Build repository for Fedora 40, dnf shows a missing dependency error as `nothing provides whiptail`, making the package uninstallable.

```
Error: 
 Problem: conflicting requests
  - nothing provides whiptail needed by mympd-18.2.2-1.1.x86_64 from home_jcorporation
(try to add '--skip-broken' to skip uninstallable packages)
```

**To Reproduce**

(in Fedora 40)
1. Download the `.repo` file from [here](https://download.opensuse.org/repositories/home:/jcorporation/Fedora_40/)
2. Add the repository using `dnf config-manager addrepo --from-repofile home_jcorporation.repo`
4. Try to install with `dnf install mympd.x86_64`

**Expected behavior**

myMPD is correctly installed.

**Server platform (please complete the following information):**
 - OS: Fedora Linux 40
 - OS version: Fedora release 40 (Forty)
 - Platform: x86_64
 - MPD version: 18.2.2

**Additional context**

Same error occurs when downloading and installing the RPM package file directly.

`whiptail` is already installed in the system.

Thank you for making myMPD!

**Comment by jcorporation** [comment]
whiptail is hardcoded in the dependeny list. How is the package named in fedora?

**Comment by Crawron** [comment]
> whiptail is hardcoded in the dependeny list. How is the package named in fedora?

there's a binary for whiptail in the package `newt` https://packages.fedoraproject.org/pkgs/newt/newt/
