### ISSUE TITLE
UI broken with long streaming url.

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#139]
**Describe the bug**
UI is broken as attached.

**To Reproduce**
You may reproduce this with the following streaming.
http://serpent0.duckdns.org:8088/kbs1fm.pls

**Expected behavior**
UI should stay in the format and not exceed the visible area.

**Screenshots**
Refer to the attached file.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - Browser : Firefox
 - Version : 68.0.1

![2019-08-09-164410_1600x900_scrot](https://user-images.githubusercontent.com/12131158/62763141-cfd9ec80-bac5-11e9-86d0-06ad0848150a.png)

**Comment by jcorporation** [comment]
Is now fixed in devel.

**Comment by parkmino** [comment]
It works fine with 'Playback'.
Please review 'Queue' as well.

![2019-08-19-220739_1600x900_scrot](https://user-images.githubusercontent.com/12131158/63267815-cd4d7300-c2cd-11e9-8b38-7758f59b6cd9.png)

**Comment by jcorporation** [comment]
Is now fixed also for all Title columns.

**Comment by parkmino** [comment]
Still same problem with queue.

**Comment by parkmino** [comment]
Sorry, it works fine.
Cache issue on my side.
