### ISSUE TITLE
Scripts are not working since update to newest version

### ISSUE THREAD

**Issue by td598** [jcorporation/myMPD#1391]
myMPD version: 9.0.0

I use the following scripts:
- Blissify
- Similar Artist
- Widget Albums

running each of the scripts lead to the following error message:

API Fehler
Fehler beim Zugriff auf http://192.168.178.43:8080/script/default/SimilarArtists?count=10,
Fehlercode: 500 - Internal server error

API Fehler
Fehler beim Zugriff auf http://192.168.178.43:8080/script/default/WidgetAlbums?entries=5&view=random,
Fehlercode: 500 - Internal server error

Fehler beim Ausführen des Skripts Blissify: Unknown error: method is NULL

**Comment by jcorporation** [comment]
There was an error in the central Lua API wrapper. Is now fixed in devel. Please test.
