### ISSUE TITLE
"clickable" and "search" option in "Playback" is inconsistent

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#1396]
On the "Playback" screen one can hoover over the tags which are configured to be displayed. If they are clickable the pointer changes its shape to indicate that clicking on them is possible and will invoke a search for this tag value.

But at least for two tags (I have not tested all available) the behaviour appears not to be consistent:

"Filetype" - pointer does not change (correct, as it is not searchable with mpd 0.23.16) but it can be clicked (incorrect) which then produces an error "Unknown filter type: Filetype".

"Date" - pointer does not change (incorrect, as it is searchable), but it can be clicked (correct) which then invokes the search.

The MPD version used is 0.23.16 (current stable) and I can reproduce it with myMPD version 18.2.2 and 19.0.2

Actually no big deal, but I thought I report it anyway.

**Comment by jcorporation** [comment]
Thanks for reporting this bug. The click handler checks now for the `clickable` class. Only the tags witch are in the list of "Tags to browse" should be clickable.

**Comment by GK-774** [comment]
Sorry, I cannot confirm that it works now. I have "Tags to browse: Album, Albumartist, Artist, Composer", these are shown as clickable, but only "Album" triggers a reaction. Clicking e.g. "Artist" or "Albumartist" does nothing (as well as "Composer" if available).

**Comment by jcorporation** [comment]
You checked it with the devel branch?

**Comment by GK-774** [comment]
Just tested, works perfectly. Many Thanks!
