### ISSUE TITLE
Add a stop button

### ISSUE THREAD

**Issue by CultofRobots** [jcorporation/myMPD#14]
I would love a stop button next to play/pause.

Thanks.

**Comment by jcorporation** [comment]
I recently removed it, because I never used it...
Whats your use case?

**Comment by CultofRobots** [comment]
Just the opposite; I never use toggle. If I have to pause a track for a minute I go back to the beginning of the track.

I often use a "stop after current track" script as well but, with the exception of podcasts, I never pause a track in the middle and pick up where I left off.
