### ISSUE TITLE
Option to run as web file server.

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#140]
**Is your feature request related to a problem? Please describe.**
Could it be possible to add the option to act as a web file server?

**Describe the solution you'd like**
Play music in musicdirectory from remote web browsers and retrieve cover arts from other mpd clients.

**Comment by jcorporation** [comment]
This already works. The music directory is accessible under ``/library/``. In the devel branch directory listing under ``/library/`` is now enabled.
