### ISSUE TITLE
Wrong wrap of words at song titles

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#143]
**Describe the bug**
In the latest version(today) even a title with three words, is very ugly wrapped in mobile version of myMPD.

**To Reproduce**
1. Go to mympd page on your mobile phone (i have a 6.23 inch screen)
2. look at the titles of the folders or song titles

**Expected behavior**
At the previous versions one :)

**Screenshots**
![Screenshot_2019-08-20-21-25-25-346_org mozilla focus](https://user-images.githubusercontent.com/18086896/63374103-d3a52300-c391-11e9-9424-8eb20d1e9a0a.png)

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi 7]
 - OS: [Android]
 - Browser [Firefox]
 - Version [latest]

**Additional context**
I think it breaks after today's changes.

Thank you JC.

**Comment by jcorporation** [comment]
This is a problem with the fix from #139

**Comment by jcorporation** [comment]
I added a min-width of 6rem to the title columns, this should fix the issue.
