### ISSUE TITLE
Album images in Filesystem view

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#144]
**Is your feature request related to a problem? Please describe.**
Is it be possible, to display the image of the album, at the left of the title, in Filesystem View?

**Describe the solution you'd like**
Display the Album image at Filesystem View

**Comment by jcorporation** [comment]
On each row for each title / directory?
Or the coverimage once if you navigate in a subdir?

**Comment by Emilot** [comment]
On each row if you think it can be possible.

Right now it has the folder icon at the left. In the place of that icon.

**Comment by jcorporation** [comment]
It is possible, but the performance wouldn't be good and the size of the image is to small for a nice effect. Displaying the coverimage in folder is more considerable in my opinion, but I see no good place for it.

**Comment by Emilot** [comment]
Hmmm... You are right. What do you say for an "Album View" mode in Filesystem?

No text, just the coverimage of the album in a grid gallery.

**Comment by jcorporation** [comment]
A albumgrid could be nice. I saw it in other frontends. This could be a forth tab in the browse card.

**Comment by Emilot** [comment]
Perfect!

**Comment by jcorporation** [comment]
I close this issue now. Don't hesitate to open an issue for the albumgrid feature. Please describe which functions this features should have in your opinion.
