### ISSUE TITLE
[devel] Linefeed for Type in Korean

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#148]
Please refer to the following screenshot.

![2019-08-26-224648_1600x900_scrot](https://user-images.githubusercontent.com/12131158/63696082-e9fd2400-c854-11e9-9146-d38b5bde2d5d.png)

**Comment by parkmino** [comment]
It is in devel and I will reopen it later.

**Comment by parkmino** [comment]
I translated Type for Korean in devel, it linefeeds as above.

**Comment by jcorporation** [comment]
I updated the translation file and fixed linefeeds in table headers.
