### ISSUE TITLE
Support redirecting url

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#149]
When a redirecting url is added, the stream does not play.
The redirected url itself plays well.
e.g. http://serpent0.duckdns.org:8088/kbsfm.pls

**Comment by jcorporation** [comment]
Streams are handled directly by mpd. Nothing to fix in myMPD.

**Comment by parkmino** [comment]
I know mpd does not handle either.
However some mpd clients like cantata and skympc plays this stream.
That's why I asked.

**Comment by jcorporation** [comment]
Can you give me the link to the upmpdcli issue?

**Comment by jcorporation** [comment]
found: https://www.lesbonscomptes.com/upmpdcli/github-issues/upmpdcli-html/issue-105.html
