### ISSUE TITLE
Add build option for gpg package signing in build.sh

### ISSUE THREAD

**Issue by CultofRobots** [jcorporation/myMPD#154]
As title states. Thanks.

**Comment by jcorporation** [comment]
running ``makepkg --sign <packagename>`` is enough?

**Comment by CultofRobots** [comment]
> For arch: running `makepkg --sign <packagename>` is enough?

Correct for arch. I don't remember the process for debian based distros.

**Comment by jcorporation** [comment]
Debian package signings seems unusual: https://blog.packagecloud.io/eng/2014/10/28/howto-gpg-sign-verify-deb-packages-apt-repositories/

Signing is done with:
$ debsigs --sign=origin -k E732A79A test_1.0-7_amd64.deb

**Comment by CultofRobots** [comment]
Looking more into it, you probably don't even have to worry about accommodating package signing in debian. If you're running a custom repo you're probably using reprepro which handles package signing when adding to the repo. 

See here: https://wiki.debian.org/DebianRepository/SetupWithReprepro#Signing_Debian_packages_without_adding_to_repository

All that being said, I haven't run a custom debian repo in years so don't take my word for it.

**Comment by jcorporation** [comment]
dpkg-sig seems to be the preferred tool.

**Comment by jcorporation** [comment]
In devel you can now sign debian and arch packages. Set environment variables SIGN="TRUE" and GPGKEYID="<yourgpgkey>" to use this option. 

Signing the debian package triggers the lintian error "misplaced-extra-member-in-deb _gpgbuilder", but this seems normal: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758054.
