### ISSUE TITLE
Diabled coverimage support

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#158]
Cover image is not supported even when 'coverextract = true' is set in /etc/mympd.conf and /usr/lib/mympd/libmympd_coverextract.so file exists.
myMPD shows 'WARN Disabling coverimage support' when it starts up.
FYI, I have not been using MPD tags however there was no problem.

**Comment by parkmino** [comment]
Settings > Theme > Albumart shows 'cat's access the music directory', even though my music directory is readable for all users and groups.

**Comment by parkmino** [comment]
I cannot browse 'localhost/library'

**Comment by jcorporation** [comment]
Please check the music directory in the connection dialog, both errors based on a inaccesible music directory.

**Comment by parkmino** [comment]
'sudo chmod 777 -R /var/lib/mympd' seems to solve this issue.

**Comment by parkmino** [comment]
This issue has been resolved after '/var/lib/mympd' directory removed and reinstalled.
