### ISSUE TITLE
Support booklets, lyrics and more pictures

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#160]
- [x] Detect booklet.pdf file - name is configurable
- [x] Detect lyrics textfile - name is musicfile + ".txt"
- Detect embedded lyrics - ULST tag (unsynced lyrics) - moved to #220
- [x] detect all images in a directory and let users skip through

**Comment by jcorporation** [comment]
https://github.com/MusicPlayerDaemon/MPD/pull/653

**Comment by ddonindia** [comment]
How does   `Detect lyrics textfile - name is musicfile + ".txt"`  feature works ?

I added a lyrics .txt file having same name as song but unable to figure out where to see lyrics.

**Comment by jcorporation** [comment]
Lyrics should appear in a tab in the songdetails dialog.

**Comment by ddonindia** [comment]
![image](https://user-images.githubusercontent.com/16450468/79633135-44027f00-8181-11ea-8e43-e8f4678d797e.png)

```
4912933 Apr 17 21:13 '00 Forever.mp3'
   1891 Apr 18 14:30 '00 Forever.txt'
```
Sorry but I dont see it. Is there any dependency on MPD version ?
I am running MPD and myMPD on ubuntu 19.10

**Comment by jcorporation** [comment]
You must enable the publish feature of myMPD.

**Comment by ddonindia** [comment]
```
#Publishes some mpd and myMPD directories
publish = true

#Webdav support, publish must be set to true
webdav  true

```
I have this

**Comment by jcorporation** [comment]
Is your music directory configured correctly. myMPD directly access this directory for this feature.

**Comment by ddonindia** [comment]
Its working after changing connection type to `unix socket` 
Thanks for your help

**Comment by ddonindia** [comment]
Is it possible to show lyrics in `Playback` tab ?
Should I open a new issue for this?

**Comment by jcorporation** [comment]
A new issue would be good.
