### ISSUE TITLE
Publish library, playlists and pics through http and webdav

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#161]
- [x] Elaborate WebDAV support in mongoose
- [x] Publish directories
  - [x] MPD music directory
  - [x] MPD playlist directory
  - [x] pics directory
  - [x] smartpls directory

**Config options**
  - [x] Publish through http
  - [x] Enable webdav

**Comment by john-** [comment]
Would WebDAV be used to add songs to the MPD backend?   I didn't know MPD had an interface to do that.   Or would this bypass MPD?

**Comment by jcorporation** [comment]
Webdav could be used to transfer files to the filesystem. If myMPD has write access to the music directory of mpd, it can be used to create directories and upload songs and covers. Rescanning the library afterwards add the songs to the mpd database. myMPD uses no other database.
