### ISSUE TITLE
Albumart Grid View

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#162]
Add a Albumartgrid as new tab to the browse card.
- [x] get first song from all albums to display the grid 
- [x] search function album / artist tags
- [x] sort function album / artist / date 
- [x] display song list on demand 
- [x] typical album actions: add to / replace queue 
- [x] customizable template images

**Comment by Emilot** [comment]
JC is on spree....

A big salute for all the enhancements i saw!

Next version will be awesome :)

**Comment by jcorporation** [comment]
All this enhancements are only ideas. They will be spread about the next releases. The next release is a backend rewrite to integrate the dynamic string library sds and port the api to json rpc 2.0.

**Comment by john-** [comment]
I am slowly getting album art to my relatively extensive collection.   What are your thoughts on how to present those albums without cover art?   A generic image like is used elsewhere in myMPD?   That sea of generic images might get me motivated to get art for my collection :)

**Comment by Emilot** [comment]
A generic image i agree. Maybe with an addition for this request, to allow users to specify something of their own as an image?

**Comment by jcorporation** [comment]
Emilot:
![mympd](https://user-images.githubusercontent.com/18086896/65393459-78e45a00-dd89-11e9-9713-b22c23f3ed37.jpg)

My vote is of course for the album grid view. I made a "preview" suggestion for it some time ago but i haven't found the time to upload it. So here it is :)

I guess the functions like, add album to queue, play album, etc...will be included.

**Comment by jcorporation** [comment]
@Emilot: Really nice mookup. Sorting by Albumname or Albumartist?

**Comment by Emilot** [comment]
AlbumArtist JC

**Comment by Emilot** [comment]
JC i love the new covergrid! 6.0.0 will be awesome and i am grateful for your amazing work. Looking forward for the release. (as i see libmpdclient is officially at 2.17 with all the new goodies(mount, listneighbors, etc. Perfect timing!)

Greetings!

**Comment by jcorporation** [comment]
Thanks Emilot. I update the state of implementation in the first post.

**Comment by jcorporation** [comment]
Albumart Grid View is now feature complete in the rework_cover branch

**Comment by Emilot** [comment]
JC we have a few problems! 

1) In dark theme i can't see the songs(they have white color fonts)
2) When i click on image, the image resize itself and getting the 100% pixel size of the resolution(css fix)

just to mention a few small things...in the devel state.

Awesome work!

**Comment by jcorporation** [comment]
Thanks for testing Emilot, but I can't reproduce your errors. Have you cleared your browser and app cache? I am testing with Firefox and Chromium.

**Comment by Emilot** [comment]
To test this without caching clearing, etc...i choose Edge browser....

With default theme

![Edge-Mympd](https://user-images.githubusercontent.com/18086896/70946495-e7bb1180-205f-11ea-968d-c89723e57e49.jpg)

With Dark Theme
![Edge-Mympd-Dark](https://user-images.githubusercontent.com/18086896/70946521-f1447980-205f-11ea-883f-c9b4ab4fc05f.jpg)

**Comment by Emilot** [comment]
Resize issue...

Before...
![albumart resize -1](https://user-images.githubusercontent.com/18086896/70946766-7760c000-2060-11ea-9b17-b1794d55ddcf.jpg)

After...
![albumart resize -2](https://user-images.githubusercontent.com/18086896/70946792-80519180-2060-11ea-82cf-d05ec798c7af.jpg)

**Comment by Emilot** [comment]
Ok JC... With your latest commits of yours at devel, everything seems fine!

Thank you again! Really beautiful job.

**Comment by jcorporation** [comment]
Seems to be a css issue. Please try ``./build.sh cleanupdist`` before compiling as normal. The distributed dist files in devel are not up-to-date all the time.
