### ISSUE TITLE
Improve Jukebox 

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#164]
- [x] auto enable consume
- [x] keep a random list from which the songs are added, don‘t skip through the complete library/playlist each time 
- [x] enforce optional constraints on this list:
  - [x] unique artist
  - [x] unique album
  - [x] last_played older than XX

**Comment by john-** [comment]
Auto enable consume:  This makes sense.   I always have consume mode on so when I switch to jukebox mode I don't have to change it.   I guess the people that would have a problem with this are those that don't want consume mode on.

For the random list:  Is this filters applied to all the songs in the library/playlist?

The "unique artist" constraint would be if library had 20 albums by a specific artist then only album would be in the random play list?   I am not really clear how "unique artist" and "unique albums" constrain  the list.

I like the last_played older than XX to stop repeats from happening.

**Comment by jcorporation** [comment]
The random list will be filled from the database or Chosen playlist respecting the above constraints. The size of this random list is variable and the list will be appended in chunks. From this list the first x songs will be moved to the queue.

The unique artist and album constraints ensures that in the random list there tags are unique. Only one song from an artist or album. Constraints can be turned on or off.

**Comment by john-** [comment]
Sounds good.   That will for sure help balance thing out.

**Comment by jcorporation** [comment]
john-:
My vote is for the [jukebox enhancement](https://github.com/jcorporation/myMPD/issues/164#issue-496759338).    It is the one that has the most immediate use for me.   I am still trying to get my head around some of the other enhancement ideas however so may vote again later!
