### ISSUE TITLE
Improve (smart) playlists

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#165]
**Smart playlists**
- [x] Most played: Auto-value or custom value
- [x] Add interface to create default smart playlists
- [x] Option to maintain one smart playlist per browsetag
- [x] Add documentation for smart playlist format to wiki
- [x] Add shuffle and sort option to smart playlists
- [x] Add option to configure prefix (currently myMPDsmart)
- [x] Update smart playlists periodically

**Common playlists**
- [x] Add "Add to playlist" action for current song in playback card
- [x] Option to shuffle or sort playlists

**UI**
- [ ] replace a-z filter through search
- [ ] sort list by name or modification date

**Advanced dialog**
- [x] delete all smart playlists
- [x] delete all playlists
- [x] delete all empty playlists

**Comment by thaihugo** [comment]
Also allow exclusion (minus an artist or an mpd folder) and smart playlist creation using text files With a proper documentation?

**Comment by jcorporation** [comment]
Exclusion should already work with saved searches, but not for sticker based smart playlists. Folder exclusions for sticker based playlists are easy to implement. Exclusions based on tags like Artist are cumbersome to implement, because of the way stickers are implemented in mpd (Protocol).

**Comment by jcorporation** [comment]
I don’t implement new features for sticker based smart playlists. In a future version stickers will be searchable like tags.

**Comment by jcorporation** [comment]
Documentation: https://github.com/jcorporation/myMPD/wiki/Smart-playlists

**Comment by jcorporation** [comment]
UI enhancements are postponed to v7.0.0 milestone
