### ISSUE TITLE
Vote for enhancements

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#166]
All enhancements listed here are only ideas. You can vote for an enhancement, diskuss the details or propose a new enhancement. They will be implemented (or not) in no predefined order or timeline. 

Vote for a feature to push the propability for timely implementation up. Please don't vote in this issue, vote directly in the approbriated enhancement issue.

**Comment by john-** [comment]
My vote is for the [jukebox enhancement](https://github.com/jcorporation/myMPD/issues/164#issue-496759338).    It is the one that has the most immediate use for me.   I am still trying to get my head around some of the other enhancement ideas however so may vote again later!

**Comment by Emilot** [comment]
![mympd](https://user-images.githubusercontent.com/18086896/65393459-78e45a00-dd89-11e9-9713-b22c23f3ed37.jpg)

My vote is of course for the album grid view. I made a "preview" suggestion for it some time a go but i haven't find the time to upload it. So here it is :)

I guess the functions like, add album to queue, play album, etc...will be included.

**Comment by jcorporation** [comment]
Please don't vote in this issue, vote directly in the appriate enhancement issue.

**Comment by jcorporation** [comment]
Merged in issue #167
