### ISSUE TITLE
Package contains reference to $srcdir

### ISSUE THREAD

**Issue by CultofRobots** [jcorporation/myMPD#17]
**Describe the bug**
Package contains reference to $srcdir in mympd binary when building in arch linux (armv7 and x86_64)

 - v3.0.0
 - v3.0.1
 - latest git master branch
 - latest devel.

**To Reproduce**
build package using mkrelease. 
run: 
$ grep -R "$(pwd)/src" release/mympd
will return: Binary file release/mympd matches

**Desktop (please complete the following information):**
 - Arch Linux Linux 4.14.52-1-ARCH #1 SMP Thu Jun 28 00:45:47 UTC 2018 armv7l GNU/Linux
 - confirmed on Arch Linux 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux
 - also confirmed on Debian Testing 4.14.17-1 (2018-02-14)

**Additional Information
No issues in build with v2.3.0 and prior on both arch and debian testing.

**Comment by jcorporation** [comment]
Thanks for that issue. I can reproduce it. I looked closer to my code any I think this issue comes from the new mongoose (grep src/mongoose/mongoose.c mympd).
