### ISSUE TITLE
File format - File type

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#180]
JC can you add to the Playback panel these two informations?

File format (16bit/44.1kHz)
and File type (Flac, Mp3, etc...)

Thank you.

**Comment by Emilot** [comment]
![mympd_1](https://user-images.githubusercontent.com/18086896/67572066-1e4e6d00-f73e-11e9-9c6c-fc7e098f3722.jpg)
for reference!

**Comment by jcorporation** [comment]
MPD provides samplerate, bits, channels.
Filetype must be guessed from file extension.
Adding audioformat and filetype to the selectable fields should be feasible.

Btw: is this only a mookup or a patched myMPD?

**Comment by Emilot** [comment]
Oh no JC. Just a mookup...

**Comment by jcorporation** [comment]
Is now in devel.
