### ISSUE TITLE
Firefox 72 (nightly): "Can not parse settings"

### ISSUE THREAD

**Issue by 9ParsonsB** [jcorporation/myMPD#182]
**Describe the bug**
when using Firefox 72, loading MyMpd gives the error "Can not parse settings"

**To Reproduce**
1. Install FireFox 72 (nightly)
2. navigate to MyMpd

**Expected behavior**
MyMpd should load as per normal

**Screenshots**
![image](https://user-images.githubusercontent.com/6250431/67646852-0c5e0b80-f984-11e9-97c2-e534ee3a9f90.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Browser: Firefox 
 - Version: 72.0a1 (2019-10-27) (64-bit)

**Additional context**
I understand that this is probably a Firefox issue (in which case I will open a bug report in their system), although any help figuring out the issue would be much appreciated.
JS Console:
```
INFO: ServiceWorker registration successful. combined.js:1645:268
ERROR: Empty response for request: {"cmd":"MYMPD_API_SETTINGS_GET"} combined.js:1645:230
TypeError: ServiceWorker script at https://172.31.0.111/sw.js for scope https://172.31.0.111/ encountered an error during installation.
```

**Comment by jcorporation** [comment]
What myMPD version?
Your myMPD installation works with a stable firefox?
Can you look at the network tab of the web console and are there any errors?

**Comment by 9ParsonsB** [comment]
The MyMpd version was master at the time of testing. pacman reports: `5.6.2-1`
Yes, it works with stable FireFox and Chrome.
the network tab shows the following:
![image](https://user-images.githubusercontent.com/6250431/67724332-d4fa6800-fa32-11e9-8c56-5e7280238862.png)
so it looks like it doesn't like the self-signed cert... I have created an exception for it though so not sure why it still doesn't work.

**Comment by 9ParsonsB** [comment]
I was able to discover a work-around by navigating to `https://172.31.0.111/api` where Firefox prompted for me to accept the self signed cert again (after which I was given an invalid API request), then navigating to MyMpd worked as per usual.

Maybe missing something from the http header / ssl cert configuration?`

**Comment by jcorporation** [comment]
For ssl there is no special configuration needed / available. You can import the myMPD ca certificate (in filesystem ``/var/lib/mympd/ssl/ca.pem`` or download it in the About dialog to trust the certificate).

**Comment by 9ParsonsB** [comment]
I already an ssl cert generated and set. I guess my issue now becomes "why did I have to make an exception for `https://172.31.0.111` and `https://172.31.0.111/api`?" which I guess is more of a Firefox issue.
