### ISSUE TITLE
Initializing myMPD error in v.5.7.0

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#190]
myMPD version: [5.7.0]

**Describe the bug**

Stuck at "Initializing myMPD"

**Screenshots**

![mympd 2](https://user-images.githubusercontent.com/18086896/68706808-31b06380-0599-11ea-8186-ecb2d83ebb59.jpg)

![mympd](https://user-images.githubusercontent.com/18086896/68706833-3f65e900-0599-11ea-8d60-e2b49d4f1bb4.jpg)

**Client plattform (please complete the following information):**
Firefox latest version.

Chrome latest version

Cleared cache

**Comment by jcorporation** [comment]
Please try to run ``rm dist/htdocs/index.html.gz`` before building. It seems this file was outdated in this release

**Comment by Emilot** [comment]
Perfect JC!

Case solved.
