### ISSUE TITLE
Albumart size is not changing v.5.7.1 

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#193]
myMPD version: [5.7.1]

**Describe the bug**

Change size number at Settings (350 ex.) and nothing happens.

**Expected behavior**

Change image size

**Screenshots**

**Server plattform (please complete the following information):**
 - MPD version: [0.21.16]
 - Libmpdclient Version: [2.16]

**Client plattform (please complete the following information):**
 - Browser [Chrome, Firefox]
 - Browser version [latest]

**Debug logs (please attach if it can be usefull)**

No errors at web console. Also this is happens to devel edition.

**Comment by jcorporation** [comment]
Fixed in devel
