### ISSUE TITLE
Tag emulation from folder structure.

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#195]
I would be helpful to emulate tags based on folder structures. e.g. /artist - album/songs, /artist/albums/songs.
You could refer to Cantata which supports this feature.

**Comment by jcorporation** [comment]
Cantata seems to use a cache for the mpd database. myMPD queries MPD directly, which is in my opinion the better way. Without a cache, this feature is to complex to implement.

Why you don‘t use tags, if you want such features?

**Comment by parkmino** [comment]
I have no idea how much this feature is complicated to implement.
Cantata supports this feature and simply I like this feature.

Tagging is somewhat tedious work to do and it hard to tag wave files without converting to aiff.
Without tags, DB updates fast and huge DB is acceptable even though the music storage is more than several TB, UPnP media server could be the only solution.

**Comment by jcorporation** [comment]
What features should work with tag emulation?

**Comment by parkmino** [comment]
You took this issue as enhanced and asked me the reason why.
And you asked me what it means? I do not not understand what you are talking about.

**Comment by jcorporation** [comment]
My question revised: should the emulated tags allow the same functionality as real tags  e.g. Browse by Tag, search by Tag or is this only a feature how songs are displayed?

**Comment by parkmino** [comment]
Yes, even tag editor can be used.

**Comment by john-** [comment]
Seems like using directory and file names in place of explicit tags will have a lot of corner conditions and require esoteric configuration (e.g. pattern matching).   If wav file doesn't support tags convert them to flac and add tags to that.   Yes, there is upfront work but I picture anything else to be pretty brittle.

**Comment by jcorporation** [comment]
Thanks for this feature request, but I don't implement it. The backend structure of myMPD queries MPD directly and uses no cache. This behaviour is a essential design decision of myMPD.
