### ISSUE TITLE
Remove coverextract plugin 

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#199]
The coverextract plugin should be replaced with a native c implementation.

- [x] libid3tag for id3 tag support 
- [x] libflac for flac and ogg support

Any other format to consider?

**Comment by Emilot** [comment]
JC take a look at Ape, Apple's .M4A/ACC and Microsoft's WMA. I am not sure about the last two, though.

**Comment by jcorporation** [comment]
Are this music formats are widely used?

**Comment by Emilot** [comment]
Ape is a known file format. ACC is used in streaming radio services. WMA i wouldn't bother at all.

**Comment by jcorporation** [comment]
This function does not work with streams. I will look into APE support.

**Comment by jcorporation** [comment]
It seems APE is not widely supported. I don't think it is worth the effort to support this format for embedded coverart. The upcoming MPD 0.22 supports also embedded albumart. If then new readpicture command supports embedded images in APE tags, myMPD would support it either.
