### ISSUE TITLE
UI Enhancements 

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#200]
- [x] move column select in table header
- [x] add quick playback settings (random, single, etc.) to playback card 
- [x] polish notifications

**Improve covergrid**
- [x] add all database browse tags to filter and sort selects
- [x] merge covergrid with database view -> v6.7.0
- [x] configurable minimal amount of songs in an album for the album to appear in the covergrid

**Improve playlists**
- [x] replace a-z filters with searchbar
- [x] sort playlists by name

**Improve filesystem browsing**
- [x] replace a-z filters with searchbar
- [x] show pictures in directories

**Improve queue**
- [x] add goto playing track button

**Comment by jcorporation** [comment]
> configurable minimal amount of songs in an album for the album to appear in the covergrid

In the backend myMPD implements the covergrid by searching for all songs with the track number 1. The track number is now configurable with the config options ``covergridminsongs``.

**Comment by pinkdotnl** [comment]
With the new covergrid, which is my main search view, I would like to see an option to rearrange the tabs. But I just noticed that you already intent to merge covergrid with database view, which would be even better :-)

**Comment by koflesinge** [comment]
Covergrid is awesome.
It would be even better if we could click on the albumart, and be offered option to add to queue, replace queue, ...
As we do in the Database view

Thanks !

**Comment by pinkdotnl** [comment]
> Covergrid is awesome.
> It would be even better if we could click on the albumart, and be offered option to add to queue, replace queue, ...
> As we do in the Database view
> 
> Thanks !

This is already possible by clicking on the album title below the cover.

**Comment by koflesinge** [comment]
Thanks for the tip. I didn't notice before.

But once you click on the coverart to see the tracklist, you cant add
the full album to the playlist.

**Comment by jcorporation** [comment]
> On another note, would you consider merging the playback and queue view ?

If more people support this future request

**Comment by pinkdotnl** [comment]
> > On another note, would you consider merging the playback and queue view ?
> 
> If more people support this future request

For me, adding the queue would be an option for the desktop view, there is a lot of whitespace we  could use. In mobile view I personally see no added value. Queue is just one touch away.

**Comment by jcorporation** [comment]
Mobile and desktop view should be the same. I don‘t want different features for different devices.

**Comment by koflesinge** [comment]
To explain me better perhaps.
Many players merge queue and playback view. I find it quite useful, so i can search for a song, and seek through it, see how many songs are left in the queue while looking at the cover, ...

With myMpd, I find myself going back and forth between the two views.

I do understand that you dont want different features for different devices.

Maybe then, adding a smaller playback control in the queue view could be the best of both world ?

**Comment by jcorporation** [comment]
I'm thinking about a playbar on the side or bottom of the screen.

**Comment by john-** [comment]
There is already play controls in upper right at all times.   Maybe just add song timer.   I just noticed that there is speed button to display with some of the server settings (Random, Consume, etc).   Now that I know about that it might be nice to have that as well!

**Comment by jcorporation** [comment]
The place on the upper right corner is rather limited on mobile devices (I test with a iPhone 11). 

My idea: 
The playbar will unifiy both bars at top and bottom. In landscape orientation the bar is at the top or bottom, in vertical mode left or right. This bar could also host the quick playback settings.

**Comment by koflesinge** [comment]
Maybe the top bar can be a bit bigger, with a seek a bar, a small cover
view, and a "next song in the queue"  ?

Then the playback view is useful only for full track info and a big
cover ?

**Comment by jcorporation** [comment]
This could be possible. I will build some mookups before rebuilding the ui.

**Comment by KamilBaczkowski** [comment]
In the playback view artist and album info have the clickable class, but clicking either does nothing. It would be nice if that two routed to respectively artist's albums and singular album view. The only way I can do it now is by clicking the song name and using the artist/album links in there.
