### ISSUE TITLE
mympd 5.7.2 keeps crashing when the song changes, when I change settings etc..

### ISSUE THREAD

**Issue by archphile** [jcorporation/myMPD#203]
I just did a clean install and created mympd package using the provided PKGBUILD.

I keep getting various errors:

mympd crashes:

- when changing any of the settings and saving
- when a song ends and the next one starts
- when I add an album

The error I get is "Websocket connection failed".

Software details:

**ArchlinuxARM aarch64
myMPD 5.7.2
MPD 0.21.16
libmpdclient 2.17**

Please feel free to ask me for any additional debugging output that might be useful to you.

Greetings,
Mike

**Comment by jcorporation** [comment]
The MPD verbose log and the myMPD debug log would be useful.

**Comment by archphile** [comment]
myMPD 5.7.2
MPD .21.16
libmpdclient 2.17

I cannot find any log from myMPD. I changed log level to 4 and this is the output when running it from the terminal:

This is when the song changes to the next one:
```
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/mpd_client.c:345: Entering mpd idle mode
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/web_server.c:191: Sending notify to conn_id 3: {"jsonrpc":"2.0","method":"update_queue","params":{"state":2,"queueLength":6,"queueVersion":6,"songPos":0,"nextSongPos":1}}
Illegal instruction
```

This is when changing settings:

```
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/mpd_client.c:345: Entering mpd idle mode
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/mpd_client.c:309: Leaving mpd idle mode
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/mpd_client.c:317: Checking for idle events
VERBOSE  /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/mpd_client.c:97: MPD idle event: options
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/mpd_client/mpd_client_utility.c:30: Push websocket notify to queue: {"jsonrpc":"2.0","method":"update_options","params":{}}
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/mpd_client.c:345: Entering mpd idle mode
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/web_server.c:167: Setting music_directory to /var/lib/mpd/music
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/web_server.c:170: Setting rewrite_patterns to /library/=/var/lib/mpd/music,/pics/=/var/lib/mympd/pics
VERBOSE  /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/web_server.c:270: HTTP request (3): /api
VERBOSE  /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/web_server.c:393: API request (3): {"jsonrpc":"2.0","id":0,"method":"MYMPD_API_SETTINGS_GET","params":{}}
DEBUG    /home/alarm/packages-master/mympd-archphile/src/myMPD-v.5.7.2/src/web_server.c:191: Sending notify to conn_id 4: {"jsonrpc":"2.0","method":"update_options","params":{}}
Illegal instruction
```

This is the MPD verbose log:

https://pastebin.com/9kL9LiMg

**Comment by jcorporation** [comment]
Illegal instruction sounds bad. Can you compile it with debug symbols enabled and run it under gdb?
```
./build.sh memcheck
gdb debug/mympd
```
under gdb type ``run`` to start the program
Press Ctrl+C and type ``bt 50`` after the error appears.

**Comment by archphile** [comment]
I have never used the build.sh script before. If I install this way, will I be able to uninstall after? Can I compile with debug symbols using the PKGBUILD?

**Comment by jcorporation** [comment]
The debug build don't installs anything, it just compiles.

**Comment by archphile** [comment]
I am trying to run it but I get this:

```
(gdb) run
Starting program: /root/myMPD-master/debug/mympd 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
INFO     /root/myMPD-master/src/main.c:310: Starting myMPD 5.7.2
INFO     /root/myMPD-master/src/main.c:311: Libmpdclient 2.17.0
INFO     /root/myMPD-master/src/main.c:312: Mongoose 6.16
INFO     /root/myMPD-master/src/config.c:359: Parsing config file: /etc/webapps/mympd/mympd.conf
WARN     /root/myMPD-master/src/config.c:361: Can't parse config file /etc/webapps/mympd/mympd.conf, using defaults
INFO     /root/myMPD-master/src/log.c:26: Setting loglevel to DEBUG
INFO     /root/myMPD-master/src/utility.c:164: Localstate dir: "/var/lib/mympd"
INFO     /root/myMPD-master/src/utility.c:164: SSL certificates: "/var/lib/mympd/ssl"
INFO     /root/myMPD-master/src/cert.c:77: CA certificate and private key found
INFO     /root/myMPD-master/src/cert.c:133: Server certificate and private key found
INFO     /root/myMPD-master/src/web_server.c:98: Listening on http port 80
INFO     /root/myMPD-master/src/web_server.c:112: Listening on ssl port 443
DEBUG    /root/myMPD-master/src/web_server.c:113: Using certificate: /var/lib/mympd/ssl/server.pem
DEBUG    /root/myMPD-master/src/web_server.c:114: Using private key: /var/lib/mympd/ssl/server.key
INFO     /root/myMPD-master/src/main.c:123: Droping privileges to mympd
ERROR    /root/myMPD-master/src/utility.c:182: Document root: "/root/myMPD-master/htdocs" don't exists
[Inferior 1 (process 1238) exited with code 01
```

**Comment by jcorporation** [comment]
Strange, does "/root/myMPD-master/htdocs" really doesn't exist or are only the permissions to restrictive?

**Comment by archphile** [comment]
No, it exists:

[root@archphile myMPD-master]# ls -la
total 108
drwxr-xr-x 9 root root  4096 Dec 17 15:26 .
drwxr-x--- 5 root root  4096 Dec 17 15:25 ..
-rwxr-xr-x 1 root root 16747 Dec 11 00:28 build.sh
drwxr-xr-x 2 root root  4096 Dec 11 00:28 cmake
-rw-r--r-- 1 root root  6426 Dec 11 00:28 CMakeLists.txt
drwxr-xr-x 4 root root  4096 Dec 11 00:28 contrib
drwxr-xr-x 5 root root  4096 Dec 17 15:26 debug
drwxr-xr-x 5 root root  4096 Dec 11 00:28 dist
-rw-r--r-- 1 root root   323 Dec 11 00:28 .eslintrc.js
drwxr-xr-x 4 root root  4096 Dec 11 00:28 .github
-rw-r--r-- 1 root root   116 Dec 11 00:28 .gitignore
-rw-r--r-- 1 root root  1353 Dec 11 00:28 .gitlab-ci.yml
drwxr-xr-x 6 root root  4096 Dec 11 00:28 htdocs
-rw-r--r-- 1 root root 18011 Dec 11 00:28 LICENSE
-rwxr-xr-x 1 root root   375 Dec 11 00:28 mkrelease.sh
-rw-r--r-- 1 root root  3081 Dec 11 00:28 README.md
-rw-r--r-- 1 root root   324 Dec 11 00:28 SECURITY.md
drwxr-xr-x 6 root root  4096 Dec 11 00:28 src
[root@archphile myMPD-master]# cd htdocs/
[root@archphile htdocs]# ls
assets	css  index.html  js  mympd.webmanifest	sw.js  sw.js.in  test
[root@archphile htdocs]# ls -la
total 124
drwxr-xr-x 6 root root  4096 Dec 11 00:28 .
drwxr-xr-x 9 root root  4096 Dec 17 15:26 ..
drwxr-xr-x 2 root root  4096 Dec 11 00:28 assets
drwxr-xr-x 2 root root  4096 Dec 17 15:25 css
-rw-r--r-- 1 root root 88172 Dec 11 00:28 index.html
drwxr-xr-x 2 root root  4096 Dec 17 15:26 js
-rw-r--r-- 1 root root   443 Dec 11 00:28 mympd.webmanifest
-rw-r--r-- 1 root root  2097 Dec 11 00:28 sw.js
-rw-r--r-- 1 root root  2103 Dec 11 00:28 sw.js.in
drwxr-xr-x 2 root root  4096 Dec 11 00:28 test

**Comment by jcorporation** [comment]
I think the mympd user has no access to this directory, becaus it is under /root

**Comment by archphile** [comment]
I was compilint latest git version by mistake. I now compiled 5.7.2 and I get the same error:

I will compile under a different location and let you know.

**Comment by archphile** [comment]
I did a 

`chown -R mympd:mympd  myMPD-v.5.7.2 `

and nothing changed. Should I build as a normal user?

**Comment by jcorporation** [comment]
The underlying directory /root is the problem, not the permission of the mympd directory. The complete path to the htdocs directory must have the correct permissions (rx).

**Comment by archphile** [comment]
I created a new user, I compiled again, I tested with various different permissions and I still get the same error.

**Comment by jcorporation** [comment]
Can you paste the output of myMPD?

**Comment by archphile** [comment]
I created a user mympd from scratch with a shell and a password:

useradd -m -G users -s /bin/bash mympd
passwd mympd

I added him in sudoers

he compiled as you advised and run the gtb with sudo.

Mympd runs without any issue at all. I cannot reproduce the mentioned issues. I assume that something is missing from the pkgbuild.

**Comment by jcorporation** [comment]
With ``./build.sh release`` you can compile it with the same settings as the pkgbuild. The binary then is found in the directory ``release``.

**Comment by archphile** [comment]
I just did a ./build.sh release and the issues came back:

```
[mympd@archphile myMPD-v.5.7.2]$ sudo ./release/mympd
INFO     Starting myMPD 5.7.2
INFO     Libmpdclient 2.17.0
INFO     Mongoose 6.16
INFO     Parsing config file: /etc/webapps/mympd/mympd.conf
WARN     Can't parse config file /etc/webapps/mympd/mympd.conf, using defaults
INFO     Setting loglevel to INFO
INFO     Localstate dir: "/var/lib/mympd"
INFO     SSL certificates: "/var/lib/mympd/ssl"
INFO     CA certificate and private key found
INFO     Server certificate and private key found
INFO     Listening on http port 80
INFO     Listening on ssl port 443
INFO     Droping privileges to mympd
INFO     Smartpls dir: "/var/lib/mympd/smartpls"
INFO     State dir: "/var/lib/mympd/state"
INFO     Pics dir: "/var/lib/mympd/pics"
INFO     Empty dir: "/var/lib/mympd/empty"
INFO     Starting mympd api thread
INFO     Starting mpd client thread
INFO     Starting webserver thread
INFO     Reading states
INFO     Starting mpd_client
INFO     MPD connecting to 127.0.0.1:6600
INFO     MPD connected
INFO     MPD protocoll version: 0.21.11
WARN     Disabling featLibrary support
WARN     Disabling coverimage support
INFO     MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date OriginalDate Composer Performer Disc Label MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID MUSICBRAINZ_WORKID 
INFO     myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
INFO     myMPD enabled searchtags: Artist Album AlbumArtist Title Genre Composer Performer 
INFO     myMPD enabled browsetags: Artist Album AlbumArtist Genre Composer Performer 
INFO     Enabling advanced search
INFO     Updated smart playlist myMPDsmart-bestRated with 0 songs, minValue: 0
INFO     Updated smart playlist myMPDsmart-mostPlayed with 2 songs, minValue: 2
INFO     Updated smart playlist myMPDsmart-newestSongs
Illegal instruction
```
https://i.imgur.com/qQ0TKxw.png

**Comment by archphile** [comment]
I just read this:

https://github.com/jcorporation/myMPD/pull/204

As I understand, the purpose of your PKGBUILD is to be used with your script. When I say I used the PKGBUILD, I mean that I did it the Archlinux way, This means, that I used these files:

https://github.com/archphile/packages/tree/master/mympd-archphile

based on your PKGBUILD, with some path modifications and I just run makepkg -s.

I am just mentioning it, in case this affects the package creation.

**Comment by jcorporation** [comment]
The difference between debug and release build is the usage of embedded assets in release.
Can you run it under gdb?

**Comment by archphile** [comment]
Do you mean to:

./build.sh release

and then:

gdb release/mympd?

**Comment by jcorporation** [comment]
yes

**Comment by archphile** [comment]
```
(gdb) run
Starting program: /home/mympd/myMPD-v.5.7.2/release/mympd 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
INFO     Starting myMPD 5.7.2
INFO     Libmpdclient 2.17.0
INFO     Mongoose 6.16
INFO     Parsing config file: /etc/webapps/mympd/mympd.conf
WARN     Can't parse config file /etc/webapps/mympd/mympd.conf, using defaults
INFO     Setting loglevel to INFO
INFO     Localstate dir: "/var/lib/mympd"
INFO     SSL certificates: "/var/lib/mympd/ssl"
INFO     CA certificate and private key found
INFO     Server certificate and private key found
INFO     Listening on http port 80
INFO     Listening on ssl port 443
INFO     Droping privileges to mympd
INFO     Smartpls dir: "/var/lib/mympd/smartpls"
INFO     State dir: "/var/lib/mympd/state"
INFO     Pics dir: "/var/lib/mympd/pics"
INFO     Empty dir: "/var/lib/mympd/empty"
INFO     Starting mympd api thread
[New Thread 0xfffff7a461e0 (LWP 2282)]
INFO     Starting mpd client thread
INFO     Reading states
[New Thread 0xfffff72451e0 (LWP 2283)]
INFO     Starting webserver thread
INFO     Starting mpd_client
INFO     MPD connecting to 127.0.0.1:6600
[New Thread 0xfffff6a441e0 (LWP 2284)]
INFO     MPD connected
INFO     MPD protocoll version: 0.21.11
WARN     Disabling featLibrary support
WARN     Disabling coverimage support
INFO     MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date OriginalDate Composer Performer Disc Label MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID MUSICBRAINZ_WORKID 
INFO     myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
INFO     myMPD enabled searchtags: Artist Album AlbumArtist Title Genre Composer Performer 
INFO     myMPD enabled browsetags: Artist Album AlbumArtist Genre Composer Performer 
INFO     Enabling advanced search
INFO     Updated smart playlist myMPDsmart-bestRated with 0 songs, minValue: 0
INFO     Updated smart playlist myMPDsmart-mostPlayed with 2 songs, minValue: 2
INFO     Updated smart playlist myMPDsmart-newestSongs

Thread 4 "mympd_webserver" received signal SIGILL, Illegal instruction.
[Switching to Thread 0xfffff6a441e0 (LWP 2284)]
0x0000aaaaaab151f4 in web_server_loop ()
(gdb) bt 50
#0  0x0000aaaaaab151f4 in web_server_loop ()
#1  0x0000fffff7bfd5d4 in start_thread () from /usr/lib/libpthread.so.0
#2  0x0000fffff7b4141c in thread_start () from /usr/lib/libc.so.6
```
Just to memtion that it crashes as soon as i reach the web page. I don't do anything else.

**Comment by jcorporation** [comment]
It really seems to be a problem with the embedded assets. I don't have a aarch64 setup to reproduce this error. x86 (64 bit) and armv7l (raspberry pi 3) works fine. Is it right, that you use a 64 bit kernel on arm?

**Comment by archphile** [comment]
Yes I use kernel 5.4.3 + ArchlinuxARM aarch64. This OS (with aarch64) is the OS I have been using since day one with mympd.

**Comment by jcorporation** [comment]
Can you elaborate which myMPD version worked? Embedded assets are introduced with 5.6.0

**Comment by archphile** [comment]
I checked, it was for sure 5.5.3.

**Comment by jcorporation** [comment]
I updated incbin to the latest master. Can you test the myMPD devel branch?

**Comment by archphile** [comment]
I just tested with:

./build.sh release
gdb release/mympd?

and everything seem to be ok!

**Comment by archphile** [comment]
I just created a package based on a new PKGBUILD that uses development code:

https://github.com/archphile/packages/blob/master/mympd-archphile-devel/PKGBUILD

Everything is now fine.

Thanks again!
