### ISSUE TITLE
Show more playing song info when tags are disabled

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#207]
It would be good to show more song info on playing panel when tags are disabled.
The tag info could be readable from the file just like cover image.
If tags are not available, only showing simple song info would be helpful.

**Comment by jcorporation** [comment]
You mean to extract infos like artist, album, title from filename and path?

**Comment by parkmino** [comment]
Either way should be fine, tag extraction or estimation, only for the playing song.

**Comment by jcorporation** [comment]
Your songs are tagged and you have tags disabled in MPD? I am not duplicating MPD tag reading functions. If you would tag like functions you must simply activate tags. myMPD wont‘t get workarrounds.
