### ISSUE TITLE
Covergrid does not work for mpd 0.20

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#208]
myMPD version: 6.0.0

**Describe the bug**

I tried covergrid however it does not work for me.
MPD connection is lost for seconds and covergrid is empty.
Debug log is attached.

[mympd.log](https://github.com/jcorporation/myMPD/files/3990713/mympd.log)

**Server plattform (please complete the following information):**
 - OS: Ubuntu
 - OS version: 18.04.3
 - Plattform: x86_64
 - MPD version: 0.20.23
 - Libmpdclient Version: as in mympd 6.0.0

**Comment by parkmino** [comment]
I cleared up all the music directory, however, mpd connection is lost again.

**Comment by parkmino** [comment]
Hm... I tried my precompiled mpd 0.21.5 & 0.22, both are fine.
Is MPD should be higher than 0.21.x to use this feature?

**Comment by jcorporation** [comment]
Yes, the covergrid works only with MPD 0.21.x

**Comment by parkmino** [comment]
OK and please disable this feature for mpd 0.20 and earlier.
