### ISSUE TITLE
build in gentoo

### ISSUE THREAD

**Issue by antonellocaroli** [jcorporation/myMPD#211]
I did the buil on gentoo, everything seems to work properly, the only thing that seems not to work is the database card in browse, what could be the reason?

![image](https://user-images.githubusercontent.com/11161093/72638544-e8e3a500-3963-11ea-98ba-1e2c21837546.png)

**Comment by antonellocaroli** [comment]
sorry I solved it by setting the path to the music in mympd.conf

other question...I used ./build.sh install to install it
but isn't there a ./build.sh uninstall ?

to a new version just redo the procedure and overwrite the old one? or do you have to clean it first?

**Comment by jcorporation** [comment]
There is no uninstall function. A upgrade overwrites the old binary and installs a sample configuration file beside the current one.

A uninstall could be usefull, I will add it to one of the next releases.

A Gentoo ebuild would be great. myMPD should be easy installable on most distributions.
