### ISSUE TITLE
Korean update for devel

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#212]
As attached.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/4088858/ko-KR.txt)

**Comment by jcorporation** [comment]
Thanks for your translation. I recently added two another missing phrases to the de-DE translation.

**Comment by parkmino** [comment]
A couple of translations added as below.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/4090349/ko-KR.txt)
