### ISSUE TITLE
Wiki - Packages

### ISSUE THREAD

**Issue by antonellocaroli** [jcorporation/myMPD#219]
Hi,

if you want you can add in "mympd is available in the following distributions", even GentooPlayer

http://gentooplayer.com/

https://audiophilestyle.com/forums/topic/55235-gentooplayer/page/31/?tab=comments#comment-1024286

**Comment by jcorporation** [comment]
Thanks for your hint and integration of myMPD in GentooPlayer. It looks like cool piece of software. The wiki page is updated.
