### ISSUE TITLE
Cannot add tracks on queue

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#22]
**Describe the bug**
There are three folders in mnt folder of archlinux filesystem. One is nas-samba, one is nas-nfs, last is usb-disk.

From fstab file i mount nas-samba folder to Music NAS environment(to my case is a windows home server) and share my music tracks to raspberry pi.

Everything work great until the new "Append queue" function. The strange here is that i can queue an .m3u file but not any track, even from the same folder. I cannot add any mp3, flac, etc track...

**To Reproduce**
1. Go to 'Browse'
2. Click on 'Filesystem'
3. Scroll down to 'any mounted folder and try to add a track from the little "ADD" button on the right'
4. No error. I click it, but nothing happens.

**Expected behavior**
To be added to queue

**Screenshots**
![untitled-2](https://user-images.githubusercontent.com/18086896/42777889-12c3c5a2-8944-11e8-972f-620332f8ce9a.jpg)

![untitled-1](https://user-images.githubusercontent.com/18086896/42777891-12fb6eee-8944-11e8-84e8-fa956958dc77.jpg)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Firefox, Chrome
 - Version Latest

**Additional context**

**Comment by Emilot** [comment]
Forgot to mention that in folder webradio everything is working fine with .pls files.

![untitled-4](https://user-images.githubusercontent.com/18086896/42778135-d8f35e40-8944-11e8-90be-da52ab105ee4.jpg)
![untitled-3](https://user-images.githubusercontent.com/18086896/42778136-d9137072-8944-11e8-9288-db951a23dbec.jpg)

**Comment by jcorporation** [comment]
Thanks for your bug report. One additional question:
What happens if you click on the row itself?

**Comment by Emilot** [comment]
Unfortunately it worked. With the latest master version 3.20. i cannot add anything to queue. I see the "Added" signal on the top right, but nothing in queue page :(

![untitled-6](https://user-images.githubusercontent.com/18086896/42782616-1de0802a-8952-11e8-86c8-231cd059ca80.jpg)

![untitled-5](https://user-images.githubusercontent.com/18086896/42782617-1e03cc92-8952-11e8-90cb-2113c55903a4.jpg)

**Comment by jcorporation** [comment]
Appears the added signal also on song files?
Your queue page looks strange. On an empty queue, a empty message should appear.
I pushed a moment ago some queue view fixes to master.

**Comment by Emilot** [comment]
Yes, the added signal appears on song files, too. Look at the first images.

Let me check with 3.2.0.1

Thank you for the instant support!

**Comment by Emilot** [comment]
New situation.

Now i can add song files, if i click on the title bar, but not from add icon(like previous)

I cannot add a web radio file in any way(added icon or click on bar title)

PS. Now there is a sign "Empty queue" in queue :)

**Comment by jcorporation** [comment]
Very strange, in my setup this works all without any error. Can you recompile it with mkdebug.sh and starting mympd manually. The debug output can be helpfull.

**Comment by Emilot** [comment]
Error...

/usr/bin/ld: cannot find -lasan

i guess i have to install a prerequisite...

**Comment by jcorporation** [comment]
right, libasan3. it should be in your distri repos

**Comment by jcorporation** [comment]
I added better error handling for the ajax requests. Can you try current master and give me feedback, if a error occurs?

**Comment by Emilot** [comment]
Unfortunately i cannot execute the mkdebug script. In Archlinux i have gcc and gcc-libs already installed but i keep getting the same error. I guess something is wrong with the enviroment. Debian uses /usr/bin and Archlinux /usr/lib, but it is out of my knowledge base in Linux :(

With the latest master:

New condition. When i press the "Add icon" on a music folder, i can see the "Append queue", etc..signs. It didn't show anything until now. But inside the folder(at music files i mean) the "Add icon" doesn't work. I can add them if i click on the title.

Still no webradio file(.pls) can be added at queue. Even if i click on the title.

**Comment by jcorporation** [comment]
You can find the javascript console in Firefox under Web Developer -> Web Console.
It seems that these are javascript problems. You tried to clean your browser cache?

**Comment by Emilot** [comment]
Οκ!

This error appears on every page:

![untitled-4](https://user-images.githubusercontent.com/18086896/42940367-c1c3e590-8b48-11e8-8bd8-3214d6676b63.jpg)
 
This is the error when i hit "Add icon" on a track file:

![untitled-5](https://user-images.githubusercontent.com/18086896/42940437-f94087e4-8b48-11e8-802f-05664c7f3431.jpg)

**Comment by jcorporation** [comment]
I think I found the error, why the popup don't appear on a track file.
The other javascript errors should by also fixed in current master

**Comment by Emilot** [comment]
Jcorp the minified files are updated? I cannot see any difference :(

Same errors in console.

**Comment by jcorporation** [comment]
now are the minfied files alos updated

**Comment by Emilot** [comment]
Jcorp you are doing a professional work with Mympd. I really love your work so far.

Thank you for everything!

Everything working fine :)

**Comment by jcorporation** [comment]
Many thanks. Then i'm closing this ugly bug now...
