### ISSUE TITLE
Korean update for devel

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#221]
as attached.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/4189536/ko-KR.txt)

**Comment by jcorporation** [comment]
A few more phrases have been added. Can you also translate them before the new version is released.

**Comment by parkmino** [comment]
Yes, I've been catching it up.
Please find the attached file.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/4212713/ko-KR.txt)

**Comment by jcorporation** [comment]
Incorporated in devel, thanks

**Comment by parkmino** [comment]
A couple of translations added as attached.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/4243628/ko-KR.txt)
