### ISSUE TITLE
Gitlab pipeline hangs

### ISSUE THREAD

**Issue by rollenwiese** [jcorporation/myMPD#222]
myMPD version: registry.gitlab.com/jcorporation/mympd:latest (3 days ago)

mympd hangs on the splash screen with a javascript error.

I'm using firefox, haven't tested any other browsers.

**TypeError: a is nullcombined.js:9:386**

    Y http://chinook:40000/js/combined.js:9
    <anonymous> http://chinook:40000/js/combined.js:147

**Screenshots**
![2020-02-14_12-47](https://user-images.githubusercontent.com/5793456/74554786-54e80780-4f28-11ea-9467-7eb940012eea.png)

Will add more info when I can.

**Comment by jcorporation** [comment]
3 days ago? Master was not changed since 18 days or is this the devel branch?

**Comment by rollenwiese** [comment]
Hey yeah it's version 6.2.0. Let me fiddle with the browser and see if that's it or maybe the missing playlist dir:

```
INFO     Starting myMPD 6.2.0
INFO     Compiled with embedded libmpdclient
INFO     Libmympdclient 1.0.2 based on libmpdclient 2.19.0
INFO     Mongoose 6.16
INFO     Parsing config file: /etc/mympd.conf
INFO     Setting loglevel to INFO
INFO     Localstate dir: "/var/lib/mympd" created
INFO     Listening on http port 80
INFO     Droping privileges to mympd
INFO     Smartpls dir: "/var/lib/mympd/smartpls" created
INFO     State dir: "/var/lib/mympd/state" created
INFO     Pics dir: "/var/lib/mympd/pics" created
INFO     Empty dir: "/var/lib/mympd/empty" created
INFO     Covercache dir: "/var/lib/mympd/covercache" created
ERROR    MPD playlists dir: "/var/lib/mpd/playlists" don't exists
INFO     Starting mympd api thread
INFO     Starting mpd client thread
INFO     Starting webserver thread
INFO     Reading states
INFO     Starting mpd_client
INFO     MPD connecting to 192.168.9.5:6600
INFO     MPD connected
INFO     MPD protocoll version: 0.21.11
INFO     MPD music_directory: "/usr/share/mympd/htdocs/library/"
INFO     Enabling featLibrary support
INFO     MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date OriginalDate Composer Performer Disc Label MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID MUSICBRAINZ_WORKID 
INFO     Enabled mympdtags: Artist Album AlbumArtist Title Track Genre Date 
INFO     Enabled searchtags: Artist Album AlbumArtist Title Genre 
INFO     Enabled browsetags: Artist Album AlbumArtist Genre 
INFO     Enabled generate pls tags: Genre 
INFO     Enabling advanced search
INFO     Enabling single oneshot feature
INFO     Cleaning covercache /var/lib/mympd/covercache
INFO     Deleted 0 files from covercache
INFO     Cleaning covercache /var/lib/mympd/covercache
INFO     Deleted 0 files from covercache
INFO     Cleaning covercache /var/lib/mympd/covercache
INFO     Deleted 0 files from covercache
```

**Comment by rollenwiese** [comment]
Happens in all browsers for me chrome/edge/firefox. I wonder if it's a packagin issue with the container build. I tried both :latest and :devel tagged containers and both result in the same error for me. Will build an arch package and see if that gives me the same issue.

**Comment by jcorporation** [comment]
The container build seems outdated. I got some pipeline errors from gitlab. I fixed recently some javascript errors in devel. This could be the problem.

**Comment by jcorporation** [comment]
Hm, the gitlab pipelines timing out. I don‘t know why... eventually gitlab has a problem.

**Comment by rollenwiese** [comment]
Yeah I can see that it's hanging on the first mkdir in the Dockerfile. N/S if that a gitlab issue or a dockerfile issue. Seems like a Gitlab issue. I triggered one of my builds (not mympd) and it finished but went pretty slow.   When I have some time I can clone and mess around and see if there's something to be fixed.

**Comment by jcorporation** [comment]
Thanks I don't changed anything in my gitlab ci setup.

**Comment by jcorporation** [comment]
https://gitlab.com/gitlab-com/support-forum/issues/5202
