### ISSUE TITLE
Artist Grid View [Request]

### ISSUE THREAD

**Issue by ghost** [jcorporation/myMPD#226]
A good option IMO is having a Artist Grid View, where for example an artist.jpg in the artist folder (or a dedicated folder setup in mympd settings) could be display there.

**Comment by jcorporation** [comment]
Can you explain a little bit more the usage of a Artist Grid View? What functions / features should be included?

As an alternative I thought about a  filesystem tab that can be switched from list to icons, as it is in windows explorer. The icons can be the folder.jpg files. Arrange your albums in artists folders and you have something like a artist grid.

**Comment by a491765** [comment]
That's it !

For me a artist grid just provide  another way to display artist list in a grid.
Option still same as today in your artist list

This is an example from picoreplayer + LMS view :+1: 
Here the 3 dots provide all option (replace queue, add queue, more info....)

![Grid](https://user-images.githubusercontent.com/55695217/75319010-14fc1b00-586c-11ea-9c77-58c42d8139f4.jpeg)

**Comment by jcorporation** [comment]
myMPD simply displays the image in the folder, in filesystem view. The image name is already configurable in the settings dialog. I see no need to differentiate between album and artist images for this approach.

**Comment by jcorporation** [comment]
Is now in devel.
