### ISSUE TITLE
Randomly unpauses MPD (maybe Jukebox related)

### ISSUE THREAD

**Issue by dtorres** [jcorporation/myMPD#227]
I'm using the Jukebox feature and it works great, like thank you so much for this amazing thing.

myMPD version: 6.1.0

**Describe the bug**

Now, the issue is... sometimes, at random intervals music will unpause and start playing. 
It woke me up a couple of times even.

I've discarded it being a MPD bug by stopping myMPD from running and using it through MPC exclusively for a few days.

I've also discarded it being my browser going rogue and sending a command by having myMPD running and only controlling through MPC

Sometimes music will be unpaused a few minutes after it was paused, others, I come back home and the jukebox has played half my collection.

**To Reproduce**

No idea yet, sorry. Will update as I can.

**Expected behavior**

For music to stay paused until I tell it to

**Screenshots**

**Server plattform (please complete the following information):**
 - OS:  Raspbian
 - OS version: buster
 - Plattform: Raspberry PI 3
 - MPD version: 0.21.5 (0.21.5)

**Comment by jcorporation** [comment]
Recently I had the same issue. It should be already fixed in 6.2.0 but this needs further testing.

**Comment by dtorres** [comment]
For my education, can you point me to the commit(s) that fix this?

**Comment by jcorporation** [comment]
83d5177

**Comment by dtorres** [comment]
Ahhh, no wonder I couldn't find related fixes. I was only looking at the master branch.

I'll make a build from devel and post back

**Comment by dtorres** [comment]
Seems to work, playback hasn't restarted.

Vielen Dank!
