### ISSUE TITLE
Tracks duplication + tracknumber not correponding to tag of file

### ISSUE THREAD

**Issue by a491765** [jcorporation/myMPD#229]
Hi,

Two questions here :

1/ I used to rip my Cds with .log .cue and a playlist .m3u the hole in the album folder.
My problem is that mympd show dupplication. The both tracks in folder and the tracks in the playlist (see screenshot) are shown in browse tab > Databse > Artist > Album

How to disable playlist's tracks view ? (I'd like only tracks files to be shown).

2/ My files are listed as 01.xxxx 02.xxxx all tracks are tagged as tracknumber 01 02 03....

Why mympd delete the 0 and show tracks as 1. 2. 3. 
How to correct that and having the 01 02 03 display ?

I'm using Collybia OS 1.1 with mympd 6.0

Thanks for helping.

![Screenshot_20200227_212708](https://user-images.githubusercontent.com/55695217/75484252-b12b3c80-59a8-11ea-97d7-57d105938954.png)

**Comment by jcorporation** [comment]
Only one thing in one issue please and use the issue template.

> 2/ My files are listed as 01.xxxx 02.xxxx all tracks are tagged as tracknumber 01 02 03....

This is a mpd behaviour. My test with mpc or a direct connection to the mpd socket with telnet shows tracknumbers without leading zeros.

> 1/ I used to rip my Cds with .log .cue and a playlist .m3u the hole in the album folder.
My problem is that mympd show dupplication.

myMPD uses the following mpd command to get the list of songs: 
`find AlbumArtist "Death Grips" Album "The Money Store"`

- Which mpd version?
- Do you have example files for me? I don't use cue files.

**Comment by a491765** [comment]
Ok sorry for that.

2/ ok so i undesrtand that if mympd show 1 instead of 01 its du to mpd and not mympd.
i will search on mpd then to see how to change that.

1/ MPD
Protocol version	0.22.0
Libmpdclient version	2.18.0
Libmympdclient version	1.0.0

as example 
```

My HDD SUB > Library > Lana Del Rey > Ultraviolence >
01
02
03
...
15
Cover.jpeg
Ultraviolance.cue
Ultraviolence.log
Ultraviolence.m3u
```

**Comment by jcorporation** [comment]
MPD since 0.22 includes the cue sheet contents in the database. I think this is the cause of the duplicate tracks, not the m3u playlist.

**Comment by a491765** [comment]
Oh ok, well is there a way to manage this ?

**Comment by jcorporation** [comment]
Read the docs: https://www.musicpd.org/doc/html/user.html#the-music-directory-and-the-database
