### ISSUE TITLE
Display issue in covergrid

### ISSUE THREAD

**Issue by a491765** [jcorporation/myMPD#230]
I have a display issue on Browse > Covergrid > Pick an album
The color fonts doesn't match well in "Light" and "Default" Theme (see screenshots)
Collybia OS 1.1 mympd 6.0

![Screenshot_20200228_074508](https://user-images.githubusercontent.com/55695217/75517271-a0a5b100-59fe-11ea-88a3-2a77f4aa1c30.png)

![Screenshot_20200228_074536](https://user-images.githubusercontent.com/55695217/75517386-d9458a80-59fe-11ea-8dba-7bb0ecb47054.png)

But this works fine in "Dark" Theme

![Screenshot_20200228_075003](https://user-images.githubusercontent.com/55695217/75517442-fe39fd80-59fe-11ea-881e-a60aaed91ecb.png)

**Comment by jcorporation** [comment]
This bug is already fixed in the latest version.

**Comment by a491765** [comment]
Ok thank you.
Is there a way to update mympd easyli within rebuild it ?

**Comment by jcorporation** [comment]
For Collybia OS you should wait for a new release or ask the guis from Collybia, but here are precompiled Packages: https://github.com/jcorporation/myMPD/wiki/Prebuild-Packages

**Comment by Emilot** [comment]
A new release is on the way! Thank you JC.

PS. One of the guys from Collybia OS :)

**Comment by a491765** [comment]
Glad to hear, thank you both of you for your job.
