### ISSUE TITLE
Jukebox song mode does not add songs

### ISSUE THREAD

**Issue by john-** [jcorporation/myMPD#231]
myMPD version: 6.2.1

When I attempt to enter jukebox mode (10 songs) there are no songs added to the queue.   It does work with album as the mode.

I just upgraded to 6.X from 5.X.   I did not upgrade any dependencies.

**To Reproduce**

1. Go to Settings|Jukebox
2. Click on Song, Playlist "Database", keep queue length "10", enforce uniqueness "Album", Last played older than (hours) "24"
3. Click "Apply"
4. No songs are added to queue.   Error in logs:

Feb 29 10:26:41 frontaudio mympd[4532]: INFO     MPD protocoll version: 0.19.0
Feb 29 10:26:41 frontaudio mympd[4532]: INFO     MPD music_directory: "/library/jukebox"
Feb 29 10:26:41 frontaudio mympd[4532]: INFO     Enabling featLibrary support
Feb 29 10:26:41 frontaudio mympd[4532]: INFO     MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID
Feb 29 10:26:41 frontaudio mympd[4532]: INFO     Enabled mympdtags: Artist Album AlbumArtist Title Track Genre Date Composer Performer
Feb 29 10:26:41 frontaudio mympd[4532]: INFO     Enabled searchtags: Album AlbumArtist Artist Composer Genre Performer Title
Feb 29 10:26:41 frontaudio mympd[4532]: INFO     Enabled browsetags: Album AlbumArtist Artist Composer Genre Performer
Feb 29 10:26:41 frontaudio mympd[4532]: INFO     Enabled generate pls tags: Genre
Feb 29 10:26:41 frontaudio mympd[4532]: WARN     Disabling advanced search, depends on mpd >= 0.21.0 and libmpdclient >= 2.17.0.
Feb 29 10:26:41 frontaudio mympd[4532]: WARN     Disabling single oneshot feature, depends on mpd >= 0.21.0 and libmpdclient >= 2.18.0.
Feb 29 10:26:41 frontaudio mympd[4532]: WARN     Jukebox queue didn't contain 50 entries
Feb 29 10:26:41 frontaudio mympd[4532]: ERROR    Error adding song(s)
Feb 29 10:26:41 frontaudio mympd[4532]: ERROR    Error adding song(s), trying again
Feb 29 10:26:41 frontaudio mympd[4532]: ERROR    MPD error: incorrect arguments (9)

**Expected behavior**

10 songs would be added to the playlist.

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: Unbuntu 16.04
 - OS version 3.14.79-116
 - Plattform: aarch64
 - MPD version: 0.19.12
 - Libmpdclient Version: 2.19.0

Mongoose version | 6.17

**Client plattform (please complete the following information):**
 - Device: Odroid C2
 - OS: Linux
 - Browser: Firefox
 - Browser version: 70

**Debug logs (please attach if it can be usefull)**

See https://github.com/jcorporation/myMPD/wiki/Debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
 **Configuration (please attach if it can be usefull)**

 - /etc/mympd.conf
 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 
 **Additional context**

**Comment by jcorporation** [comment]
Your library is big enough to fullfill these constraints?

**Comment by john-** [comment]
Yes.   If I use Album mode for jukebox that does work (adds 10 albums worth of songs).

![image](https://user-images.githubusercontent.com/2359125/75613444-6b2ebf80-5af3-11ea-9c93-54e0fb10e224.png)

**Comment by jcorporation** [comment]
Ok, big enough... Can you test it with different parameters, e.g. only one song

**Comment by john-** [comment]
Starting with empty queue it will not work with one song.   Things that do work:   With Jukebox mode "Album" I can add random albums from the database.   With Jukebox mode "Song" I can use Playlist other than "Database".   I can get songs added in the case I tried.

Seems like anything to do with Jukebox mode "Song" and Playlist "Database" do not work with even one song.

**Comment by jcorporation** [comment]
Thanks for narrowing down the problem

**Comment by jcorporation** [comment]
Your mpd version is to old. The jukebox (in database mode) searches the database with the "window" parameter to support large databases. This parameter is only support in mpd versions 0.20 and above.

I have to decide what the best fix is for old mpd versions:

1. Disable the jukebox database mode
2. Disable the window parameter with the risk that it not works with large databases

**Comment by john-** [comment]
For what it is worth I was looking at upgrading mpd however on Odroid C2 platform apparently I need to do a non-supported (by Odroid) Ubuntu upgrade from 16 to 18.   I might see about installing mod from source.

I am not sure how many people are in the same boat as me with these SBCs.   That said I tend towards option 2 but I also understand that the code should be kept clean even if that risks loss of functionality for some users (option 1).

I am OK with whatever option.  However, jukebox mode is my most used myMPD feature so that would for sure force me to upgrade mpd if the feature stopped :)

**Comment by jcorporation** [comment]
I think option 1 is the best. I don't know how many users are out there with an mpd older than 0.20.0. Is this worth a survey?

**Comment by john-** [comment]
Others can chime in but my first thought is that this platform does not have a lot of myMPD useage and updating to more recent mpd is pretty low bar all things considered.  Even for others impacted  myMPD jukebox functionality is small subset of everything else it does that continues to work despite this old version of mpd.

**Comment by jcorporation** [comment]
Changes are now in devel. The ui display now a error if this mode is enabled with mpd < 0.20.0.

**Comment by john-** [comment]
For anyone else using odroid c2 and Ubuntu 16.04 with mpd 0.19:  I used the unofficial/unsupported instructions here to get to mpd 0.20:  [Odroid C2 - distribution upgrade from Ubuntu 16.04 to 18.04](https://forum.odroid.com/viewtopic.php?t=34251)
