### ISSUE TITLE
installdeps fails on debian based ARMv6 hardware

### ISSUE THREAD

**Issue by dtrv** [jcorporation/myMPD#234]
myMPD version: 6.2.1

**Describe the bug**

Java 11 does not support ARMv6 based hardware. Debian/Raspian Buster's `default-jre-headless` installs openjdk-11. So `./build.sh installdeps` fails.
(See also https://github.com/MichaIng/DietPi/issues/3182)

**To Reproduce**

1. Get ARMv6 based single-board computer/ RPi zero
2. Install raspbian buster
3. `./build.sh installdeps`
4. oh no!
```sh
[..]
Setting up ca-certificates-java (20190405) ...
head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
Error occurred during initialization of VM
Server VM is only supported on ARMv7+ VFP
dpkg: error processing package ca-certificates-java (--configure):
 installed ca-certificates-java package post-installation script subprocess returned error exit status 1
Processing triggers for ca-certificates (20190110) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

Error occurred during initialization of VM
Server VM is only supported on ARMv7+ VFP
E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
done.
Errors were encountered while processing:
 ca-certificates-java
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Expected behavior**

Installs build dependencies without error.

**Server plattform (please complete the following information):**
 - OS: raspbian
 - OS version: buster
 - Plattform: RPi zero/ARMv6
 - MPD version: 6.2.1

**Comment by jcorporation** [comment]
Isn't that rather a Debian bug?

**Comment by jcorporation** [comment]
I merged your pull request

**Comment by dtrv** [comment]
You're right. This should get fixed on Rasbians maintainer side. But I guess they'll not switch back to java-8 because of RPi 1 & zero. Maybe sometimes java-11 supports ARMv6 again? Then we could remove this workaround. Or java dependency gets removed from myMPD?

For me ARMv6 based hardware is perfect for running myMPD. Thanks for your great work! And thanks for your fast response!

Shall I invite you to a beer? Regards from the neighborhood ;-)

**Comment by jcorporation** [comment]
> Thanks for your great work! And thanks for your fast response!
Thanks, positive feedback is always great and motivating
