### ISSUE TITLE
Jukebox mode selects only from first 1000 songs in database mode

### ISSUE THREAD

**Issue by thaihugo** [jcorporation/myMPD#239]
MyMPd 6.2.3
Mpd protocol version: 0.21.4
Libmpdclient version: 2.19.0
Libmympdclient version: 1.0.2

Manual update on standard install 6.2.0 on dietpi Buster on raspberry pi 4 2gb

Mpd root is /mnt/ssd/Music
There are 5 subfolders. All the music is parsed by mpd, and ssen by mympd.
However, using the jukebox option with the "Database" source for content will give only music from the first folder in alphabetical list (Compilations in my case)
All the smart playlist are generated using, at first glance, music from all folders.

As I cannot seem to be able to create a smart playlist myself (still trying to figure out the problem on my end before opening an issue) I cannot provide a new smart playlist to replace the database option.

Expected behavior: jukebox using database (default) option should get music from all folders in the database. This was the case in previous versions of mympd

Actual behavior: jukebox select music only from the first subfolder of the music database.

Thanks for any insight!

**Comment by jcorporation** [comment]
Please attach debug logs from myMPD and verbose logs from MPD.

**Comment by thaihugo** [comment]
[Archive.zip](https://github.com/jcorporation/myMPD/files/4322446/Archive.zip)

Here it is.

I've disabled smartplaylist, as it seems to struggle with the location folder, having full rights, creating the files but complaining about the fact it cannot write the file.

I've launched mympd, and refreshed the jukebox playlist. It seems it stop on the first folder because it is blocked in it's or mpd's scan process?

**Comment by jcorporation** [comment]
Thanks for the logs. The jukebox code in database mode iterates only through the first 1000 songs, thats a bug.

**Comment by thaihugo** [comment]
Thanks,

Does it means I should test it, or wait for 6.3.0?

I Can git clone the devel branch using this commands:
`git clone https://github.com/jcorporation/myMPD.git
git checkout devel `

But I don't know where to find the build script.

**Comment by jcorporation** [comment]
You could test it if you want. The `build.sh` script is in the root of the checked out repository.

**Comment by thaihugo** [comment]
Ok, I've tested it and my method is to clear the playlist to get a new jukebox selection. On the first time, I get new music from everywhere, then if I clear more times, it goes back to the same selection for the first 1000. I'm on devel, as I have a mount option in the menu that is not in release, and I've cleaned my cache

**Comment by jcorporation** [comment]
Please attach the myMPD debug logs.

**Comment by thaihugo** [comment]
Sorry about that.
First pass is from everywhere (20 song limit)
Delete the queue,  next pass and subsequent are as before (with a strange obsession for the same tracks)
[mympdtaketwo.log.zip](https://github.com/jcorporation/myMPD/files/4323886/mympdtaketwo.log.zip)

**Comment by jcorporation** [comment]
Strange behavior... it is eventually a problem with the enforcing constraints. Can you set "Enforce uniqueness" to "Song" and check if the behaviour is changing?

**Comment by jcorporation** [comment]
I think I found the error, the used reservoir sampling method works only in the first pass correctly. I pushed the first version of the untested fix.

**Comment by thaihugo** [comment]
This fix is working for me. I will be testing further but initial tests are saying no more limitation.


Thanks a lot for your incredible work.

**Comment by thaihugo** [comment]
Also, is there any reason mympd would be complaining the playlist to be smaller than 50? I got a hang with mympd, but I cannot reproduce the bug.

**Comment by jcorporation** [comment]
Please post the complete log with the error.

**Comment by thaihugo** [comment]
Mympd basically hang if queue is under 50 songs.
[Archive.zip](https://github.com/jcorporation/myMPD/files/4332235/Archive.zip)

**Comment by jcorporation** [comment]
It seems your selected playlist myMPDsmart-Genre-Downtempo is non-existant or empty.

**Comment by thaihugo** [comment]
yes, I'm not sure if it's the smart playlist, as I thought I disabled them before, but I certainly trust you judgment on this issue. For now, a 20 song jukebox is not blocking the system, so It is definitely not the simple fact to have too few songs. You can close this issue as the main cause is resolved on the dev version.

Thanks a lot
