### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by antonellocaroli** [jcorporation/myMPD#241]
I'm trying to make an ebuild for gentoo.

after giving ./build.sh release

the files I need to get into the system are:

the mympd binary
the configuration file in /etc/mympd.conf
and the init script

Is there anything else?

what is /etc/mympd.conf.dist ?

**Comment by antonellocaroli** [comment]
other file you need is 
cli_tools/mympd-config

I've come this far and it seems to work

`# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Copyright 2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6

inherit eutils user cmake-utils

MY_PN="myMPD"

DESCRIPTION="myMPD is a standalone and mobile friendly web mpdclient"
HOMEPAGE="https://github.com/jcorporation/myMPD"
SRC_URI="https://github.com/jcorporation/${MY_PN}/archive/v${PV}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86 ~arm ~arm64"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

S="${WORKDIR}/${MY_PN}-${PV}"

pkg_setup() {
  enewgroup mympd
	enewuser mympd -1 -1 -1 audio
}

src_compile() {
        default
        ./build.sh release
}

src_install() {
	cd release
  dobin mympd
  dobin cli_tools/mympd-config
  newinitd "${FILESDIR}/${PN}.init.d" "${PN}"
  insinto /etc
  newins "${FILESDIR}/${PN}.conf" "${PN}.conf"
}
`

Is something missing?

how do you create the mympd.conf.dist file ?

**Comment by jcorporation** [comment]
Cool, an ebuild for Gentoo. Can I distribute it with the myMPD source package? Can you also explain how to use it? I want to update the wiki accordingly.

The mympd.conf.dist file is only created if a mympd.conf file exists. The conf files are created with the mympd-config utility at install time, see cmake/CopyConfig.cmake.in

**Comment by antonellocaroli** [comment]
you can do whatever you want with it.

but you confirm those are the files? and you don't need any more?

bin mympd
bin mympd-config
mympt.conf (in /etc)
and the initscript?

to use it in gentoo you have to create a local overlay

https://wiki.gentoo.org/wiki/Custom_repository

or following my redame and using layman...

https://github.com/antonellocaroli/GP-overlay/blob/master/README.md

then install with the usual emerge commands

emerges --ask mympd

**Comment by jcorporation** [comment]
> but you confirm those are the files? and you don't need any more?

Yes, this are all files.
