### ISSUE TITLE
Album art from ID3/ MP3

### ISSUE THREAD

**Issue by onkobu** [jcorporation/myMPD#243]
**Is your feature request related to a problem? Please describe.**
I have many audiobooks in the same folder, no chapters just one file per audio book. They're heavily tagged also with album art (ID3v2 embedded image extension, PIC/ APIC). It is not feasible to move each file into a directory to hold a folder.jpg.

**Describe the solution you'd like**
Instead use the embedded album art in ID3v2.

**Describe alternatives you've considered**
For music/ albums there are already directories and I added folder.jpg to some of them. For single-file audio-books this is not feasible. Sometimes they even come with no additional data, except embedded image.

**Additional context**
Render the image of the MP3 as album art in play view.

**Comment by jcorporation** [comment]
myMPD already supports embedded albumart for mp3 and flac: https://github.com/jcorporation/myMPD/wiki/Albumart.

**Comment by jcorporation** [comment]
@onkobu: Works this for you?

**Comment by onkobu** [comment]
I've also read through the changes with upcoming mpd 0.22, presumably it ships your patched(/ backported?) libmpdclient. I'll sort of track or push this from Gentoo side.

**Comment by jcorporation** [comment]
My libmpdclient (Libmympdclient) ships only with myMPD and is compiled in, no shared library. libmympdclient is based on the master branch of libmpdclient. I am pushing changes upstream if the code qualitiy is acceptable. 

The albumart and readpicture command is only supported in my fork.
