### ISSUE TITLE
myMPD says mpd would be down if directory being displayed was deleted

### ISSUE THREAD

**Issue by onkobu** [jcorporation/myMPD#244]
myMPD version: 6.2.3

**Describe the bug**

When viewing directory content with myMPD and deleting the directory on disk being displayed it flickers between connection lost/ reconnecting. This looks as if mpd would be down which isn't the case. Maybe error handling is a bit off.

**To Reproduce**

1. Go to Browser -> File System
2. dive into the directory structure somewhere
3. delete the directory being displayed on disk (from command line)
4. myMPD starts to flicker/ reconnect to mpd

**Expected behavior**

If the directory to fetch content for returns an error, handle it correctly, e.g. go to root/ media directory.

**Server plattform (please complete the following information):**
 - OS: Gentoo
 - OS version -
 - Plattform: x86_64
 - MPD version: 0.21.18-r1
 - Libmpdclient Version: 2.16

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: Gentoo
 - Browser Firefox
 - Browser version 68.6.0esr

 **Additional context**

I stumbled upon this while cleaning up directories shifting content around. While moving/ deleting directories in command line being displayed in myMPD this happened.

**Comment by jcorporation** [comment]
I can't reproduce this issue with current devel. Devel now displays the error message in the list. 
@onkobu: Can you test with current devel?

**Comment by onkobu** [comment]
I'll re-check with next release containing the relevant changes. It's not that urgent and doesn't happen this often. Thanks for the fast reply.
