### ISSUE TITLE
Empty list in filesystem section

### ISSUE THREAD

**Issue by salvatorebattiato** [jcorporation/myMPD#245]
Hello,
I just installed mympd on my dietpi raspberry pi 4 using your updated repository, after some problems starting mpd.socket service (it seems I have first start mpd.socket and then mpd.service)
Now mympd (using auto generated config) starts, but it does not show anything in Filesystem section. 
Music dir in mpd is /home/dietpi and set to auto in mympd.
![image](https://user-images.githubusercontent.com/38722664/78933319-6cb3b600-7aa9-11ea-9f75-e7ae6bcc3535.png)

**Comment by jcorporation** [comment]
You have build the initial MPD database? Main Menu -> Update-> Update Database

**Comment by salvatorebattiato** [comment]
Auto update option is activated and I also ran mpc update but it's not showing anything in database nor moving filesystem

**Comment by jcorporation** [comment]
Shows mpc Songs?

**Comment by salvatorebattiato** [comment]
Apparently nano didn't worked first time updating the conf. Now it's working fine, thanks.
