### ISSUE TITLE
Add feature detection for mount and neighbors 

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#246]
I built my own mpd without neighbour plugin, however the mount menu is always visible.
Please add option to disable this.

**Comment by jcorporation** [comment]
There is already an option to hide the mount menu entry, look at: https://github.com/jcorporation/myMPD/wiki/Configuration

The next point release adds an autodetect features.

**Comment by parkmino** [comment]
Yes, "mounts = false" does not show mount.
Auto detect would be helpful.
