### ISSUE TITLE
Display song lyrics in Playback tab

### ISSUE THREAD

**Issue by ddonindia** [jcorporation/myMPD#250]
**Describe the solution you'd like**
Currently myMPD supports lyrics in `Song details` tab.
It would be great if I can get lyrics of currently playing song in `Playback` tab.

**Comment by jcorporation** [comment]
How should the lyrics displayed? 
- Link to a popup
- Collapsed element under the cover 
- or somerhing else?

**Comment by ddonindia** [comment]
May be a tab next to `Playback`.
I just realized clicking on song title brings lyrics pop up. But its not dynamic and doesn't change on next song.

**Comment by jcorporation** [comment]
Updating the song details modal would be good enough?

**Comment by ddonindia** [comment]
Yes that should do

**Comment by ddonindia** [comment]
Basically I am looking for two things:

1.  lyrics changes based on current song playing.
2.  I can use player controller (next previous etc ) while lyrics is displayed.

**Comment by jcorporation** [comment]
Feature is now in devel. Testing would be very usefull.

**Comment by ddonindia** [comment]
thanks will try today.

**Comment by ddonindia** [comment]
Cool its working with txt files. Will check with embalmed lyrics 
But I am unable to set dark theme.   For some reason with this build my theme got reset to default I am not able to change to Dark.
Apply or Save button just don't do anything.

**Comment by jcorporation** [comment]
Please try a ./build.sh cleanupdist before building myMPD again.

**Comment by ddonindia** [comment]
Thanks  ` ./build.sh cleanupdist`  worked.  Thanks alot for implementing this so quickly.
Some of my songs have multiple lyrics attached. Is it possible to siplay multiple lyrics?

**Comment by jcorporation** [comment]
More than one USLT tag? This should be possible, please open a new issue.
