### ISSUE TITLE
Extracting lyrics directly from song

### ISSUE THREAD

**Issue by ddonindia** [jcorporation/myMPD#251]
**Describe the solution you'd like**
myMPD supports displaying lyrics of songs from the library.  limitation here is there must be file with  songfilename.txt. 

I was wondering if its possible to extract lyrics directly from songs tag ( if available ) and display it.
There is an other issue which is blocked on MPD to support this but I don't see its happening any time soon or ever ( PR is stuck since two years :) ). 

Can myMPD use some library like taglib to extract this information ?

**Describe alternatives you've considered**
Use eyeD3 to extract lyrics and store in .txt file. 

**Additional context**
https://github.com/jcorporation/myMPD/issues/160

**Comment by jcorporation** [comment]
myMPD uses libid3tag and libflac to extract embedded coverimages. Both libraries should support reading the lyrics tag.

**Comment by ddonindia** [comment]
If you can point me to right section of the code I can try implement it.

**Comment by jcorporation** [comment]
There is no backend for lyrics. The lyrics feature uses only the simple publish backend. The lyrics backend should be similar as the cover backend. An uri /lyrics/songuri and a eventhandler in web_server.c and other modifications in detect_extra_files function and in the frontend. Hi simple small hack.

**Comment by jcorporation** [comment]
There is now a branch for reading embedded lyrics. The infrastructure code for reading embedded lyrics is there. Access /lyrics/<songuri> to get the lyrics. The code for lyric textfiles works. The code for reading ULST tag in id3 tagged files does not work (function handle_lyricsextract_id3).

If this function works I will merge this in devel and adopt the old lyrics code.

**Comment by jcorporation** [comment]
I managed to read lyrics from my testfile. I would next add support for flac files.

**Comment by jcorporation** [comment]
Feature is now in devel.
