### ISSUE TITLE
Add all to queue fails

### ISSUE THREAD

**Issue by vkitchen** [jcorporation/myMPD#252]
myMPD version: 6.3.0
mpd version: 0.21.22

**Describe the bug**

The 'Add all to queue' button on the database tab upon click fails with the following error 'No response for method MPD_API_DATABASE_SEARCH'

**To Reproduce**

1. Go to 'Browse'
2. Select 'Database' tab
3. Select an album or artist
4. Click 'Add all to queue'
5. Error occurs

**Expected behavior**

All tracks should be added to the queue

**Server platform (please complete the following information):**
 - OS: ArchlinuxArm
 - OS version: Latest (updates fully applied at time of bug occurrence)
 - Plattform: Armv7
 - MPD version: 0.21.22
 - Libmpdclient Version: 2.18
 
 **Additional context**

Provided what I thought to be relevant. Happy to provide any further information or try to debug if desired. Great work you've been doing on your mpd frontend btw. Much appreciated!

**Comment by jcorporation** [comment]
Thanks for your bug report. Bug is now fixed in devel.
