### ISSUE TITLE
CoverGrid repeating each track as an album

### ISSUE THREAD

**Issue by AgentKith** [jcorporation/myMPD#254]
myMPD version: 6.3.1

Browse -> CoverGrid showing every track as it's own album

Go to browse, and then click on the CoverGrid tab. This should be showing albums only. But I'm seeing duplicates of the same album. If an album has 10 tracks, the album is repeated 9 times (n-1).

**To Reproduce**

1. Go to 'Browse'
2. Click on 'CoverGrid'
3. Click every album, it shows the correct tracks in the album. But the number of albums displayed is duplicated by "total number of tracks" -1.
4. It's doing the opposite of first song (displays everything but the first song, hence n-1).

**Expected behavior**

It should only show the first song of each album (instead of the opposite). 

**Screenshots**
![CoverGrid](https://user-images.githubusercontent.com/26515682/80331046-962a5b00-8879-11ea-8ac8-69232c60339a.jpg)

**Server plattform (please complete the following information):**
 - OS: Ubuntu
 - OS version 16.04 LTS
 - Plattform: x86_64
 - MPD version: 0.21.22
 - Libmpdclient Version: libmpdclient2 (from Ubuntu). AFAICT mympd or mpd don't use this?

**Client plattform (please complete the following information):**
 - Device: Intel PC
 - OS: Windows 10
 - Browser: Firefox
 - Browser version: 75.0

**Debug logs (please attach if it can be usefull)**

 - Browser network console
![Param](https://user-images.githubusercontent.com/26515682/80331370-7c3d4800-887a-11ea-9d23-6d9fd33b6605.png)
![Response](https://user-images.githubusercontent.com/26515682/80331375-7fd0cf00-887a-11ea-91b8-b31c71bb0c7b.png)

 **Configuration (please attach if it can be usefull)**

**Comment by AgentKith** [comment]
BTW, forgot to mention myMPD is built from source. And this is my build commands:
```
./build.sh cleanupdist
ENABLE_SSL="OFF" ENABLE_LIBID3TAG="ON" ./build.sh release
```

FWIW I tried with libid3tag ON and OFF and still get the same results.

**Comment by jcorporation** [comment]
This could be the case if your songs in your Albums has all the track number set to one. For the covergrid myMPD does a search for all tracks with number one.

**Comment by AgentKith** [comment]
Here's the tag info for one of the albums (Col 7#):
![image](https://user-images.githubusercontent.com/26515682/80340100-9d119780-8892-11ea-9b87-1f71039c1e5a.png)

Interestingly, if I modify src/mpd_client/mpd_client_browse.c, line #370 to such:
```
sds expression = sdscatprintf(sdsempty(), "((Track != '%d')", config->covergridminsongs);
```
The returned JSON message appears to be correct (Note first song URI is now returning the first track now, instead of 2 and up):
![image](https://user-images.githubusercontent.com/26515682/80340263-e82baa80-8892-11ea-826d-62e09423b704.png)

I'm still tracing through to find the issue (as I'm not sure if this is MPD, or libmpdclient or myMPD related). Seems somewhere is inverting the search result for tracks?

There's also a potential problem to this search. What if the album has no tags for Track (or any tags at all?), will this search still show the album if it's not ID3 tagged?

**Comment by jcorporation** [comment]
myMPD uses the embedded libmpdclient not the shared library from the system. 

The covergrid does not work if the music files are not correctly taged. 

This search is the fastest method to get all needed information in one pass from mpd.

**Comment by jcorporation** [comment]
MPD verbose log and myMPD debug log of the unpatched myMPD will be usefull. I can not reproduce the behavior.

**Comment by jcorporation** [comment]
@AgentKith: I close this issue now as invalid. Please post appropriated debug logs if I should dig deeper in this issue.
