### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#255]
myMPD does not display any kind of foreign letters - which can be seen in this screenshot (in this case Korean letters).

![Untitled](https://user-images.githubusercontent.com/13167467/80431148-045e3480-88f1-11ea-9f77-6e52ea3064f8.png)

My tags are all UTF-8, and if you need help testing things out, you have my email.

I was thinking it might be a font lacking, but you know best, so over to you, mate :)

**Comment by therion23** [comment]
![image](https://user-images.githubusercontent.com/13167467/80433910-a1709b80-88f8-11ea-9c18-4da7e7148004.png)

**Comment by jcorporation** [comment]
Can you switch the locale to korean? Then the ui items should disappear if its a font issue.

**Comment by therion23** [comment]
Setting the locale to ko_KR changes the language of the UI but helps nothing with the playlist appearance. The last screenshot should read Šarlo Akrobata, Čechomor and Þeyr, btw, forgot to mention that.

**Comment by jcorporation** [comment]
Then this seems to be not a font issue. Can you look at the network console of your browser and grab the response of one of those api calls? If the response is ok the problem is in the frontend else in the backend.

In my deployment I have also unicode characters in tags and they are working. Does a other client displays your tags correctly?

**Comment by therion23** [comment]
MALP for Android shows all characters just fine, yes.

Looking at the mpd database, i have this entry:
Artist: Þeyr
myMPD shows the URL as:
Browse/Database/Artist!0/-/-/%20 eyr

If you tell me how to "grab a response" i will gladly do it :)

**Comment by jcorporation** [comment]
Open the web browser console -> network tab -> select the response of a api request.

Or start myMPD with debug logging enabled.

**Comment by therion23** [comment]
I hope this is what you are looking for:

{"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_DATABASE_TAG_ALBUM_TITLE_LIST","data":[{"Type":"song","Track":"1","Title":"                 :             ","Duration":274,"LastModified":1326881652,"uri":"Artists/Собаки Табака/Найду, убью!/01 - Ангел мой - Эпизод.mp3"},{"Type":"song","Track":"2","Title":"        ,                   ,                           ","Duration":190,"LastModified":1326881599,"uri":"Artists/Собаки Табака/Найду, убью!/02 - Грех, богатство, любовь и азарт.mp3"},{"Type":"song","Track":"3","Title":"                       ","Duration":193,"LastModified":1326881654,"uri":"Artists/Собаки Табака/Найду, убью!/03 - Подлая падла.mp3"},{"Type":"song","Track":"4","Title":"            :                             ?","Duration":150,"LastModified":1326881557,"uri":"Artists/Собаки Табака/Найду, убью!/04 - Эпизод - Как моя девочка -.mp3"},{"Type":"song","Track":"5","Title":"          ","Duration":305,"LastModified":1326881641,"uri":"Artists/Собаки Табака/Найду, убью!/05 - Чужие.mp3"},{"Type":"song","Track":"6","Title":"                           ","Duration":700,"LastModified":1326881657,"uri":"Artists/Собаки Табака/Найду, убью!/06 - Венки забвения.mp3"},{"Type":"song","Track":"7","Title":"I refuse","Duration":278,"LastModified":1326881643,"uri":"Artists/Собаки Табака/Найду, убью!/07 - I refuse.mp3"},{"Type":"song","Track":"8","Title":"                         (2009)","Duration":213,"LastModified":1326881640,"uri":"Artists/Собаки Табака/Найду, убью!/08 - В теле христа (2009).mp3"},{"Type":"song","Track":"9","Title":"               ","Duration":592,"LastModified":1326881659,"uri":"Artists/Собаки Табака/Найду, убью!/09 - До рвоты.mp3"},{"Type":"song","Track":"10","Title":"                        ","Duration":270,"LastModified":1326881644,"uri":"Artists/Собаки Табака/Найду, убью!/10 - Хуй без хлеба.mp3"},{"Type":"song","Track":"11","Title":"            :           ","Duration":149,"LastModified":1326881625,"uri":"Artists/Собаки Табака/Найду, убью!/11 - Эпизод - Радио.mp3"},{"Type":"song","Track":"12","Title":"            ","Duration":241,"LastModified":1326881663,"uri":"Artists/Собаки Табака/Найду, убью!/12 - Голова.mp3"},{"Type":"song","Track":"13","Title":"I Refuse (The All Seeing I/Hypnoskull)","Duration":240,"LastModified":1326881634,"uri":"Artists/Собаки Табака/Найду, убью!/13 - I Refuse (The All Seeing I -Hypnoskull).mp3"}],"totalEntities":13,"returnedEntities":13,"Album":"          ,         !","search":"          ,         !","tag":"Album","AlbumArtist":"                         ","totalTime":3795}}

**Comment by jcorporation** [comment]
That is it, are the tags correct in this ouputu?

**Comment by therion23** [comment]
Okay, out of all that, when refreshing the browser view of an album, two debug lines seem interesting:

DEBUG    /usr/local/src/myMPD/src/mpd_client/mpd_client_api.c:636: Push response to queue for connection 4: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_DATABASE_TAG_ALBUM_TITLE_LIST","data":[{"Type": "song","Track":"1","Title":"En...","Duration":303,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/01 - En....mp3"},{"Type": "song","Track":"2","Title":"...Nema j  i","Duration":207,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/02 - ...Nema jói.mp3"},{"Type": "song","Track":"3","Title":"Hringt","Duration":222,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/03 - Hringt.mp3"},{"Type": "song","Track":"4","Title":"Heilarokk","Duration":351,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/04 - Heilarokk.mp3"},{"Type": "song","Track":"5","Title":"Svi  ","Duration":312,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/05 - Svið.mp3"},{"Type": "song","Track":"6","Title":"Eftir v  gi  ","Duration":277,"LastModified":1490637593,"uri":"A...

and

DEBUG    /usr/local/src/myMPD/src/web_server.c:225: Sending response to conn_id 4: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_DATABASE_TAG_ALBUM_TITLE_LIST","data":[{"Type": "song","Track":"1","Title":"En...","Duration":303,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/01 - En....mp3"},{"Type": "song","Track":"2","Title":"...Nema j  i","Duration":207,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/02 - ...Nema jói.mp3"},{"Type": "song","Track":"3","Title":"Hringt","Duration":222,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/03 - Hringt.mp3"},{"Type": "song","Track":"4","Title":"Heilarokk","Duration":351,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/04 - Heilarokk.mp3"},{"Type": "song","Track":"5","Title":"Svi  ","Duration":312,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í hel/05 - Svið.mp3"},{"Type": "song","Track":"6","Title":"Eftir v  gi  ","Duration":277,"LastModified":1490637593,"uri":"Artists/Þeyr/Þagað í h...

Could it possibly be the locale of the mpd instance creating the database?

**Comment by jcorporation** [comment]
If it is the locale of the mpd database other clients should have the same problem. Can you give one of the music files for local testing?

**Comment by therion23** [comment]
Yes, of course - right now i am rebuilding an mpd database with a different locale to see if it makes any difference, if not, i can hexdump the tag header of a file or send you a song, you choose.

**Comment by therion23** [comment]
Sorry to have wasted your time, it is indeed a locale problem - rebuilding the database with a forced locale and pointing myMPD to that shows up just fine. This is a case of a broken Linux installation and not a bug, as i suspected.

Thank you for your patience, if you are ever in Copenhagen, first and second drinks are on me. Thank you for your help!

**Comment by jcorporation** [comment]
No problem

**Comment by jcorporation** [comment]
What mpd version do you use?

**Comment by therion23** [comment]
Built from git - think two days ago? Not more than a week anyway.

**Comment by jcorporation** [comment]
I now also have the problem with unicode characters. It seems to be a problem with current git master of mpd.

**Comment by therion23** [comment]
That explains a lot - the one that worked for me yesterday was a stock .deb package, which is probably way behind.

**Comment by jcorporation** [comment]
https://github.com/MusicPlayerDaemon/MPD/commit/bca9678683eb8dbb31e7b5f348d9a3436639de22

This commit fixes a regression of printable ascii characters. I will test the newest version.
