### ISSUE TITLE
Smart  playlist not using latest settings

### ISSUE THREAD

**Issue by ddonindia** [jcorporation/myMPD#257]
myMPD version: master branch

Smart play list changes not reflecting.

**To Reproduce**

I have following set in smart play list 
![image](https://user-images.githubusercontent.com/16450468/80867313-397fd380-8cb1-11ea-8ce4-e9985cab2946.png)
but still getting older play lists.
Tried removing older play lists, restarting MPD, myMPD and server. But no luck

**Expected behavior**

Play list should reflect current selection.

**Screenshots**

![image](https://user-images.githubusercontent.com/16450468/80867383-71871680-8cb1-11ea-82d7-af550a10df55.png)

![image](https://user-images.githubusercontent.com/16450468/80867418-7e0b6f00-8cb1-11ea-822a-2687e38be935.png)

**Server plattform (please complete the following information):**
 - OS: Ubuntu LTS
 - OS version 20.04
 - Plattform: arm 64
 - MPD version: latest master

**Comment by jcorporation** [comment]
Please enable debug mode and attach logs

**Comment by ddonindia** [comment]
I dont see this issue with devel branch must be something wrong in my settings.
