### ISSUE TITLE
Support for multiple USLT tags

### ISSUE THREAD

**Issue by ddonindia** [jcorporation/myMPD#258]
https://github.com/jcorporation/myMPD/issues/250 implemented reading lyrics from music file. But if there are multiple lyrics only first lyrics is shown. 
This feature request is to  support multiple USLT tags.

**Additional context**
https://github.com/jcorporation/myMPD/issues/250#issuecomment-623002627

**Comment by jcorporation** [comment]
- [x] support for id3 tags
- [ ] support for vorbis comments
- [ ] improve lyrics display ui
