### ISSUE TITLE
high cpu usage if mpd is not running/dead

### ISSUE THREAD

**Issue by ddonindia** [jcorporation/myMPD#259]
myMPD version: master and devel branch

On my setup I have configured myMPD to connect MPD over local socket.
If for some reason MPD is down myMPD is taking ~30% CPU.  May be due to constant retries.

Server plattform (please complete the following information):
    OS: Ubuntu LTS
    OS version 20.04
    Plattform: arm 64
    MPD version: latest master

**Comment by jcorporation** [comment]
Please enable debug of myMPD and post the log.

**Comment by jcorporation** [comment]
commit #70ee7d0 shoud solve this issue. Don't hesitate to reopen this issue if it does not work for you.

**Comment by ddonindia** [comment]
Working fine.
