### ISSUE TITLE
Webradio RadioParadise CoverArt support

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#260]
**Is your feature request related to a problem? Please describe.**
Right now myMPD show a static image when someone play a webradio .pls file.

**Describe the solution you'd like**
I know that RadioParadise (very famous webradio station) has a dynamic coverart enviroment. I would like to see the albumart of the current song it plays.

**Describe alternatives you've considered**
At this url http://legacy.radioparadise.com/xml/now.xml RadioParadise has all the information we need.

Thank you.

**Comment by jcorporation** [comment]
I don‘t like implementing a feature for only one webradio. We need a more general approach.
