### ISSUE TITLE
Support for synchronized lyrics (LRC ) files

### ISSUE THREAD

**Issue by ddonindia** [jcorporation/myMPD#262]
Is possible to support synchronized lyrics files(LRC) in myMPD ?
I was doing some research and https://lusaisai.github.io/Lyricer/ looks promising.  

As myMPD already supports publishing .txt lyrics, I am hoping publishing and using .lrc should also be possible.

**Comment by jcorporation** [comment]
.lst files or the SYLT id3 tag could be supported.

**Comment by jcorporation** [comment]
- [x] support for file
- [x] support for id3 tags
- [x] support for vorbis comments
- [ ] improve lyrics display ui

**Comment by jcorporation** [comment]
@ddonindia : with what program do you add sylt tags to mp3 files?

**Comment by ddonindia** [comment]
MusicBrainz Picard https://picard.musicbrainz.org/

**Comment by jcorporation** [comment]
Sure, that Picard Support writes the SYLT tag? I thought Picard supports only ULST tags.

**Comment by ddonindia** [comment]
Sorry now got your point. For SYLT(SYnchronized Lyrics & Text) I use minilyrics and its configured to save .lrc files next music file.
