### ISSUE TITLE
Cannot disable HTTPS

### ISSUE THREAD

**Issue by KamilBaczkowski** [jcorporation/myMPD#263]
myMPD version: [e.g. 5.6.2]

I cannot disable HTTPS. Even though in my config I have set `ssl = false`, when I try to visit the mympd client, it redirects me to the HTTPS version of MyMPD

**To Reproduce**

1. Set `ssl = false` in the config file
2. Go to MyMPD
3. Receive a 301 Moved response that redirects to HTTPS even though HTTPS is disabled

**Expected behavior**

MyMPD shouldn't switch to HTTPS

**Server plattform:**
 - OS: Manjaro
 - OS version current testing
 - Plattform: x86_64
 - MPD version: 0.21.23

**Client plattform:**
 - Device: Laptop
 - OS: Fedora 32
 - Browser: Firefox
 - Browser version: 76

[mympd.conf.txt](https://github.com/jcorporation/myMPD/files/4620201/mympd.conf.txt)

**Comment by ddonindia** [comment]
Did you try to restart myMPD after changing config ?
Also try to clear browser cache.

**Comment by KamilBaczkowski** [comment]
Yeah, I restarted MyMPD with `systemctl restart mympd`, and also proceeded with a system reboot after that didn't work. I tried using the private/incognito mode of the browser on multiple devices, even ones that I didn't use to view MyMPD previously and the redirect always happens

**Comment by jcorporation** [comment]
Which myMPD version? Please enable debug and attach the log.

**Comment by KamilBaczkowski** [comment]
For some reason MyMPD is reading config file from `/etc/webapps/mympd/mympd.conf`, so not a bug. Closing.

**Comment by jcorporation** [comment]
This is the default path for arch linux based distributions.
