### ISSUE TITLE
Extra architectures for Debian Precompiled myMPD packages

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#264]
Please add armel & armhf architectures to the Debian Prebuild packages available through the Open Build Service. That would be wonderful :)

**Comment by jcorporation** [comment]
There are only this options available:
 - [x] i586
 - [x] x86_64
- ppc
- ppc64
- s390x
- local
- armv6l
 - [x] armv7l
 - [x] aarch64
- ppc64le
- aarch64_ilp32
- riscv64

**Comment by tsunulukai** [comment]
armv6l might do the trick for the armel debians.

**Comment by jcorporation** [comment]
Unfortunately armv6l build does not work with strange dependency errors. I think its a problem of the build service.

> nothing provides debhelper >= 10, nothing provides cmake, nothing provides libssl-dev, nothing provides libid3tag0-dev, nothing provides libflac-dev, nothing provides build-essential

**Comment by jcorporation** [comment]
https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets

Not supported eventually. Do you know a other build service?

**Comment by tsunulukai** [comment]
There's always the option of making it an official debian package, it then gets automatically compiled for all their supported archs, but I have no idea how much of a hassle this would represent...

Debian Build Service: https://www.debian.org/devel/buildd/
Distributing debian packages: https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html 
Becoming a sponsored maintainer: https://wiki.debian.org/SponsoredMaintainer

I'll take a look to see how easy it would be to have a debian package builder run inside a chrooted debian.

**Comment by jcorporation** [comment]
An official Debian package would be cool, but I think myMPD evolves to fast for debian.

**Comment by tsunulukai** [comment]
I tinkered a bit yesterday and found a easy way to create debian packages for different architectures and distributions.

It leverages `sbuild`, which is the tool used by the debian build service `buildd` and qemu-user-static to enable cross-compilation support. `sbuild` does all the compilation & packaging work inside chroots, resolving dependencies by itself and leaving your host clean of any compilation artefact or dependency.

The first step is to create chroots for each target (distro/arch): The script [create-build-chroots.sh.txt](https://github.com/jcorporation/myMPD/files/4658801/create-build-chroots.sh.txt) will do that for you, you just need to adapt the list of target distribution & architectures.

The next script will then use `sbuild` in combination with the chroots generated before to compile and package myMPD from the latest master source. [build-mympd-debian.sh.txt](https://github.com/jcorporation/myMPD/files/4658795/build-mympd-debian.sh.txt)

**Comment by jcorporation** [comment]
Very cool scripts. Integrating this in GitHub actions and publishing the resulting packages would be perfect.

**Comment by jcorporation** [comment]
I will integrate your scripts in the myMPD build.sh script in one of the next versions.
