### ISSUE TITLE
No response for method MPD_API_DATABASE_SEARCH

### ISSUE THREAD

**Issue by langrock** [jcorporation/myMPD#265]
myMPD version: 6.3.1

**Describe the bug**

When trying to add an entire album or all songs by an artist to the queue, a "No response for method MPD_API_DATABASE_SEARCH" is being displayed and no songs are being added to the queue.

**To Reproduce**

1. Browse to any artist or album
2. Click the "Add all to queue" button
3. See error message

**Expected behavior**

Songs should be added to queue

**Server plattform (please complete the following information):**
 - OS: DietPi
 - OS version: 6.30
 - Plattform: ARM
 - MPD version: 0.21.22

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: macOS
 - Browser Safari
 - Browser version: 13.1

**Debug logs (please attach if it can be usefull)**

See https://github.com/jcorporation/myMPD/wiki/Debug

 - myMPD debug log
ERROR    No response for cmd_id 34
ERROR    Browser don't support gzip compression

 
 **Configuration (please attach if it can be usefull)**

 - /etc/mympd.conf
[mympd_conf.txt](https://github.com/jcorporation/myMPD/files/4654892/mympd_conf.txt)

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state
[state.zip](https://github.com/jcorporation/myMPD/files/4654884/state.zip)

``)
 
 **Additional context**

**Comment by jcorporation** [comment]
Is already reported in #252 and fixed in current devel (commit adb1551)
