### ISSUE TITLE
Almost DOS like behavior when one has lots of "genres", doesn't respect config

### ISSUE THREAD

**Issue by mfeif** [jcorporation/myMPD#267]
myMPD version: 6.4.0

**Describe the bug**

My files have lots of genre tags in them, (which I'm not happy about, but cleaning them is a separate job I guess) apparently, and when making Smart playlists, it took like an hour to make them. It seems like it's taking "title" and so on as a genre tag, too. Literally everything seems to be a playlist! 

Anyway, the client never got past the "Fetch MPD settings" message. I edited /etc/mympd.conf to disable with `smartpls = false` and `generateplstags = Artist` but when I set debug logging and watch, it's still making/remaking genre playlists.

It seems that there are lots of settings that are ignored. Here's my relevant settings:
```conf
taglist = AlbumArtist, Album, Title, Track, Date
searchtaglist = Artist, AlbumArtist, Album, Title
browsetaglist = AlbumArtist, Album
smartpls = false
# only update 'smart' playlists once a day
smartplsinterval = 86400
generateplstags = Artist
```

And from the log, here's what it's sending the client on startup:
```json
{"jsonrpc":"2.0","id":0,"method":"MYMPD_API_SETTINGS_SET","params":{"jukeboxMode":0,"jukeboxPlaylist":"Database","jukeboxQueueLength":1,"jukeboxLastPlayed":24,"jukeboxUniqueTag":"Title","autoPlay":false,"coverimage":true,"coverimageName":"folder, cover","bookletName":"booklet.pdf","love":false,"loveChannel":"","loveMessage":"love","taglist":"Artist, Album, AlbumArtist, Title, Track, Genre, Date","searchtaglist":"Artist, Album, AlbumArtist, Title, Genre","browsetaglist":"Artist, Album, AlbumArtist, Genre","stickers":true,"smartpls":true,"smartplsSort":"","smartplsPrefix":"myMPDsmart","smartplsInterval":14400,"generatePlsTags":"Genre","mpdHost":"/run/mpd/socket","mpdPass":"","mpdPort":6600,"lastPlayedCount":20,"maxElementsPerPage":100,"musicDirectory":"auto"}}
```

So I've never gotten past "Fetch MPD settings" in the client, and am assuming it is getting stuck making playlists. It's also ignoring my searchtaglist, taglist and so on.
[debug.log](https://github.com/jcorporation/myMPD/files/4670673/debug.log)

So I tried to

**To Reproduce**

I haven't got past the startup screen, it's all console, and listed above.

**Expected behavior**

MyMPD respects setting in conf file.

**Server plattform (please complete the following information):**
 - OS: Ubuntu
 - OS version: 19.10
 - Plattform: x86_64
 - MPD version: 0.21.13

**Client plattform (please complete the following information):**
 - Device: MacBookPro
 - OS: OSX 14
 - Browser Chrome, Safari, Firefox all tried, including "private modes" to rule out stuff
 - Browser version [e.g. 22]

**Debug logs (please attach if it can be usefull)**

[debug.log](https://github.com/jcorporation/myMPD/files/4670675/debug.log)

 
 **Configuration (please attach if it can be usefull)**

[mympd.conf.txt](https://github.com/jcorporation/myMPD/files/4670676/mympd.conf.txt)

 **Additional context**

**Comment by mfeif** [comment]
A little more. I poked around, disabled the service and got manual. I tried `mympd reset_state` and then `mympd /etc/mympd.conf dump_config`.

It's attached here. It seems like most of my settings are getting ignored. What's weird is that I can connect on port 8002, as per my config, though the dumped config doesn't reflect that.

[dump_config.conf.txt](https://github.com/jcorporation/myMPD/files/4670699/dump_config.conf.txt)

**Comment by mfeif** [comment]
Ok, after letting it cook a while longer, The UI has come up.

Maybe the "reset_state" helped.

**Comment by mfeif** [comment]
Just want to say that now that it's running, it's super impressive. Thanks for your work, and for sharing it with all of us!

**Comment by jcorporation** [comment]
1) myMPD uses most settings from the config file only if there is no appropriated state file: https://github.com/jcorporation/myMPD/wiki/Configuration

2) The dump_config dumps config defaults not your configuration.

3) Smart playlist generation is done within the main MPD connection. Thats why your web ui sticks with "fetching MPD settings". Generating the playlists in an extra thread with a own MPD connection could resolve this issue.

**Comment by mfeif** [comment]
1. So it ignores /etc/mympd.conf even if it's been changed? That seems unexpected.

2. Ok.

3. I understand.

**Comment by mfeif** [comment]
Well, I'd say that this isn't a bug, then... I just have bad luck with the tags that taggers have inserted into my many files.

**Comment by jcorporation** [comment]
> 1. So it ignores /etc/mympd.conf even if it's been changed? That seems unexpected.

Yes, Web UI settings have always precedence.
