### ISSUE TITLE
MPD disconnect

### ISSUE THREAD

**Issue by antonellocaroli** [jcorporation/myMPD#268]
I always have this error the first time I open the web page, then I go to menu > mpd connection
and the problem is solved automatically.

![image](https://user-images.githubusercontent.com/11161093/82780937-e389f000-9e58-11ea-888a-72d77860e0e0.png)

![image](https://user-images.githubusercontent.com/11161093/82780946-ea186780-9e58-11ea-9bad-1fe6de0e98ac.png)

the same problem happens on the phone, but here it is difficult to solve, it is difficult to access the menu.

![image](https://user-images.githubusercontent.com/11161093/82781002-074d3600-9e59-11ea-8591-89d09dd81382.png)

Config file:

http://dpaste.com/040FS48.txt

**Comment by jcorporation** [comment]
Browser: which browser and which plattform? Log from the browser console would be helpfull.

Phone: What phone is it? Websockets over https in iPhones works is the CA is trusted.

**Comment by antonellocaroli** [comment]
chrome iphone

**Comment by jcorporation** [comment]
You could disable ssl or import the myMPD CA for the websocket connection to work on iPhone.

For your desktop session I need the webbrowser logs.

**Comment by jcorporation** [comment]
commit #0a36a97 should fix this issue.
