### ISSUE TITLE
Embedded covers do not show in WSL

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#277]
myMPD version: 6.4.1

**Describe the bug**

When mympd runs in Windows 10 WSL1 (Windows Subsystem for Linux) with mpd.exe, embedded covers are not available.

**To Reproduce**

1. In Windows 10, run "mpd mpd.conf"
2. In WSL, run "sudo mympd"
3. Open "Browse > Covergrid"

**Expected behavior**

It shows embedded covers as well as external covers.

**Server plattform (please complete the following information):**
 - OS: Windows
 - OS version: Windows 10 Home 2004
 - Plattform: x86_64
 - MPD version: 0.21.23

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10 & Ubuntu Linux 20.04 in WSL
 - Browser: chrome
 - Browser version: 83.0

**Debug logs (please attach if it can be usefull)**

[mympd.log](https://github.com/jcorporation/myMPD/files/4720969/mympd.log)
 
 **Additional context**

FYI, music directories are different between mpd in Windows (d:\Music) and mympd in WSL (/mnt/d/Music).

**Comment by jcorporation** [comment]
> DEBUG    /build/mympd-syQ4gK/mympd-6.4.1/src/web_server/web_server_albumart.c:194: Mimetype of /mnt/d/Music//Various Artists - [멜론] 2020년 05월 09일 TOP100 (320Kbps)/090 HYNN (박혜원) - 시든 꽃에 물을 주듯.MP3 is application/octet-stream

This was the problem. myMPD does not detect the mime type of your music file, because the extension is all upper case. I fixed it quickly in devel, can you give it a try?

**Comment by parkmino** [comment]
Now it shows "ERROR    Can't parse id3_file: /mnt/d/Music//Various Artists..."

**Comment by parkmino** [comment]
Hmm...
I changed one of the file extinctions to small.
Some files show covers while others are not.

**Comment by parkmino** [comment]
After initializing, it works fine.
Thanks a lot!

![mympd](https://user-images.githubusercontent.com/12131158/83616489-dee4da80-a5c2-11ea-815e-14db88df7556.png)

**Comment by jcorporation** [comment]
Please enable debug and attach the log of myMPD and MPD.

**Comment by parkmino** [comment]
Please find the attached file for mympd log.

[mympd.log](https://github.com/jcorporation/myMPD/files/4763164/mympd.log)

mpd.log is quite simple as attached.
Should I download debug version for this?

[mpd.log](https://github.com/jcorporation/myMPD/files/4763172/mpd.log)

**Comment by jcorporation** [comment]
> ERROR    /build/mympd-5yEJ8Y/mympd-6.4.2/src/web_server/web_server_albumart.c:225: Can't parse id3_file: /mnt/d/Music//Various Artists - [멜론] 2020년 05월 09일 TOP100 (320Kbps)/069 Maroon 5 - Memories.MP3

This error is thrown if `id3_file_open` can not open or parse the file. 
- are filesystem permissions correct? You could check it with the myMPD browse function.
- Try to remove the last `/` in your music directory config.

**Comment by parkmino** [comment]
1. No problem with browse function, only embedded covers are broken.
2. I removed "/" at the last, however it points out the same directory "/mnt/d/Music//.." in error message.

**Comment by jcorporation** [comment]
You changed it in the web ui in the connection dialog?

**Comment by parkmino** [comment]
No, I edited musicdirectory in /etc/mympd.conf

**Comment by jcorporation** [comment]
> No, I edited musicdirectory in /etc/mympd.conf

Web UI overrides this setting.

**Comment by parkmino** [comment]
I changed it in web browser and duplicated slashes are gone.
However error message as following and no embedded covers.

ERROR    Can't parse id3_file: /mnt/d/Music/Various Artists - [멜론] 2020년 05월 09일 TOP100 (320Kbps)/087 Anne-Marie - Birthday.MP3

**Comment by parkmino** [comment]
reset_state & clear_covercache did work and embedded covers show up after reboot.
Thanks!
