### ISSUE TITLE
Change current hyphen behaviour

### ISSUE THREAD

**Issue by pinkdotnl** [jcorporation/myMPD#279]
Currently hyphenation is always done, even inside words. 
[https://github.com/jcorporation/myMPD/blob/ca6bbe4f068fc6f046124d1877ecccfa5f15e534/htdocs/css/mympd.css#L73](url)

An option would be to change 'break-all' to 'break-word':
[https://www.w3schools.com/cssref/css3_pr_word-break.asp](url)
This will respect words and will only break a word to prevent overflow.

**Comment by jcorporation** [comment]
This seems to be a follow-up of #143 and #139. I don't know what is the best fix for all of this issues. Eventually it can be rechanged to break-word if the gui strips the query part.

**Comment by jcorporation** [comment]
Changing break-all to break-word seems to be fine.

**Comment by Emilot** [comment]
I must re-open this issue because i have the same problem. The tiles are very ugly, like lists. Then i saw this issue and add this:

  **_word-break: break-word;
  min-width: 6rem;_**

to mympd.css

The titles are fine now in mobile but i do not know if it cause issues with hyphen behavior...thing.

**Comment by jcorporation** [comment]
I think removing break word from td[data-col=Title] is the better solution. I added this to the v6.6.0 branch. Please test it.

**Comment by Emilot** [comment]
Great JC! Fixed. Thank you.
