### ISSUE TITLE
Add HTTP Auth

### ISSUE THREAD

**Issue by 9ParsonsB** [jcorporation/myMPD#29]
**Is your feature request related to a problem? Please describe.**
I would like to put this on a public port but bots (or people) always end up finding it and pressing random buttons (e.g. I have come home to Never Gonna Give You Up on repeat multiple times)

**Describe the solution you'd like**
Please add HTTP Auth either on connect, or to be able to press buttons.

**Describe alternatives you've considered**
Or some other form of authentication (per connection basis).

**Additional context**
![image](https://user-images.githubusercontent.com/6250431/44501507-ce56bf00-a6d0-11e8-9d87-8ceb53ba892d.png)

**Comment by jcorporation** [comment]
Hi,

firstly thanks for your feature request.

I shortly tried out basic auth support, but there are some issues with it:
1. ServiceWorkers and the Webapp Manifest have issues with http basic auth
2. Basic auth for websockets does not work

For 1. there are possible workarounds, but for 2. I found no acceptable workarounds. Not protecting websockets leads to pseudo security in my opinion (ympd bypassed http auth for websocket connections). So basic auth is no option to implement.

Implementing a own session management is currently to big for this lightweight project.

I would recommend to put myMPD behind a reverse proxy to do the authorization things.

**Comment by 9ParsonsB** [comment]
@jcorporation Thanks for your response. I didn't know you could do HTTP auth via reverse proxy. 
Will look into it. 
Thanks.
