### ISSUE TITLE
AlbumArtist Tag / Covergrid

### ISSUE THREAD

**Issue by pinkdotnl** [jcorporation/myMPD#291]
myMPD version: Version: 6.4.2
RPi 3 - Raspbian10

Not clear if this is a bug or intended use.

The AlbumArtist tag is linked to Covergrid? If I disable the tag AlbumArtist in 'Tags to use', Covergrid tab is removed from the Browse view. If I enable AlbumArtist again, Covergrid is displayed in the Browse view.

I would like to disable the Albumartist tag, but keep the covergrid. This is currently not possible.

**Comment by jcorporation** [comment]
In the current code base the covergrid uses the albumartist tag hardcoded. Thats why it is disabled if you disable this tag. In the process of merging the covergrid with the database view, I can try to remove this dependency. Why do you not want the AlbumArtist tag?

**Comment by pinkdotnl** [comment]
There are several reasons not to. 1 of them is that I don't have compilations in my music library. Another thing is that the AlbumArtist tag is (in my opinion) often mis-used or wrongly interpreted (by apps and people). To prevent unwanted artist entries in my library, I removed the AlbumArtist tag. As MPD falls back to Artist in this case, it isn't a big deal for me, other than it shows the AlmbumArtist entry in the drop-down menu when opening the Covergrid for the first time. After selecting Album or Artist, the AlbumArtist entry disappears.

It looks like AlbumArtist is the default view when opening a tab like Database or Covergrid. When merging the Covergrid into the Database view, it might be an idea to make it possible to select a default view in settings?

**Comment by Emilot** [comment]
+1 for the selection JC...

**Comment by jcorporation** [comment]
A selectable default view is a good idea.

**Comment by jcorporation** [comment]
The covergrid in devel should now be working without the AlbumArtist tag. Feel free to reopen the issue if it does not work for you.
