### ISSUE TITLE
MYMPD does not force ReplayGain setting to MPD after restart

### ISSUE THREAD

**Issue by thaihugo** [jcorporation/myMPD#292]
myMPD version: 5.6.2

Hi,

It seems the timer setting is reseting the replaygain parameter. When a new timer defines a new playlist for the jukebox, the replaygain get back to none from "song" for example.

Tell me if you cannot reproduce this on your side, i'll send logs and exact protocol.

Thanks

Thaihugo

**Comment by jcorporation** [comment]
Please upgrade to the latest release and post all necessary logs and informations - use the bug report template

**Comment by thaihugo** [comment]
Sorry, not the right diagnosis on my side.

I though mympd would be enforcing Replaygain parameter to MPD at each restart, but MPD resets to it's config file mpd.conf parameter when starting.

I've set the replaygain parameter in mpd.conf and it's staying.
Except if it's not expected, it's not a bug from Mympd.

**Comment by jcorporation** [comment]
I think your MPD needs a state file to preserve such settings across restarts. myMPD sets and reads such options over the mpd protocoll and dont save it elsewhere.
