### ISSUE TITLE
Request: Prebuilt Packages for ArchLinux ARM 

### ISSUE THREAD

**Issue by m040601** [jcorporation/myMPD#296]
Thank you so much for your well kept work on this very usefull package.
I noticed that you provide a lot of prebuild binaries for different distros and architecture.

You build for ARM, as I can see here for Raspbian
https://download.opensuse.org/repositories/home:/jcorporation/Raspbian_10/armhf/

You also do so for Archlinux, but it's only for x64.
https://download.opensuse.org/repositories/home:/jcorporation/Arch/

There is also Archlinux ARM (completely independent from Archlinux x86)
It's a very well maintained distro with official support  for many ARM devices.

Example the Raspberry Pi
https://archlinuxarm.org/platforms
pi zero: armv6h
pi2 : armv7h
pi3 and 4 : aarch64

Another very trending and popular ARM distribution is ManjaroARM.  . It supports the Raspberry Pi 4. It's basicly built from ArchlinuxARM, so the same Raspberry Pi 4 package would work in both.

I've been using ympd for years on the Raspberry Pi. 
But would like to change to mympd. Unfortunately there is no package for it.

Would it be possible to provide these prebuild arm binaries ?
Not everyone uses Raspbian on the Raspberry Pi.
Thanks in advance.

**Comment by jcorporation** [comment]
I tried to enable the armv6l, armv7l, and aarch64 repositories in the build service from suse. Unfortunately this architecture are not supported (unresolvable package errors before building starts). I have seen your comment in https://aur.archlinux.org/packages/ympd/. I think the best would be indeed a package in AUR. I have the same problem with Debian arm packages (#264)

**Comment by jcorporation** [comment]
thanks to @L0ric0 there is now a package build in AUR: https://aur.archlinux.org/packages/mympd/
