### ISSUE TITLE
hard deps for mympd

### ISSUE THREAD

**Issue by L0ric0** [jcorporation/myMPD#297]
**Is your feature request related to a problem? Please describe.**
Make it clear in the README that myMPD has no hard dependencys (dependencys which need to stay installed after building of the binary)

**Describe the solution you'd like**
just a sentance in the README as most programs normaly need one or two deps

**Describe alternatives you've considered**
well if there are hard deps list them

**Additional context**
it is realy hard to build a pkgbuild for the arch aur as myMPD would not have any deps but only optdeps or makedeps

**Comment by jcorporation** [comment]
A sentence in the dependencies section like: 
`myMPD has no hard runtime dependencies beside the standard c libraries. Not installing the optional dependencies leads only to a smaller subset of myMPD functions.`

> it is realy hard to build a pkgbuild for the arch aur as myMPD would not have any deps but only optdeps or makedeps

Why is this a problem? If you want you can create two pkgbuilds - one with all dependencies as non-optional (myMPD-heavy) and one without all optional dependencies (myMPD-light).

**Comment by L0ric0** [comment]
the problem was that today it is quite hard to belive that a program realy doesn't need anything else than the standard c libs. So building the package is not realy a problem with the knowledge that all of the deps are optional as stated.

Another question all the optional packages need to be installed at compile time and after for myMPD to work or is it possible to build with all options enabled  and removing the optional deps after installation and have myMPD still working (obviously with a reduced featureset) as the librarys are loaded at runtime if they are found?

**Comment by jcorporation** [comment]
For building you need the libraries and there devel parts (header files). The header files are only needed at compile time. The libraries are needed also at runtime.  Arch don't differentiate this, e.g. Debian or rpm based distros does. 

Summarized:
If you compile myMPD with a library you need this library also at runtime. I think this is a standard behavior.
