### ISSUE TITLE
Liblua5.3 instead of 5.3-0

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPD#300]
myMPD version: [6.5.1], on raspbian

When using " build.sh pkgdebian" , the package produced is uninstalable

**To Reproduce**

1. Run build.sh installdeps
2. Run build.sh pkgdebian
3. run dpkg -i packages/mympd*.deb
4. Cant install because liblua5.3 dependency is not met

**Proposed fix**

liblua5.3 seems to be named liblua5.3.-0 in raspbian (same in debian ?)

replacing "liblua5.3" by "liblua5.3-0" in the debian control file seems to fix the bug.

Thanks !

**Comment by jcorporation** [comment]
Is already fixed in devel.
