### ISSUE TITLE
Issue with queue display when clearing the queue

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#302]
myMPD version: 6.5.1

Queue screen is unusable if it's emptied while the queue display was on a page displaying songs beyond the value set in the pagination setting.

**To Reproduce**

Fill the queue with more than <pagination> songs
Go to page 2 or beyond
Clear the queue
an error popup displays "Bad song index"
Press F5
The queue view does not show the current queue and an error popup displays "Bad song index"
No control is visible to change the page in the queue view.
You can't see the queue unless adding enough song to fill the pagination until the page you were seeing before clearing the queue.

**Expected behavior**
The Queue view should display the current queue and the pagination should be reset to page 1.

**Screenshots**

 
 **Additional context**
To manually fix the issue, one can also manually change the page ID in the URL to reset the pagination view to page 1 :
from
https://192.168.1.1/MyMPD/?#/Queue/Current!200/any/-/
to
https://192.168.1.1/MyMPD/?#/Queue/Current!0/any/-/

**Comment by jcorporation** [comment]
Thanks for reporting this bug, is now fixed in devel.
