### ISSUE TITLE
Korean Translation for 6.6.0

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#306]
as attached.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/5043818/ko-KR.txt)

**Comment by jcorporation** [comment]
Updated, thanks for your timely translation efforts!

**Comment by parkmino** [comment]
Add an Korean translation.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/5145198/ko-KR.txt)
