### ISSUE TITLE
Header set Content-Security-Policy "frame-ancestors 'self';"

### ISSUE THREAD

**Issue by payback007** [jcorporation/myMPD#307]
myMPD version: latest

Hi all,

I want to embedd mympd for audio playback using in smarthome visu application. There I try to embedd with an "iframe" the mympd application into EDOMI.

After starting visu application, the iframe always ending up with following failure report:

`[Error] Refused to load http://[IP-adress of mympd]:90/ because it does not appear in the frame-ancestors directive of the Content Security Policy.`

Tried the same already with an aditional reverse proxy setup, ending up in same error.

**Expected behavior**

Is it possible to extend the webserver configuration for iframe support?

From searching the internet I found following solution:
**Content-Security-Policy: frame-ancestors 'self'**
This should maybe do it.

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: debian buster
 - Plattform: x86_64
 - MPD version: latest_stable

**Client plattform (please complete the following information):**
 - Device: webinterface or mobile
 - OS: android as well as OSX
 - Browser chrome and safari

Thanks for the support!

**Comment by jcorporation** [comment]
frame-ancestors is set explicitly to 'none' and X-Frame-Options to deny. But I don't think I add a security hole if I add self.
Is now changed in the devel branch. 

Please test and close this issue if it works.

**Comment by payback007** [comment]
thanks for the fast support, but unfortunately the error keep same:

**Refused to load _http://IP-address/_ because it does not appear in the frame-ancestors directive of the Content Security Policy.**

I think it is a matter of need of source address, examples from internet show:
**Content-Security-Policy: frame-ancestors 'self' https://www.example.org;**

-> but my coding knowledge is too poor how to code in the actual used IP address.

**Comment by jcorporation** [comment]
This headers are defined in `src/web_server/web_server_utility.h`. There you can customize it to your requirements. I role back the commit 2388bce.

**Comment by payback007** [comment]
solved the topic, expand "frame-ancestors" with an "*" would resolve my problem:

**frame-ancestors * 'self'**

here is the full working configuration for these two sections:

#define EXTRA_HEADERS_DIR "Content-Security-Policy: default-src 'none'; "\
                          "style-src 'self' 'unsafe-inline'; font-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; "\
                          "connect-src 'self' ws: wss:; manifest-src 'self'; "\
                          "media-src *; frame-ancestors * 'self'; base-uri 'none';\r\n"\
                          "X-Content-Type-Options: nosniff\r\n"\
                          "X-XSS-Protection: 1; mode=block"

#define EXTRA_HEADERS "Content-Security-Policy: default-src 'none'; "\
                      "style-src 'self'; font-src 'self'; script-src 'self'; img-src 'self' data:; "\
                      "connect-src 'self' ws: wss:; manifest-src 'self'; "\
                      "media-src *; frame-ancestors * 'self'; base-uri 'none';\r\n"\
                      "X-Content-Type-Options: nosniff\r\n"\
                      "X-XSS-Protection: 1; mode=block"

Is an enhancement stil possible? It would be safe for future updates and I expect everybody will have the same topic if using the client with "iframe".

**Comment by jcorporation** [comment]
I think you don't need the 'self' if you have a *. Can you test it without the 'self' again?

When I chose these settings, I didn't think that users might want to embed myMPD in other applications. So I like to change this setting.

**Comment by payback007** [comment]
Yes you are right, also working with a *, the option 'self' is not needed.

Thank you very much for implementation and your great work on myMPD!
