### ISSUE TITLE
Local playback with Google Chrome with ssl enabled and HTTP stream

### ISSUE THREAD

**Issue by Trois-Six** [jcorporation/myMPD#311]
myMPD version: [6.6.0](https://github.com/jcorporation/myMPD/tree/0480f77c8bc23d51c6e3f4ef00484e2a52c274c8)

**Describe the bug**

When ssl is enabled in myMPD and local playback is enabled with a HTTP stream (not HTTPS), the local playback works for Firefox (79.0-1) but not for Google Chrome.
Now that I know the problem, it's an expected behaviour, but I think that it should be documented or explained in the UI.

**To Reproduce**

1. Enable ssl in myMPD
2. Activate a HTTP output in MPD
3. Configure the URI to this output in myMPD
4. Play a song

**Expected behavior**

We should have the same behaviour on every browser, or the behaviour should be documented.

**Server platform:**
 - OS: Raspbian
 - OS version: 10.4
 - Plattform: Raspberry Pi 2
 - MPD version: 0.21.5-3

**Client platform:**
 - Device: Laptop
 - OS: Debian Sid
 - Browser: Google Chrome
 - Browser version: 84.0.4147.125-1

**Debug logs**

 - Browser error console:
```shell
Mixed content: load all resources via HTTPS to improve the security of your site
Even though the initial HTML page is loaded over a secure HTTPS connection, some resources like images, stylesheets or scripts are being accessed over an insecure HTTP connection. Usage of insecure resources is restricted to strengthen the security of your entire site.
AFFECTED RESOURCES: 
1 request: mpd.mp3
1 response: mpd.mp3, restriction status: automatically upgraded
```

**Comment by jcorporation** [comment]
Thanks for that issue. This is realy bad for the local player functionality. I think Firefox would move to the same restriction anytime soon.

myMPD can display a warning if the local player is activated and myMPD itself is served via https and display a link to the wiki with further explanation.

To solve the problem setup a ssl reverse proxy for the http stream (simply with stunnel). You can use the certificate of myMPD. Then change the local player setting to URI: https://<mpdhost>:<sslport>. Port setting uses always http, but that can be changed in a next version of myMPD.

Example stunnel configuration:
```
[mpd-https]
client = no
accept = <sslport>
connect = 127.0.0.1:<mpd http stream port>
cert = /var/lib/mympd/ssl/server.pem
key = /var/lib/mympd/ssl/server.key
```

But the best would be if MPD would also provide a HTTPS stream.

**Comment by Trois-Six** [comment]
I confirm it works with stunnel and your last commits.
Thx a lot for your efficiency!
