### ISSUE TITLE
Percentage signs in folder names

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#313]
myMPD version: [e.g. 5.6.2] (of course - from git)

**Describe the bug**

Using the filesystem browser, it is not possible to enter a folder with a percentage ("%") sign in it. You can, however, replace "%" with "%25" in the URL that comes up, and browse it just fine - it does not cause problems in other views. You can also click the triple bar and play it, no problem. Tested with both Chrome and Firefox, and they both seem annoyed about "100% Live" getting URL'ed as "100%%20Live".

If it matters, my music_directory is CIFS mounted, but i doubt it's that - you know better 👍 

Greetings,
Bo

**Comment by jcorporation** [comment]
Is now fixed in devel.

**Comment by therion23** [comment]
Danke schön - that's two drinks i owe you now!
