### ISSUE TITLE
Long URI out of box in Queue

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#321]
myMPD version: 6.6.0

As attached.

![2020-08-29-210421_1600x900_scrot](https://user-images.githubusercontent.com/12131158/91636796-45508c00-ea3e-11ea-985f-00d244ced373.png)

**Comment by jcorporation** [comment]
Seems to be a regression of: Change current hyphen behaviour #279

**Comment by jcorporation** [comment]
`word-wrap: break-word` is not working in chrome, is now fixed in devel.
