### ISSUE TITLE
devuan ascii install

### ISSUE THREAD

**Issue by 0jd** [jcorporation/myMPD#325]
myMPD version: 6.6.1
I installed the debian 9.0 package on Devuan ascii system but when I tried to start the service it did not go into the background and did not create a pidfile

I had to add some parms to start-stop-daemon in /etc/init.d/mympd
under start I added --background and  --make-pidfile to the start-stop-daemon command.
under stop I added --remove-pidfile to the start-stop-daemon command.

**Comment by jcorporation** [comment]
Thanks for your bug report. Can you please attach your working init script?

**Comment by 0jd** [comment]
here's the init script: (with txt suffix added...)
[mympd.txt](https://github.com/jcorporation/myMPD/files/5158203/mympd.txt)

**Comment by 0jd** [comment]
I attached it to the thread, I hope.

**Comment by jcorporation** [comment]
Thanks, I added your parameters.
