### ISSUE TITLE
Local Playback:  Error loading Stream

### ISSUE THREAD

**Issue by john-** [jcorporation/myMPD#326]
myMPD version: 6.6.1

Trying to get local playback working for the first time.  1)  In Settings|General I selected "Local playback" and specified HTTP Port 8000.  2)  When I check the output device using icon in upper right corner it indicates "Error loading stream".

Adding a song to the queue has the same results.

I haven't done any other configuration when attempting to make this work.

**To Reproduce**

**Expected behavior**

I would hear music on my laptop instead of the speakers on same system as myMPD.

**Server plattform (please complete the following information):**
 - OS: Linux running on Odroid C2
 - OS version:  TBD
 - Plattform: aarch64
 - MPD version: 0.20.18

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: Fedora 32 maybe
 - Browser firefox
 - Browser version 78.0.2

**Comment by jcorporation** [comment]
You have read this wiki article: https://github.com/jcorporation/myMPD/wiki/Local-playback

**Comment by john-** [comment]
I read the wiki page.  However I am not using SSL.

I did not know I needed to configure a stream output in mpd.   I will close this ticket and do that part now.
