### ISSUE TITLE
Play circle icon invisible in android portrait mode

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#327]
myMPD version: 6.6.1

**Describe the bug**

Play circle icon is not visible in android portrait mode for the latest Chrome & Firefox as attached.

![Screenshot_20200910-052316](https://user-images.githubusercontent.com/12131158/92649814-9017b100-f326-11ea-89a3-190df667baf3.png)

**Comment by jcorporation** [comment]
You mean the icon in the left top? This is intentional hidden on small screens.

**Comment by parkmino** [comment]
Oh, I see.
