### ISSUE TITLE
Bottom menu bar location varies in Firefox

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#328]
myMPD version: 6.6.2

**Describe the bug**

Bottom menu bar location is not fixed when moving around the menus for Firefox.

**Screenshots**

![Screenshot_20200917-072223](https://user-images.githubusercontent.com/12131158/93399190-02a10780-f8b8-11ea-86b7-523a8e07b04a.png)

**Client plattform (please complete the following information):**
 - Device: Samsung Galaxy Note5
 - OS: Android 7.0
 - Browser: Firefox
 - Browser version: 80.1.3

**Comment by jcorporation** [comment]
What do you mean with "when moving arround"? Is it a new behavior with this myMPD version or this new browser version?

**Comment by parkmino** [comment]
I am not sure about the myMPD version and Firfox version, because I've been using Chrome mostly.
Clicking the bottom menus should reproduce this at Firefox.

**Comment by jcorporation** [comment]
I have here no android device with firefox. Firefox on desktop has no problems. I use the default ".fixed-bottom" class of bootstrap.

you can try:
```
.fixed-bottom {
    position: absolute !important;
}
```
This is set to `fixed` in bootstrap.

**Comment by parkmino** [comment]
Firefox desktop has no problem either on my side.
The above solution does not work.

**Comment by jcorporation** [comment]
I can not reproduce the issue. I have installed the latest Firefox on a Fire tablet and myMPD works like a charm. But I tested it with the devel version of myMPD that has a reworked UI.

It should look like this screenshot:

![image](https://user-images.githubusercontent.com/765844/95382996-c119e000-08ea-11eb-8f12-e294fabf65c7.png)

**Comment by parkmino** [comment]
Firefox mobile might have this issue and resolve it.
Anyway, UI will be changed and I will test with the next release.

**Comment by parkmino** [comment]
Firefox mobile just have been updated and I don't see any problem yet.
