### ISSUE TITLE
EXTM3U playlist titles for streams

### ISSUE THREAD

**Issue by tbarg** [jcorporation/myMPD#329]
Thank you for this awesome MPD frontend! It is the only one that leaves almost nothing to desire.

I have one enhancement proposal though: I keep a playlist with online radio streams. The list is in EXTM3U format, which means that it contains a descriptional title besides the stream address. MPD supports such playlists, and sets the track titles to these descriptional titles when the playlist is loaded (when the stream is played, MPD replaces the titles with the icecast title tag, if it finds any in the stream). At least ncmpcpp displays the EXTM3U descriptional titles when I let MPD load the playlist. myMPD does not do that for some reason, but rather displays the last component of the stream address as the track title. For example, if the playlist file is

#EXTM3U
#EXTINF:-1,Radio Paradise Main Mix
https://stream.radioparadise.com/aac-320
#EXTINF:-1,WQXR Classical (New York)
http://stream.wqxr.org/wqxr.aac

then myMPD displays "aac-320" and "wqxr.aac" in the queue, whereas ncmpcpp displays "Radio Paradise Main Mix" and "WQXR Classical (New York)", which is much more useful. It would be awesome if myMPD could also display these titles.
Again, thank you very much for this awesome client!

**Comment by jcorporation** [comment]
myMPD does not read the playlist file directly. It get its content through the mpd protocol.
A quick test to list the contents of your m3u files shows:
```
lsinfo Webradios
playlist: Webradios/radioparadise.m3u
Last-Modified: 2020-09-20T07:10:56Z

listplaylist Webradios/radioparadise.m3u
file: https://stream.radioparadise.com/aac-320
OK
```
It seems the mpd protocol don`t respond with the extended m3u info. Reads ncmpcpp the playlist files directly? Can you start mpd in verbose mode and look at the log file which commands ncmpcpp calls?

**Comment by tbarg** [comment]
I think the way it works is that the client (e.g. mpc) only
tells mpd to load the playlist. MPD itself then populates
the queue, with the title info from the m3u file.

ncmpcpp does not read the file directly.

Does this help? I don't have access to my server right now,
so can't do the logging test atm.

**Comment by tbarg** [comment]
By loading the playlist I mean calling
"mpc load <name of the playlist>".

**Comment by jcorporation** [comment]
I can not reproduce your extm3u behavior. I used your submitted playlist and loaded it with mpc load. Both, mpc and ncmpcpp displays the last part of the uri, not the extended info of the extm3u playlist. Also at the protocol level, mpd does not respond with the extended info.

I test with MPD 0.22

```
telnet localhost 6600
playlistinfo
file: https://stream.radioparadise.com/aac-320
Time: 0
duration: 0.000
Pos: 0
Id: 1
file: http://stream.wqxr.org/wqxr.aac
Time: 0
duration: 0.000
Pos: 1
Id: 2
OK
```

Please provide the verbose log of mpd and the mpd protocol response and reopen the issue.
