### ISSUE TITLE
Usability enhancements (mostly covergrid)

### ISSUE THREAD

**Issue by tbarg** [jcorporation/myMPD#330]
After using mympd a bit more, I have two enhancement proposals:

- It would be nice if the covergrid would use the full available window width. Presently, it seems to be limited to 5 columns maximum.

- It would also be nice if the covergrid search field would have an option to match any of genre/artist/albumartist/album.

- I am missing a button/shortcut to jump to the currently playing song in the queue.

Thank you for your great work!

**Comment by jcorporation** [comment]
For the future: please open for each feature request / bug one issue. It is easier to track it.

> It would be nice if the covergrid would use the full available window width. Presently, it seems to be limited to 5 columns maximum.

This is a limitation of the current bootstrap card based layout, but I am working on a new design of myMPD without this cards.

> It would also be nice if the covergrid search field would have an option to match any of genre/artist/albumartist/album.
That is a limitation of the mpd protocol. The search expression syntax does not have a "OR" keyword only "AND". That limits the function to search only one tag or any tags for a specific string.

> I am missing a button/shortcut to jump to the currently playing song in the queue.
Good idea -> will be implemented in one of the next version.

**Comment by tbarg** [comment]
On Sun, Sep 20, 2020 at 00:39:58 -0700, Jürgen Mang wrote:
> For the future: please open for each feature request / bug one issue. It is easier to track it.

Ok, will do.

> > It would be nice if the covergrid would use the full available window width. Presently, it seems to be limited to 5 columns maximum.
>
> This is a limitation of the current bootstrap card based layout, but I am working on a new design of myMPD without this cards.

Great!

> > It would also be nice if the covergrid search field would have an option to match any of genre/artist/albumartist/album.
>
> That is a limitation of the mpd protocol. The search
> expression syntax does not have a "OR" keyword only "AND".
> That limits the function to search only one tag or any
> tags for a specific string.

Ok, in that case it would be helpful to have an option that
matches any tag.

> > I am missing a button/shortcut to jump to the currently playing song in the queue.
>
> Good idea -> will be implemented in one of the next version.

Nice!

**Comment by tbarg** [comment]
On Sun, Sep 20, 2020 at 15:16:35 +0200, tbarg wrote:
> > That is a limitation of the mpd protocol. The search
> > expression syntax does not have a "OR" keyword only "AND".
> > That limits the function to search only one tag or any
> > tags for a specific string.
>
> Ok, in that case it would be helpful to have an option that
> matches any tag.

Strange that there is no "or" in the mpd find syntax. Could
this be done on the client side, by combining the results of
several "find" commands?

**Comment by jcorporation** [comment]
> Strange that there is no "or" in the mpd find syntax. Could this be done on the client side, by combining the results of several "find" commands?

That is possible but not the best way. MPD should support OR at the protocol level. You should create feature request for MPD.
