### ISSUE TITLE
Song details, album peculiarities

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#331]
myMPD version: 5.6.2 pulled from git and built an hour ago
MPD version: 0.21.20 from the Ubuntu repository

I have found two issues that are most likely related.

For the first example, let's say i have two albums named "Kraftwerk" and "Kraftwerk 2". No matter if i search or browse, i click the triple bar on one of the songs from Kraftwerk, click Song details, and then click the hyperlinked album title.

If i from here choose "Add all from queue", it will add both albums. It looks like the hyperlinked album title becomes a substring match which is then added to the queue, instead of only the album you are looking at.

The second example follows the same path up to clicking the album title. If the album title is a single character, "Add all to queue" will not add anything. This is probably related to the search function ignoring less than two characters, but you know best.

Update: This goes for artists as well. If i browse artists and choose "Act", "Add all to queue" will add every track by every artists whose names contains "act".

Tested with Firefox on macOS and Chrome on Android.

**Comment by jcorporation** [comment]
Adding whole albums in this view uses the old search syntax. This is the source of the problem. In covergrid myMPD uses search expressions and older views uses the path of the first file.

For the upcoming 6.7.0 the database and covergrid are unified and this issue will be fixed.

**Comment by therion23** [comment]
Fantastic. Thank you once again!
