### ISSUE TITLE
replace apend to queue from cover grid issue

### ISSUE THREAD

**Issue by ds06042014** [jcorporation/myMPD#332]
Hi - I'm not sure if this is a known issue or not (I couldn't see it mentioned before) but when you click on a covergrid view to replace or append to the queue it seems to add the entire database to the queue rather than just the album?

**Comment by jcorporation** [comment]
I can not reproduce your issue. Is this behaviour with all your Albums?

**Comment by ds06042014** [comment]
No on some I get an error saying ‘)’ expected

**Comment by jcorporation** [comment]
I need the mympd debug and the mpd verbose log

**Comment by jcorporation** [comment]
Without logs I can not help you. Feel free to reopen this issue if you can provide logs.
