### ISSUE TITLE
segfault if creation of sticker_cache fails

### ISSUE THREAD

**Issue by laclaro** [jcorporation/myMPD#335]
Hi,

simple as that: I get a segmentation fault when using a port different to 6600 in my mympd.conf. Did anyone notice that?

The debug log shows no error. The link to the server is established on port 6601 before is crashes.

**Background: Why not use port 6600?** I run a multi-instance mpd system. The instance listening on Port 6600 is the database instance, the others on 6601 and 6602 and so on are satellite instances using that database providing audio outputs like streams or locally on my media server.

Best,

Henning

**Comment by jcorporation** [comment]
I can not reproduce your issue. Please use the bug report template to open a bug and provide all necessary information. https://github.com/jcorporation/myMPD/wiki/Debug can help to produce the right log files.

**Comment by laclaro** [comment]
Hi,

i debugged as suggested. The issue is with the sticker. If I disable stickers in the config file, the issue is gone. Any suggestions how to dig further?

Here is the core dump:
[mympd_core_dump.txt](https://github.com/jcorporation/myMPD/files/5387211/mympd_core_dump.txt)

Best regards,

Henning

**Comment by jcorporation** [comment]
Thanks for the log. It indicates two problems:
- sticker cache creation fails with an mpd error -> pleas provide the mpd log (verbose loglevel)
- double free bug if sticker creation failes -> fixed in commit 8b60ee228367ad3cd65b1e12a6578438684b79f9

You know you have a very old mpd version running?

**Comment by laclaro** [comment]
My MPD version is default on Ubuntu 18.04: 0.20.18

```
ii  libmpdclient2                               2.11-1                                          amd64        client library for the Music Player Daemon
ii  mpd                                         0.20.18-1build1                                 amd64        Music Player Daemon
```

MPD verbose log does not say much: https://gist.github.com/laclaro/65e08ce399f2598a04b49429c8602728

**Comment by jcorporation** [comment]
```
[2] process command "search file "" window 0:1000"
Oct 17 18:55 : exception: Connection closed by the server
Oct 17 18:55 : client: [2] command returned 2
```

This is the error.
