### ISSUE TITLE
CRITICAL: mpd host/port settings ignored

### ISSUE THREAD

**Issue by tidux** [jcorporation/myMPD#336]
myMPD version: 6.6.2

In /etc/mympd.conf I have the following lines:

```
[mpd]
#Connection to mpd, unix socket or host/port, socket preferred
#host = /run/mpd/socket
host = 192.168.1.2
port = 6600
#pass = 
#host = /run/mpd/socket
```

The file has 0644 permissions.  When I run `strace mympd` I see the file being open()'ed.  However, the program tries to connect to a nonexistent socket.

```
14:52:33 INFO     mpdworker Starting mpd_worker
14:52:33 INFO     mpdworker MPD worker connecting to socket /run/mpd/socket                                           
14:52:33 ERROR    mpdworker MPD worker connection: No such file or directory                                          
14:52:33 ERROR    mpdworker MPD worker connection failed
14:52:33 INFO     mpdclient Starting mpd_client
14:52:33 INFO     mpdclient MPD connecting to socket /run/mpd/socket                                                  
14:52:33 ERROR    mpdclient MPD connection: No such file or directory                                                 
14:52:33 ERROR    mpdclient MPD connection failed
```
Those last three lines repeat forever.

Also, your bug template has spelling errors throughout it.  If you're going to provide a template, proofread it.

**To Reproduce**

Create a configuration file that matches my description above.

**Expected behavior**

MyMPD connects to mpd and starts.

**Screenshots**

N/A

**Server platform (please complete the following information):**
 - OS: Debian
 - OS version 10.6
 - Platform: aarch64
 - MPD version: 

**Client platform (please complete the following information):**
N/A

**Comment by jcorporation** [comment]
After first start, myMPD does not use /etc/mympd.conf for connection information, but the settings in the web ui. You can use mympd reset_state to reset the settings to the values of /etc/mympd.conf

Documentation is here: https://github.com/jcorporation/myMPD/wiki/Configuration
