### ISSUE TITLE
Better handle big collection in the database tab

### ISSUE THREAD

**Issue by atohmdiy** [jcorporation/myMPD#337]
Hello,
First congratulation, mympd is a very nice ui. I'd like to use it but unfortunately the way it handles my music collection in the database tab do not suit my needs. In term of ui for my collection, my favorite app is quod libet with panel view, i have genre, artist, album on the upside and tracks / play on the downside. It's simple and handy for big collection but it's not working great for small portable thing like smartphone.
The alternative i use is mpdroid or vanilla music player interface, with genre, artist, album, then title tabs. There is also the Cantata way that work, with a tree interface.
Here in mympd you can select genre / album / artist but the second tab always end with an album list (that you can tune). In my case i like to start with the genre so when you have a lot of album in a genre you end with a very big list. 
And as you can only filter by name you cannot really filter one specific artist, you end with all the album in the genre that start with the choose letter. It's very imprecise...
The album view is great but you really need to add the ability to select different level of selection before accessing it.
Best regards

**Comment by jcorporation** [comment]
The next version of myMPD gets a new unified view for database tags that combines the database and the covergrid view. Eventually this view is better for your taste.

**Comment by jcorporation** [comment]
In the next version you can define more than one search expression in the albumgrid (same as in advanced search)

**Comment by jcorporation** [comment]
Feature is now in devel
