### ISSUE TITLE
Pregress bar stops when changing from local file to stream

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#340]
myMPD version: 6.7.0

**Describe the bug**

Progress bar stops when changing to a stream in the middle of playing a local file.

**Expected behavior**

Progress bar should be initialized.

**Screenshots**

![image](https://user-images.githubusercontent.com/12131158/96515417-3d73d200-12a0-11eb-93d2-90a3ece64e6b.png)

**Comment by jcorporation** [comment]
Ugly, it was a division through zero in the code. Is now fixed in devel.
