### ISSUE TITLE
Show menu name when mouse-over on it.

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#342]
It would be good to show the menu name when mouse-over on the icon, i.e. Playback, Queue, Browse, Search.
Queue and Browse icons are confusing.

**Comment by jcorporation** [comment]
The four navigatoin links have a title attribute. Your browser should show a tooltip on mouseover.

**Comment by parkmino** [comment]
Firefox 82.0 does not show the tooltips while chromium and microsoft edge are fine.
Close this issue if firefox has this problem.
