### ISSUE TITLE
Playlist deleted when sorted

### ISSUE THREAD

**Issue by niawag** [jcorporation/myMPD#343]
myMPD version: 6.7.0

**Bug**
When I'm editing a playlist, if I try to sort it by Album, Artist or other criteria, it remove a part a all of the playlist content.

**To Reproduce**
1. Go to Playlists
2. Select "Edit Playlist" for a specific Playlist
3. Sort by Album (or other) 
4. Deletion of part or all tracks in the playlist

**Expected behavior**
It should sort the playlist, not remove tracks

**Screenshots**
Normal playlist:
![image](https://user-images.githubusercontent.com/5684014/96747409-89219b00-13c8-11eb-860d-f19b52abd5bb.png)

After sorting by album:
![image](https://user-images.githubusercontent.com/5684014/96747341-71e2ad80-13c8-11eb-997d-e3f9409b5d46.png)

**Server plattform (please complete the following information):**
 - OS: CoreELEC (official): 9.2.4.2 (Amlogic-ng.arm)
 - Plattform: arm64
 - MPD version: e.g. 0.21.4

**Client plattform (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS, Windows 10, Ubuntu Linux 19.10]
 - Browser version [e.g. 22]

**Debug logs (please attach if it can be usefull)**

See https://github.com/jcorporation/myMPD/wiki/Debug

 - myMPD debug log (put the error in bold)
> VERBOSE  webserver /myMPD/src/web_server.c:323: HTTP request (4): /api
> DEBUG    webserver /myMPD/src/web_server.c:496: API request (4): {"jsonrpc":"2.0","id":0,"method":"MPD_API_PLAYLIST_SORT","params":{"uri":"soirée_mpd","tag":"Album"}}
> VERBOSE  webserver /myMPD/src/web_server.c:506: API request (4): MPD_API_PLAYLIST_SORT
> DEBUG    mpdclient /myMPD/src/mpd_client.c:337: Leaving mpd idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:372: Handle request
> VERBOSE  mpdclient /myMPD/src/mpd_client/mpd_client_api.c:64: MPD CLIENT API request (4)(0) MPD_API_PLAYLIST_SORT: {"jsonrpc":"2.0","id":0,"method":"MPD_API_PLAYLIST_SORT","params":{"uri":"soirée_mpd","tag":"Album"}}
> VERBOSE  mpdclient /myMPD/src/mpd_shared/mpd_shared_playlists.c:92: Sorting playlist soirée_mpd by tag Album
> DEBUG    mpdclient /myMPD/src/mpd_shared/mpd_shared_tags.c:64: Setting interesting mpd tag types
> DEBUG    mpdclient /myMPD/src/mpd_shared/mpd_shared_tags.c:64: Setting interesting mpd tag types
> **ERROR    mpdclient /myMPD/src/mpd_shared.c:81: MPD error: No such directory (9)**
> DEBUG    mpdclient /myMPD/src/mpd_client/mpd_client_api.c:827: Push response to web_server_queue for connection 4: {"jsonrpc":"2.0","id":0,"error":{"method":"MPD_API_PLAYLIST_SORT","code": -32000,"message":"No such directory"}}
> DEBUG    mpdclient /myMPD/src/mpd_client.c:383: Entering mpd idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:337: Leaving mpd idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:345: Checking for idle events
> VERBOSE  mpdclient /myMPD/src/mpd_client.c:107: MPD idle event: stored_playlist
> DEBUG    mpdclient /myMPD/src/utility.c:55: Push websocket notify to queue: {"jsonrpc":"2.0","method":"update_stored_playlist","params":{}}
> DEBUG    mpdclient /myMPD/src/mpd_client.c:383: Entering mpd idle mode
> DEBUG    webserver /myMPD/src/web_server.c:249: Sending response to conn_id 4: {"jsonrpc":"2.0","id":0,"error":{"method":"MPD_API_PLAYLIST_SORT","code": -32000,"message":"No such directory"}}
> DEBUG    webserver /myMPD/src/web_server.c:228: Sending notify to conn_id 5: {"jsonrpc":"2.0","method":"update_stored_playlist","params":{}}
> VERBOSE  webserver /myMPD/src/web_server.c:323: HTTP request (4): /api
> DEBUG    webserver /myMPD/src/web_server.c:496: API request (4): {"jsonrpc":"2.0","id":0,"method":"MPD_API_PLAYLIST_CONTENT_LIST","params":{"offset":0,"filter":"-","uri":"soirée_mpd","cols":["Pos","Title","Artist","Album","Duration"]}}
> VERBOSE  webserver /myMPD/src/web_server.c:506: API request (4): MPD_API_PLAYLIST_CONTENT_LIST
> DEBUG    mpdclient /myMPD/src/mpd_client.c:337: Leaving mpd idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:345: Checking for idle events
> VERBOSE  mpdclient /myMPD/src/mpd_client.c:107: MPD idle event: update
> INFO     mpdclient /myMPD/src/mpd_client/mpd_client_state.c:44: Update database ID: 1
> DEBUG    mpdclient /myMPD/src/utility.c:55: Push websocket notify to queue: {"jsonrpc":"2.0","method":"update_started","params":{"jobid":1}}
> DEBUG    mpdclient /myMPD/src/mpd_client.c:372: Handle request
> VERBOSE  mpdclient /myMPD/src/mpd_client/mpd_client_api.c:64: MPD CLIENT API request (4)(0) MPD_API_PLAYLIST_CONTENT_LIST: {"jsonrpc":"2.0","id":0,"method":"MPD_API_PLAYLIST_CONTENT_LIST","params":{"offset":0,"filter":"-","uri":"soirée_mpd","cols":["Pos","Title","Artist","Album","Duration"]}}
> DEBUG    mpdclient /myMPD/src/mpd_client/mpd_client_api.c:827: Push response to web_server_queue for connection 4: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_PLAYLIST_CONTENT_LIST","data":[],"totalEntities":0,"returnedEntities":0,"offset":0,"filter":"-","uri":"soirée_mpd","smartpls":false}}
> DEBUG    mpdclient /myMPD/src/mpd_client.c:383: Entering mpd idle mode
> DEBUG    webserver /myMPD/src/web_server.c:228: Sending notify to conn_id 5: {"jsonrpc":"2.0","method":"update_started","params":{"jobid":1}}
> DEBUG    webserver /myMPD/src/web_server.c:249: Sending response to conn_id 4: {"jsonrpc":"2.0","id":0,"result":{"method":"MPD_API_PLAYLIST_CONTENT_LIST","data":[],"totalEntities":0,"returnedEntities":0,"offset":0,"filter":"-","uri":"soirée_mpd","smartpls":false}}
> DEBUG    mpdworker /myMPD/src/mpd_worker.c:159: Leaving mpd worker idle mode
> DEBUG    mpdworker /myMPD/src/mpd_worker.c:167: Checking for idle events
> VERBOSE  mpdworker /myMPD/src/mpd_worker.c:203: MPD idle event: database
> DEBUG    mpdworker /myMPD/src/mpd_worker/mpd_worker_smartpls.c:43: Smart playlists are disabled
> DEBUG    mpdworker /myMPD/src/mpd_worker.c:183: Entering mpd worker idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:337: Leaving mpd idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:345: Checking for idle events
> VERBOSE  mpdclient /myMPD/src/mpd_client.c:107: MPD idle event: database
> DEBUG    mpdclient /myMPD/src/utility.c:55: Push websocket notify to queue: {"jsonrpc":"2.0","method":"update_database","params":{}}
> VERBOSE  mpdclient /myMPD/src/mpd_client.c:107: MPD idle event: update
> DEBUG    webserver /myMPD/src/web_server.c:228: Sending notify to conn_id 5: {"jsonrpc":"2.0","method":"update_database","params":{}}
> INFO     mpdclient /myMPD/src/mpd_client/mpd_client_state.c:44: Update database ID: 0
> DEBUG    mpdclient /myMPD/src/utility.c:55: Push websocket notify to queue: {"jsonrpc":"2.0","method":"update_finished","params":{}}
> DEBUG    mpdclient /myMPD/src/mpd_client.c:383: Entering mpd idle mode
> DEBUG    mpdworker /myMPD/src/mpd_worker.c:159: Leaving mpd worker idle mode
> DEBUG    mpdworker /myMPD/src/mpd_worker.c:177: MPD worker handle request
> VERBOSE  mpdworker /myMPD/src/mpd_worker/mpd_worker_api.c:49: MPD WORKER API request (-1)(0) MPDWORKER_API_STICKERCACHE_CREATE: {"jsonrpc":"2.0","id":0,"method":"MPDWORKER_API_STICKERCACHE_CREATE","params":{}}
> DEBUG    webserver /myMPD/src/web_server.c:228: Sending notify to conn_id 5: {"jsonrpc":"2.0","method":"update_finished","params":{}}
> DEBUG    mpdworker /myMPD/src/mpd_shared/mpd_shared_tags.c:48: Disabling all mpd tag types
> VERBOSE  mpdworker /myMPD/src/mpd_worker/mpd_worker_stickercache.c:57: Creating sticker cache
> VERBOSE  mpdworker /myMPD/src/mpd_worker/mpd_worker_stickercache.c:114: Sticker cache updated successfully
> DEBUG    mpdworker /myMPD/src/mpd_shared/mpd_shared_tags.c:64: Setting interesting mpd tag types
> DEBUG    mpdworker /myMPD/src/mpd_worker.c:183: Entering mpd worker idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:337: Leaving mpd idle mode
> DEBUG    mpdclient /myMPD/src/mpd_client.c:372: Handle request
> VERBOSE  mpdclient /myMPD/src/mpd_client/mpd_client_api.c:64: MPD CLIENT API request (-1)(0) MPD_API_STICKERCACHE_CREATED: {"jsonrpc":"2.0","id":0,"method":"MPD_API_STICKERCACHE_CREATED","params":{}}
> VERBOSE  mpdclient /myMPD/src/mpd_client/mpd_client_api.c:174: Sticker cache was replaced
> DEBUG    mpdclient /myMPD/src/mpd_client.c:383: Entering mpd idle mode
> DEBUG    mympdapi  /myMPD/src/mympd_api/mympd_api_timer.c:95: Timer with id 1 triggered
> VERBOSE  mympdapi  /myMPD/src/mympd_api/mympd_api_timer_handlers.c:28: Start timer_handler_covercache

 - MPD verbose log (hard to find something related to my issue)
> Oct 21 18:30 : simple_db: removing empty directories from DB
> Oct 21 18:30 : client: [8] process command "status"
> Oct 21 18:30 : client: [8] command returned 0
> Oct 21 18:30 : client: [8] process command "idle update"
> Oct 21 18:30 : client: [8] command returned 1
> Oct 21 18:30 : simple_db: sorting DB
> Oct 21 18:30 : client: [3] process command "idle"
> Oct 21 18:30 : client: [3] command returned 1
> Oct 21 18:30 : simple_db: writing DB
> Oct 21 18:30 : client: [3] process command "status"
> Oct 21 18:30 : client: [3] command returned 0
> Oct 21 18:30 : client: [3] process command "listplaylistinfo "soirée_mpd""
> Oct 21 18:30 : client: [3] command returned 0
> Oct 21 18:30 : client: [3] process command "idle"
> Oct 21 18:30 : client: [3] command returned 1
> Oct 21 18:30 : update: finished: _Playlists
> Oct 21 18:30 : client: [8] process command "status"
> Oct 21 18:30 : client: [8] command returned 0
> Oct 21 18:30 : client: [2] process command "idle database"
> Oct 21 18:30 : client: [2] command returned 1
> Oct 21 18:30 : client: [3] process command "status"
> Oct 21 18:30 : client: [3] command returned 0
> Oct 21 18:30 : client: [3] process command "idle"
> Oct 21 18:30 : client: [3] command returned 1
> Oct 21 18:30 : client: [8] process command list
> Oct 21 18:30 : client: process command "status"
> Oct 21 18:30 : client: command returned 0
> Oct 21 18:30 : client: process command "currentsong"
> Oct 21 18:30 : client: command returned 0
> Oct 21 18:30 : client: [8] process command list returned 0
> Oct 21 18:30 : client: [8] closed
> Oct 21 18:30 : client: [2] process command "tagtypes "clear""
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 0:1000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 1000:2000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 2000:3000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 3000:4000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 4000:5000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 5000:6000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 6000:7000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 7000:8000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 8000:9000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 9000:10000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 10000:11000"
> Oct 21 18:30 : client: [2] command returned 0
> Oct 21 18:30 : client: [2] process command "search file "" window 11000:12000"

 
 **Configuration (please attach if it can be usefull)**
mympd.conf:
> #myMPD configuration file
> 
> [mpd]
> #Connection to mpd, unix socket or host/port, socket preferred
> #host = /run/mpd/socket
> host = 192.168.0.99
> port = 6600
> #pass =
> 
> #absolut path of music_directory of mpd
> #none = no local music_directory
> #auto = get music_directory from mpd (only supported, if connected to mpd socket)
> musicdirectory = /music
> 
> #absolut path of mpd playlist_directory
> playlistdirectory = /playlists
> 
> #MPD compiled with regex support
> regex = true
> 
> [webserver]
> #Webserver options
> webport = 80
> 
> #Enable ssl
> #Certificates are generated under /var/lib/mympd/ssl/
> ssl = false
> sslport = 0
> 
> #Publishes some mpd and myMPD directories
> publish = false
> 
> #Webdav support, publish must be set to true
> webdav = false
> 
> 
> [mympd]
> #Loglevel
> #0 = error
> #1 = warn
> #2 = info
> #3 = verbose
> #4 = debug
> loglevel = 4
> 
> #myMPD user
> #group is the primary group of this user
> user = mympd
> 
> #Usage of stickers for play statistics
> stickers = true
> 
> #Mixrampdb settings in gui
> mixramp = false
> 
> #Enable system commands defined in syscmds section
> syscmds = false
> 
> 
> [syscmds]
> Shutdown = sudo /sbin/halt
> #To use this command add following lines to /etc/sudoers (without #)
> #Cmnd_Alias MYMPD_CMDS = /sbin/halt
> #mympd ALL=NOPASSWD: MYMPD_CMDS

 
 **Additional context**
I'm running mympd with docker

**Comment by jcorporation** [comment]
I can not reproduce your issue. The mpd log does not show the error that the mympd log shows. Can you please retry to collect the mpd log?

**Comment by niawag** [comment]
Hi and sorry for the delay, I reproduced the error and provide the whole log file from startup to bug.
[mpd_grep.log](https://github.com/jcorporation/myMPD/files/5439278/mpd_grep.log)

**Comment by jcorporation** [comment]
Strange issue. Can you Test with an up to date MPD version?

**Comment by niawag** [comment]
I've made a few tests and the non ascii chars doesn't seems to be the issue but it led me to it! I've found an album with a wrong path (I changed it in the folders, not in the playlist). With the paths corrected it's working as it should.

It's easy to test, just have to edit the path to a song in the playlist, edit playlist and sort it by album (or whatever).

Maybe it shouldn't remove the whole playlist and tell that there is wrong items in it?

**Comment by jcorporation** [comment]
myMPD uses a command list to clear the playlist and add the songs in the desired order.
https://www.musicpd.org/doc/html/protocol.html#command-lists
The behaviour in command lists in mind myMPD should use a other approach for sorting/shuffling playlists. Creating a temporary playlist with the sorted songs and then removing and renaming should be a more bullet proof way.

**Comment by jcorporation** [comment]
Is now fixed in devel.
