### ISSUE TITLE
SCAD ISO didn't work on 1.5.0 RPI3

### ISSUE THREAD

**Issue by cdtsuipo** [jcorporation/myMPD#344]
the mdp.log has error as 

exception: Failed to open ISO9660 file /mnt/usb-disk/sda2-ata-TOSHIBA_DT01ABA3/music/1008/The Dave Brubeck Quartet - Time Out (1959)/TIME OUT.iso
++ WARN: unexpected PVD type 0

**Comment by jcorporation** [comment]
I think mpd does not support sacd, but anyway this is a problem of  mpd not of myMPD. myMPD is only a frontend.

**Comment by cdtsuipo** [comment]
sorry , my mistake, i thought here are CollybiaOS form...
