### ISSUE TITLE
Improve pagination

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#346]
Improve pagination, replace through endless scrolling?

Anyone prefers the current pagination mode over endless scrolling? If yes, why?

**Comment by john-** [comment]
The current pagination really doesn't work for me.   I would like to give endless scrolling a try and expect I will like it better.

**Comment by payback007** [comment]
I would also prefer endless scrolling -> it is better to handle for wall mounted tablets/displays.

**Comment by jcorporation** [comment]
I have chosen to improve the pagination and not implementing endless scrolling. I think pagination is the better approach for myMPD.

Improvements made:
- more consistent pagination footer 
- add element limits per view (chosable in the footer)

**Comment by Emilot** [comment]
JC I like the new pagination mode but it has two "problems"...

1) How can i go to the first page if i want?
2) It is kind slow. It draws some CPU (RPi 4) when i hit ""Next", nothing too much but it is something for RPi, even at 25 albums per page

**Comment by jcorporation** [comment]
1. I will add a first and last button to the pagination groups
2. slowness is caused by #398, I revert or optimize it
