### ISSUE TITLE
Docker Image Not Respecting MPD Host?

### ISSUE THREAD

**Issue by diabl0w** [jcorporation/myMPD#347]
myMPD version: Docker

**Describe the bug**

I am running the latest docker container, but is failing to start with the errors:
> 07:27:38 INFO         mpdclient MPD connecting to 127.0.0.1:6600
> 07:27:38 ERROR    mpdclient MPD connection: Connection refused
> 07:27:38 ERROR    mpdclient MPD connection failed

despite pointing to a different ip address in my docker run command:

> docker run -e "MYMPD_MPDHOST=192.168.111.108" -p 4545:80 -it ghcr.io/jcorporation/mympd/mympd92.168.111.108" -p 4545:80 -it ghcr.io/jcorp

**To Reproduce**

> 1. docker pull ghcr.io/jcorporation/mympd/mympd:latest
> 2. docker run -e "MYMPD_MPDHOST=192.168.111.108" -p 4545:80 -it ghcr.io/jcorporation/mympd/mympd92.168.111.108" -p 4545:80 -it ghcr.io/jcorp

**Expected behavior**
mympd should be trying to connect to 192.168.111.108, not 127.0.0.1

**Server plattform (please complete the following information):**
 - OS: proxmox/debian lxc
 - Plattform: x86
 - MPD version: 0.21.5

**Comment by diabl0w** [comment]
since I am already running in a container, I just set the docker network mode to host so it works

**Comment by jcorporation** [comment]
MYMPD_MPDHOST should be MPD_HOST
Details: https://github.com/jcorporation/myMPD/wiki/Configuration

**Comment by diabl0w** [comment]
> MYMPD_MPDHOST should be MPD_HOST
> Details: https://github.com/jcorporation/myMPD/wiki/Configuration

WHOOPS! Thank you. Can you tell me one thing quickly? ... I am hoping to use this web app to control multiple mpd instances. In the current implementation, is it possible to do this? i.e quickly going into a menu and selecting another mpd instance that has been configured?

**Comment by jcorporation** [comment]
Not at the moment, but a feature is on the roadmap: #304

**Comment by diabl0w** [comment]
> Not at the moment, but a feature is on the roadmap: #304

AMAZING! Thank you... so much potential here that is not available anywhere else. Might I informally make a feature suggestion for implementing snapcast support (really just being able to control volume of individual clients in a group, but more integration would be even better). That would make this the defacto best home audio client solution. It is already nice and lightweight with a clean UI and uses mpd instead of mopidy which is great.

**Comment by jcorporation** [comment]
Thanks for your feedback. Feel free to open a feature request.
