### ISSUE TITLE
Choose "Browse" destination / Customizable menu

### ISSUE THREAD

**Issue by niawag** [jcorporation/myMPD#352]
Is it (or would it be) possible to set the "Browse" destination? I'm not really using Library and I'd like to choose another endpoint for this. This could be set in the config file or the in-app settings.

I tried to disable all the tags to browse and it made the "Library" disappear from "Browse" entry but it's still sending me there when clicking on it from another page.

Another, broader, way to achieve this would be to allow a complete customization of the menus. I'd like the top level with Play / Queue / Playlists / Filesystem but I'm sure others would like another setup.

**Comment by jcorporation** [comment]
I think a customizable navigation bar is the best approach and should be relatively easy to implement.

**Comment by jcorporation** [comment]
Is now implemented in devel. The documentation for this feature is here: https://github.com/jcorporation/myMPD/wiki/Custom-navbar-icons

**Comment by niawag** [comment]
Great! That was fast!

I'll test as soon as v6.8.0 is out and I may add some explanation in the wiki to help setting this with docker (should'nt be complicated)

**Comment by jcorporation** [comment]
v6.8.0 is already released.

**Comment by niawag** [comment]
Great, 6.8.0 is working nice but I'm not sure I can achieve what I want with the new navbar option. I'd like to directly access Playlists and Filesystem and I've added this to the navbar_icons file:
 
>  {
>     "ligature": "playlist_play",
>     "title":"Playlists",
>     "options": ["Browse/Playlists"],
>     "badge":""
>   },
>   {
>     "ligature": "folder",
>     "title":"Filesystem",
>     "options": ["Browse/Filesystem"],
>     "badge":""
>   },
> 
I can see the icons but the link is not valid.
I also tested with "options": ["Playlists"] and "options": ["Filesystem"], same result. 

Is it a misunderstanding of how it works or is it not possible to do it?

**Comment by jcorporation** [comment]
The slashes in the uri are the separators of the options array. This should work:
```
{
"ligature": "playlist_play",
"title":"Playlists",
"options": ["Browse","Playlists"],
"badge":""
},
{
"ligature": "folder",
"title":"Filesystem",
"options": ["Browse","Filesystem"],
"badge":""
},
```

**Comment by niawag** [comment]
That's it! Thanks a lot!
