### ISSUE TITLE
volume_off, volume_down and volume_up displayed instead of symbol

### ISSUE THREAD

**Issue by jdr85** [jcorporation/myMPD#354]
myMPD version: 6.7.0

In 6.7.0 "volume_off" (0 %), "volume_down" (1-49 %) and "volume_up" (50-100 %) are displayed instead of a volume symbol.
It does not have any horrible effect but is just a cosmetic thing. See attached screenshots.

**Server plattform:**
 - OS: Arch Linux ARM
 - OS version: current
 - Plattform: armv6l
 - MPD version: 0.22.3-1
 - Device: Raspberry Pi 1B

**Client plattform (please complete the following information):**
 - Device: Device independent
 - OS: OS independent
 - Browser: Browser independent
 - Browser version: -
![volume_off](https://user-images.githubusercontent.com/67578404/99414232-e856ca80-28f6-11eb-9493-99ee40754f95.PNG)
![volume_down](https://user-images.githubusercontent.com/67578404/99414244-eab92480-28f6-11eb-8df3-cfd3943ed709.PNG)
![volume_up](https://user-images.githubusercontent.com/67578404/99414237-ea208e00-28f6-11eb-9ec8-829b9a8be465.PNG)

**Comment by jcorporation** [comment]
Thanks for your bug report. It is already fixed in devel.
