### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#355]
Notifications should be improved, first ideas:

- each message should get a facility, e.g. player, script, queue, trigger, database
- each message should get a severity: info, warn, error

It should be configurable which facility / severity combination shows a notification on page or with the web notification api. Does anyone use the web notifications?

Add a new modal to display, filter and delete notifications.

**Comment by john-** [comment]
I don't conspicuously use notifications.   The "on page notifications" and "Media session support" may be telling me stuff as it is the only ones I have enabled.   The option for "Web notifications" is unavailable for me (it says "Notifications are blocked".

I tend to want less chatty interfaces so your idea of assigning a facility and severity would let me turn on things important to me and filter everything else.

**Comment by jcorporation** [comment]
„Web notifications Must be allowed by browser settings. This is a feature of the original ympd, but I think that nobody uses that and it could be removed.
