### ISSUE TITLE
display of multidisc albums

### ISSUE THREAD

**Issue by payback007** [jcorporation/myMPD#358]
myMPD version: 6.8.0

Multidisc album are showing a album cover for each CD of the album. If accessing one CD of the multidisc album, all tracks are shown in the correct way. Is it possible to get only one cover shown in the album view for multidisc albums? The files are stored within one folder, CD number is tagged.

**Comment by jcorporation** [comment]
You must enable the Disc tag in the myMPD setttings.

**Comment by payback007** [comment]
Thank you very much, it was quite easy ;-)
