### ISSUE TITLE
Korean Translation Update

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#361]
Please find the attached file.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/5577525/ko-KR.txt)

**Comment by jcorporation** [comment]
Thank you, is now in devel.

**Comment by parkmino** [comment]
Added missing translations.

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/5578493/ko-KR.txt)

**Comment by parkmino** [comment]
Update for v6.8.2

[ko-KR.txt](https://github.com/jcorporation/myMPD/files/5610597/ko-KR.txt)
