### ISSUE TITLE
Missing translation on script window

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#363]
![2020-11-21-222349_1600x900_scrot](https://user-images.githubusercontent.com/12131158/99878393-5fb69200-2c48-11eb-8194-1f07155b7709.png)

The following translations seem to missing on script page.

```
Goto view
Replace queue
Execute Script
App
Tab
Offset
Filter
Sort
```

**Comment by jcorporation** [comment]
Is now fixed in devel, the option field was not translated and some options are not in the extra_phrases.txt list for translation.
