### ISSUE TITLE
Error:  Incorrect arguments

### ISSUE THREAD

**Issue by john-** [jcorporation/myMPD#364]
myMPD version: 6.8.1

When I click on the Browse icon there is a pop-up error message "Incorrect arguments".   This error also pops up when I select what I want to search by (e.g. Albumartist).

I am still getting used to the new interface so there may be other problems that result from this 

I have not made any config changes as part of the upgrade to this version.

**Steps to reproduce**

1. Click Brose icon

**Expected behavior**

I expect no error pop-up.

**Server plattform (please complete the following information):**
 - OS: Arch linux
 - OS version: 3.16.81-49
 - Plattform: Odroid C2
 - MPD version: 0.20.18

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: Arch Linux
 - Browser Firefox
 - Browser version: 78.0.2

**Comment by jcorporation** [comment]
Could be a problem with an old MPD version. Please post the mympd debug and the mpd verbose log.

**Comment by john-** [comment]
Here is the mympd log to start.  I will add mpd log once I create it.

[mypd.log](https://github.com/jcorporation/myMPD/files/5592580/mypd.log)

**Comment by jcorporation** [comment]
It is no more necessary. It is a incompatibility between myMPD 6.8.x and MPD 0.20.0

**Comment by john-** [comment]
Sounds good if the feature can be disabled.

It turns out I am running Ubuntu and the combined with Odroid-C2 makes upgrading a pain.   I will look at dong that but will take a whole so thanks if the disabling can occur.   If not I will downgrade mympd and still be very happy with it!

**Comment by jcorporation** [comment]
myMPD disables commonly features if a feature is not detected or the mpd version is to old. I only forgot some checks. Is now fixed in devel. It would be cool if you can test it.

**Comment by john-** [comment]
I just used devel and there is no more error.   I will close this ticket and see about upgrading mpd.
