### ISSUE TITLE
Problem with 6.8.1

### ISSUE THREAD

**Issue by ustraub** [jcorporation/myMPD#367]
I have installed the new version 6.8.1 on a raspberry running Raspbian Stretch lite from source code (compiling, installing). That seemed to work. 

I have recreated /etc/mympd.conf by running 'sudo mympd-config' without specifying any parameters.

I have then started mympd by 'sudo /usr/bin/mympd'. The program works and displays some messages. When I try to open the mympd website from Windows I get the initial web page showing the myMPD logo and the message 'Can not parse settings' with a red button 'Reload' below.  The reload button reacts to the mouse hover (red color get a bit darker) and it seems to process the click event, but the result is only that the same error message is shown again.

I was running mympd 5.2.0 before and this version did not have similar problems. 

How can I get version 6.8.1 to work?

Regards
Ulrich Straub

**Comment by jcorporation** [comment]
I can not reproduce your issue. Please open the network console of your browser and grab all responses from /api. Delete first the browser cache and the application cache and delete the serviceworker.

**Comment by ustraub** [comment]
Hi,

I found the problem. I was using Firefox with NoScript and the mympd page was not set as trusted. 

I have noticed some more problems however. How should/can I report them? All together in the current issue? Or by creating separate issues? 

Regards
Ulrich Straub

**Comment by jcorporation** [comment]
Separate issues please.
