### ISSUE TITLE
Howto: New home screen

### ISSUE THREAD

**Issue by ustraub** [jcorporation/myMPD#369]
When opening the mympd page a large grey panel appears with the text "You have not added any Home icons yet. You can add views, playlists, and scripts."
![grafik](https://user-images.githubusercontent.com/46170211/100279848-9271ca80-2f67-11eb-9b6a-8438fe715826.png)

**Comment by john-** [comment]
Looks like it is part of the new home page feature.   I see at least one place in other parts where one can add item to that page.  I think it was the search function.

**Comment by jcorporation** [comment]
Right, you can add home icons from all views, from the context menu of playlists and in the script window.

**Comment by pinkdotnl** [comment]
The new home screen is indeed a handy feature. I already created some views. Some not that good, which I want to delete. I can't seem to find a way to delete a unwanted view, other than removing them all by using:
`mympd reset_state`
Is there another way to remove views from the home screen?

**Comment by ustraub** [comment]
Hi,
it seemed obvious to me what I meant when opening this issue. Obviously it was unclear. So let me explain. I believe that this empty grey panel looks bad when you start the program the first time. And it is unclear what the purpose of this grey panel is and why it appears. 

From the comments I understand now that the grey panel is the empty home screen. But it is still unclear what the home screen is. From the comments it seems one can add some views. What are views? Links to albums? Links to songs? Links to a subpage? What happens when you click on a link? Can the home screen be removed/disabled? Is it always present? How do you add links? 

In general the possibility to customize the initial view is clearly an improvement. I am not criticizing its existence,

Sorry for my "dumb" questions, but I think that other newbies stumble over the same problems.

Regards
Ulrich Straub

**Comment by jcorporation** [comment]
@pinkdotnl: click on the text of an icon to open a context menu. From this you can edit or delete an icon. Reordering of the icons with drag and drop.

**Comment by jcorporation** [comment]
@ustraub:
The home screen is designed as an individual starting point. I added my favorite radio station (playlist), a script that enables the jukebox mode with my prefered playlist, a view to show the newest albums, ...

- the home screen can be disabled with a config option, the option is documented in the wiki.
- view: link to a view (subpage) with all options set as the view was added, e. g. browse database with album selected as tag and sorted by date. It behaves like a browser bookmark. Add this directly from the view with the add to home screen icon.
- playlist: the playlist replaces the current queue. Add this from the context menu of a playlist.
- Script: script to execute, add this from the script overview.

I hope this description helps. 

But a question: how should this home screen should be designed to be more self explanatory?

I think no one would read a manual... or would dig through the issues here.

I suspect myMPD has meanwhile so many features and configurable options that it is not easy to understand.

**Comment by john-** [comment]
I was not expecting the home screen but felt the basic text "You have not added any Home Icons yet. You can add views, playlists and scripts." was enough for me to understand that if I wanted to do something I need to take an action.

There could be an argument made for some default entries that linked to the other screens (e.g. Playback).   These can be removed by those users that take the next step of customizing.   Yes, this would be redundant but would provide some context for those just starting out or those that have no desire to customize.
