### ISSUE TITLE
Version 6.8.1: Clicking on small folder icon does not work

### ISSUE THREAD

**Issue by ustraub** [jcorporation/myMPD#372]
When clicking the small folder folder icon of the song at the bottom of the page (see screenshot) an empty white dialog appears with only a Close button 

![grafik](https://user-images.githubusercontent.com/46170211/100281078-88e96200-2f69-11eb-8923-d6d69a42e966.png)

**Comment by jcorporation** [comment]
You mean clicking on the cover image? Is the image embedded or an image in the folder? Are there errors in the javascript log of your webbrowser or a error in the myMPD log?

The noscript blocking notification has nothing todo with it?
