### ISSUE TITLE
Adjustable lower limit of volume control

### ISSUE THREAD

**Issue by ustraub** [jcorporation/myMPD#375]
Currently the volume control runs from 0 to 100. However when I set the volume to 80 (or so) it has already fallen silent. The useable range of the volume control runs from 80 (or so) to 100. The range from 0 to 80 is not useable.

I would like an option (in the mympd.conf file) to set the lower limit of the volume control to a user-defined value (for example 80). When the volume control is moved to the left then the volume should be this value (80) and not 0 (like now).

**Comment by jcorporation** [comment]
I like this feature request. I think a max volume setting is also useful.
