### ISSUE TITLE
Albums missing in new browse grid

### ISSUE THREAD

**Issue by mirutoyoshi** [jcorporation/myMPD#376]
myMPD version: 6.8.1
The new interface is great!!

After upgrade from 6.6.2. - I did reset the myMPD settings to see if that helped.

Many albums are now missing in the new covergrid view. 
The missing albums can still be found and played from the filesystem view. 
It appears that the only albums appearing in the grid have the disc tag set. The missing ones don't have that tag. 
When I add the disc number and total disc tags in foobar2000 then the album appears in the covergrid.

**Server platform (please complete the following information):**
 - OS: Arch
 - OS version: up to date
 - Platform: ARM
 - MPD version: 0.22.3

**Client platform (please complete the following information):**
 - Device: Laptop & phones
 - OS: Windows 10, Android
 - Browser: Firefox, Chrome
 - Browser version: Any

**Comment by jcorporation** [comment]
Disabling the disc tag should resolve your issue. Either in myMPD settings or in the mpd config.

**Comment by mirutoyoshi** [comment]
Yes, you're right, now all the albums show again.
However, now the issue of multi-disc albums appearing multiple times is back. 
So I will probably tag all albums with the disc tag.

But I wonder if it is possible to guess a default value in the case of a missing tag - in this case guess disc=1 - instead of not showing the files?

**Comment by jcorporation** [comment]
That is unfortunately not possible the mpd filter syntax allows only „and“ no „or“. myMPD maintenance no own database and relies on the features of the mpd database queries.

**Comment by mirutoyoshi** [comment]
OK, thanks for clarifying
