### ISSUE TITLE
Generic Multimedia Controls

### ISSUE THREAD

**Issue by niawag** [jcorporation/myMPD#378]
Is it possible to add generic multimedia control to allow a direct acces to it from notification (on Android) or multimeid control pop-up (Win10 and others) ?
It seems it's possible with standard, W3C compliant tech: https://w3c.github.io/web-roadmaps/media/control.html

If I'm not clear enough, this is what I'd like to have: 
For android: 
![image](https://user-images.githubusercontent.com/5684014/100729586-3c6ab000-33c9-11eb-9502-b0016a522d68.png)
For other OS (here win10):
![image](https://user-images.githubusercontent.com/5684014/100729963-b7cc6180-33c9-11eb-9f74-449430ac3be0.png)
(not related to myMPD, except the name and music ;))

Keep up the GREAT work!

**Comment by jcorporation** [comment]
I have already played around with this api. But there was a crook: 

> There is no notification for audio from the Web Audio API unless it is played back via an audio element.

https://developers.google.com/web/updates/2015/07/media-notifications

A basic media session api support is already integrated in myMPD.

**Comment by niawag** [comment]
Argh, didn't thought that not having audio output could be a problem!

What is the basic media session capable of ? It is activated on myMPD install and I don't know what it brings (win10 or android), the multimedia key of my keyboard have no action on myMPD

**Comment by jcorporation** [comment]
I must look in the code, but things as play/stop/prev/next and current song information should be implemented. I think this could work if you enable local playback. In settings there is a media session option to activate. I can only test with Windows 10, I have no access to an android phone.

**Comment by niawag** [comment]
Ok, I'll try to make local playback work and test it, I'll report if I found any bug

**Comment by jcorporation** [comment]
I have tested it with current iOS and I see the generic audio control buttons of iOS if local playback. But this buttons control only the local playback. If the media session api would work, this buttons should control the mpd playback behavior.

**Comment by niawag** [comment]
I've been able to test it and it works, I think there is nothing more that can be done so I'm closing this issue.
