### ISSUE TITLE
Smart playlists

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#38]
- Most played songs
- Best rated songs
- Newest songs

**Comment by Emilot** [comment]
That will be great...! Thx jcorp 👍

**Comment by jcorporation** [comment]
Smart playlists would be implemented as "saved searches". One file per smart playlist in directory /var/lib/mympd/smartpls defines the smart playlist. myMPD will save and update the smart playlist as native playlist in the mpd playlist directory with a myMPDsmart prefix.

Update smart playlist:
- on myMPD startup
- change of mpd database
- manual trigger

**Comment by jcorporation** [comment]
Smart playlists are not as easy as it should be with the mpd protocol...
- myMPDsmart-bestRates: list all liked songs
- myMPDsmart-mostPlayed: list most played songs -> it takes the most played song, halfes the play count  and add all songs with play count above this value to the playlist

**Comment by jcorporation** [comment]
Add interface for editing smart playlists
