### ISSUE TITLE
Album actions not working

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#381]
myMPD version: 6.8.3

Search for an Artist, go to Album actions, Replace Queue, Notification "Songs added", previous queue gets cleared but zero songs are added.

**Comment by jcorporation** [comment]
In what view does this not work? In search or in browse?

**Comment by GK-774** [comment]
In search view. And yes the tags are enabled.

**Comment by jcorporation** [comment]
Debug log of myMPD and verbose log of mpd would be useful

**Comment by GK-774** [comment]
Please find attached the requested log files. Log levels were "verbose" for mpd and 4 for myMPD.

They are splitted as follows:
Started myMPD: mympd_log_startup.txt
Opened myMPD in browser: mympd_log_connect.txt and mpd_log_connect.txt
Search for "John Lennon": mympd_log_search.txt and mpd_log_search.txt
Album action "Replace queue" for album "Gimme Some Truth": mympd_log_albumaction.txt and mpd_log_albumaction.txt

The Metadata looks like this (ffprobe):
  Metadata:
    TITLE           : Instant Karma! (We All Shine On) (Ultimate Mix)
    ARTIST          : John Lennon, Yoko Ono
    TRACKTOTAL      : 36
    DISCTOTAL       : 1
    ALBUM           : Gimme Some Truth
    GENRE           : Pop
    album_artist    : John Lennon
    disc            : 1
    DATE            : 2020
    track           : 01

[logs.tar.gz](https://github.com/jcorporation/myMPD/files/5665321/logs.tar.gz)

**Comment by jcorporation** [comment]
I found the bug. It is fixed in the v6.9.0 branch. Thanks for reporting.
