### ISSUE TITLE
Back Button, missing Stop Button

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#382]
Back Button
Expected result: Back button skips to the beginning of the song, second press to the beginning of the previous song.
Actual result: If there is no precceding song (e.g. in consume mode) the back button does nothing.

Stop button is missing
Expected result: Stop button should do what "mpc stop" does, stop the song and skip to its start, or in case of a stream disconnect (Later Play would reconnect).
Actual result: The stop button is missing. When using Pause instead for a stream, it plays the remaining cache on second press and then stops when the cache is exhausted.

**Comment by jcorporation** [comment]
Back button should work as the mpc prev command and this does work as you described I think, but I have not tested this.

You can replace the pause button with a stop button, see configuration in the wiki.

**Comment by GK-774** [comment]
OK, I will test it with mpc. For replacing Pause with Stop, this would solve the issue for streams as described but I would certainly miss the Pause button. It would be nice to have both. They serve different purposes.

**Comment by jcorporation** [comment]
Displaying pause or stop button was only a decision for the current layout for a symmetric look of the playbar. It is possible to add a configuration setting to customize this buttons. Personally I ever used only the pause button.

**Comment by john-** [comment]
I like the simplification of a single button.   I lean towards the pause button as I never used stop.   I never used streams so that maybe shaped my expectations.

**Comment by jcorporation** [comment]
That is the common problem with ui design. Everbody has its own preferences. More configurable options can solve this with the drawback of more complexity.

**Comment by GK-774** [comment]
> Back button should work as the mpc prev command and this does work as you described

I have just tested "mpc prev" and unlike the back button, mpc prev skips to the beginning of the currently playing song (starts over playing the current song) if there is no preceding song in the queue. 

The stream is just the local radio stream, and yes the stop would not be a requirement otherwise, but pausing a radio stream currently requires pause - remove stream from queue - add it again. With a stop button it would be just stop and play.

**Comment by jcorporation** [comment]
I checked the code. myMPD uses the same mpd protocol command, but disabled the back button if song position is 0. Is now fixed in v6.9.0 branch

**Comment by jcorporation** [comment]
you can now set `footerstop=both` in mympd.conf to add a stop button.

**Comment by GK-774** [comment]
Just compiled and tried the 6.9.0 branch and I´m sorry to say both issues are not working as expected.

footerstop=both in the config just does nothing (no stop button).

The back button does not what "mpc prev" does. It is simply greyed out when there is no song before the current song while "mpc prev" moves to the beginning of the current song and continues to play from there. The latter is the expected behaviour I think as every other client or player I´m aware of works that way.

I hope I dont annoy you with this issue reporting and understand if it´s not of high priority.

**Comment by jcorporation** [comment]
It is pobably the usual problem: the old javascript files are used
1. you forgot to run `./build.sh cleanupdist` before building
2. the browser cache or the app cache is not cleared

**Comment by GK-774** [comment]
Happy to report it works ok :-)  I was not aware of "cleanupdist" because I always build rpms and usually from the latest release. Many thanks !
