### ISSUE TITLE
Reset Search on browse

### ISSUE THREAD

**Issue by niawag** [jcorporation/myMPD#385]
(Not sure if it's a bug or a feature request)

In Filesystem view, when I'm searching for an artist folder the search is working well but, if I browse inside a folder, the search/filter is still undergoing and results in an empty folder. To see what's inside I need to delete the searched term. Would it be possible to reset the search/filter when a user start to browse after a search?

Here is an example of a search for Bob Marley:
![image](https://user-images.githubusercontent.com/5684014/101642245-11b8d100-3a33-11eb-8a31-401359cba2d0.png)
Then I browse to the result (clicking on the folder):
![image](https://user-images.githubusercontent.com/5684014/101642307-24cba100-3a33-11eb-8a35-3fc122b00a77.png)
To be able to see something I need to clear the Search bar and, only then, it works:
![image](https://user-images.githubusercontent.com/5684014/101642476-5a708a00-3a33-11eb-86fa-e0b2476ccec4.png)

**Comment by jcorporation** [comment]
I thin resetting the search is the best behavior

**Comment by jcorporation** [comment]
Is now implemented in v6.9.0 branch

**Comment by Emilot** [comment]
JC can i ask in addition to this issue...

Is it possible to have the same behavior if i go inside a folder and press the "Back button" on my mouse? Because now, whatever i have written remains in "Search" field. Is it possible to Reset it as well?

Thank you.
