### ISSUE TITLE
Click on Album title behavior at Browse

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#386]
myMPD version: [6.8.3]

**Describe the bug**

When i click an album title at the "Browse" card and then click on the next to it, it sends me on the top or middle of the this page, and i have to go back to the bottom and choose the action i wanted to do in the first place.
Same happens if you click twice on the album title.

**To Reproduce**

1. Go to Browse card
2. Scroll down to the bottom of the page
3. 'Click on 'Album Title'. Menu appears. Now click on the next album or to the empty space
4. you will get up on the page

**Expected behavior**

Stay at the album you click.

Chrome, Firefox same behavior...

**Comment by jcorporation** [comment]
Is now fixed in the v6.9.0 branch
