### ISSUE TITLE
Next page in Queue greyed out

### ISSUE THREAD

**Issue by jdr85** [jcorporation/myMPD#390]
Hi Jürgen,

myMPD version: 6.9.0

Server plattform:

    OS: Arch Linux ARM
    OS version: current
    Plattform: armv6l
    MPD version: 0.22.3
    Device: Raspberry Pi 1B

Client plattform (please complete the following information):

    Device: Device independent
    OS: OS independent
    Browser: Browser independent
    Browser version: -

Since (at least) 6.8.3 and now in 6.9.0 clicking next page in the queue view does not work. It works when I'm on page #1, but then it stops working.

![grafik](https://user-images.githubusercontent.com/67578404/102710843-8dc5db00-42b5-11eb-91e3-79566165dbad.png)
![grafik](https://user-images.githubusercontent.com/67578404/102710853-9dddba80-42b5-11eb-91e6-faeba6e36954.png)

I can however go to another page by selecting the page number in the dropdown menu.
![grafik](https://user-images.githubusercontent.com/67578404/102710871-b51ca800-42b5-11eb-912f-e3b4596d6022.png)

**Comment by jcorporation** [comment]
It is a general pagination problem.
