### ISSUE TITLE
"Play next" in queue

### ISSUE THREAD

**Issue by jdr85** [jcorporation/myMPD#391]
Hi Jürgen,

I would love to have a "play next" feature in myMPD. This function would re-arrange the selected title in the queue so that it would be played after the currently playing song. At the moment, I have to temporarily switch to M.A.L.P. for this as this MPD client has this feature.

Best regards

**Comment by jcorporation** [comment]
Play next should be already possible for single files and directories. 

myMPD uses a search to add albums to the queue. For search MPD doesn’t support a „insert after playing song“, but there is a feature request: https://github.com/MusicPlayerDaemon/MPD/issues/888

**Comment by jdr85** [comment]
Hi Jürgen,
I think an example would be best for explanation.

Let's imagine I have a play queue
1: Song A <-- currently playing
2: Song B
3: Song C
4: Song D

Now I am enthusiastic about Song D and want to listen to it as soon as the currently playing song is over. So I would like to select Song D and just click/tap "Play Next" or something similar so that the queue would now be:

1: Song A <-- currently playing
2: Song D
3: Song B
4: Song C

Some re-arranging is already possible with Drag & Drop, but 
i) This would work in the above example but would not really work when for example song 17 is playing and I want to play song 98227 next.
i) Drag & Drop does not work too well on tablet/smartphone

Best Regards

**Comment by jcorporation** [comment]
I understand. Can you enable the mpd verbose log and capture the commands malp issues? 

In random mode the priority of the song should changed, in normal mode the song should moved.

**Comment by jdr85** [comment]
Sorry, my music player was out of order as I needed its USB-SATA adapter otherwise, so I was not able to capture the mpd verbose log.
But now I recommissioned it and I see that the feature has been implemented and seems to work properly. That's great, thanks!
