### ISSUE TITLE
Integrate ListenBrainz for scrobbling, etc

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#394]
### Basic functions

- [x] add config option for api token
- [x] hate/love trigger
- [x] scrobbler script
- [x] pin/unpin script
- [x] hate/love script

### Advanced

- https://github.com/jcorporation/myMPD/discussions/735

### API documentation

https://listenbrainz.readthedocs.io/en/latest/users/api/

**Comment by jcorporation** [comment]
MUSICBRAINZ_TRACKID is the recording id

**Comment by jcorporation** [comment]
Love/Hate waits for migration of api from msids to mbids: https://github.com/strawberrymusicplayer/strawberry/issues/788

**Comment by jcorporation** [comment]
Thanks for the hint, I will test it.

**Comment by jcorporation** [comment]
@MonkeyDo: I tested the recording-feedback api, now I get an error in the webinterface in the love/hate tab: https://tickets.metabrainz.org/browse/LB-1099

**Comment by jcorporation** [comment]
@MonkeyDo: tested the `/pin` endpoint: it works like a charm.

**Comment by MonkeyDo** [comment]
Glad to know pinning is working as expected!

Looks like we still have teething issues with the love/hate feature using MBIDs.
We are working on a fix for the issue you had on the ListenBrainz website (the page doesn't crash anymore on [beta.listenbrainz.org](https://beta.listenbrainz.org/user/jcorporation/feedback/)).
However it was a symptom of a deeper issue, and you will see some items are missing data in that love/hate page until we fix it for good ("No metadata for…").

**Comment by jcorporation** [comment]
I can confirm that beta.listenbrainz.org is working. I think I scrobbled MBIDs as recording_msid in the past and that was the origin of the problem. I managed to remove all the invalid entries in the love/hate tabs with some api calls. Adding and removing love/hate does now work with MBIDs as you described. Thanks for your help!
