### ISSUE TITLE
local playback

### ISSUE THREAD

**Issue by seancmalloy** [jcorporation/myMPD#396]
When I use the stunnel workaround (http>https) for local playback I get this error

Dec 31 13:09:15 raspbian mympd[3320]: INFO     mympd     Parsing config file: /etc/mympd.conf
Dec 31 13:09:15 raspbian mympd[3320]: WARN     mympd     Unkown config option: mpd-https - accept
Dec 31 13:09:15 raspbian mympd[3320]: WARN     mympd     Unkown config option: mpd-https - connect
Dec 31 13:09:15 raspbian mympd[3320]: WARN     mympd     Unkown config option: mpd-https - cert
Dec 31 13:09:15 raspbian mympd[3320]: WARN     mympd     Unkown config option: mpd-https - key

I am hosting mympd with https 8443 and mpd httpd output is http. Added proxy config in mympd.conf, etc.

[mpd-https]
accept = 8443
connect = 127.0.0.1:(my mpd httpd port)
cert = /var/lib/mympd/ssl/server.pem
key = /var/lib/mympd/ssl/server.key

Cant parse unkown config options.

I have verified that my mpd httpd (and icecast stream) stream is accessible/playable local and over internet. And it looks like mympd works fine, connects/controls mpd.

Did I just put the mpd-https in the config or not enable local playback during build, or something?

Any help is appreciated.

**Comment by jcorporation** [comment]
You must add the config to the stunnel.conf, not to the mympd.conf. MyMPD and stunnel must run on different ports.

**Comment by seancmalloy** [comment]
thanks for the prompt response time. after creating stunnel.conf and adding mpd-https config i see that it does indeed work, as far as proxy mpd httpd stream to different port, but i still fail to see how it is integrated with mympd. how exactly does mympd play the local plackback/stream, if mympd played a stream from different port wouldnt that have to be configured in mympd? do i have to manually open second webpage and open the stream? what am i missing? thnx again

**Comment by jcorporation** [comment]
You can configure the stream in the settings.

**Comment by seancmalloy** [comment]
sorry to be a a pain, but i did not see an option for mpd httpd stream in mympd.conf when initially set it up. just checked, only settings for mpd server not stream. is the documentation? or can you tell me the setting to add? thnx

**Comment by jcorporation** [comment]
You can set this option in the gui.

BTW: https://github.com/jcorporation/myMPD/wiki/Configuration

**Comment by seancmalloy** [comment]
awesome, dont know how i didnt see the config wiki.

thnx

USER ERROR USER ERROR USER ERROR
