### ISSUE TITLE
Scripting - executing shell command does not work

### ISSUE THREAD

**Issue by seancmalloy** [jcorporation/myMPD#399]
**Is your feature request related to a problem? Please describe.**
syscmd was a good feature to add, but an option to include switches would be an improvement 

**Describe the solution you'd like**
? an option to enable variables, adding input field with syscmd that would append switches

**Describe alternatives you've considered**
? a custom pages feature or embedded html allowing custom (basic) code

**Additional context**
The need for this, for me anyways, is to control my rtl-sdr dongle. Why you ask? I use rtl_fm for local rf, mpd alsa input for capture, mpd httpd for stream, and now mympd to control mpd. So it would make sense to control rtl-sdr from mympd (for me) I currently either configure it by command line or web form (see pic). I dont see that mympd has an custom pages feature for embedded external sites or custom code, so my web form is out. syscmd would work if it could pass switches. rtl_sdr & rtl_fm have like a dozen switches i would be happy with one variable (frequency) and hard code the rest in config. 

being able to pass switches with the syscmd would make a lot more possible though

![sdr](https://user-images.githubusercontent.com/23019226/103469764-e75aea80-4d36-11eb-80ab-7e70fc4badfd.png)

**Comment by jcorporation** [comment]
Syscmds are a depracated feature and are replaced through the script feature. For script you can define arguments. Examples are in the wiki.

**Comment by seancmalloy** [comment]
i did enable scripting but it has the same issue even using mympd.os_capture; all variables / switches are hard code coded, that is there is no mechanism for input "on the fly" in gui. If you need different switches to pass to the bin, you need a separate script. but that being the case, it still doesn't work for me. i created a script to exec sys command w/ parameters but doesn't work (but works from local sh) 

-- {"order":1,"arguments":[]}
output = mympd.os_capture("rtl_fm -f 94.5M -M fm -s 200000 -r 48000 - | aplay -r 48000 -f S16_LE")
return output

i am missing something, or is this just not possible?

**Comment by jcorporation** [comment]
It is possible. You must add arguments to the script. If you execute the script, myMPD asks for inputs in a modal. In the script these inputs are accessible through the arguments array. I hope the screenshot can clarify this.

![image](https://user-images.githubusercontent.com/765844/103483215-02386800-4de6-11eb-836a-a8e8bd352c9a.png)

**Comment by seancmalloy** [comment]
i see what your saying and i think you may be right, but unfortunately i dont know lua. i created a script with 1 argument named frequency, but how do i insert that value into :

return arguments["frequency"]
output = mympd.os_capture("rtl_fm -f "frequency"M -M fm -s 200000 -r 48000 - | aplay -r 48000 -f S16_LE")
return output  

and also is the return output executed as if i was on local sh? because running this script with no arguments fails.
  
thnx, your help is appreciated

**Comment by jcorporation** [comment]
This should work:
```
output = mympd.os_capture("rtl_fm -f " .. arguments["frequency"] .. "M -M fm -s 200000 -r 48000 - | aplay -r 48000 -f S16_LE")
return output
```

**Comment by seancmalloy** [comment]
when i exec the script the notification bar on right pops up with green exclamation but is blank with no detail. i do not see the rtl_fm process starting and get errors in syslog. by the way is an option to created own log? syslog shows - aplay: main:828: audio open error: No such device, which tells me that the rtl_wasnt started first. does your argument required double quotation?

**Comment by jcorporation** [comment]
Try to put the command in a shell script and call the shell script with the argument. I assume the pipe in the command could be the problem.

**Comment by seancmalloy** [comment]
sames errors when executing sh script by mympd, even without args; dont know how lua script would even pass args to sh script anyway. very odd, i exec this bin with php system() in my webpage fine. you can close this, it is beyond the scope of mympd. ill setup a lua env and figure it out. thanks anyways

**Comment by jcorporation** [comment]
os.execute should work. I use it in some scripts in myMPDos. Scripts are executed with the mympd user. You should start myMPD in debug mode and in foreground, script errors should be then logged to the console.

**Comment by seancmalloy** [comment]
os.execute("rtl_fm -f 94.5M -M fm -s 200000 -r 48000 - | aplay -r 48000 -f S16_LE") does work locally when i call it as mympd: runuser -u mympd /usr/local/bin/lua /var/lib/mympd/scripts/fm.lua

i had to add mympd user to audio group because of pulseaudio

but that same command does not work with mympd scripting, nor mympd calling ext script to do same

i increased log level 3 to 4 but pretty much get same details:

ALSA lib pcm_direct.c:1824:(_snd_pcm_direct_get_slave_ipc_offset) Invalid value for card
aplay: main:828: audio open error: No such device

why would os.execute() work local but not through mympd? any thoughts? does mympd lua scripting use the io lib different than a local lua? should the script (at top) work?

**Comment by jcorporation** [comment]
I don’t know the syntax of rtl_fm, could it be that -f points to a file? Then you should use a absolute path. myMPD work dir is /var/lib/mympd.

**Comment by jcorporation** [comment]
runuser does not change the environment. This could be the difference. Your log message indicates that aplay  can not open your soundcard. Is alsa configured with a .asoundrc file?

**Comment by seancmalloy** [comment]
i know but mympd user doesnt have login by default. i gave mympd a password and logged  in and it can run the command fine, both via sh and lua script. also su - mympd then cmd works logged as other user.  ??? everything works but mympd executing the script

my asound.conf for alsa, this is old config set i was working on sdr web interface but seems to work fine

# playback PCM device: using loopback subdevice 0,0
pcm.amix {
  type dmix
  ipc_key 219345
  slave {
   pcm "hw:Loopback,0,0"
   channels 1
   rate 22050
  }
}

# capture PCM device: using loopback subdevice 0,1
pcm.asnoop {
  type dsnoop
  ipc_key 219345
  slave {
   pcm  "hw:Loopback,1,0"
   channels 1
   rate 22050
  }
}

# duplex device combining our PCM devices defined above
pcm.aduplex {
  type asym
  playback {
   pcm "amix"
  }
  capture {
   pcm "asnoop"
  }
}

pcm.!default {
  type plug
  slave {
   pcm "aduplex"
   channels 1
  }
}

**Comment by jcorporation** [comment]
myMPD don't set the supplementary groups of the destination user when droping the privileges. Above commit fixes that.

Thats the difference between runuser and the myMPD execution of the script. I suppose that you added the mympd user to the audio group to allow access to alsa.

I testet it with the following script:

```
os.execute("id");
os.execute("aplay -l 2>&1");
```

**Comment by seancmalloy** [comment]
ok, so rebuilt/reinstalled mympd and same issues. that error no device found is caused by rtl_fm  (and rtl_test) not finding the usb rtl sdr dongle, when i test dump1090 with mympd lua script i get rtlsdr: no supported devices found. for some reason the command coming from mympd cannot access usb devices, while the local mympd user can.

**Comment by jcorporation** [comment]
You used devel? Running the command with sudo could also be an option.

**Comment by seancmalloy** [comment]
Voilà, that works. when i start mympd in sh (su -l mympd  > cmd) it starts the rtl_fm process via lua script. i thought mympd was run as user mympd. do i have to add user & group to the service file now? will that break everyting?

**Comment by jcorporation** [comment]
myMPD drops the privileges to the specified user itself if is started with uid 0. No need to add user/group directives to the systemd service file. You can try to remove the Protect* and Restrict* options in the systemd unit. Eventually this the cause.

**Comment by seancmalloy** [comment]
thanks for the clarification and all the help. i removed the Protect* and Restrict* options it now starts and executes cmd fine. will updates re insert these systemd options? you can close this thread as everything appears to be working .thanks again

**Comment by jcorporation** [comment]
Yes, an update overrides the systemd unit.
