### ISSUE TITLE
Cannot add albums with special characters at album titles

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#400]
myMPD version: [6.9.1]

**Describe the bug**

When i try to add an album with a special character in it, it throws an error.

**To Reproduce**

1. Go to an album in Browse page
2. Click on album title
3. press "Append to queue

**Expected behavior**

to append

**Screenshots**

![error mympd](https://user-images.githubusercontent.com/18086896/103486409-581d0800-4e06-11eb-8651-ed8b197f9c6a.jpg)

![error mympd 2](https://user-images.githubusercontent.com/18086896/103486429-8e5a8780-4e06-11eb-9173-d2c96f1d41d1.jpg)

**Comment by jcorporation** [comment]
It seems the values are not properly escaped for the mpd search expression.

**Comment by jcorporation** [comment]
The last commit should fix this issue, can you please test?

**Comment by Emilot** [comment]
Perfect JC!

Thank you one more time!
