### ISSUE TITLE
Contextmenu for icons are not user friendly

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#402]
There seems to be a regression on issue 357 in version 6.9.1.

I can add new entries to the homescreen without any problem, I can reorder them by drag&drop, but can't edit/delete them once created. This worked fine in a previous version. 
Right click on Windows or long press on Android on the shortcuts doesn't provide any popup menu to edit/modify them. There's also  no overlayed button on any part of the shortcut tile to access such a menu.

Tried from a variety of client devices (Firefox/Edge on Windows ; Firefox/Chrome on Android smartphone or tablet) without any result.
The only way I found to adapt them once created is by editing the /var/lib/mympd/state/home_list file with a text editor.

**Comment by tsunulukai** [comment]
Disregard - I had forgotten those functions were available when clicking on the text, not on the icon...
It's quite un-intuitive though, I think adding the option to reach the context menu with a long icon press on android or a right click on computers could help make this more intuitive.

This could be generalized overall in the UI.

**Comment by jcorporation** [comment]
I do not like contextmenus on right click in web applications. Eventually a context menu icon at the bottom right of the icon would be more accessible.

**Comment by jcorporation** [comment]
I added the popover menu for right clicks on home icons and album cards. Adding a overlay button does not look so nice.

**Comment by jcorporation** [comment]
And thanks to https://github.com/john-doherty/long-press-event there is now a long press also possible.
