### ISSUE TITLE
improved pagination with option "all" not working

### ISSUE THREAD

**Issue by payback007** [jcorporation/myMPD#405]
myMPD version: [6.10.0]

Thank you for the new update on myMPD!

Just installed the new version and tested new pagination. I got a failure setting the option "all". Up to max. number of 200 is working, setting also all the other available steps like 25, 50 or 100 per page. Setting of "all" resulting in this failure:

<img width="173" alt="error_pagination_option_show_all" src="https://user-images.githubusercontent.com/25882000/104109447-3cb27100-52ce-11eb-91e5-59673f8524e1.png">

**Comment by Emilot** [comment]
Confirm the bug.

Here is the java error...

![error](https://user-images.githubusercontent.com/18086896/104109724-6cb34180-52d9-11eb-9df7-782aa680b206.jpg)

Can we have an "arrow" if someone want to go to the last page.

Thnx JC!

**Comment by jcorporation** [comment]
> Can we have an "arrow" if someone want to go to the last page.

The number of total elements ist not defined in all query results from mpd. Where I know the number of total entries there should be already a last page arrow, e.g. in the queue view.

**Comment by jcorporation** [comment]
This are two bugs:

1. settings don't allow max_elements_per_page to be zero
2. UINT_MAX ist to large for the MPD search window

Both are fixed in v6.11.0 branch. Thanks for reporting.
