### ISSUE TITLE
Make default action customizable when clicking on album/song/folder in browse view

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#406]
**Is your feature request related to a problem? Please describe.**
Not really a "problem", more of an UX annoyance:
When browsing the Database view, clicking on an album picture defaults to replacing the queue.
When browsing the Playlist view, clicking on a playlist defaults to appending to the queue
When browsing the FileSystem view, clicking on a song defaults to appending to the queue, clicking on a folder opens the subfolder

**Describe the solution you'd like**
It would be great to have an option enabling users to choose the default action in those different browsing views :
- Replace Queue
- Append to queue

Same would be great for a long-presses on folders in the Filesystem view

**Comment by jcorporation** [comment]
> Same would be great for a long-presses on folders in the Filesystem view

I think long press and right click should behave the same on all elements: opening the context menu

Setting the action for a normal click should be usefull.

**Comment by jcorporation** [comment]
Is now implemented in the 6.11.0 branch
