### ISSUE TITLE
Album covers disappeared in versions 6.10.0 and 6.11.0

### ISSUE THREAD

**Issue by DoDiesis** [jcorporation/myMPD#408]
myMPD version: **6.10.0** (stable) and also **6.11.0** (development)

I have a working installation of myMPD 6.9.1. All the album covers (fetched from MPD) are shown. If I run myMPD **6.10.0**, or 6.11.0, the album covers are no more shown (only a few of them are shown). If I update the database, all the covers disappears. When switching back to myMPD 6.9.1 all the covers are correctly shown again.

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: Linux  (ArchLinux)
 - OS version: 5.10.7
 - Platform: x86_64 (AMD Ryzen 5)
 - MPD version: 0.22.3

**Client plattform (please complete the following information):**
 - Device: Desktop PC
 - OS: Linux 5.10.7
 - Browser: Firefox and Chromium
 - Browser version: 84.0.2 (Firefox), 87.0.4280.141 (Chromium)

**Debug logs (please attach if it can be usefull)**
/mpd_client/mpd_client_api.c:67: MPD CLIENT API request (8)(0) MPD_API_ALBUMART: {"jsonrpc":"2.0","id":0>
/mpd_client/mpd_client_api.c:918: No response for cmd_id 70
/mpd_client/mpd_client_api.c:925: Push response to web_server_queue for connection 8: {"jsonrpc":"2.0",">
/mpd_client.c:395: Entering mpd idle mode
/web_server.c:248: Sending response to conn_id 8: {"jsonrpc":"2.0","id":0,"error":{"method":"MPD_API_ALB>
/web_server/web_server_utility.c:90: Browser don't support gzip compression
/web_server/web_server_utility.c:127: Serving file /assets/coverimage-notavailable.svg ()
/mpd_client.c:349: Leaving mpd idle mode
/mpd_client.c:384: Handle request
/mpd_client/mpd_client_api.c:67: MPD CLIENT API request (7)(0) MPD_API_ALBUMART: {"jsonrpc":"2.0","id":0>
/mpd_client/mpd_client_api.c:918: No response for cmd_id 70
/mpd_client/mpd_client_api.c:925: Push response to web_server_queue for connection 7: {"jsonrpc":"2.0",">
/mpd_client.c:395: Entering mpd idle mode
/web_server.c:248: Sending response to conn_id 7: {"jsonrpc":"2.0","id":0,"error":{"method":"MPD_API_ALB>
/web_server/web_server_utility.c:90: Browser don't support gzip compression
/web_server/web_server_utility.c:127: Serving file /assets/coverimage-notavailable.svg ()
/mpd_client.c:349: Leaving mpd idle mode
/mpd_client.c:384: Handle request
/mpd_client/mpd_client_api.c:67: MPD CLIENT API request (11)(0) MPD_API_ALBUMART: {"jsonrpc":"2.0","id":>
/mpd_client/mpd_client_api.c:918: No response for cmd_id 70
/mpd_client/mpd_client_api.c:925: Push response to web_server_queue for connection 11: {"jsonrpc":"2.0",>
/mpd_client.c:395: Entering mpd idle mode
/web_server.c:248: Sending response to conn_id 11: {"jsonrpc":"2.0","id":0,"error":{"method":"MPD_API_AL>
/web_server/web_server_utility.c:90: Browser don't support gzip compression
/web_server/web_server_utility.c:127: Serving file /assets/coverimage-notavailable.svg ()
/web_server.c:321: HTTP request (6): /api
/web_server.c:491: API request (6): {"jsonrpc":"2.0","id":0,"method":"MYMPD_API_HOME_LIST","params":{}}
/web_server.c:501: API request (6): MYMPD_API_HOME_LIST
/mympd_api.c:116: MYMPD API request (6): {"jsonrpc":"2.0","id":0,"method":"MYMPD_API_HOME_LIST","params">
/mympd_api.c:557: Push response to web_server_queue for connection 6: {"jsonrpc":"2.0","id":0,"result":{>
/web_server.c:248: Sending response to conn_id 6: {"jsonrpc":"2.0","id":0,"result":{"method":"MYMPD_API_>
/mympd_api/mympd_api_timer.c:96: Timer with id 1 triggered
/mympd_api/mympd_api_timer_handlers.c:28: Start timer_handler_covercache
/maintenance.c:40: Cleaning covercache /var/lib/mympd/covercache
/maintenance.c:41: Remove files older than 1610223205 sec
/maintenance.c:68: Deleted 0 files from covercache
 
 **Configuration (please attach if it can be usefull)**
 - /etc/webapps/mympd/mympd.conf

# myMPD configuration file
#
# SPDX-License-Identifier: GPL-2.0-or-later
# myMPD (c) 2018-2020 Juergen Mang <mail@jcgames.de>
# https://github.com/jcorporation/mympd
#

[mpd]
#Connection to mpd, unix socket or host/port, socket preferred
#host = /run/mpd/socket
host = 127.0.0.1
port = 6600
#pass = 
#host = /var/lib/mpd/socket

#absolut path of music_directory of mpd
#none = no local music_directory
#auto = get music_directory from mpd (only supported, if connected to mpd socket)
musicdirectory = auto

#absolut path of mpd playlist_directory
playlistdirectory = /var/lib/mpd/playlists

#MPD compiled with regex support
regex = true

[webserver]
#Webserver options
webport = 80

#Enable ssl
#Certificates are generated under /var/lib/mympd/ssl/
ssl = true
sslport = 443

#Publishes some mpd and myMPD directories
publish = false

#Webdav support, publish must be set to true
webdav = false

[mympd]
Loglevel
#0 = error
#1 = warn
#2 = info
#3 = verbose
#4 = debug
loglevel = 4

#myMPD user
#group is the primary group of this user
user = mympd

#Usage of stickers for play statistics
stickers = false

#Mixrampdb settings in gui
mixramp = false

#Enable system commands defined in syscmds section
syscmds = false

#Enable lua scripting
scripting = true

#Chroot to /var/lib/mympd
chroot = false
readonly = false

[syscmds]
Shutdown = sudo /sbin/halt
#To use this command add following lines to /etc/sudoers (without #)
#Cmnd_Alias MYMPD_CMDS = /sbin/halt
#mympd ALL=NOPASSWD: MYMPD_CMDS

[screenshot]
With version 6.11.0
![image](https://user-images.githubusercontent.com/76726999/104822244-66751600-5841-11eb-9351-fae2fad424ef.png)

With version 6.9.1
![image](https://user-images.githubusercontent.com/76726999/104822265-9ae8d200-5841-11eb-83ed-6a3596a1ab71.png)

**Comment by jcorporation** [comment]
6.11.0 is in development and the album grid.

Please attache the complete logs from startup including the error. Is the problem only in the album grid view or also in playback?

**Comment by DoDiesis** [comment]
> 6.11.0 is in development and the album grid is broken.
> 
> Use latest release for bug reporting.
**The bug happens with version 6.10.0 too.**
> 
> Please attache the complete logs from startup including the error. Is the problem only in the album grid view or also in playback?
Output of systemctl status mypd command
[mympd.systemctl_status.txt](https://github.com/jcorporation/myMPD/files/5825717/mympd.systemctl_status.txt)

Output of system logs (journalctl) from myMPD startup up to viewing the albums page:
[mympd.journal.txt](https://github.com/jcorporation/myMPD/files/5825719/mympd.journal.txt)

Hope this helps.

**Comment by jcorporation** [comment]
Seems to be a bug in handling the albumart request for mpd. 

Sidenote:

If mpd runs on the same machine you should use the socket connection or set the music directory manually. Then myMPD reads the albumart directly, that is faster than getting the albumart through mpd.

**Comment by DoDiesis** [comment]
> Seems to be a bug in handling the albumart request for mpd.
> 
> Sidenote:
> 
> If mpd runs on the same machine you should use the socket connection or set the music directory manually. Then myMPD reads the albumart directly, that is faster than getting the albumart through mpd.

Yes, I know, but I'm now testing the new versions, before deploying them in the real digital players I have in the "music room".

If you need some more info, or test, feel free to ask.

**Comment by jcorporation** [comment]
- Are you have only flac files? 
- Albumart is in the folder or embedded?

**Comment by DoDiesis** [comment]
Only FLAC files.
Albumarts are in the folder.

This is my directory structure:
[tree.txt](https://github.com/jcorporation/myMPD/files/5825805/tree.txt)

**Comment by jcorporation** [comment]
Strange, git says the albumart functions in the mpd_client thread are not touched between this versions. I test, if I can reproduce this bug.

**Comment by jcorporation** [comment]
Above commit should fix this issue.

**Comment by DoDiesis** [comment]
I can confirm that it works.
Thank you.
