### ISSUE TITLE
myMPD 6.11 different database result compared to 6.10

### ISSUE THREAD

**Issue by payback007** [jcorporation/myMPD#419]
After update from myMPD version 6.10 to 6.11 there is a different database result. In myMPD version 6.10 all albums are shown, in version 6.11 there seem to be a maximum. Different settings for "max. album per page" doesn't have any influence to the result. "rescan database" or "update database" also show no difference.

In "notifications" there are no errors reported.

Referting back to version 6.10 all albums are shown again.

**Comment by jcorporation** [comment]
Can you run myMPD in debug mode and attach the log?

**Comment by payback007** [comment]
By the way if stoping and starting one the the mympd-services, a error is displayed on the webpage:

![error_albumcache](https://user-images.githubusercontent.com/25882000/106387887-32225d80-63dc-11eb-946e-47e60a0d7897.png)

Also attached the output of the webbroweser logfile.

[browser_log.txt](https://github.com/jcorporation/myMPD/files/5899965/browser_log.txt)

Is there a way to write a logfile into a specific logfile on debian? The console mode seem not working for my setup, I'm running myMPD as multiple instances by service and for direct start by console I would need to parse special config files which seem not be possible easily.

**Comment by jcorporation** [comment]
The album cache not ready message directly after startup  is normal. myMPD creates it caches in the background. 

You can add as first option the config file to use, e.g. mympd /etc/mympd2.conf. Writing to a logfile is not supported.

**Comment by payback007** [comment]
Was working, please find attached console logfile:

[console_log.txt](https://github.com/jcorporation/myMPD/files/5899991/console_log.txt)

myMPD is not really localized, showing up the application in english, but the settings are set to "browser default".

**Comment by payback007** [comment]
Also there is now no database found anymore. I would have to restart the myMPD_PC and the some data from the database is shown. Attached the logfile after trying to open some searches from "home screen":

[console_log_2.txt](https://github.com/jcorporation/myMPD/files/5899998/console_log_2.txt)

**Comment by jcorporation** [comment]
Have you disabled the stickercache? There is a bug which does not create the albumcache, if the stickercache is disabled.

**Comment by payback007** [comment]
No, in every mpd instance the sticker database is connected to **/media/mpd/sicker.sql**

I checked, the file is existing.

**Comment by jcorporation** [comment]
I think you should use separate sticker databases for each mpd instance. In myMPD you should set stickercache=true in the mympd section.

But both should not be the issue. 

Two questions:
Are you getting no albums or only to few?
With or without filters?

**Comment by payback007** [comment]
So in the meantime I found the setting with the stickercache. Is it **sticker_cache = true** as in the wiki or **stickercache = true** as in our post?

I have 3 different sorting rules:
- Album -> containing "genre == music"
- Hörspiele -> containing "genre == audioplay"
- Hörbücher -> containing "genre == audiobook"

audioplay and audiobook seem to be complete, music have missing albums. only music has items > 200 albums. Maybe that's the reason?

**Comment by jcorporation** [comment]
It is `stickercache = true`. I fixed the error in the wiki. There should be now problems with the number of items.

**Comment by payback007** [comment]
Mh...

- genre "music" shows 159 albums
- genre "audioplay" shows 197 albums
- genre "audiobook" shows 38 albums
- 394 albums are shown if removing all filters

Database is reporting 583 albums overall and overall 189 albums are missing at the moment. Most of them are in music, but I'm not sure that some also are missing in the other folders.

In the meantime I updated "sickercache" -> nothing changed.

**Comment by jcorporation** [comment]
In your logs I see only "Albumcache not ready" responses. I see also no cache creation request. Can you please grab logs again?
From startup and the albumlist with no filters and album list with filters.

**Comment by payback007** [comment]
1) `sudo systemctl stop mympd1` -> stoping
2) `sudo mympd /media/mympd/mympd1.conf` -> starting without problems -> error on "albumcache not ready"

logfile: [console_log_3.txt](https://github.com/jcorporation/myMPD/files/5900529/console_log_3.txt)

**Comment by payback007** [comment]
aditionally I reverted my mympd_VM back to previous version 6.10:

- gerne "music": 316 albums
- gerne "audioplay": 199 albums
- gerne "audiobook": 42 albums
- overall albums: 583 albums, if mpd counts differently, sum of mympd would be 557 albums.

I will check if it is a matter of tags, but I'm really sure I have set album artist in every album. Do to sorting issues I'm adapting this always manually. 99% of the albums also have set an album cover manually, so this should also be no topic. Does 6.11 differ from 6.10 regarding tags?

**Comment by jcorporation** [comment]
There is again no line with MPDWORKER_API_CACHES_CREATE in your logs. Without this the album cache is not build and you see the warnning in the gui.

At creation and sorting time warnings are issued if albums are skipped.

You can try the devel branch. I fixed there already some bugs.
- album cache is created always
- sorting discards no albums
- album counts are displayed in the log

**Comment by payback007** [comment]
Tried to install the acutal devel branch, but there seem to be errors with myMPD webserver:

<img width="720" alt="install_error_devel_branch" src="https://user-images.githubusercontent.com/25882000/106503208-a258de00-64c5-11eb-84c1-23d41160710e.png">

**Comment by jcorporation** [comment]
It seems you compiled and run release, but your browser has the debug version in the cache.

**Comment by payback007** [comment]
I deleted all caches on the browser already and the version is 6.11.1:

`Usage: ./build.sh <option> Version: 6.11.1`

Shouldn't this be the right version? then `./build.sh release` and `./build.sh install` -> there are some failures like 

[build_logs.txt](https://github.com/jcorporation/myMPD/files/5906240/build_logs.txt)

Also a `./build.sh cleanupdist` didn't change anything.

**Comment by jcorporation** [comment]
It seems there is a error in creating the release assets....

**Comment by payback007** [comment]
Looks quite good now! There are some issues with tagging, this I have to check. The database seem working with the devel branch.

**Comment by jcorporation** [comment]
Great! Please report any further errors and also success. I will wait for your feedback before releasing 6.11.1

**Comment by payback007** [comment]
Yes, please give me a few hours to clean up my tag errors ;-)

Thank you very much for your great, great work on myMPD!!!

**Comment by jcorporation** [comment]
Thanks for testing!
