### ISSUE TITLE
No stop button in bottom playback row

### ISSUE THREAD

**Issue by onkobu** [jcorporation/myMPD#426]
myMPD version: 6.10.0

**Describe the bug**

The bottom playback row has 3 controls at the left side: previous, pause, next. It doesn't offer a stop button anymore. Playing streams pauses them (connection open + buffering). I can't stop this except using `mpc stop` or another mpd UI.

**Expected behavior**

Both options should exist, like pausing an audio book while taking a bio break as well as stopping a stream becoming too scary a few minutes before going to bed.

**Comment by jcorporation** [comment]
You can enable the stop button in the configuration. Look into the wiki for reference. Next version will get a option in the ui.
