### ISSUE TITLE
Mixed-up fields in queue view

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#429]
myMPD version: 6.11.2

**Describe the bug**

When using a custom column layout in queue view, field values can get mixed up when another track begins playing.

**To Reproduce**

1. Go to queue view
2. Configure custom colums configuration as follows: Pos, Artist, Album, Track, Title
3. Load an album in the queue; observe all fields are as expected
4. Play a song in the queue
5. Observe that the Artist field of the current song contains the track title instead
6. Press next, the problem propagates to each new played track
7. Refresh the window: all fields are displayed as they should
8. Select another song in the queue: the field content gets mixed up again for each played track since the refresh.

**Expected behavior**
Fields value should match the field name.

**Screenshots**
Correct display when loading the queue view
![1 - Loading queue view](https://user-images.githubusercontent.com/4215150/108261388-e1449000-7163-11eb-8a17-bd12201fbeab.png)

Mismatched fields after a few tracks were played
![2 - MismatchedFields while playing](https://user-images.githubusercontent.com/4215150/108261396-e3a6ea00-7163-11eb-9f70-40fcf21aa8f4.png)

**Server plattform:**
 - OS: Debian
 - OS version 10.8
 - Plattform: x86_64
 - MPD version: 0.22.3 (from deb https://deb.kaliko.me/debian-backports/ stable-backports main)

**Client plattform:**
 - Device: Desktop Computer
 - OS: Windows 10
 - Browser Firefox 85.0.2 and Edge 88.0.705.68
 
**Client plattform:**
 - Device: Android smartphone
 - OS: Android 10
 - Browser Firefox, Firefox nightly and Chrome

**Comment by tsunulukai** [comment]
Hello Jürgen,

Just tried the latest 6.11.3 build. The issue still happens exactly as described.

**Comment by jcorporation** [comment]
The assets in this release are from 6.11.2. I forgot to update this files before releasing. I have now updated the files and created a new release. Please test again.

**Comment by tsunulukai** [comment]
That did the trick ! Thanks :)
