### ISSUE TITLE
Synchronized lyrics won't show

### ISSUE THREAD

**Issue by Hajuskin** [jcorporation/myMPD#437]
myMPD version: [e.g. 5.6.2]

**Describe the bug**
I have unsynchronized lyrics in most of my mp3 files (embedded as UNSYNCEDLYRICS). I recently started to add synchronized lyrics to some of them (embedded as SYLT). I updated the database and played the tracks, but the synced lyrics won't show, neither in the playing tab nor in the song details. Even worse, the unsynchronized lyrics, which have been displayed before, won't show up anymore.
In the log, when requesting lyrics from a file without synced lyrics, there is a message "No synced lyrics found for *filename*" and the unsynced lyrics are shown. Requesting lyrics from a file with synced lyrics there is no such message which let me think that the synced lyrics are found in these file, but somehow they will not be displayed.

**Server plattform (please complete the following information):**
OS Information: linux armv7l Raspbian GNU/Linux 10 (buster)
Kernel Version: 5.10.11-v7l+
Total CPU: 4
Total memory: 4 GB

Docker Version: 20.10.3 (API: 1.41)

MPD version: 0.22.6

**Debug logs (please attach if it can be usefull)**
log for a file with no synced lyrics:
```
2021-02-26T22:26:34.909800965Z VERBOSE  webserver API request (31): MPD_API_LYRICS_GET,
2021-02-26T22:26:34.959069507Z VERBOSE  mpdclient MPD CLIENT API request (31)(0) MPD_API_LYRICS_GET: {"jsonrpc":"2.0","id":0,"method":"MPD_API_LYRICS_GET","params":{"uri":"MP3/J/Joe Cocker/Joe Cocker!/04 She Came in Through the Bathroom Window.mp3"}},
2021-02-26T22:26:34.960101218Z VERBOSE  mpdclient No synced lyrics found for /music/MP3/J/Joe Cocker/Joe Cocker!/04 She Came in Through the Bathroom Window.mp3
```

log for a file with synced lyrics
```
2021-02-26T22:22:11.129042502Z VERBOSE  webserver API request (32): MPD_API_LYRICS_GET,
2021-02-26T22:22:11.132776983Z VERBOSE  mpdclient MPD CLIENT API request (32)(0) MPD_API_LYRICS_GET: {"jsonrpc":"2.0","id":0,"method":"MPD_API_LYRICS_GET","params":{"uri":"MP3/A/A Perfect Circle/Mer de Noms/04 Judith.mp3"}}
```

**Comment by jcorporation** [comment]
Which myMPD version? Please enable debug and post the log. Can you also attach a example file with SYLT tags?

**Comment by Hajuskin** [comment]
Thank you for looking into that :)

**Comment by jcorporation** [comment]
I wrote a small test program: https://gist.github.com/jcorporation/a253021849978b6b2fb5636ffca9159d

It would be great if you can test it against your sylt taged files and attach the output here.

**Comment by Hajuskin** [comment]
Testet with 3 files:

```
0: encoding: 0
0: lang: eng
0: timestamp: 2
0: contenttype: 1
0: desc: Lyrics were Saved by MiniLyrics.
0: lyrics:
	Text: I'm a rolling thunder a pouring rain, 0 ms
	Text: 0Hell's Bells, 
```
```
0: encoding: 0
0: lang: eng
0: timestamp: 2
0: contenttype: 1
0: desc: 
0: lyrics:
	Text: I was walkin' down the street, Error - line to long

```
```
0: encoding: 0
0: lang: eng
0: timestamp: 2
0: contenttype: 1
0: desc: Lyrics were Saved by MiniLyrics.
0: lyrics:
	Text: Ev'rybody's building the big ships and the boats, Error - line to long
```

**Comment by jcorporation** [comment]
Thanks for testing. I found some parsing bugs and incompatibilities with minilyrics. I primary tested with sylt tags from kid3. Recent changes in the gist and in the code from the v6.12.0 branch fixes this. You can try it if you want.

**Comment by jcorporation** [comment]
If all works, I want to optimize the display of the synced lyrics in the playback card.

**Comment by Hajuskin** [comment]
The output is definitely better, but when the timestamp exceeds ~65 seconds the time isn't read correctly anymore and some garbage is picked up.

Output from the same files (the lyrics in the second file starts at 01:27)
```
0: encoding: 0
0: lang: eng
0: timestamp: 2
0: contenttype: 1
0: desc: Lyrics were Saved by MiniLyrics.
0: lyrics:
Ev'rybody's building the big ships and the boats: 00:05.870
Some are building monuments: 00:12.40
Others, jotting down notes: 00:15.180
Ev'rybody's in despair: 00:18.300
Ev'ry girl and boy: 00:21.240
But when Quinn the Eskimo gets here: 00:23.870
Ev'rybody's gonna jump for joy: 00:27.620
Come all without, come all within: 00:30.550
You'll not see nothing like the mighty Quinn: 00:36.190
I like to do just like the rest, I like my sugar sweet: 00:42.130
But guarding fumes and making haste: 00:48.590
It ain't my cup of meat: 00:51.650
Ev'rybody's 'neath the trees: 00:54.960
Feeding pigeons on a limb: 00:57.590
But when Quinn the Eskimo gets here: 01:00.650
All the pigeons gonna run to him: 01:03.980
Come all without, come all within: 00:00.00
nA cat's meow and a cow's moo,: 00:00.00
AÂJust tell me where it hurts yuh, honey: 00:00.00
WüNobody can get no sleep: 00:00.00
n®But when Quinn the Eskimo gets here: 00:00.00
ˆ&Come all without, come all within: 00:00.00
«ÆCome all without, come all within: 00:00.00
ÙÀ
```
```
0: encoding: 0
0: lang: eng
0: timestamp: 2
0: contenttype: 1
0: desc: Lyrics were Saved by MiniLyrics.
0: lyrics:
I'm a rolling thunder a pouring rain: 00:00.00
f¶My lightning's flashing across the sky: 00:00.00
Š8I won't take no prisoners: 00:00.00
¢„Nobody's putting up a fight: 00:00.00
¼°I'm gonna get you. Satan get you: 00:00.00
Ý: 00:00.00
ï(You got me ringing: 00:00.00
âMy temperature's high
0Hell's Bells: 00:00.00
BI'll give you black sensations: 00:00.00
RIf you're into evil: 00:00.00
a`See my white light flashing: 00:00.00
sŠ'Cause if good's on the left: 00:00.00
„I won't take no prisoners: 00:00.00
–lNobody's puttin' up a fight: 00:00.00
°zI'm gonna take you to hell: 00:00.00
ÃÚSatan get you: 00:00.00
Ò0: 00:00.00
áä: 00:00.00
óHell's Bells: 00:00.00
: 00:00.776
®: 00:00.00
Æ,satan' coming to you: 00:00.00
Øjhe's ringing them now: 00:00.00
é"my temperature's high: 00:00.00
û’across the sky: 00:00.00

they're taking you down: 00:00.00
Bthey're dragging you down: 00:00.00
/¸gonna split the night: 00:00.00
@òthere's no way to fight yeah: 00:00.00
U’Hells Bells!
```
```
0: encoding: 0
0: lang: eng
0: timestamp: 2
0: contenttype: 1
0: desc: 
0: lyrics:
I was walkin' down the street: 00:28.119
Concentratin' on truckin' right: 00:32.749
I heard a dark voice beside of me: 00:37.219
And I looked round in a state of fright: 00:41.809
I saw four faces one mad: 00:46.249
A brother from the gutter: 00:49.119
They looked me up and down a bit: 00:51.389
And turned to each other: 00:53.699
: 00:55.849
I say: 01:04.539
I don't like cricket oh no: 01:04.839
I love it: 00:00.00
!_I love it: 00:00.00
E•You got to show some respect: 00:00.00
VÏ`Cause you ain't heard me out yet: 00:00.00
mïWell he looked down at my silver chain: 00:00.00
=I said you've got to be jokin' man: 00:00.00
ÀÓHe said I like it I want it: 00:00.00
ÝAnd you'll be sorry you crossed me: 00:00.00
ïA long way from home: 00:00.00
And I say: 00:00.00
oI love it: 00:00.00
=QI love it: 00:00.00
bDon't you queer on me pitch: 00:00.00
sÏ`Cause you ain't heard me out yet: 00:00.00
–ÏI hurried back to the swimming pool: 00:00.00
»I heard a dark voice beside me say: 00:00.00
ÝoShe said I've got it you want it: 00:00.00
úAnd if you try it you'll like it: 00:00.00
	: 00:00.00
3Don't like Jamaica oh no: 00:00.00
JMDon't like Jamaica oh no: 00:00.00
mDon't you walk thru her words: 00:00.00
†ÅDon't you walk thru her words: 00:00.00
˜Ç: 00:00.00
ìUI love it (Dreadlock Holiday): 00:00.00
ÝI love it (Dreadlock Holiday): 00:00.00
2¹I love her (Dreadlock Holiday)

```

**Comment by Hajuskin** [comment]
If you're looking for features, jumping to a part of the song by clicking on the corresponding part of the lyrics would by nice to have :)

**Comment by jcorporation** [comment]
Strange, can you copy the Sylt Tag in an empty sound file and provide it to me for better analyzes? What tool do you use for tagging files with Sylt tags?

**Comment by Hajuskin** [comment]
I have send you two test files via email.

**Comment by jcorporation** [comment]
> If you're looking for features, jumping to a part of the song by clicking on the corresponding part of the lyrics would by nice to have :)

Good idea, displaying the current line below the coverimage was my attempt to improve this feature.

**Comment by jcorporation** [comment]
This gist is updated, for me the synced lyrics looks good.

**Comment by Hajuskin** [comment]
Tested several files, all fine!

I think MusicBee has a nice implementation of displaying synchronized lyrics. It has a scrollable textfield which constantly scrolls to keep the played part in view. The recent line is highlighted, the previous and next lines are also colored, the rest is greyed out. You can also manually scroll, that will deactivate auto scrolling until the recent line comes back into view. And you can click on any line which will play the file at this timestamp.

**Comment by jcorporation** [comment]
Greate! myMPD v6.12.0 will have similar sylt display.

**Comment by Hajuskin** [comment]
> Greate! myMPD v6.12.0 will have similar sylt display.

Nice, looking forward! :)
