### ISSUE TITLE
JC please bring these tags to myMPD. It would be very helpful for all the "classical" music friends out there :)

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#445]
JC please bring these tags to myMPD. It would be very helpful for all the "classical" music friends out there :)

This is the PR to MPD with the new tags:

https://github.com/MusicPlayerDaemon/MPD/pull/858/commits/8f1e7385b71ee3f8e6140a22fbd74d6361f414d5

Thank you!

_Originally posted by @Emilot in https://github.com/jcorporation/myMPD/discussions/444_

**Comment by jcorporation** [comment]
Quick look at the code. libmpdclient needs a patch to support the new tags. I will work on it and create a pull request for the official libmpdclient. myMPD uses my fork with additional functionality, that was not yet merged into upstream.

**Comment by jcorporation** [comment]
Is now in devel and will be released with v6.12.1. Note that MPD support this tags only in the upcoming 0.23.x release not for the stable 0.22.x release.

**Comment by Emilot** [comment]
Thank you JC. I will wait for libmpdclient if i understand right.

MPD i can compile it with these changes no need to wait.

Thanx!
