### ISSUE TITLE
Precompiled myMPD packages

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#45]
- myMPD.spec file for rpm based distributions
- Debian packagebuild
- pkgbuild for Archlinux

**Comment by jcorporation** [comment]
myMPD.spec file creates
Build with openSUSE Build Service is successfull.

https://build.opensuse.org/package/show/home:jcorporation/myMPD

**Comment by jcorporation** [comment]
Added debian packaging rules

**Comment by CultofRobots** [comment]
I have a package build and post install for arch linux if you want to borrow from it. 

https://github.com/CultofRobots/archphile-custom/tree/master/mympd

**Comment by jcorporation** [comment]
Thanks, I look into it

**Comment by jcorporation** [comment]
Your PKGBUILD looks awesome. I added it to master.

**Comment by CultofRobots** [comment]
Thanks. Mike from archphile.org has one that compiles from git as well. It's a bit more streamlined since it's for arch on raspberry pi but I'm sure you could use it.

https://github.com/archphile/packages/tree/master/mympd-archphile

**Comment by archphile** [comment]
My PKGBUILD is based on the assumption that jcorporation will continue to provide the minified files.

Having the above in mind, I tried to make the PKGBUILD simpler, not adding all the sections that have to do with closure compiler etc..

Just a last comment, on the existing PGKBUILD in your master: you need to also get **mympd.install** from CultofRobots repo!

**Comment by CultofRobots** [comment]
You also have to change the sha256sum for the tar.gz on each new release or use 'SKIP'. If not, the build will fail before it even starts.

**Comment by jcorporation** [comment]
Thanks for that hint. I fixed it in 4.1.2. I moved mympd.install to contrib/archlinux.install. I have here no archlinux, so I can't test the PKGBUILD...

**Comment by archphile** [comment]
jcorporation,

do you intend to provide the minified files, or we will need to make them ourselves in the near future?

regards,
Mike

**Comment by jcorporation** [comment]
for master branch and the release files:
minfied files are under the dist/ directory

for devel branch:
no minified files are provided
