### ISSUE TITLE
Feat: remember page offset for filesystem browsing navigation

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#454]
When i am at the third page for example, i open a folder and then press "Back" or the "..." to go to the upper level, then i am at the first page and i have to go all that through again. As you imagine this is very frustrating to anyone :)

_Originally posted by @Emilot in https://github.com/jcorporation/myMPD/discussions/453_

**Comment by jcorporation** [comment]
@Emilot: do you want to test?

**Comment by Emilot** [comment]
JC it is fine. If i had "100" number for the pagination, is it possible when i return back from a folder, to return to that folder and not going all the way up or i am asking too much :) ?

In any way...Thank you JC for your support! Awesome work.

**Comment by jcorporation** [comment]
Good point, implemented in last commit.

**Comment by Emilot** [comment]
JC i think this enhancement, is broken in the "devel" branch. I doesn't return to the folder i was, in Filesystem page

**Comment by jcorporation** [comment]
You should open a new issue. Posting to closed issues is not a good idea.

**Comment by Emilot** [comment]
Ok JC. I thought it was the same thing as the old one. No problem.

Thank you
