### ISSUE TITLE
API call not working anymore after update to 7.0.1

### ISSUE THREAD

**Issue by payback007** [jcorporation/myMPD#462]
Hi,

just updated to version 7.0.1 -> update process working without issues and also multi-instance support is working as from previous version.

If have running 5 instances in parallel:
mympd: "http://ip:80/api"
mympd1: "http://ip:81/api"
mympd2: "http://ip:82/api"
mympd3: "http://ip:83/api"
mympd4: "http://ip:84/api"

One thing I found so far, the API call is seem now only working for port 80 any more. I did an album cover call with the API by a batch script for each instance with following script:

`#!/bin/sh

URI=$(curl -s -k http://ip:port/api -d'{"jsonrpc":"2.0","id":0,"method":"MPD_API_PLAYER_CURRENT_SONG","params":{}}' | jq -r .result.uri)
echo "http://ip:port/albumart/${URI}"`

The call will give back the actual album cover adress  wich is display afterwards on my smarthome tablet. This has to be done, because mympd is not open all the time but some information is displayed in a overview page, like actual album cover.

Call on "mympd1 - 4" doesn't give back any API call, calling directly via browser doen't give any feedback. Only port-80 is working.

**Comment by payback007** [comment]
UPDATE: debug level helped to solve the issue -> with version 7.0.1 there seem to be some differences of API call:

for mympd: "http://ip:80/api" -> this call is working
for mympd1: "http://ip:81/api/" -> the call has to be done with an additional "/" sign at the end! Same for the other instances.

By the way "http://ip:80/api" with an additional "/" is **NOT** working!

**Comment by jcorporation** [comment]
Correct api endpoint is `/api/`. This was changed in version 7.0.1 with commit cdf70a5e1223ec7bdd5581589b1cdf11030d28c8.
I forgot to list this change in the release notes.

**Comment by payback007** [comment]
Thank you for the information, I already corrected it in my API-calls and all is working.
