### ISSUE TITLE
Can´t build with openssl disabled

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#463]
myMPD version: 7.0.1

Building with -DENABLE_SSL=OFF results in the build process correctly telling "Openssl is disabled"
but the build later fails, see attached build_error_without_ssl.txt
Building with openssl works without problems in the same environment, BTW.

[build_error_without_ssl.txt](https://github.com/jcorporation/myMPD/files/6272901/build_error_without_ssl.txt)

**Comment by jcorporation** [comment]
Thanks for reporting. Is fixed in devel.
