### ISSUE TITLE
Popup menu at Queue card

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#464]
myMPD version: [6.12.1]

**Describe the bug**

When i try to move a track in the queue list, a menu appears with the usual commands (see the screen) and stick there forever.

**To Reproduce**

1. Go to Queue card
2. Click on a track
3. move it up or down
4. a menu appears

**Expected behavior**

No reason for any menu to appear when i click and drag a track.

**Screenshots**

![mympd](https://user-images.githubusercontent.com/18086896/113901578-abbd3a00-97d7-11eb-8a6b-c74595098bb6.jpg)

Firefox browser

Thank you

**Comment by jcorporation** [comment]
Unwanted side effect of #406

**Comment by ideonaudio** [comment]
Hi JC,

Unfortunately i still see this menu when i try to drag a track in different position in Queue card.

![mympd](https://user-images.githubusercontent.com/63471607/120112875-70f4d400-c180-11eb-85d1-447b9f860b7f.jpg)

Another issue related to this, is the ability to drag a track further than the end of my screen tracks. When i try to drag a track and go to the end of my visual track list the scroll bar on the left do not move to show me the next track and i cannot drag it further than this...

![mympd 2](https://user-images.githubusercontent.com/63471607/120112967-eb255880-c180-11eb-80bc-a9de9b2ffbad.jpg)

Thank you!

**Comment by jcorporation** [comment]
Version, Browser, any errors in the javascript console?

Already clevrerer browser and app cache?

**Comment by Emilot** [comment]
JC sorry i used my other account...

latest version.

./build.sh purge
./build.sh release
./mympd

Firefox and Chrome

No errors at javascript console...

If i try to move one track more, i got a second menu window and a third, etc.... :)

**Comment by Emilot** [comment]
"is not supported natively", you mean through Bootstrap? No even at the last version?

and do you think you can do it by writing something on your own?

**Comment by Emilot** [comment]
To clarify one thing.

If i move it fast, then no menu appears. But if i delay a few seconds then menu appears.

**Comment by jcorporation** [comment]
myMPD uses the native html 5 drag& drop api.

**Comment by Emilot** [comment]
Is it time configurable in coding? (after x secs will appear). If yes i can add two secs more for menu to appear. If not then it is fine and i get it.

As for scrolling if you can write a workaround will be very helpful...

Thank you JC!

**Comment by jcorporation** [comment]
myMPD uses this JavaScript library to implement long press: https://github.com/john-doherty/long-press-event

I tested with current master and the popup menu disappears if dragging starts.

I add scrolling in drag & drop mode to #474

**Comment by Emilot** [comment]
Cool!
