### ISSUE TITLE
Group the albums by album name only

### ISSUE THREAD

**Issue by edhelas** [jcorporation/myMPD#470]
myMPD version: 7.0.2

Albums that are taggued with different artists are not grouped under the same "Album".

**Expected behavior**

Even if an album is actually containing different artists, it should be displayed as one unique album. You could use the `musicbrainz_albumid` as a way to keep things grouped.

**Screenshots**

![Capture d’écran_2021-04-15_00-13-29](https://user-images.githubusercontent.com/3726886/114787130-90c26b00-9d7f-11eb-9d57-24f276057f71.png)

**Comment by edhelas** [comment]
One small (unrelated) suggestion. For the #BrowseDatabaseListList element, you can use `justify-content: space-around/space-between` to align the albums properly and fill all the width.

**Comment by jcorporation** [comment]
myMPD uses Album+AlbumArtist to distinguish albums. 

justify-content: this breaks the last row, if there are fewer items.

**Comment by edhelas** [comment]
Regarding the justify-content, indeed it's not possible to fix the last line, you have to move to a CSS grid layout.
For the other issue, I actually have an "albumartist" tag on all those albums to group them. Maybe this tag is not prioritized properly ?

![Capture d’écran_2021-04-15_19-57-17](https://user-images.githubusercontent.com/3726886/114916298-eef55980-9e24-11eb-8faf-9ed1faa8ad71.png)

Also regarding the album list, two small remarks:
-  is it possible to keep the ordering persistent after page reloads (as well as the other parameters like pagination, filtering parameter maybe except the search input and the page), I tend to order my collection in a specific way and I'm loosing the setting each time I reload
- When clicking on the "Browse Library" button in the main menu, if you are currently viewing an album, would it be possible to go back to the general "album grid" view ?

**Comment by jcorporation** [comment]
Is the albumartist tag enabled in mpd and myMPD? In my environment grouping works.

Please use the discussions for enhancement requests. There is a ideas category.

Issues are only used for bugs and accepted feature requests.

**Comment by edhelas** [comment]
Oh yes actually they were not enabled in the mpd.conf (actually it is shown in your Wiki, my bad). I had to fully clear the cache and now it's working. Thanks for the support.

I'll put my other remarks in the ideas category :)
