### ISSUE TITLE
unclear if mympd supports ipv6

### ISSUE THREAD

**Issue by L0ric0** [jcorporation/myMPD#476]
myMPD version: [e.g. 5.6.2]

**Describe the bug**

using the reverse prox configuration provided in the wiki mympd is not accessible. The root of this seems to be mympd not supporting ipv6 as all nginx error try to connect to `[::1]`. changing the nginx config to `proxy_pass http://127.0.0.1:8080/;` removed the problem. please clarify somewere if mympd supports ipv6 and if not fix the wiki

**To Reproduce**

1. configure mympd to bind to `host = localhost`
2. configure nginx reverseproxy like in the wiki (`proxy_pass http://localhost:8080/;`)
3. randomly mympd will be accessible or not

**Expected behavior**

mympd is always accessible

**Server plattform (please complete the following information):**
 - OS: Archlinux
 - Plattform: x86_64

**Client plattform (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: Windows 10
 - Browser firefox
 - Browser version 88

See https://github.com/jcorporation/myMPD/wiki/Debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
 **Configuration (please attach if it can be usefull)**

 - /etc/mympd.conf
 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 
 **Additional context**

**Comment by jcorporation** [comment]
Thanks for the hint. myMPD does not support IPv6. I corrected the wiki entry.
