### ISSUE TITLE
Cannot parse cover images

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#498]
myMPD version: 7.0.2

**Describe the bug**

Cannot parse cover images showing the following error message.
'ERROR    webserver Can't parse id3_file: ...'

**To Reproduce**

Clear the cover cache in myMPD and web browser, then parse cover images.

**Server plattform (please complete the following information):**
 - OS: Android, Windows
 - OS version: 7, 10
 - Plattform: Samsung Note5, x86_64
 - MPD version: 0.22.8

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu Linux 20.04.2, Windows 10
 - Browser: Google Chrome, Microsfot Edge
 - Browser version: 90.0.4430.212, 90.0.818.66

**Comment by jcorporation** [comment]
Please attach myMPD debug log. OS = Windows 10? Did you mean WSL?

**Comment by parkmino** [comment]
Please find the attached file.
Server OS is Windows 10 running mpd.exe and Android 7 running apk.

[mympd.log](https://github.com/jcorporation/myMPD/files/6527788/mympd.log)

**Comment by jcorporation** [comment]
Music directory is set to auto and you use a non socket connection. myMPD falls back to the MPD albumart command and that fails.

**Comment by parkmino** [comment]
I do not get any mpd.log as follows.
It is weird that only the played cover images show.

C:\mpd>mpd.0.22.8.debug.exe -v mpd.conf
config_file: loading file mpd.conf
May 23 23:59 : vorbis: Xiph.Org libVorbis 1.3.7
May 23 23:59 : opus: libopus 1.3.1
May 23 23:59 : hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
May 23 23:59 : exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
May 23 23:59 : simple_db: reading DB
May 23 23:59 : curl: version 7.76.1
May 23 23:59 : curl: with Schannel

**Comment by parkmino** [comment]
I set the music directory for mpd.exe for Windows and cover images show.
However it is not possible for Android.

**Comment by jcorporation** [comment]
> However it is not possible for Android.

If myMPD has no direct access to the music directory you should set it to none. myMPD can retrieve albumart through the mpd protocol.

- albumart in folders (albumart command, since mpd 0.21): cover.png, cover.jpg, cover.tiff or cover.bmp
- embedded albumart (readpicture command, since mpd 0.22)

**Comment by parkmino** [comment]
Set the music directory as none also shows cover images in Windows.
However Android does not show cover images.
I will close this issue cause it might be the problem only for Android mpd 0.22.8 version.
