### ISSUE TITLE
albumart not displayed if file path with "#" character

### ISSUE THREAD

**Issue by pink-salt** [jcorporation/myMPD#501]
myMPD version: 7.0.2

If the file path (either folder name or file name) has a "#" character, the album art cannot be displayed.

**To Reproduce**

For any song file name with a "#" in it, for example, http://192.168.1.32:1333/albumart/samba/AIX/The%20Carl%20Verheyen%20Band%20-%20Rumor%20Mill/1.%20Wildflower%20#2.flac

**Expected behavior**

The albumart will be broken.

**Screenshots**

https://www.dropbox.com/s/hq0zl80iav9q1hh/albumart%20error.jpg?dl=0

**Server plattform (please complete the following information):**
 - OS: DietPI
 - OS version v7.1.2
 - Plattform: armv7l
 - MPD version: 0.21.4

**Client plattform (please complete the following information):**
 - Device: desktop
 - OS: Windows 10
 - Browser Firefox
 - Browser version 88.0.1

 **Additional context**

If I manually URL encode the "#" character and amend the URL to http://192.168.1.32:1333/albumart/samba/AIX/The%20Carl%20Verheyen%20Band%20-%20Rumor%20Mill/1.%20Wildflower%20%232.flac, it works.

**Comment by jcorporation** [comment]
The javascript function encodeURI does not encode #. I added my own function wrapper that encodes # to %23. I hope I fixed all occurrences.
