### ISSUE TITLE
Scaling background image

### ISSUE THREAD

**Issue by pgzh** [jcorporation/myMPD#503]
I'd like to suggest a possible enhancement:
If a background image is selected it would be nice if it were scaled to fill the background area completely.

Depending on the width/height ratio, there may be an area above and below or left and right where the bgimage isn't displayed.

If the height of the image is smaller than the display area (or more precisely the width/height ratio of the image is greater than that of the display), maybe it could be scaled to full height and cropped left and right.
If the width is smaller than the display area (width/height ratio smaller than that of the display), it could be scaled to full width and cropped top and bottom.

Especially on mobile devices with rotating displays the whole area would be covered by the bgimage this way.

On top of that it would be really cool if the bgimage would extend to the whole display and the bars at the top and the bottom could be configured with adjustable transparency.

Thanks for making this great mpd client!!

**Comment by jcorporation** [comment]
The css for the background sizing is:
```
background-position: center center; 
background-size: contain;  
background-repeat: no-repeat;
```

Transparency for the toolbars could be an option.
