### ISSUE TITLE
Lua scripting cannot be enabled in v8.0.0 git

### ISSUE THREAD

**Issue by pgzh** [jcorporation/myMPD#508]
myMPD version: v8.0.0

**Describe the bug**

Feature lua scripting cannot be enabled in settings, showing "Lua is not compiled in" although lua-dev is present and found by build.sh

**To Reproduce**

Build mympd v8.0.0 from git and check Features tab in settings

**Expected behavior**

Ability to enable/disable lua scripting

**Screenshots**

Attached screenshot of Features tab in settings
![Screenshot at 2021-06-09 21-54-53](https://user-images.githubusercontent.com/38223870/121420462-651dc480-c96d-11eb-916f-82b6743facb5.png)

**Server plattform (please complete the following information):**
 - OS: Raspbian
 - OS version 10.0 with latest stable updates
 - Plattform: armhf RPi 3 B+
 - MPD version: 0.21.5

**Client plattform (please complete the following information):**
 - Device: PC x86_64
 - OS: Debian 10.0
 - Browser chromium
 - Browser version 90.0.4430.212

**Debug logs (please attach if it can be usefull)**

See https://github.com/jcorporation/myMPD/wiki/Debug
- log of build.sh output
[build.log](https://github.com/jcorporation/myMPD/files/6626554/build.log)

 **Configuration (please attach if it can be usefull)**

 - /etc/mympd.conf
[mympd.txt](https://github.com/jcorporation/myMPD/files/6626556/mympd.txt)

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
[mympd_state.tar.gz](https://github.com/jcorporation/myMPD/files/6626566/mympd_state.tar.gz)
 
 **Additional context**

If the bug is not reproducible, please try disabling lua scripting and then try to re-enable it in the settings. I am not 100% sure it worked and stopped working after I disabled it once.

**Comment by pgzh** [comment]
Github won't allow uploading .conf or .tar files.
Changed extension of mympd.conf to mympd.txt and created a gz archive with tar -czf instead of -cf.
Probably the bug report template should be updated to consider this.

**Comment by jcorporation** [comment]
The mympd.conf US obsolet for v8.0.0. I rework the template after release, thanks for the hint.

**Comment by jcorporation** [comment]
> If the bug is not reproducible, please try disabling lua scripting and then try to re-enable it in the settings. I am not 100% sure it worked and stopped working after I disabled it once.

This reproduced the issue.

**Comment by pgzh** [comment]
Thanks for taking care of this so quickly!
I saw you removed the conf file and syscommands for 8.0.0 - what would be the preferred replacement for a shutdown syscommand in this branch?
Shutting down my Pi via the webinterface is so convenient ;-)

**Comment by jcorporation** [comment]
Use a simple lua script to shutdown your Pi: https://github.com/jcorporation/myMPD/wiki/Scripting

**Comment by pgzh** [comment]
Lua scripting works like a charm, now I understand why you decided to drop the syscommands stuff - especially considering you're also making the config file obsolete.
Thank you!
