### ISSUE TITLE
mympd should be system user & group instead of normal user & group

### ISSUE THREAD

**Issue by CultofRobots** [jcorporation/myMPD#51]
add "-r" or "--system" to lines 54 & 56 in mkrelease.sh
`54: [ "$?" = "2" ] && sudo groupadd -r mympd`
`56: [ "$?" = "2" ] && sudo useradd -r -g mympd -d /var/lib/mympd -s /usr/sbin/nologin mympd`

From an organizational standpoint it's better to use a system account for a service as opposed to a normal user account. Will also keep mympd out of the login dialog.

from the man page:
>-r, --system
>Create a system account.
> 
>System users will be created with no aging information in /etc/shadow, and their numeric identifiers are chosen in the SYS_UID_MIN-SYS_UID_MAX range, defined in /etc/login.defs,
>instead of UID_MIN-UID_MAX (and their GID counterparts for the creation of groups).
>
>Note that useradd will not create a home directory for such a user, regardless of the default setting in /etc/login.defs (CREATE_HOME). You have to specify the -m options if you want
>a home directory for a system account to be created.

**Comment by jcorporation** [comment]
Fixed in devel
