### ISSUE TITLE
Cosmetic issue: Track duration in queue

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#511]
Hello!

With the 7.x branch, and maybe before, there is a strange cosmetic misbehaviour, which is very low priority.

Add a playlist to the queue, watch the queue, and every time a track finishes, the playtime changes from mm:ss to number of seconds, like this:

![2021-06-12-161347_363x266_scrot](https://user-images.githubusercontent.com/13167467/121778959-aa263e80-cb99-11eb-88d1-318ce44b94d6.png)

It seems browser independent, and really nothing that breaks anything, so save it for whenever you are fixing other cosmetic stuff anyway, ok? :)

**Comment by jcorporation** [comment]
Thanks for your bug report. This small issue will be fixed in the next release.
