### ISSUE TITLE
Homescreen link bad url

### ISSUE THREAD

**Issue by sabolv** [jcorporation/myMPD#512]
myMPD version: 7.0.2

Filesystem browse link added to homescreen does not work. i.e. homescreen link to folder local/Radio redirects browser to url http://localhost/#/Browse/Filesystem/!0/100/-/-/-/(local%2FRadio). When I remove parentheses around string local%2FRadio then url works. Record {"name":"Radio","ligature":"radio","bgcolor":"#ffe788","image":"","cmd":"appGoto","options":["Browse","Filesystem","","0","100","-","-","-","local/Radio"]} in /var/lib/mympd/state/home_list appears to be ok.

1. Click on Browse -> Filesystem
2. Browse to filesystem folder
3. Click on "Add to homescreen" button
4. Click on Home -> Created link
5. Error JavaScript error: Uncaught TypeError: Cannot read property 'images' of undefined appears in popup window. Filesystem browser displays last displayed folder (not folder of homescreen link)

**Comment by jcorporation** [comment]
I can reproduce the bug in v7.0.2. In v8.0.0 the bug is already fixed.
