### ISSUE TITLE
Embedded albumart from ALAC (m4a) files are not displayed

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#518]
MyMPD Version: 7.0.2
MPD Version: 0.22.9
Connection	/var/run/mpd/socket
Protocol version	0.22.4
Libmpdclient version	2.20.0
Libmympdclient version	1.0.5

MyMPD has access to the music folder, they are browseable and the file
folder.jpg which I extracted with mpc readpicture is consequently displayed.

**Comment by jcorporation** [comment]
myMPD itself can not handle m4a files, but ist should fallback to the readpicture command. Please attach debug logs.

**Comment by jcorporation** [comment]
Error found: myMPD does not ask MPD for the albumart of music directory is acessable. This is already fixed in devel.

**Comment by GK-774** [comment]
Ups, have read this to late - so the log files are not needed any more ? (I could provide them now). A question, how would I fix that in 7.0.3 ? Or will there be a 7.0.3 with the most important bugs fixed?

**Comment by jcorporation** [comment]
There will be on fix for the 7.0.x series the next Release will be 8.0.0. I hope to release it this month.
