### ISSUE TITLE
Build with openssl disabled failes

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#519]
myMPD version: 8.0.0 (July 6th)

Building with -DENABLE_SSL=OFF results in the build process correctly telling "Openssl is disabled"
but the build later fails, see attached build_error_without_ssl.txt
Building with openssl works without problems in the same environment.

[build_error_without_ssl.txt](https://github.com/jcorporation/myMPD/files/6770725/build_error_without_ssl.txt)

**Comment by jcorporation** [comment]
Thanks for the bug report, is now fixed.
