### ISSUE TITLE
Search function hangs (unresponsible page)

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#528]
Versions:
myMPD   8.0.0
Connection	/var/run/mpd/socket
Protocol version	0.22.4
Libmpdclient version	2.20.0
Libmympdclient version	1.0.6
OS  CentOS 8

Steps taken:
Did a search (any tag) for one string, enter and a second string.
Results get displayed but the page became unresponsible. (Actually
all, could not change to homescreen or any other of the streams).
The URL of the unresponsible page looks like:
http://192.168.0.2/#/Search!0/0/any/Title/-/((any%20contains%20'Victor')%20AND%20(any%20contains%20'Jara'))

With the Chrome based browser used I got
"You can wait for the page to become responsive or close it."
Clicked Wait without success, after some time the same message appeared again,
so I clicked "Close" and got the message "This tab was reloaded due to an error on the page."
Repeated search with the same result. Log is attached.

Safari (iPad) and Firefox (Android) dont issue such messages but otherwise the result is the same.

**Comment by jcorporation** [comment]
I can not reproduce your issue. I see no log attached. Browser log and myMPD debug log is interesting.

**Comment by GK-774** [comment]
Sorry, the mympd log:
[mympd_20210717.log.gz](https://github.com/jcorporation/myMPD/files/6835133/mympd_20210717.log.gz)
For the mpd log I have to repeat it again.

**Comment by jcorporation** [comment]
myMPD log shows no unusual behavior.  I need no MPD log. A browser log could be interesting.

**Comment by GK-774** [comment]
I´m not aware of browser logs - how would one activate those ?
[mympd_20210717_2.log.gz](https://github.com/jcorporation/myMPD/files/6835168/mympd_20210717_2.log.gz)
![Screenshot_20210717_203448](https://user-images.githubusercontent.com/75694230/126046772-7873ad42-e20a-40b8-aeb9-eda8fdb1d8af.png)

**Comment by jcorporation** [comment]
Look at the webdeveloper console: https://developer.mozilla.org/en-US/docs/Tools/Web_Console

**Comment by GK-774** [comment]
Ok installed Firefox, the console as such just shows:

Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
192.168.0.2
Content Security Policy: The page’s settings blocked the loading of a resource at data:application/font-woff;base64,d09GRg… (“font-src”). 3
INFO: Startup length: 306ms combined.js:8:67701
INFO: Connecting to ws://192.168.0.2/ws/ combined.js:8:67701
INFO: Websocket is connected combined.js:8:67701
Script terminated by timeout at:
updateTable@http://192.168.0.2/js/combined.js:8:162657
parseSearch@http://192.168.0.2/js/combined.js:8:168872
sendAPI/ajaxRequest.onreadystatechange@http://192.168.0.2/js/combined.js:8:141584
combined.js:8:162657
Content Security Policy: The page’s settings blocked the loading of a resource at data:application/font-woff;base64,d09GRg… (“font-src”). 3

Debugger tab shows something for combined.js (attached)
[debugger_combined_js.txt.gz](https://github.com/jcorporation/myMPD/files/6835185/debugger_combined_js.txt.gz)

**Comment by GK-774** [comment]
While I looked at issue #524 I remembered that I had increased the max_output_buffer_size
at some point in the past in mpd.conf to accomodate a client that I tried at the time.
So now I commented that out for restoring the default and this improved the situation
for this issue substantially.
I now get a (very short, a second or so) "websocket disconnected" after entering the first
search term but from then onwards it gets responsible again once it has sorted the results.
So, sorry, it appears it was a misconfiguration on my side (which got unnoticed because it seemed not
to matter in the past).

**Comment by jcorporation** [comment]
A websocket disconnect should not appear. Can you collect new logs?

**Comment by jcorporation** [comment]
The default buffer size of libmpdclient is 4096 and not configureable. The mpd default buffer size is 8192. I prepared a patch for libmpdclient to make it configureable at compile time and raises the default to 8192. With this patch in upstream, I can make the buffer size configureable at myMPD compile time.

Why cantata needs so a large buffer size?

As a workaround you can try to set the max list elements to a lower number, not to any. myMPD will hard limit the number of results to 1000 in the next release to prevent the stale webui problem.

**Comment by jcorporation** [comment]
Can you test with devel again? Issue should be fixed.

**Comment by GK-774** [comment]
Will do so this evening. As the buffer of libmympdclient has now been increased to 32768 bytes,
shall I set this in mpd.conf as well (max_output_buffer_size "32768")?

**Comment by jcorporation** [comment]
> shall I set this in mpd.conf as well (max_output_buffer_size "32768")?

No, because:
- max_output_buffer_size in mpd.conf are kilobytes and represent the maximum size of a complete response
- libmympdclients buffer_size is in bytes and the maximum size of one response line, I think the 32768 is to big, I will shrink it to 8192 bytes before releasing 8.0.1
- myMPD should work with the default values of MPD

**Comment by GK-774** [comment]
Works as designed nicely now, I could not identify any issues with the search.

I have set the max list entries to a lower value (50 currently) following your recommendation three days ago. This led me to the question if the current "search as you type" strategy is optimal. When you type the first letter of a search that must be generating tons of "results" that you are not looking for.
I wonder if a possibility to enter some search strings (and/or substrings) and then start the search, would not be a better solution. Anyway, this is not the scope of this bug report and the issue at hand appears to be solved.
