### ISSUE TITLE
loglevel does not work

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#532]
Loglevel in /etc/mympd.conf does not work for 8.0.1.
It shows only NOTICE level at the moment.

**Comment by jcorporation** [comment]
/etc/mympd.conf is obsolet, look at the release notes and documentation.

**Comment by parkmino** [comment]
Should I edit /var/lib/mympd/logglevel file?
I did it and no effect.
Please advise me how to do it.

**Comment by Emilot** [comment]
https://jcorporation.github.io/myMPD/configuration/

**Comment by parkmino** [comment]
Did you try to edit /var/lib/mympd/config/loglevel?
It does not work on my side.

**Comment by parkmino** [comment]
> https://jcorporation.github.io/myMPD/configuration/

Did you try to edit /var/lib/mympd/config/loglevel?
It does not work on my side.

**Comment by jcorporation** [comment]
Editing the loglevel file and restart should work. The loglevel is always overridden by the environment as described in the documentation.

There are only some options in the config directory. All other options are configureable with the web ui.

**Comment by parkmino** [comment]
It does not work on my side, please check it.

**Comment by tsunulukai** [comment]
I reproduced this issue on my setup too:

Setting a loglevel into the file `/var/lib/mympd/config` has no effect whatsoever and seems to default to loglevel 5 (notice) instead.. I checked that the MYMPD_LOGLEVEL was unset.

Nevertheless, using `export MYMPD_LOGLEVEL=<level>` before starting mympd does indeed impact the log verbosity as expected.
