### ISSUE TITLE
Background color picker for home icon with transparent background

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#535]
myMPD version: 8.0.1

**Describe the bug**

When choosing an image whose background is transparent as icon for a home icon, you need to choose the background color first by selecting "Use ligature", then chose the icon to be able to select the background color of your choice.

**Expected behavior**

The color picker should be available to select the background color when choosing a custom picture.

**Screenshots**

![image](https://user-images.githubusercontent.com/4215150/126869571-56741baf-5429-4abe-b046-f96ccb72ff87.png)
![image](https://user-images.githubusercontent.com/4215150/126869588-0b56b96b-ac9a-4b80-bf93-f009261208f6.png)
![image](https://user-images.githubusercontent.com/4215150/126869622-19a94a88-b6d2-4e3c-94cc-cb6980512982.png)
![image](https://user-images.githubusercontent.com/4215150/126869631-d39c7602-7324-4a3b-8356-887877c6450e.png)

**Comment by jcorporation** [comment]
This was by design: picture or ligature +background. But selecting a background for a transparent picture makes sense.
