### ISSUE TITLE
Track is skipped when clicking to seek backward

### ISSUE THREAD

**Issue by escalopoulet** [jcorporation/myMPD#538]
myMPD version: 6.11.1

**Describe the bug**

While playing a song, the behaviour when clicking to skip forward/backward
in strange. When clicking *after* the current position of the track on the horizontal 
"progression bar" (which indicates the position of the current track), the behaviour
is correct (i.e. seek forward).

However, when clicking *before*, instead of seeking backward, the current track
is skipped and the next song of the playlist starts.

**To Reproduce**

1. start a playlist
2. click on the progression bar to seek forward or simply wait a bit
3. click *before* on the progression bar
4. error : the current song is skipped, and the next one in the playlist starts

**Expected behavior**

Normally, the interface should keep the same track, and plays the song
at the instant the user clicked at.

**Server plattform (please complete the following information):**
 - OS: DietPI
 - OS version: 7.4.2
 - Plattform: aarch64 / arm64
 - MPD version: 0.21.5-3

**Client plattform (please complete the following information):**
 - Device: PC
 - OS: Gentoo Linux
 - Browser : Firefox
 - Browser version  78.12.0esr

**Comment by jcorporation** [comment]
This issue was fixed with 6.11.2. Please always test with latest stable version before opening an issue.

**Comment by escalopoulet** [comment]
I am so sorry for my incorrect issue ... 
I was updating diepti with "apt update", but a reinstallation of software
with dietpi-software was necessary for updating mympd.

I just updated and everything works fine.

Congratulations for your very nice software !!!
