### ISSUE TITLE
Error when viewing empty queue

### ISSUE THREAD

**Issue by sevmonster** [jcorporation/myMPD#543]
myMPD version: 8.0.2

**Describe the bug**

The element in question is `#QueueCurrentList > tfoot > tr > td`
I get this error when opening the queue when it is empty: `Uncaught TypeError: Cannot create property 'textContent' on string '' (https://mpd.dominion.sev.monster/js/combined.js: 8)`
If the queue had content previously, the `tfoot > tr > td` is created successfully but the content is not updated and I get this error: `Uncaught TypeError: Cannot create property 'textContent' on string '<tr><td colspan="6"><small>1 Song</small></td></tr>' (https://mpd.dominion.sev.monster/js/combined.js: 8)`

**To Reproduce**

1. Open the queue
2. The footer does not update if the queue is empty, and an error occurs

**Expected behavior**

1. Open the queue
2. If the queue is empty, show "0 Songs" or similar in the footer

**Screenshots**

Starting with a blank queue causes an error:
![image](https://user-images.githubusercontent.com/16788697/128403195-bd109d72-9829-49fb-bc6e-c2ff0f31aae8.png)
Adding songs works as expected:
![image](https://user-images.githubusercontent.com/16788697/128397473-d938dbce-a3a5-4038-8801-4d9512344f3c.png)
Removing the songs does not update the footer and an error occurs:
![image](https://user-images.githubusercontent.com/16788697/128397515-b85523f1-1e9f-4434-9870-3187f2d69b52.png)
![image](https://user-images.githubusercontent.com/16788697/128397547-a1f5dc3e-bcb3-4966-9152-a55954004d14.png)

**Server plattform (please complete the following information):**
 - OS: Alpine Linux
 - OS version edge
 - Plattform: x86_64
 - MPD version: 0.22.4
 - Libmpdclient version: 2.20.0
 - Libmympdclient version: 1.0.6

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Microsoft Windows 10 LTSC 2016
 - Browser: Chromium
 - Browser version: 90.0.4430.95

**Debug logs (please attach if it can be usefull)**

No other useful information was observed with debug build and valgrind.
 
 **Configuration (please attach if it can be usefull)**

Fresh install with no configuration changes.

**Comment by jcorporation** [comment]
Thanks for your bug report. This issue is already fixed in the devel branch with commit 36c3de18788d241a3f78792d5bba69906cb7b014.
