### ISSUE TITLE
Can't browse cross-device links in filesystem

### ISSUE THREAD

**Issue by sevmonster** [jcorporation/myMPD#544]
myMPD version: 8.0.2

**Describe the bug**

Softlinks are not followed when they are cross-device. I have tested this with ext4 and zfs filesystems. Softlinks to the same device and normal directories work fine. MPD is able to index softlinks to other devices so playback and MPD API-provided album art work correctly.

**To Reproduce**

1. Open the filesystem browser
2. Open a directory that is a softlink to some other filesystem
3. Receive "Invalid URI" error

**Expected behavior**

1. Open the filesystem browser
2. Open a directory that is a softlink to some other filesystem
3. Browse the directory as if it were any other

**Screenshots**
![image](https://user-images.githubusercontent.com/16788697/128439375-b396ccf8-278f-4182-a42b-dec33a1901f8.png)
![image](https://user-images.githubusercontent.com/16788697/128438705-b2f6809e-58ab-4c93-99ab-8c5c78bfe582.png)
![image](https://user-images.githubusercontent.com/16788697/128438561-2343e6b5-daf6-41e2-af1d-b5b10dda05fd.png)
![image](https://user-images.githubusercontent.com/16788697/128439436-641de951-054a-4a75-af8e-8ce94d5222e6.png)

**Server plattform (please complete the following information):**
- OS: Alpine Linux
- OS version edge
- Plattform: x86_64
- MPD version: 0.22.4
- Libmpdclient version: 2.20.0
- Libmympdclient version: 1.0.6

**Client plattform (please complete the following information):**
- Device: Desktop
- OS: Microsoft Windows 10 LTSC 2016
- Browser: Chromium
- Browser version: 90.0.4430.95

**Debug logs (please attach if it can be usefull)**

No other useful information was observed with debug build and valgrind. Log level 7 did not show any errors, just that the request was made.

**Configuration (please attach if it can be usefull)**

Fresh myMPD install with no configuration changes.

mpd.conf:
```
music_directory                 "~/music"
```

 **Additional context**

I've noticed this issue since I starting using myMPD at around I believe version 7.0.0 but never got around to reporting it.

I did verify that the service user is able to read the folder normally:
```
%sev@host: sudo -u mympd -g mympd ls '/var/lib/mpd/music/link/tagged/1000mods/Liquid Sleep EP (2009)'
01 Burnt Sleep.flac   02 Liquid Sleep.flac  cover.jpg
```

**Comment by jcorporation** [comment]
It is not a bug but a security feature. Mongoose, the http server component, will not follow symlinks pointing outside the document root. Enabling this would cause security issues.

**Comment by tsunulukai** [comment]
If you really need to access data from another FS in your mympd web server, you can use bind mount to mount the foreign fs into your music library:

```
mkdir ~/mpd/music/remotefsdir/
mount --bind /some/existing/directory ~/mpd/music/remotefsdir/
```

Beware of the side effects, because it's somewhat equivalent to hard linking a directory, which is not allowed in linux.
You can find a list of side effects here: https://unix.stackexchange.com/questions/22394/why-are-hard-links-to-directories-not-allowed-in-unix-linux

**Comment by sevmonster** [comment]
> If you really need to access data from another FS in your mympd web server, you can use bind mount to mount the foreign fs into your music library:

MPD is now segfaulting when attempting to load album art.

```
Aug 11 13:23 : client: [0] process command "albumart "bindmount/some/path/file.mp3" "0""
zsh: segmentation fault  sudo mpd --no-daemon -v
```

**Comment by jcorporation** [comment]
There is no mongoose option to disable this behavior. You should open a issue in the mongoose repository, but I do not think this request would be implemented.

MPD should also not segfault with bind mounts they should be transparent to the user space. You should open a bug in the mpd repository.

**Comment by tsunulukai** [comment]
> MPD is now segfaulting when attempting to load album art.
> 
> ```
> Aug 11 13:23 : client: [0] process command "albumart "bindmount/some/path/file.mp3" "0""
> zsh: segmentation fault  sudo mpd --no-daemon -v
> ```

I cannot reproduce this behaviour on my system.
I tested this with Debian Bullseye (11.0) x64, mpd 0.22.6, mympd 8.0.3

 ```
/mnt/NAS/Music = mpd root dir (ext4 FS)
/home/mpd = foreign fs (ext4 FS)
/mnt/NAS/Music/test = bindmound of /home/mpd folder
 ```

I can play /mnt/NAS/Music/test/test.mp3 (/home/mpd/test.mp3 in reality) with mpd with no issue at all. No segfault trying it.
Browsing the folder with myMPD works great too.

**Comment by sevmonster** [comment]
> I cannot reproduce this behaviour on my system.
> I tested this with Debian Bullseye (11.0) x64, mpd 0.22.6, mympd 8.0.3

I switched back to using a softlink and it still occurs, so I think this may be due to a change in MPD. Try upgrading to 0.22.10 and see if it occurs. There were some changes to the `albumart` command a few days ago, and I upgraded to it recently.

I will try downgrading to 0.22.9 (or maybe 0.22.6 as you have success with it) and see if it still occurs. If not, I think readonly bind mount is the solution for my problems.

**Comment by sevmonster** [comment]
Yep, it's 0.22.10. 0.22.9 does not crash.

**Comment by jcorporation** [comment]
Then you should open a bug report for MPD.

**Comment by jcorporation** [comment]
https://github.com/cesanta/mongoose/commit/894a16883307cb6d236473e2f6fa2311e3fde747

It seems that next version of mongoose would support softlinks.
