### ISSUE TITLE
No lyrics on Playback tab

### ISSUE THREAD

**Issue by Hajuskin** [jcorporation/myMPD#546]
myMPD version: 8.0.3

**Describe the bug**

I can see the lyrics in the song details, but there are not displayed on the playback tab. Lyrics are of course enabled in the settings.

(Another small issue: In the screenshot you can see that in dark mode there is a small bright line on the right side of the cover image, seems like the background is a bit wider than the picture. It's only visible if the picture is scaled down when the window size is reduced.)

**Screenshots**

![2021-08-10_210019](https://user-images.githubusercontent.com/51139914/128919525-920fbf4d-1eab-4918-b6f7-3c0c6b0dcfcc.png)
![2021-08-10_210027](https://user-images.githubusercontent.com/51139914/128919539-c1c09cf2-2913-4014-af41-9375f34b245a.png)

**Server plattform (please complete the following information):**
 - Docker Image
 - MPD version: 0.22.9

**Client plattform (please complete the following information):**
 - OS: Windows 10 and Android 11
 - Browser: Chrome

**Debug logs (please attach if it can be usefull)**

See https://github.com/jcorporation/myMPD/wiki/Debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
 **Configuration (please attach if it can be usefull)**

[state.zip](https://github.com/jcorporation/myMPD/files/6964019/state.zip)

**Comment by jcorporation** [comment]
Is fixed with ebe2c2a9b29b6fbb1de090e5ebcf40bf01947320 in devel and 8.1.0.

**Comment by Hajuskin** [comment]
Looks good, thank you!
