### ISSUE TITLE
Browsing Albums triggers mpd stop

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#550]
Versions used:

myMPD 8.0.3 and 8.1.0
(both show same behaviour, logs are from 8.1.0)

MPD 0.22.10
Connection	/var/run/mpd/socket
Protocol version	0.22.4
Libmpdclient version	2.20.0

MPD was playing (a stream in this case, but had the same effect with files as well) and browsed through albums until this eventually triggerd "MYMPD_API_PLAYER_STOP" and playing stops.
Log file (debug) is attached.

Best Regards,
Georg
[20210812-mympd.zip](https://github.com/jcorporation/myMPD/files/6974821/20210812-mympd.zip)

**Comment by jcorporation** [comment]
There are mpd errors in the log. It seems a mpd bug: https://github.com/MusicPlayerDaemon/MPD/issues/1225

**Comment by GK-774** [comment]
I dont get a segfault in mpd. If I click "Play" it just continues to play from where it stopped.

**Comment by jcorporation** [comment]
Ok. I can not reproduce your issue. Please attach the verbose mpd log and the web browser debug log. I need to know why the mpd connection breaks and what the browser does when the issue occurs.

**Comment by jcorporation** [comment]
Looking through the logs again, I found another issue. Cover extraction for `georg/anything_else_mp3_aac/Action
ata_Distance/Wired_CD/16-Matmos.mp3` fails. Libid3tag thinks there is a tag with 0 bytes length. Can you check this file if it has a correct APIC tag?

**Comment by GK-774** [comment]
Sorry for the late answer, I´m on holiday right now. Built 8.0.4 and mpd 0.22.10 with the fix from https://github.com/natsukagami/mpd-mpris/issues/27 today and with this two versions I could not observe this bug anymore.
