### ISSUE TITLE
JSON-RPC API Connection close not respected

### ISSUE THREAD

**Issue by Trekky12** [jcorporation/myMPD#551]
Hello, 

first I would like to say thank you for this great project 👍 

Unfortunately I have a little problem when using the JSON-RPC API. I am using a embedded device (a Particle Photon, similar to Arduino or ESP) to create a request to mympd.
The HTTP Client of the embedded device is not capable to keep connections alive so I am sending the header "Connection: close" with my request.
Apparently this client header is not respected by the server and the server doesn't send the corresponding "Connection: close" header back. When sending a HTTP 1.0 request the server also doesn't respect that and responds with a HTTP 1.1 which doesn't close the connection.
This results in a endless waiting of the embedded device.

Is it possible to respect the "Connection: close" header of the client and send a "Connection: close" header with a response or send a HTTP 1.0 response instead of a HTTP 1.1 response when the client is sending a HTTP 1.0 request?

The corresponding lines should be here: https://github.com/jcorporation/myMPD/blob/master/src/web_server.c#L250, https://github.com/jcorporation/myMPD/blob/master/src/web_server/web_server_utility.c#L126

Thank you for your help!

**Comment by jcorporation** [comment]
I am not sure what is the right behavior:
- send a connection close header back
- Closing the connection at server side

I must look at the specs.

**Comment by jcorporation** [comment]
Fix is now in devel. Will you give it a try?

**Comment by Trekky12** [comment]
Thank you very much! The patch is working basically. The response contains the neccessary header with Connection: close and the connection is also closed.
Unfortunately there is no longer a response body so it is not possible to query for specific attributes (like the current volume).

So for example the curl request:
```
curl "http://<IP>/api/" -d '{"jsonrpc":"2.0","id":0,"method":"MYMPD_API_PLAYER_VOLUME_GET"}' -H "Content-Type: application/json" -H "Connection: close" -v
```

results in

```
> POST /api/ HTTP/1.1
> Host: <IP>
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Connection: close
> Content-Length: 63
>
} [63 bytes data]
* upload completely sent off: 63 out of 63 bytes
* Empty reply from server
100    63    0     0  100    63      0   2032 --:--:-- --:--:-- --:--:--  2032
* Connection #0 to host <IP> left intact
curl: (52) Empty reply from server
```

Without the closing connection the result is:
```
> POST /api/ HTTP/1.1
> Host: <IP>
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 63
>
} [63 bytes data]
* upload completely sent off: 63 out of 63 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 86
<
{ [86 bytes data]
100   149  100    86  100    63    688    504 --:--:-- --:--:-- --:--:--   688{"jsonrpc":"2.0","id":0,"result":{"method":"MYMPD_API_PLAYER_VOLUME_GET","volume":40}}
* Connection #0 to host <IP> left intact
```

Is it possible to close the connection and still receive a response?

**Comment by jcorporation** [comment]
I hopped setting the connection to is_draining does this exactly. I will revert the commit in devel and search for a other solution.

**Comment by Trekky12** [comment]
> I do not see the even header in your test with connection: close.

What do you mean with this?

I also think the asynchronous handling of the request could be the problem.

**Comment by jcorporation** [comment]
In your test with the connection close header, myMPD response is empty, even the response headers are not sent.

**Comment by jcorporation** [comment]
For the 8.1.0 release I have reworked the connection handling, it should now respect the "connection: close" request header.

You could test it with this release. Be warned, v8.1.0 is w.i.p and could break anytime.

This changes are too big to go into the next bug fix release.

**Comment by Trekky12** [comment]
Thank you very much @jcorporation! With the changes in v8.1.0 it is working as expected 🥳

**Comment by jcorporation** [comment]
Thanks for testing.
