### ISSUE TITLE
Issues while starting in termux

### ISSUE THREAD

**Issue by piyushgarg** [jcorporation/myMPD#552]
myMPD version: 8.0.4

**Describe the bug**

I am able to build mympd over **termux** (after some hiccups) and able to open the website() but it is not connecting to mpd. It is always connecting via socket. I have made some changes to accommodate some build related changes as well to make it compile. But still it is not connecting to MPD. Please review the diff file.

archive contains the following:
1. build log
2. changes (diff)

Issues:
1. Compile Issues
2. lua library did not detect despite it is installed
  .../files/myMPD $ pkg list-installed|grep lua
  liblua54/stable,now 5.4.3 aarch64 [installed]
3. mpd connection issues
4. configure mympd to use $HOME/.config/mympd instead of /data/data/com.termux/files/usr/var/lib/mympd/

.../files/myMPD $ ./release/mympd --help

Version:
Usage: ./release/mympd [OPTION]...

myMPD 8.0.4
(c) 2018-2021 Juergen Mang <mail@jcgames.de>
https://github.com/jcorporation/myMPD

Options:
  -c, --config           creates config and exits
  -h, --help             displays this help
  -u, --user <username>  username to drop privileges to (default: mympd)
  -s, --syslog           enable syslog logging (facility: daemon)
  -w, --workdir <path>   working directory (default: /data/data/com.termux/files/usr/var/lib/mympd)

// the following does not seem to be working
export MPD_HOST=127.0.0.1
export MPD_PORT=6611

startup log
.../files/myMPD $ ./release/mympd -u u0_a238
11:18:42 NOTICE   mympd     Workdir: "/data/data/com.termux/files/usr/var/lib/mympd"
11:18:42 NOTICE   mympd     Config dir: "/data/data/com.termux/files/usr/var/lib/mympd/config"
11:18:42 NOTICE   mympd     Setting loglevel to NOTICE
11:18:42 NOTICE   mympd     Starting myMPD 8.0.4
11:18:42 NOTICE   mympd     Libmympdclient 1.0.6 based on libmpdclient 2.20.0
11:18:42 NOTICE   mympd     Mongoose 7.3
11:18:42 WARN     mympd     Can not open /etc/resolv.conf
11:18:42 ERROR    mympd     No such file or directory
11:18:42 NOTICE   mympd     Listening on http://0.0.0.0:8181
11:18:42 NOTICE   mympd     State dir: "/data/data/com.termux/files/usr/var/lib/mympd/state"
11:18:42 NOTICE   mympd     Smartpls dir: "/data/data/com.termux/files/usr/var/lib/mympd/smartpls"
11:18:42 NOTICE   mympd     Pics dir: "/data/data/com.termux/files/usr/var/lib/mympd/pics"
11:18:42 NOTICE   mympd     Empty dir: "/data/data/com.termux/files/usr/var/lib/mympd/empty"
11:18:42 NOTICE   mympd     Covercache dir: "/data/data/com.termux/files/usr/var/lib/mympd/covercache"
11:18:42 NOTICE   mympd     Starting mympd api thread
11:18:42 NOTICE   mympd     Starting webserver thread
11:18:42 NOTICE   mympdapi  Reading states
11:18:42 NOTICE   mympdapi  MPD connecting to socket /run/mpd/socket
11:18:42 ERROR    mympdapi  MPD connection: No such file or directory
11:18:42 ERROR    mympdapi  MPD connection failed
11:18:45 NOTICE   mympdapi  MPD connecting to socket /run/mpd/socket
11:18:45 ERROR    mympdapi  MPD connection: No such file or directory
11:18:45 ERROR    mympdapi  MPD connection failed

[mympd.tar.gz](https://github.com/jcorporation/myMPD/files/7064696/mympd.tar.gz)

**Comment by piyushgarg** [comment]
Thanks for quick help. I am able to run it now.

git clone git@github.com:jcorporation/myMPD.git
cd myMPD
export MYMPD_INSTALL_PREFIX=$PREFIX
./build.sh release


.../files/myMPD $ ls $PREFIX/include/lua5.4/
lauxlib.h  lua.h  lua.hpp  luaconf.h  lualib.h

.../files/myMPD $ cat  $PREFIX/lib/pkgconfig/lua54.pc 
V=5.4
R=5.4.3

prefix=/data/data/com.termux/files/usr
INSTALL_BIN=${prefix}/bin
INSTALL_INC=${prefix}/include/lua${V}
INSTALL_LIB=${prefix}/lib
INSTALL_MAN=${prefix}/man/man1
INSTALL_LMOD=${prefix}/share/lua/${V}
INSTALL_CMOD=${prefix}/lib/lua/${V}
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/lua${V}

Name: Lua
Description: An Extensible Extension Language
Version: ${R}
Requires: 
Libs: -L${libdir} -llua${V} -lm
Cflags: -I${includedir}


.../files/myMPD $ ls $PREFIX/lib/liblua5.4.so
/data/data/com.termux/files/usr/lib/liblua5.4.so


--------

[  0%] Building C object CMakeFiles/mympd.dir/src/main.c.o
clang-12: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
clang-12: error: argument unused during compilation: '-s' [-Werror,-Wunused-command-line-argument]
make[2]: *** [CMakeFiles/mympd.dir/build.make:76: CMakeFiles/mympd.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mympd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

--------


[  6%] Building C object CMakeFiles/mympd.dir/src/log.c.o
/data/data/com.termux/files/myMPD/src/log.c:55:24: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
        vsyslog(level, fmt, args);
                       ^~~
1 error generated.
make[2]: *** [CMakeFiles/mympd.dir/build.make:174: CMakeFiles/mympd.dir/src/log.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mympd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2



.../files/myMPD $ find $PREFIX/include/ -name "*syslog*"
/data/data/com.termux/files/usr/include/sys/syslog.h
/data/data/com.termux/files/usr/include/syslog.h
/data/data/com.termux/files/usr/include/boost/log/sinks/syslog_backend.hpp
/data/data/com.termux/files/usr/include/boost/log/sinks/syslog_constants.hpp



There seems to be a valid syslog.h file in /data/data/com.termux/files/usr/include/syslog.h (attached) but still not picked up.


--------

[ 43%] Building C object CMakeFiles/mympd.dir/dist/src/frozen/frozen.c.o
error: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Werror,-Wunknown-warning-option]
make[2]: *** [CMakeFiles/mympd.dir/build.make:860: CMakeFiles/mympd.dir/dist/src/frozen/frozen.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mympd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

After build

export MPD_HOST=localhost
expirt MPD_PORT=6611
./release/mympd -w $HOME/.config/mympd

It was still trying to connect to socket and it does not saving the changes via browser. Finally I had to change the config files inside mympd to change the default connection settings. 


After that it is working fine. Now I am able to start and constrol using mobile browser.
In all with little changes it used to work.
[syslog.h.tar.gz](https://github.com/jcorporation/myMPD/files/7070175/syslog.h.tar.gz)

**Comment by jcorporation** [comment]
I build myMPD only with gcc, you build it with clang. That’s are the cause of the compile errors. These errors should be easily reproduce and fixable. I open a new issue for it, this is not termux related.

Lua not found:
Try `set(ENV{LUA_DIR} "/usr/lib/lua5.4")` in the Cmakelists.txt. Of course with the right path.

Please set loglevel to debug and reproduce the not working change of mpd host. 
- delete the workdir 
- Export the mpd variables
- https://jcorporation.github.io/myMPD/debug

**Comment by piyushgarg** [comment]
Checked the debug logs. its working fine as expected now.
