### ISSUE TITLE
Compile errors with clang

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#553]
[  0%] Building C object CMakeFiles/mympd.dir/src/main.c.o
clang-12: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
clang-12: error: argument unused during compilation: '-s' [-Werror,-Wunused-command-line-argument]
make[2]: *** [CMakeFiles/mympd.dir/build.make:76: CMakeFiles/mympd.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mympd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

--------

[  6%] Building C object CMakeFiles/mympd.dir/src/log.c.o
/data/data/com.termux/files/myMPD/src/log.c:55:24: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
        vsyslog(level, fmt, args);
                       ^~~
1 error generated.
make[2]: *** [CMakeFiles/mympd.dir/build.make:174: CMakeFiles/mympd.dir/src/log.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mympd.dir/all] Error 2
make: *** [Makefile:136: all] Error 

[ 43%] Building C object CMakeFiles/mympd.dir/dist/src/frozen/frozen.c.o
error: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Werror,-Wunknown-warning-option]
make[2]: *** [CMakeFiles/mympd.dir/build.make:860: CMakeFiles/mympd.dir/dist/src/frozen/frozen.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/mympd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

_Originally posted by @piyushgarg in https://github.com/jcorporation/myMPD/issues/552#issuecomment-907572608_

**Comment by jcorporation** [comment]
With the above commit myMPD v8.1.0 (not stable) compiles fine with clang 12 on ubuntu.

**Comment by piyushgarg** [comment]
Great!! myMPD 8.1.0 compiles and build fine now on clang/termux.

Even after setting the proper LUA_DIR in cmake file, _missing LUA_LIBRARIES_ is still a problem with cmake on termux. Its not blocker as of now.

**Comment by jcorporation** [comment]
Great, I close this issue now.
