### ISSUE TITLE
myMpd and mpd socket

### ISSUE THREAD

**Issue by antonellocaroli** [jcorporation/myMPD#560]
how come mympd as default setting has as host mpd /run/mpd/socket

it should not be /var/run/mpd/socket

as recommended also in the documentation?

https://mpd.readthedocs.io/en/stable/user.html#configuration

`To bind to a local socket (UNIX domain socket), specify an absolute path or a path starting with a tilde (~). Some clients default to connecting to /var/run/mpd/socket so this may be a good choice:`

**Comment by jcorporation** [comment]
Nowadays most distributions defaults to `/run/mpd/socket`. It seems for me the more modern approach.
