### ISSUE TITLE
Unable to run behind reverse proxy

### ISSUE THREAD

**Issue by L0ric0** [jcorporation/myMPD#562]
Trying to set up mympd behind a reverse proxy with the new config.
When setting
```
#/var/lib/mympd/config/http_host
127.0.0.1
```
and
```
#/var/lib/mympd/config/http_port
8080
```
and configuring nginx to forward requests to `domain.tld/mympd` to `127.0.0.1:8080` the browser is redirected to `https://127.0.0.1` which obviously is wrong.

Could the ability to run mympd behind a reverseproxy be added again?

**Comment by jcorporation** [comment]
You should disable ssl. If ssl is enabledd myMPD redirects http to https.
