### ISSUE TITLE
Error Message : Invalid value for "smartplsGenerateTagList": ""

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#566]
myMPD version: 8.1.0

**Describe the bug**

"Apply" or "Save" in Settings does not work showing the error message "Invalid value for "smartplsGenerateTagList": """.

[mympd.log](https://github.com/jcorporation/myMPD/files/7235801/mympd.log)

![2021-09-27-201232_1600x900_scrot](https://user-images.githubusercontent.com/12131158/134898336-45806f1d-43d1-4085-b44c-45b223120117.png)

**Comment by jcorporation** [comment]
Thanks for reporting this bug. It is fixed in devel.
