### ISSUE TITLE
8.1.0 - Searching for more than one string, "Enter" deletes with some browsers?

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#567]
With 8.0.4 I could add a string in the search field, press enter add another string to narrow down the search and so forth (A bit unwieldly but workable).
With 8.1.0 pressing enter now immediately clears the search field with Chrome and Edge (Windows),
Safari and Edge on an iPad continue to work the same way as with 8.0.4 for some reason, though.

**Comment by GK-774** [comment]
Firefox 90.0.1 (64bit Windows) same effect, "enter" clears the search field.

**Comment by jcorporation** [comment]
This could be a bad side effect of 40a131c

**Comment by jcorporation** [comment]
Bug should be fixed in devel. Pressing enter emits a click event to the clear button in some browsers. I moved the clear action to the mouseup event.
