### ISSUE TITLE
Jukebox mode: add whole albums

### ISSUE THREAD

**Issue by CultofRobots** [jcorporation/myMPD#57]
I would love the ability to randomly add whole albums instead of just single tracks while in jukebox mode either from the database or a playlist. It's a feature I use in [**mpd-sima**](https://kaliko.me/code/mpd-sima/) which automagically adds tracks or albums to the playlist based off of last.fm recomendations of the previous track. It's pretty much like having my own pandora. 

Thanks.

**Comment by jcorporation** [comment]
I like this feature request. I schedule following features for the jukebox mode in the 4.3.0 release:
- add whole albums
- maintain a configurable number of tracks in queue (for those people who like crossfading) 

last.fm recommendations are at the moment out of scope for myMPD. In the future a interface for last.fm  scrobbling and recommendations could be possible. But at the moment I focus in the development of non-cloud features.

**Comment by CultofRobots** [comment]
I wasn't suggesting last.fm recommendation integration. I was just using that feature of mpd-sima to explain why I was suggesting adding whole albums to jukebox mode. Having completely random, unrelated albums queue up in jukebox mode is actually preferable to me.

A configurable number of tracks in queue is a great idea as well. Nice addition. Thanks.

**Comment by jcorporation** [comment]
At the moment myMPD can add only whole albums from database, not from a playlist.
