### ISSUE TITLE
Clicking "between" the left menu buttons shows a Javascript error

### ISSUE THREAD

**Issue by edhelas** [jcorporation/myMPD#574]
myMPD version: [e.g. 8.1.1]

**Describe the bug**

See title

**To Reproduce**

Click on the space between the buttons in the left menu.
See the following error be notified:

    TypeError: cmd is null (https://edhelas.movim.eu/mympd/js/combined.js: 8)

**Comment by jcorporation** [comment]
Why do you click between icons? ;)

Fix was merged with commit bfa2140a4eb26b2cf5f4431f4cf314bf0e3de333.
