### ISSUE TITLE
Timers doesn't work, json error

### ISSUE THREAD

**Issue by thaihugo** [jcorporation/myMPD#575]
myMPD version: 8.1.1

Hello,

as a follow up to #569, any timer action does send an error in the log and do not execute. It wasn't working on 8.1.0 too.

the error in the log is:

`Oct 04 08:03:34 DietPi mympd[25948]: WARN mympdapi  Invalid json object type for JSON path "$.params.arguments": 0

 Oct 04 08:03:34 DietPi mympd[25948]: ERROR    mympdapi  Error processing method "MYMPD_API_SCRIPT_EXECUTE"`

this is on Dietpi on Raspberry pi 4

Thanks for your help
Thaihugo

**Comment by jcorporation** [comment]
The root cause was a incorrect internal api call. The new stricter json parser since 8.1.0 causes this issue. 

Should be now fixed, would you test?

**Comment by thaihugo** [comment]
It is working now. 
I'll open a last bug about an error message in the log probably related to json. This one is resolved. Thanks a lot.
