### ISSUE TITLE
Adding keyboard shortcuts

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPD#58]
**Context**
I use mpd on a remote server, and I alternatively command it with MyMPD or ncmpcpp.
I really like the keyboard shortcuts on ncmpcpp

**Solution**
Would you please consider adding keyboard shortcuts to mympd ?
I especially miss the "Tab" to switch between Browse and Queue/Playback

**Ncmpcpp keyboard shortcuts**
[https://pkgbuild.com/~jelle/ncmpcpp/](url)

**Comment by jcorporation** [comment]
Thanks for your feature request. 
There are already some keyboard shortcuts (the same as in ympd):
- cursor left: previous song
- cursor right: next song
- space: play / pause

Further shortcuts should be possible. But I think the "Tab" is not a good shortcut for a web application, because it breaks default browser behaviour.

**Comment by jcorporation** [comment]
Do you miss any other keyboard shortcuts?

**Comment by koflesinge** [comment]
Yes

- Browsing through tab (queue, playslist, library) with numbers. Like "1" for queue, "2" for playlist, ...

- What is really handy in ncmpcpp are the library shortcuts. 
+ "Up" and "Down" to move between items 
+ "Enter" to enter a sub-item (like to enter the Artist to see albums )
+ "Space" to queue an item ( either Folder, Artist, Albums, Song...)
+ "A" to add an item to a playlist

- Also "U" to update the mpd database

Thank you very much

**Comment by jcorporation** [comment]
The devel branch supports now navigation in all the tables with keyboard.
- n = start table navigation mode

In table navigation mode:
- n = focus next table
- p = focus previous table
- Enter = click event
- Space = popup menu
- x = add item to a playlist
- d = remove item from queue
- q = append item to queue
- Q = replace queue through item

The popup menus are now also keyboard accesible.
