### ISSUE TITLE
Volume: Volumecontrol disabled

### ISSUE THREAD

**Issue by tmyo** [jcorporation/myMPD#581]
It does not work with hardwear volume.
Thank you very much. 
(In alsamixser, it is recognized as a hardwear mixer and can operate.)

**Comment by jcorporation** [comment]
Can a other mpd client change the volume? Try `mpc volume 50`. 

If this works it is an myMPD issues else a bad mpd configuration.

If it is a myMPD issue, please use the bug template to post valid debug data.
