### ISSUE TITLE
SW/PWA doesn't work behind reverse proxy with path prefix

### ISSUE THREAD

**Issue by Warr1024** [jcorporation/myMPD#586]
myMPD version: 8.1.3

**Describe the bug**

When myMPD is running behind a reverse proxy with path prefix, (e.g. a /mympd/ that's stripped off by the proxy) then the service worker is not installed, and thus the PWA is not installable under Chrome.

**Potential fix**

I was able to make the app installable by just replacing the absolute paths hard-coded into client js with relative ones in line https://github.com/jcorporation/myMPD/blob/master/htdocs/js/mympd.js#L439, and I can submit a PR if this fix is acceptable.

**To Reproduce**

1. Using an nginx reverse proxy that strips off the path prefix:
```
  location ~ ^.*/mympd/(?<suburi>.*) {
    proxy_pass http://127.0.0.1:8081/$suburi$is_args$args;
    # ...;
  }
```
2. Open myMPD through the proxy in Chrome.

**Expected behavior**

1. Observe that myMPD interface works as expected.
2. Open webdev console and see no errors.
3. See the "Install myMPD..." option (NOT just "add to home screen" or "create shortcut") option in Chrome menu.

**Observed behavior**

1. Observe that myMPD interface works as expected.
2. Open webdev console and see errors trying to install ServiceWorker.
3. Do NOT see the "Install myMPD..." option (NOT just "add to home screen" or "create shortcut") option in Chrome menu.
4. In Chrome webdev Application tab, see that app is not installable because it does not have a working ServiceWorker.

**Server plattform (please complete the following information):**
 - OS: alpine 3.12.0 inside docker 20.10.5 inside raspbian 10
 - Plattform: ARM64 Ras Pi 3B+
 - MPD version: 0.21.11

**Client plattform (please complete the following information):**
 - Device: Macbook Pro 2019, ThinkPad T430, Pixel 4a
 - OS: OSX 11.6.1, Debian 10, Android 12
 - Browser Chrome/Chromium
 - Browser version Chrome 95, Chromium 90

**Comment by jcorporation** [comment]
Thanks for the finding! The js should use only relative paths. Would be fixed for the next minor release.

**Comment by jcorporation** [comment]
Should be fixed in the v8.2.0 branch. Can you test?

**Comment by Warr1024** [comment]
I couldn't get the v8.2.0 branch to load at all.  I got an error calling dispose on an undefined thing, added a null guard to it, but then now get an error about trying to get classList from undefined that I can't trace.  It seems like the js code doesn't work when initially loading the site, only if the page was already initialized.

**Comment by jcorporation** [comment]
Bug is also fixed in devel yoo can try this branch.

**Comment by Warr1024** [comment]
Tested in f50473df and it works.

**Comment by jcorporation** [comment]
Greate!
