### ISSUE TITLE
Web Notifications Broken

### ISSUE THREAD

**Issue by Warr1024** [jcorporation/myMPD#587]
myMPD version: 8.1.3

**Describe the bug**

The web notifications feature does not work.  Hitting the "Apply" button in the settings tab causes the checkbox for it to toggle on and off, but under no circumstances are web notifications used. Only on-page notifications work.

I have cobbled together a partial fix (code changes) for this that seems to work on Desktop, but I still haven't got it working on Android (seems to be a permissions issue).

**To Reproduce**

1. Make sure "notification" permission is allowed in browser settings.
2. Open myMPD web interface.
3. Open icon menu -> Settings -> Settings -> Notifications tab.
4. Check "Web notifications".
5. Hit Apply.

**Expected behavior**

1. Checkbox stays checked.
2. Notifications are delivered via Web Notification system (system-level notifications) instead of only on-page (i.e. you can receive notifications while myMPD is not visible).

**Observed behavior**

1. Checkbox toggles itself each time you hit the Apply button.
2. If you use Save, checkbox state is not saved and is set to some arbitrary state when the Settings tab is re-opened.
3. Regardless of the checkbox state, notifications are never delivered by Web Notifications at all.

**Server plattform (please complete the following information):**
 - OS: alpine 3.12.0 inside docker 20.10.5 inside raspbian 10, using an nginx reverse proxy
 - Plattform: ARM64 Ras Pi 3B+
 - MPD version: 0.21.11

**Client plattform (please complete the following information):**
  - Device: Macbook Pro 2019, ThinkPad T430, Pixel 4a
  - OS: OSX 11.6.1, Debian 10, Android 12
  - Browser Chrome/Chromium
  - Browser version Chrome 95, Chromium 90

**Comment by jcorporation** [comment]
Web notifications needs a webbrowser permission. The browser should ask for it, but I have tested this fears long time ago…

**Comment by Warr1024** [comment]
I seem to remember this feature worked correctly in v6.5.2 using the same browsers.

I think the "permission problem" that affects Mobile may be because permissions checks are stricter on Mobile (I don't have an "always allow" option, only an "ask" one, and Chrome tends to be very strict about *when* you can ask, i.e. it needs to be immediately during a user 'click' event for some permissions).

I can submit a PR with my partial fix for now, and maybe that would help.  The fact that I can get it to at least mostly work on Desktop at least proves that it's on the right track.

**Comment by jcorporation** [comment]
A PR is of course helpful. Please base the PR on the v8.2.0 branch. In this branch much parts of the javascript was reworked.

**Comment by jcorporation** [comment]
Is fixed in the v8.2.0 branch. Enabling the button should trigger the browser to ask for allowing the requested permission.
Works for me in Firefox.

**Comment by Warr1024** [comment]
I have not been able to get the v8.2.0 branch to work due to multiple errors with the js, and this fix doesn't seem to be merged into devel yet.

**Comment by jcorporation** [comment]
Right, this fix is not merged into devel. It can’t be easily merged because the implementation divers.
