### ISSUE TITLE
Radio in file .pls

### ISSUE THREAD

**Issue by antonellocaroli** [jcorporation/myMPD#588]
myMPD version: [8.1.3]

when I try to add a radio (saved in a .pls file) I get this error:
![image](https://user-images.githubusercontent.com/11161093/139537357-72e305b7-43c3-4155-a847-d98471a6ffd3.png)

premise that with cantata .pls files work....

**Comment by jcorporation** [comment]
This is a known bug fixed in the v8.2.0 branch. But thanks for reporting this.

**Comment by jcorporation** [comment]
My error it was fixed for an other API method.
