### ISSUE TITLE
MYMPD_API_PLAYER_VOLUME_SET doesn't work

### ISSUE THREAD

**Issue by cjohnsto-nz** [jcorporation/myMPD#592]
**Describe the bug**
MYMPD_API_PLAYER_VOLUME_SET doesn't work if using the example code.
![image](https://user-images.githubusercontent.com/21297202/139620928-318dea59-d95c-4c61-a9fa-77add0a54c48.png)

**To Reproduce**

Create a new script. Add MYMPD_API_PLAYER_VOLUME_SET from the API dropdown. return raw_result. Result returned is 
![image](https://user-images.githubusercontent.com/21297202/139620928-318dea59-d95c-4c61-a9fa-77add0a54c48.png)

**Expected behavior**
Expect the default code to set the player volume to 50. Does not work.

Ubuntu 20.04

**Comment by cjohnsto-nz** [comment]
Almost all of the script examples return a similar error actually.

**Comment by jcorporation** [comment]
Thanks for reporting this issue. The json parser in the backend is since 8.1.0 stricter. It seems all methods from the dropdown with numbers as values are not working.

I also noticed that the documentation is outdated.

Both will be fixed in the next patch release 8.1.4

**Comment by cjohnsto-nz** [comment]
Awesome :) Is there a format that would work in the meantime, or is the API completely broken for scripting?
________________________________

**Comment by jcorporation** [comment]
I think only the automatic generation of the command is broken. Look for the correct format in the api documentation.

**Comment by cjohnsto-nz** [comment]
The documentation doesn't really detail the format. Just the parameters.

https://jcorporation.github.io/myMPD/references/api/methods

I'm unsure specifically what needs to be changed about the numbers in order for the API to work.
________________________________

**Comment by jcorporation** [comment]
Numbers should be not in quotes.

**Comment by cjohnsto-nz** [comment]
The numbers don't appear to be in quotes. If I run the output of the json.encode to return, I get this.
![Screenshot_20211101-211246_Chrome~2](https://user-images.githubusercontent.com/21297202/139641889-99167182-5ec8-468e-a383-2f79ccf5d5a3.jpg)
What about this does the parser not like?

¯\_(ツ)_/¯

**Comment by jcorporation** [comment]
Hm, this snippet looks good. I need the complete script and the debug log of myMPD.

**Comment by cjohnsto-nz** [comment]
That script was basically just the standard PLAYER SEEK example from the drop-down

`rc, raw_result = mympd_api_raw("MYMPD_API_PLAYER_SEEK_CURRENT", json.encode({seek =  2, relative =  true}))
if rc == 0 then
    result = json.decode(raw_result)
end
test = json.encode({seek =  2, relative =  true})

return test`

I can get you logs shortly, but can you see anything wrong with this in the meantime?

**Comment by jcorporation** [comment]
The script looks good.

**Comment by cjohnsto-nz** [comment]
![image](https://user-images.githubusercontent.com/21297202/139658487-dcc373a9-0f9e-4b24-b31b-61f2b6ef04d8.png)
Any ideas?

**Comment by cjohnsto-nz** [comment]
Double squiggly brackets. Not sure why it's wrapping the json in another set. I just got rid of all of the brackets and it works fine. It definitely seems like it's adding an extra set of squigglies for most api requests.
![image](https://user-images.githubusercontent.com/21297202/139659225-49b3332d-db59-4a1a-b105-193770e63465.png)

**Comment by jcorporation** [comment]
Is now fixed in devel.
