### ISSUE TITLE
a suggestion for improvements in search

### ISSUE THREAD

**Issue by archphile** [jcorporation/myMPD#6]
**Is your feature request related to a problem? Please describe.**

This is obviously a feature request and not an issue. Having been using ympd for years (which is the base of myMPD), I always found search results one of the weakest points of this client.

**Describe the solution you'd like**

Let's say that I search for "Radiohead". 

The current results will be all Radiohead songs in a list where I can choose which ones to add in queue. This is ok, but it would be really nice if I could add the whole album that the track belongs to.  For example using an icon on the right side ( named ex. "add whole album") of one track the user could have the option to add a whole album and not only the track itself.

**Describe alternatives you've considered**

The ideal search in my opinion should be based in tags. It would be perfect If I wanted to search for Artists, and I got results for all their albums or search for albums etc.. 

**Additional context**

I know it's much easier to ask others to write code for something you want than writing it yourself (unfortunately I am not a coder btw.). I don't want to be this guy. I just want to share some ideas with you. If you don't like my suggestions, please ignore me.

Thanking you in advance,

Mike

**Comment by jcorporation** [comment]
Thanks for your future request. I think your described alternative is the best idea. I must deep dive in the mpdclient api, if this is possible. In my browse-view-rewrite branch selecting tags are already supported for search. But the searchresults are displayed as so far.

For my ideas for database browse I need similar features.

**Comment by archphile** [comment]
Thanks for your reply. 

I totally agree that tagged search is the best option. However an additional enhancement, similar to my first idea and I assume much simpler, would be album directories to appear in search results. This way we have the option to add a track or a whole directory like when browsing the library.

Regards,

Mike

**Comment by jcorporation** [comment]
I have implemented another feature that is similar to your feature request. In search you can select album and in the Song list there is a add all button. These changes are in the browse-view-rewrite branch.

**Comment by archphile** [comment]
Hi jcorp,

I just built it and tested it. It works like a charm.

Thanks!

**Comment by jcorporation** [comment]
Does this feature resolve your feature request?

**Comment by archphile** [comment]
Yes, 
thanks, I forgot to close it.

Greetings,
Mike
