### ISSUE TITLE
Since 8.1.4 Albumview is not working anymore

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#601]
Since the update to 8.1.4 I have a problem with the Album view:

Sorted by "Last modified" Descending gives:
"Validation of value for JSON path "$.params.sort" has failed"

Changing sort to "Artist" results in
"Albumcache not ready"

and the album cache never gets ready. (Not after half an hour, normally takes a minute or so). "Clear app cache and reload" did not change anything.

Tested on two different machines (one CentOS7 and one CentOS8), downgrading
to 8.1.3 solved the issue immediately.

**Comment by jcorporation** [comment]
The validation accepts now Last-Modified and LastModified. v8.2.0 will only use LastModified.
Fix is now in devel.

I can not reproduce the albumcache not ready error. Please test latest devel and provide debug logs of myMPD.

**Comment by GK-774** [comment]
[mympd-8.1.5_log_debug_1.txt.zip](https://github.com/jcorporation/myMPD/files/7483614/mympd-8.1.5_log_debug_1.txt.zip)
[mympd-8.1.5_log_debug_2.txt.zip](https://github.com/jcorporation/myMPD/files/7483618/mympd-8.1.5_log_debug_2.txt.zip)


With the latest devel (8.1.5) the errors are gone (I have nevertheless attached the logs),
everything works as expected in a quick test now.
For Last-Modified vs LastModified, I did not choose that deliberatly, "Last-Modified" is what gets sent when I click the Last Modified button, no?
"Albumcache not ready" I do not get anymore, but if still required I can capture logs from 8.1.4 this evening.
Many thanks!

**Comment by jcorporation** [comment]
Not required but logs would be interesting.

**Comment by GK-774** [comment]
[mympd-8.1.4_debug_log.txt.gz](https://github.com/jcorporation/myMPD/files/7488168/mympd-8.1.4_debug_log.txt.gz)

I could not reproduce "Albumcache not ready" with 8.1.4 again when switching the view this time.
Anyway, here is the log for 8.1.4, (much of it is just building the album cache, I made sure to wait until it is finished) the actual "action" starts at about Nov 05 18:58:33 (Line 4229).
8.1.5 works just fine. Thanks!
