### ISSUE TITLE
Questions about "Jukebox" mode

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#602]
myMPD version: 8.1.5 (devel from 6.11.)

So wanted to try Jukebox which I have not used before, clicked "Jukebox" to change the view from "Queue" and got "Jukebox is disabled".
Traversed through the settings but "Jukebox" is nowhere mentioned. The documentation is rather quiet about it, so this are my questions:

What is it supposed to do? (Compared to a "hardware" jukebox adding a song to the queue already does the same, without insering a coin of course.)

Where would one enable it, to give it a try?

If it is disabled, would it not make sense to hide the "Jukebox" button as well?

Sorry for the inconvenience, but I really could not figure out how this supposed to work.

**Comment by GK-774** [comment]
Oh, sorry - my fault. It´s in the playback settings.

**Comment by jcorporation** [comment]
Please ask questions under discussion not in issues.
