### ISSUE TITLE
Save Queue: invalid filename

### ISSUE THREAD

**Issue by tatoosh** [jcorporation/myMPD#61]
I am using mympd in v4,2 which comes with the raspberry pi image from https://dietpi.com/.

Saving the playlists throws the error "invalid filename".

![image](https://user-images.githubusercontent.com/3670907/46209336-e5bb4480-c32d-11e8-9aa1-7ca66aa5d525.png)

**Comment by Emilot** [comment]
and there is no error in web-tools.

**Comment by jcorporation** [comment]
Bug fixed in latest devel.
