### ISSUE TITLE
Turning off "Genre"-based intelligent playlists doesn't take

### ISSUE THREAD

**Issue by smurfix** [jcorporation/myMPD#619]
myMPD version: 8.1.6

**Describe the bug**

I want automatic playlists for most-played songs etc., but I don't want playlists for genres or whatever.

Unfortunately, when I turn off Genre playlists and restart mympd, the flag is back on.

**To Reproduce**

1. Settings > intelligent playlists, turn them on, uncheck "Genre"
2. Save
3. Restart mympd
4. as step 1; observe "Genre" is back on

**Expected behavior**

"Genre" stays turned off.

**Comment by jcorporation** [comment]
Any errors in the myMPD log? Please attach debug output.

**Comment by smurfix** [comment]
I haven't logged that as it should be reproducible very easily.
