### ISSUE TITLE
Support embedded album covers

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#62]
I'm using the prebuilt package for Ubuntu 18.04 at openSUSE Build Service.
It looks promising.
Is it possible to show the embedded album covers as well as external ones?

**Comment by jcorporation** [comment]
Thanks.
This feature could be possible, if there is a c library that implement reading embedded album covers.
At the moment myMPD don't read tags directly, it uses only the mpd protocol to access tags.

**Comment by parkmino** [comment]
No way to test it on my side.
Because I gave up mympd due to tag issues.

**Comment by parkmino** [comment]
Reopen it now that tag issues are resolved at mympd 4.5.0.

**Comment by jcorporation** [comment]
Feature is now in devel. Further testing is required.

**Comment by jcorporation** [comment]
Feature is now in master. I close now this issue. If a problem occurs with embedded coverimages don't hesitate to reopen this issue or create a new one.

**Comment by parkmino** [comment]
Thansk for your support!

**Comment by parkmino** [comment]
myMPD is updated and the coverextract plugin is enabled.
I see the extracted cover in the music folder, however, the embedded cover does not show.
Is metadata necessary to show the embedded covers? I do not see any other reason.
For your information, Cantata shows the embedded covers without metadata and extracting covers.

**Comment by jcorporation** [comment]
No metadata is needed for the coverextract feature. Can you set loglevel to debug and send me the output?

**Comment by parkmino** [comment]
sudo mympd /etc/mympd/mympd.conf
INFO     Starting myMPD 5.2.0
INFO     Libmpdclient 2.11.0
INFO     Mongoose 6.14
INFO     Parsing config file: /etc/mympd/mympd.conf
INFO     Setting loglevel to DEBUG
INFO     /usr/src/packages/BUILD/src/main.c:249: Loading plugin /usr/share/mympd/lib/libmympd_coverextract.so
WARN     /usr/src/packages/BUILD/src/main.c:378: Not connected to socket, setting music_directory to /var/lib/mpd/music
INFO     /usr/src/packages/BUILD/src/web_server.c:84: Listening on http port 80
INFO     /usr/src/packages/BUILD/src/main.c:399: Droping privileges to mympd
INFO     /usr/src/packages/BUILD/src/global.c:43: Document root: "/usr/share/mympd/htdocs"
INFO     /usr/src/packages/BUILD/src/global.c:43: Temp dir: "/var/lib/mympd/tmp"
INFO     /usr/src/packages/BUILD/src/global.c:43: Smartpls dir: "/var/lib/mympd/smartpls"
INFO     /usr/src/packages/BUILD/src/global.c:43: State dir: "/var/lib/mympd/state"
INFO     /usr/src/packages/BUILD/src/global.c:43: Covercache dir: "/var/lib/mympd/covercache"
INFO     /usr/src/packages/BUILD/src/global.c:43: Syscmds directory: "/etc/mympd/syscmds"
INFO     /usr/src/packages/BUILD/src/mpd_client.c:235: Reading last played songs: 20
INFO     /usr/src/packages/BUILD/src/mpd_client.c:1269: MPD Connecting to 127.0.0.1:6600
INFO     /usr/src/packages/BUILD/src/mympd_api.c:375: Reading states
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State notificationWeb: false
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State notificationPage: true
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State autoPlay: false
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State jukeboxMode: 0
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State jukeboxPlaylist: Database
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State jukeboxQueueLength: 1
INFO     /usr/src/packages/BUILD/src/mpd_client.c:1300: MPD connected
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:946: Push websocket notify to queue: {"type": "mpd_connected"}
INFO     /usr/src/packages/BUILD/src/mpd_client.c:1067: MPD protocoll version: 0.21.4
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State colsQueueCurrent: ["Pos","Title","Artist","Album","Duration"]
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State colsSearch: ["Title","Artist","Album","Duration"]
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State colsBrowseDatabase: ["Track","Title","Duration"]
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State colsBrowsePlaylistsDetail: ["Pos","Title","Artist","Album","Duration"]
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State colsBrowseFilesystem: ["Type","Title","Artist","Album","Duration"]
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State colsPlayback: ["Artist","Album","Genre"]
DEBUG    /usr/src/packages/BUILD/src/mympd_api.c:411: State colsQueueLastPlayed: ["Pos","Title","Artist","Album","LastPlayed"]
INFO     /usr/src/packages/BUILD/src/mympd_api.c:306: Reading syscmds: /etc/mympd/syscmds
WARN     /usr/src/packages/BUILD/src/mpd_client.c:1098: Stickers are disabled, disabling smart playlists
WARN     /usr/src/packages/BUILD/src/mpd_client.c:1102: Playlists are disabled, disabling smart playlists
INFO     /usr/src/packages/BUILD/src/global.c:43: MPD music_directory: "/var/lib/mpd/music"
INFO     /usr/src/packages/BUILD/src/mpd_client.c:1140: Enabling featLibrary support
INFO     /usr/src/packages/BUILD/src/mpd_client.c:1185: MPD supported tags: none
INFO     /usr/src/packages/BUILD/src/mpd_client.c:1186: Tags are disabled
WARN     /usr/src/packages/BUILD/src/mpd_client.c:1251: Disabling advanced search, depends on mpd >= 0.21.0 and libmpdclient >= 2.17.0.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (-1): {"cmd":"MYMPD_API_SETTINGS_SET", "data":{"jukeboxMode": 0, "jukeboxPlaylist": "Database", "jukeboxQueueLength": 1}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:144: Setting music_directory to /var/lib/mpd/music
DEBUG    /usr/src/packages/BUILD/src/web_server.c:150: Setting rewrite_patterns to /pics/=/var/lib/mympd/pics,/library/=/var/lib/mpd/music
DEBUG    /usr/src/packages/BUILD/src/web_server.c:233: New connection id 2
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:238: New websocket request (2): /ws
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:247: New Websocket connection established (2)
DEBUG    /usr/src/packages/BUILD/src/web_server.c:233: New connection id 3
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (3): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (3): {"cmd":"MPD_API_QUEUE_LIST","data":{"offset":0}}
DEBUG    /usr/src/packages/BUILD/src/web_server.c:233: New connection id 4
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (3): {"cmd":"MPD_API_QUEUE_LIST","data":{"offset":0}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 3: {"type": "queue", "data": [], "totalTime": 0, "totalEntities": 0, "offset": 0, "returnedEntities": 0, "queue_version": 16}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 3: {"type": "queue", "data": [], "totalTime": 0, "totalEntities": 0, "offset": 0, "returnedEntities": 0, "queue_version": 16}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "update_state", "data": {"state": 1, "volume": -1, "songPos": -1, "elapsedTime": 0, "totalTime": 0, "currentSongId": -1, "kbitrate": 0, "audioFormat": { "sampleRate": 0, "bits": 0, "channels": 0}, "queueLength": 0, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 16}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "update_state", "data": {"state": 1, "volume": -1, "songPos": -1, "elapsedTime": 0, "totalTime": 0, "currentSongId": -1, "kbitrate": 0, "audioFormat": { "sampleRate": 0, "bits": 0, "channels": 0}, "queueLength": 0, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 16}}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "update_state", "data": {"state": 1, "volume": -1, "songPos": -1, "elapsedTime": 0, "totalTime": 0, "currentSongId": -1, "kbitrate": 0, "audioFormat": { "sampleRate": 0, "bits": 0, "channels": 0}, "queueLength": 0, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 16}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "update_state", "data": {"state": 1, "volume": -1, "songPos": -1, "elapsedTime": 0, "totalTime": 0, "currentSongId": -1, "kbitrate": 0, "audioFormat": { "sampleRate": 0, "bits": 0, "channels": 0}, "queueLength": 0, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 16}}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_DATABASE_FILESYSTEM_LIST","data":{"offset":0,"path":"이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4","filter":"-"}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_DATABASE_FILESYSTEM_LIST","data":{"offset":0,"path":"이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4","filter":"-"}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "browse", "data": [{"Type": "song", "Title": "이진아 - Always with us (Inspired by `파랑`).mp3", "Duration": 194, "uri": "이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}], "totalEntities": 1, "offset": 0, "returnedEntities": 1, "filter": "-"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "browse", "data": [{"Type": "song", "Title": "이진아 - Always with us (Inspired by `파랑`).mp3", "Duration": 194, "uri": "이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}], "totalEntities": 1, "offset": 0, "returnedEntities": 1, "filter": "-"}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_QUEUE_ADD_TRACK","data":{"uri":"이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_QUEUE_ADD_TRACK","data":{"uri":"이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "result", "data": "ok"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1362: Checking for idle events
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:964: MPD idle event: playlist
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:946: Push websocket notify to queue: {"type": "update_queue"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "result", "data": "ok"}
DEBUG    /usr/src/packages/BUILD/src/web_server.c:184: Sending notify to conn_id 2: {"type": "update_queue"}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "update_state", "data": {"state": 1, "volume": -1, "songPos": -1, "elapsedTime": 0, "totalTime": 0, "currentSongId": -1, "kbitrate": 0, "audioFormat": { "sampleRate": 0, "bits": 0, "channels": 0}, "queueLength": 1, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 17}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "update_state", "data": {"state": 1, "volume": -1, "songPos": -1, "elapsedTime": 0, "totalTime": 0, "currentSongId": -1, "kbitrate": 0, "audioFormat": { "sampleRate": 0, "bits": 0, "channels": 0}, "queueLength": 1, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 17}}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_CURRENT_SONG"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_CURRENT_SONG"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "result", "data": "ok"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "result", "data": "ok"}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_PLAY"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_PLAY"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "result", "data": "ok"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1362: Checking for idle events
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:964: MPD idle event: player
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "result", "data": "ok"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:946: Push websocket notify to queue: {"type": "update_state", "data": {"state": 2, "volume": -1, "songPos": 0, "elapsedTime": 1, "totalTime": 194, "currentSongId": 9, "kbitrate": 320, "audioFormat": { "sampleRate": 44100, "bits": 16, "channels": 2}, "queueLength": 1, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 17}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:184: Sending notify to conn_id 2: {"type": "update_state", "data": {"state": 2, "volume": -1, "songPos": 0, "elapsedTime": 1, "totalTime": 194, "currentSongId": 9, "kbitrate": 320, "audioFormat": { "sampleRate": 44100, "bits": 16, "channels": 2}, "queueLength": 1, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 17}}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_CURRENT_SONG"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_CURRENT_SONG"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "song_change", "data": {"pos": 0, "currentSongId": 9, "cover": "/assets/coverimage-notavailable.png", "Title": "이진아 - Always with us (Inspired by `파랑`).mp3", "Duration": 194, "uri": "이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "song_change", "data": {"pos": 0, "currentSongId": 9, "cover": "/assets/coverimage-notavailable.png", "Title": "이진아 - Always with us (Inspired by `파랑`).mp3", "Duration": 194, "uri": "이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_CURRENT_SONG"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_CURRENT_SONG"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "song_change", "data": {"pos": 0, "currentSongId": 9, "cover": "/assets/coverimage-notavailable.png", "Title": "이진아 - Always with us (Inspired by `파랑`).mp3", "Duration": 194, "uri": "이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "song_change", "data": {"pos": 0, "currentSongId": 9, "cover": "/assets/coverimage-notavailable.png", "Title": "이진아 - Always with us (Inspired by `파랑`).mp3", "Duration": 194, "uri": "이진아 - Weather - 오늘 당신의 날씨는 어떤가요 Part.4/이진아 - Always with us (Inspired by `파랑`).mp3"}}
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:255: HTTP request (4): /api
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:368: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1354: Leaving mpd idle mode.
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1371: Handle request
VERBOSE  /usr/src/packages/BUILD/src/mpd_client.c:263: API request (4): {"cmd":"MPD_API_PLAYER_STATE"}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:936: Push response to queue for connection 4: {"type": "update_state", "data": {"state": 2, "volume": -1, "songPos": 0, "elapsedTime": 14, "totalTime": 194, "currentSongId": 9, "kbitrate": 320, "audioFormat": { "sampleRate": 44100, "bits": 16, "channels": 2}, "queueLength": 1, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 17}}
DEBUG    /usr/src/packages/BUILD/src/mpd_client.c:1377: Entering mpd idle mode
DEBUG    /usr/src/packages/BUILD/src/web_server.c:201: Sending response to conn_id 4: {"type": "update_state", "data": {"state": 2, "volume": -1, "songPos": 0, "elapsedTime": 14, "totalTime": 194, "currentSongId": 9, "kbitrate": 320, "audioFormat": { "sampleRate": 44100, "bits": 16, "channels": 2}, "queueLength": 1, "nextSongPos": -1, "nextSongId": -1, "lastSongId": -1, "queueVersion": 17}}
^CVERBOSE  /usr/src/packages/BUILD/src/web_server.c:326: HTTP connection 4 closed
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:326: HTTP connection 3 closed
VERBOSE  /usr/src/packages/BUILD/src/web_server.c:326: HTTP connection 2 closed
free(): invalid pointer

**Comment by parkmino** [comment]
Hm... flac shows the embedded cover but not for mp3.
Could you please advise?

**Comment by jcorporation** [comment]
I can reproduce this issue with special german characters in filenames.
It was a locale issue with mediainfo. I fixed it accordingly to https://github.com/MediaArea/MediaInfo/issues/134.

Please compile from master and give it a try.

**Comment by parkmino** [comment]
Yeah, embedded covers generates in /var/lib/mympd/covercache/ and shows fine!
