### ISSUE TITLE
Update smart playlists produces error "Invalid API request"

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#628]
### Discussed in https://github.com/jcorporation/myMPD/discussions/627

<div type='discussions-op-text'>

<sup>Originally posted by **avalx** December 10, 2021</sup>
Every time I try to do: Main menu -> Update -> Update smart playlists I get an error popup as mentioned above.  The same happens if I go into Settings ->Maintenance -> Force Update. I've checked the mpd log but there is nothing about this. I have Genre based smartlists enabled and they are populated with the songs and I can add them to the queue. So I'm  wondering  what this error might mean, any ideas?

BTW, just discovered myMPD and so far I like it very much!</div>

**Comment by vernonjvs** [comment]
Thanks, Confirmed fixed in myMPD development branch
