### ISSUE TITLE
Playlist select for start play timer is empty

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#632]
With regard to Timer->Start Playback, I get the following warning and different Error message in the 8.2 development branch when I click on the Playlist->Database drop down and I now don't see any playlists. Please note that this is a different error message from the one I preciously reported in 8.1.6. where the Playlist->Database drop down did show playlists.
 ```
17:23:27 WARN     mympdapi  JSON path "$.params.limit" not found
17:23:27 ERROR    mympdapi  Error processing method "MYMPD_API_PLAYLIST_LIST"

```
Thanks for all your incredibly fast responses. They are much appreciated.

_Originally posted by @vernonjvs in https://github.com/jcorporation/myMPD/discussions/624#discussioncomment-1789098_

**Comment by jcorporation** [comment]
I can not reproduce your issue, please attach debug logs of myMPD

**Comment by vernonjvs** [comment]
Please see attached

**Comment by jcorporation** [comment]
The limit parameter is present, but it is type of string not number. Commit 0001cc6 sets the right default type and enforces the number type.

Please test again.

**Comment by vernonjvs** [comment]
Yes, I am pleased to confirm that with your fix in the development build, I can now see the playlists and set start and stop timers. Vielen Dank!

My use cases are as follows:
I have a Raspberry Pi Zero W with a $10 USB sound card connected to the AUX port of an old Bose Wave Radio on my nightstand. With the myMPD Timer functions, I can now easily set Stop playback events which act as a Sleep timer and Start playback events which act as an alarm clock. Thanks very very much.

In addition, have a bash script which will read my Bluetooth headphone button presses and issue the appropriate mpc play, pause, next or prev command.
