### ISSUE TITLE
Albumart for streams is no longer displayed

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#633]
myMPD 8.2.0
mpd 0.23.5
CentOS 8.5.2111

This is an example for a stream I have (among others) saved as playlist:
http://orf-live.ors-shoutcast.at/oe1-q2a

In /var/lib/mympd/pics I have for this stream:
orf-live_ors-shoutcast_at_oe1-q2a.jpg

with myMPD 8.2.0 checked out on Dec. 9th the picture (station logo) is displayed as expected and the URL ("Copy Image Link" in the browser) is:
http://192.168.0.2/albumart/http://orf-live.ors-shoutcast.at/oe1-q2a

with myMPD 8.2.0 checked out on Dec. 11th the generic green radio logo is displayed and the URL is:
http://192.168.0.2/albumart/http%3a//orf-live.ors-shoutcast.at/oe1-q2a

**Comment by jcorporation** [comment]
With commit 664490a8773fc0d73d9b61644479a5ae045d92ad the way how the image name is calculated has changed: https://github.com/jcorporation/myMPD/blob/devel/docs/references/pictures.md

**Comment by GK-774** [comment]
Sorry for the inconvenience, I overlooked that change. Yes http___orf-live_ors-shoutcast_at_oe1-q2a.jpg works as expected.
