### ISSUE TITLE
Startup error mpd connection not working

### ISSUE THREAD

**Issue by john-** [jcorporation/myMPD#64]
**Describe the bug**
I just now undated to most recent version in git and when I access the myMPD user interface I can't browse my music and no information is shown for my running mpd.
When I start at the command line I see this:
sudo ./mympd /etc/mympd/mympd.conf
Parsing config file: /etc/mympd/mympd.conf
Starting myMPD 4.3.0
Document root: /usr/share/mympd/htdocs
Error opening /var/lib/mympd/state/notificationWebError opening /var/lib/mympd/state/notificationPageError opening /var/lib/mympd/state/jukeboxModeError opening /var/lib/mympd/state/jukeboxPlaylistError opening /var/lib/mympd/state/jukeboxQueueLengthDroping privileges to nobody
Listening on http port 8081
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Error opening /var/lib/mympd/tmp/playlist.tmpMPD X: Cannot send a new command while receiving another response
MPD X: Cannot send a new command while receiving another response

There is nothing further even when I navigate through myMPD screens.

**To Reproduce**
1. Compile latest code from git
2. Changed nothing else in my system
3. Build and run mympd

**Desktop (please complete the following information):**
 - OS: 3.16.57-1-ARCH #1 SMP PREEMPT Fri Aug 31 20:51:33 MDT 2018 aarch64 GNU/Linux
 - Browser: Firefox
 - Version  myMPD 4.3.0 / mpd 0.20.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by john-** [comment]
I went back to myMPD 4.3.0 and it worked.    It looks that version updated how systemd loads myMPD and I had to fix a couple things in /etc/mympd/options before it would start.

I will try and work through versions to see what changed that broke things (or what brought out something not right in my system).

**Comment by jcorporation** [comment]
hi john,

/etc/mympd/options are not used anymore. All configuration is done through /etc/mympd/mympd.conf.
The first errors (opening /var/lib/mympd/state/*) can be safely ignored. myMPD uses default values, if they are not found. Saveing the settings once in the gui should remove this errors. In the next version the install script would install default files in this directory.

The error "Error opening /var/lib/mympd/tmp/playlist.tmp" seems the problem. Exists the directory /var/lib/mympd/tmp/ and myMPD has the rights to write to it?

**Comment by john-** [comment]
Thanks.  myMPD did not have permissions so I changed it to this:

drwxrwxr-x 2 nobody mympd 4096 Oct  7 16:26 /var/lib/mympd/tmp

Previously it was owned by mympd and group was r-w.

This got things to go farther.   See below for full log which shows a retry of some sort that ends in a seg fault.

However, I am not sure what user/permissions should be in general.

My /etc/mympd/mympd.conf has this:

#myMPD user
user nobody

The log below shows this being used when accessing some files.

However from how some files files are installed they are owned by "mympd".   For example, /var/lib/mympd/tmp was owned by mympd until I changed it.

Before I start changing things further it probably makes sense that I get that understanding first.


sudo ./mympd /etc/mympd/mympd.conf
Parsing config file: /etc/mympd/mympd.conf
Starting myMPD 4.3.0
Document root: /usr/share/mympd/htdocs
Error opening /var/lib/mympd/state/notificationWebError opening /var/lib/mympd/state/notificationPageError opening /var/lib/mympd/state/jukeboxModeError opening /var/lib/mympd/state/jukeboxPlaylistError opening /var/lib/mympd/state/jukeboxQueueLengthDroping privileges to nobody
Listening on http port 8081
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
MPD connection failed.
zsh: segmentation fault  sudo ./mympd /etc/mympd/mympd.conf

**Comment by jcorporation** [comment]
All directories and files under /var/lib/mympd must be writeable by your mympd user.
```chown -R nobody /var/lib/mympd``` should do the trick.

```
MPD X: Connection closed by the server
Updated myMPDsmart-newestSongs with 0 songs, minValue: -604800
```
It seems that myMPD can't get the last-modified value from songs in your database.
I think it was a bug in querying the database. In devel I fixed this, by testing of the returned entity type. Can you test it again?

**Comment by john-** [comment]
git log
commit dab83d0e5e63a3e7dcd96287e1967f2362f7d712 (HEAD -> devel, origin/devel)
Author: jcorporation <snip>
Date:   Sun Oct 7 23:21:44 2018 +0100

    Fix: test of entity type in mympd_smartpls_update_newest

Installing this version seemed to change my perms...so:

sudo chown -R nobody /var/lib/mympd

Results are different with this version (emphasis added on first error occurrence):

sudo ./mympd /etc/mympd/mympd.conf

[snip a bunch of repeated attempts;   leave some in]

MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
**Error updating myMPDsmart-newestSongs**
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Error updating myMPDsmart-newestSongs
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Error updating myMPDsmart-newestSongs
MPD connection failed.
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
MPD X: Connection closed by the server
Error updating myMPDsmart-newestSongs
MPD connection failed.
zsh: segmentation fault  sudo ./mympd /etc/mympd/mympd.conf

**Comment by jcorporation** [comment]
Can you run mpd with verbose logging enabled and post the messages of mpd.log?

**Comment by john-** [comment]
Attached is from the  first (and only time) I attempted to start myMPD after starting mpd:

[mpd.log](https://github.com/jcorporation/myMPD/files/2454468/mpd.log)

**Comment by jcorporation** [comment]
The error in the log file is:
```
Oct 07 18:53 : client: [1] process command "listallinfo "/""
Oct 07 18:53 : exception: error on client 1: Output buffer is full
```
myMPD is iterating through all songs to find the last-modified songs. It seems this doesn't work on very large databases.

myMPD 4.3.1 will use a better approach to find the newest songs in database. In the meanwhile you can delete ```/var/lib/mympd/smartpls/myMPDsmart-newestSongs``` to use myMPD.

Hopefully myMPD 4.3.1 will be released in this week.

**Comment by jcorporation** [comment]
The last commit should fixes your issue. Please reopen this issue, if not.

**Comment by john-** [comment]
That fixed it...thanks!

Here is the startup:

sudo ./mympd /etc/mympd/mympd.conf
Parsing config file: /etc/mympd/mympd.conf
Starting myMPD 4.3.1
Droping privileges to nobody
Document root: "/usr/share/mympd/htdocs"
Temp dir: "/var/lib/mympd/tmp"
Smartpls dir: "/var/lib/mympd/smartpls"
State dir: "/var/lib/mympd/state"
Reading states
Listening on http port 8081
MPD Connecting to 127.0.0.1:6600
MPD connected.
MPD protocoll version: 0.20.0
MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date Composer Performer Disc MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID 
myMPD enabled tags: Artist Album AlbumArtist Title Track Genre Date Composer Performer 
Updated myMPDsmart-mostPlayed with 22 songs, minValue: 2
Updated myMPDsmart-bestRated with 2 songs, minValue: 2
Updated myMPDsmart-newestSongs
