### ISSUE TITLE
Debian 11 .deb dependency issue

### ISSUE THREAD

**Issue by DarkVirtue** [jcorporation/myMPD#645]
myMPD version: 9.0.0

**Describe the bug**

Attempting to install from the .deb file from https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/amd64/ fails with 

```
The following packages have unmet dependencies:
 mympd : Depends: libpcre2 but it is not installable
```

Installers for previous versions worked fine and my system is currently running 8.1.6.

**To Reproduce**

1. On Debian 11 (Bullseye)
2. Download the .deb from  https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/amd64/ 
3. `sudo apt install ./mympd_9.0.0-1_amd64.deb`
4. Get dependency error regarding "libpcre2"

**Expected behavior**

I would expect the already-installed libpcre2-8-0 package to be sufficient for the dependency, or perhaps one of the available packages like libpcre2-posix2, libpcre2-16-0, or libpcre2-32-0.

**Server plattform (please complete the following information):**
 - OS: Debian
 - OS version 11
 - Plattform: x64
 - MPD version: 0.22.4

**Comment by jcorporation** [comment]
libpcre2-8 is the correct dependency.

#642
