### ISSUE TITLE
Cant use finger touch to start playing an entry  in the Queue

### ISSUE THREAD

**Issue by vernonjvs** [jcorporation/myMPD#648]
For latest development build, you can't use a finger touch on an entry in the queue to start playing that  entry in the queue. Basically, on the iphone, you have no way start an entry in the queue. Works fine with mouse on desktop browser. Last verified working in v7.02.

**Comment by jcorporation** [comment]
Is now fixed in devel. This bug is not iPhone or touch specific, but exists in the special queue view for small displays.

**Comment by vernonjvs** [comment]
Confirmed fixed. Thanks very much!!
