### ISSUE TITLE
myMPD does not display Extended Playlist Information

### ISSUE THREAD

**Issue by vernonjvs** [jcorporation/myMPD#650]
myMPD version: Latest Development

**Describe the bug**
myMPD displays URL instead of Extended Playlist Information in the Queue

**To Reproduce**
Create file /var/lib/mpd/playlists/Radio.m3u with the following contents
```
#EXTM3U
#EXTINF:-1,KEXP
https://kexp-mp3-128.streamguys1.com/kexp128.mp3
#EXTINF:-1,WFUV
https://onair.wfuv.org/onair-hi
#EXTINF:-1,No Agenda Stream
http://listen.noagendastream.com/noagenda
#EXTINF:-1,Progressive Radio Network
http://216.55.165.146:8000/;?type=http&nocache=51274
#EXTINF:-1,WQXR
http://stream.wqxr.org/wqxr

```

Load playlist Radio.m3u with myMPD. The Queue displays the URL information.

![myMPD-playlist](https://user-images.githubusercontent.com/46764043/147299194-288b5baa-0279-49cb-ac54-7917366e15a7.jpg)

mpc correctly displays the extended playlist information

```
$ mpc playlist
KEXP
WFUV
No Agenda Stream
Progressive Radio Network
WQXR

```
This didn't work correctly in ympd either.

Thanks very much for all your bug fixes and enhancements. The Queue progress bar is a very nice touch..

**Comment by jcorporation** [comment]
Already reported in #329. myMPD needs a small fix to fallback from Title to Name to Filename tags and the Name tag must be enabled.

**Comment by jcorporation** [comment]
Is implemented in the v9.1.0 branch (next feature release).

**Comment by vernonjvs** [comment]
> Is implemented in the v9.1.0 branch (next feature release).

Built v9.1.0 and I don't see this feature implemented.

```
$ git clone https://github.com/jcorporation/myMPD.git
$ cd myMPD/
$ git checkout v9.1.0
$ ./build.sh release
$ sudo su
# ./build.sh install
```

**Comment by jcorporation** [comment]
Have you enabled the Name tag in myMPD?

**Comment by vernonjvs** [comment]
> Have you enabled the Name tag in myMPD?

No I did not. Thanks very much for for the tip. I can confirm that Extended Playlist Information is displayed in the Queue when the Name tag is turned turned on. 

Why is displaying Extended Playlist Information not the default behavior? Thanks.

**Comment by jcorporation** [comment]
The display is handled by a generic tag handling function.
