### ISSUE TITLE
Sync lyrics tab only showing only one line of the synced lyrics

### ISSUE THREAD

**Issue by ddonindia** [jcorporation/myMPD#651]
myMPD version: master/devel branch

**Describe the bug**

Sync lyrics tab only showing only one line of the synced lyrics. Normal lyrics works fine.

**To Reproduce**

Steps to reproduce the behaviour:
1. Play some song with sync lyrics(external lyrics file) and embedded non synced lyrics
1. Go to 'Playback'
2. Click on 'Lyrics'

**Expected behavior**

Synced lyrics should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/16450468/147500769-ea564d4a-50bc-48ff-afa2-b868a115dc7c.png)
![image](https://user-images.githubusercontent.com/16450468/147500801-a903f694-ff9b-4b23-be38-c4ab18567361.png)

**Server plattform (please complete the following information):**
 - OS: Ubuntu
 - OS version 20.04
 - Plattform: x86_64
 - MPD version: master

**Client plattform (please complete the following information):**
 - Device: Linux 
 - OS: Ubuntu Linux 20.04
 - Browser Chrome, Firefox

**Comment by jcorporation** [comment]
The issue appears only for external synced lyrics? Right?

**Comment by ddonindia** [comment]
I think its only with external lyrics. 
Do you have sample file with embedded synced lyrics, I will try it ?

**Comment by jcorporation** [comment]
I could reproduce the issue with lrc files that includes `\r\n` line endings. There was a bug removing the `\r` characters.

Is now fixed in devel. Please test.

**Comment by ddonindia** [comment]
Thanks for quick fix :). 
Its working now.
