### ISSUE TITLE
mympd 9.1.0 Error loading icons from "pics" folder

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#655]
myMPD version: 9.1.0 commit c54ee99b75919214e6dc21c129996d4acc3ab70f

**Describe the bug**

In place upgrade from 9.0.3 to 9.1.0.
Before upgrade, icons from the hometab show without issues.
After upgrade, icons do not appear anymore. Error message: "Can not open directory pics"
Downgrading to 9.0.3 fixes the issue.

Browsing the picture folder works fine, though, wich confirms it's not a directory permission issue.

**Screenshots**

On version 9.0.3
![image](https://user-images.githubusercontent.com/4215150/148900730-32728794-9707-47c4-8a0f-a481af3497ac.png)

On version 9.1.0
![image](https://user-images.githubusercontent.com/4215150/148900284-e28b8d1c-22ff-46ef-8f97-f2575b6811dc.png)

![image](https://user-images.githubusercontent.com/4215150/148900428-5fa23ac8-4c6c-48ac-bae3-459368eab572.png)

**Server plattform (please complete the following information):**
 - OS: Debian
 - OS version 11 Bullseye
 - Plattform: x86_64
 - MPD version: 0.23.4

**Comment by tsunulukai** [comment]
Ok, found the problem.

Homeicons should now be moved from /var/lib/mympd/pics/ to /var/lib/mympd/pics/homeicons/
This change should be clearly documented to help users navigate this issue as they upgrade :)

**Comment by jcorporation** [comment]
The new paths are documented: https://github.com/jcorporation/myMPD/blob/v9.1.0/docs/references/pictures.md
I add a notice to the changelog too.
