### ISSUE TITLE
Integrate coverartarchive

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#660]
https://coverartarchive.org/

**Comment by jcorporation** [comment]
API is only usable with MBID metadata. Users who have maintained this tag have probably already downloaded coverimages with picard, etc.

I am unsure if this feature is really useful. Any comments?

**Comment by john-** [comment]
I tagged most of my music with picard and did not realize there was a option to download cover art with that tool.

Even in my case I would look for a tool that could automate the download of cover art vs. depend on something built into myMPD.

**Comment by jcorporation** [comment]
This is also my opinion. Closed without implementing this.
