### ISSUE TITLE
Cannot Play or edit webradio favorite

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#667]
myMPD version: devel commit ca99ad0760041d0c64fba34de032a25662bf1607

**Describe the bug**

Since the webradio favorites are sorted alphabetically:

- When trying to play a webradio from the favorites view, an error message is returned `No such playlist`
- When trying to edit a webradio from the favorites view, an error message is returned `Can not parse webradio favorite file`
- When trying to delete webradio from the favorites view, an error message is returned `Could not delete webradio favorite`

**Screenshots**
Error messages:
![image](https://user-images.githubusercontent.com/4215150/151042564-99d277cc-b9a7-4fa1-bc33-5fd6a3acb879.png)

api request when clicking on a webradio favorite:
![image](https://user-images.githubusercontent.com/4215150/151044915-ae4f3b91-89d8-42a4-94c2-d0dee113658e.png)

**Comment by jcorporation** [comment]
This was a regression from #666. Should be fixed, please test again.

**Comment by tsunulukai** [comment]
Fixed indeed !
