### ISSUE TITLE
Goto playing song behaviour (mostly cosmetic)

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#678]
myMPD version: 9.1.0 and 9.1.1

After finishing playing a playlist and MPD stopping, clicking on "Goto playing song" yields this:

`Number out of range for JSON path "$.params.offset"`

Subsequent clicks:

`TypeError: can't access property "scrollIntoView", document.getElementsByClassName(...)[0] is undefined (http://xxx.local:8080/js/combined.js: 8)`

I can reproduce it by clearing the queue entirely and then clicking "Goto playing song". Stopping MPD in the middle of a playlist (not just pause) and clicking the button works as expected, it is only when clicking after MPD finishes playing the playlist (or the playlist is empty) that the errors pop up.

Debian Bookworm x86_64 with MPD 0.23.5. Happens with both Firefox Developer (Linux) and Microsoft Edge (Windows).

**Comment by jcorporation** [comment]
Should be easy to fix.

**Comment by jcorporation** [comment]
Fixed in devel.
