### ISSUE TITLE
4.4.0 browse music files does not work with disabled tags

### ISSUE THREAD

**Issue by parkmino** [jcorporation/myMPD#68]
**Describe the bug**
mympd 4.4.0 for ubuntu 18.04 does not browse music files.
The package was downloaded from openSUSE Build Service.
Clicking 'Browse' does not change the browser's url unlike 'Playback', 'Queue' and 'Search'.

**To Reproduce**
1. Click 'Browse'

**Expected behavior**
Browse music folders and files.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox and Chrome
 - Version: the latest

**Additional context**
4.2.1 version worked fine, but it is not available from the repository any more.
Please let me know any check points on my side.

**Comment by jcorporation** [comment]
Are there any errors in the javascript console?

**Comment by jcorporation** [comment]
I meant the javascript console in your browser (Firefox: Webdeveloper -> Webconsole).

But I see in your output that myMPD finds no enabled tags. That should be the problem.

1) Can you post your mpd.conf?

2) Please also set the ```log_level = "verbose"``` in mpd.conf and post the ```mpd.log``` after restarting myMPD

3) Please try the tagtypes command on your mpd manually:
```
telnet localhost 6600
tagtypes
```
Output should be similar to:
```
tagtype: Artist
tagtype: Album
tagtype: AlbumArtist
tagtype: Title
tagtype: Track
tagtype: Name
tagtype: Genre
tagtype: Date
tagtype: Composer
tagtype: Performer
OK
```

**Comment by parkmino** [comment]
Aha

```
connected mympd.min.js:53:99
Error: Stored playlists are disabled mympd.min.js:142:300
[메시지에 대한 자세한 정보를 보거나 숨깁니다.] TypeError: app.apps[a].tabs[b].views[c] is undefined[더 알아보기] mympd.min.js:18:130
appGoto
http://localhost/js/mympd.min.js:18:130
appInit/<
http://localhost/js/mympd.min.js:34:398
```
1.
In mpd.conf,
`metadata_to_use	"none"`
Concerning tags, I do not want to enable any tags.
ympd has no problem with browsing music directory.

2~3. 
```
$ mpd --stdout --no-daemon --verbose /etc/mpd.conf
$ telnet localhost 6600
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.21.0
tagtypes
OK
```

If tags are mandatory, never mind this issue.

**Comment by jcorporation** [comment]
Tags are mandatory.
For minimum myMPD functionality, following tags must be enabled in ```mpd.conf```
```metadata_to_use "albumartist,artist,album,title,track"```

You should also enable playlists:
e.g. ```playlist_directory "/var/lib/mpd/playlists"```

**Comment by jcorporation** [comment]
I opened #69 to support mpd configurations with less features enabled.

Why you don't want to enable any tags?

**Comment by parkmino** [comment]
Disabling tags reduces overhead.
It helps with huge library and reduces time to update library.
For me, showing just folders and files are good enough like foobar2000 in windows.
There has been no problem with any other mpd clients with tags disabled.
I remember the the previous 4.2.1 version has worked fine.

**Comment by parkmino** [comment]
If browsing is disabled with tags disabled, I have no use mympd.
I think that you do not need to bother with #69.

**Comment by jcorporation** [comment]
Only the browse database tab would be disabled, because it is useless without tags. Browse filesystem would work furthermore as with ympd.

**Comment by parkmino** [comment]
OK, I got it and thanks for your support!

**Comment by jcorporation** [comment]
fixed in devel
