### ISSUE TITLE
Long filename/path support

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#697]
myMPD version: 9.1.2 (docker image)
**Describe the bug**

Cover generation fails if path is "too long".

**To Reproduce**

Have a music album with a long path. Go to mympd 'Browse' and check stdout/stderr.

**Expected behavior**

Cover generation succeeds.

**Server plattform:**
 - OS: Fedora
 - OS version 35
 - Plattform: x86_64
 - MPD version: 0.23.5

**Client plattform:**
same as above

**Debug logs**

 - myMPD debug log
 ```
ERROR    mympdapi  Can not open file "/var/cache/mympd/covercache/<long file path here>_cue_track0001.jpg.XXXXXX" for write
ERROR    mympdapi  Filename too long
```

**Comment by jcorporation** [comment]
How long are the filepath in this example? myMPD limits filepaths in the parsing code to 1000 bytes.

**Comment by jcorporation** [comment]
Fix is in devel, please test.

**Comment by dgcampea** [comment]
Tested with devel, it's working now. Thanks!
