### ISSUE TITLE
Truncated covers

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#702]
myMPD version: 9.2.0

**Describe the bug**

Album covers are truncated.
![image](https://user-images.githubusercontent.com/59268455/156595419-a8b18ace-7742-4fe6-a8aa-d201b9c9fd53.png)

**To Reproduce**

1. Go to 'Browse'.
2. (optional) clear cover cache and reload page with 'Disable Cache' from browser inspector/network tab (anything that can clear cached images on browser side). The truncation is inconsistent and may truncate covers that previously were ok or fix the broken ones.

**Expected behavior**

No truncation of images.

**Server plattform (please complete the following information):**
 - OS: Fedora 
 - OS version: 35
 - Plattform: x86_64
 - MPD version: 0.23.5

**Client plattform (please complete the following information):**
 - Browser: Firefox, Chromium

**Additional Info**

This is not a browser artifact, the images are really (visually) truncated, this can be observed by opening the direct link to the images on a new tab and saving them.

**Comment by jcorporation** [comment]
Please provide debug logs. Are the covers in the filesystem or embedded?

**Comment by jcorporation** [comment]
First: I can not reproduce your issue with latest MPD and myMPD devel.

Sorry, but the logs are incomplete. I should have logs from startup until the error occurs to see the configuration settings, mpd version and the full request flow.

From what I can see in the logs:
- myMPD has no access to the music directory and uses the mpd albumart command
- which MPD version do you use?
- I need the MPD verbose logs too

**Comment by dgcampea** [comment]
Sent you an email with the requested logs.

**Comment by jcorporation** [comment]
Sorry, I got no mail. Could you attach the logfiles to this issue?

**Comment by jcorporation** [comment]
Got the logs. There are many cue sheet related errors in the logs.

But the issue appears for embedded images in flac files? Can you provide such a file?

**Comment by dgcampea** [comment]
> But the issue appears for embedded images in flac files? Can you provide such a file?

The issue usually manifests with .tta files using cuesheets and external covers. (.tta files can't embed metadata iirc)
I've also seen it happen with other formats (an mp3 file with embedded image and cover.jpg on directory) though it's a lot less frequent.

**Comment by dgcampea** [comment]
I've checked with `readpic` and `albumart` commands on the mp3 file and I've noticed the following (using `file`):
* No image truncation was observed with mpc.
* Embedded mp3 cover file is a JFIF 1.01 JPEG file.
* *cover.jpg* file in the same directory as the mp3 file is a JFIF 1.02 JPEG file.
* External cover files for the affected .tta files are also JFIF 1.02 files.
* .tta files using JFIF 1.01 files seem unaffected by this issue. (so far)

From this, it looks like there's something strange happening with JFIF 1.02 JPEG files?

**Comment by jcorporation** [comment]
myMPD does not process the cover files. There are only read and sent as it is to the browser. Can you please provide me a file at which this issue appears?

**Comment by dgcampea** [comment]
Sent you a (pgp encrypted) email containing the problematic file. (I can resend as plain if preferred)

**Comment by jcorporation** [comment]
Please resend unencrypted. I fear that lost the private key for this public key.

**Comment by jcorporation** [comment]
I tried to reproduce your issue with your testfiles and I could not. 

- latest myMPD (9.2.1) and MPD (from master)
- with direct access to music directory and without

The coverimage is always displayed correctly.

**Comment by jcorporation** [comment]
> Retested with latest mympd and mpd 0.23.6, some interesting observations:

> 1. Initially I've manually erased covercache/ directory and didn't recreate it
> 2. Accessed cover image via URL and although the logs showed errors while attempting to cache the image, browser showed a > truncated cover (about 1/6 of the image starting from the top)
> 3. Created covercache/ directory but forgot to set owner to mympd. Write errors again but returned image to browser, this time it > wasn't as truncated (3/6 of the image)
> 4. Readjusted ownership, image gets cached successfully and even less of the image is truncated now (5/6 of image) (!!!)> 
> 5. Erased cache image, reloaded url, image is not truncated anymore.
> 6. Erased covercache/ directory or changed ownership to deny cache writes, image is still not truncated.
> 
> From the looks of it, it seems the image wasn't completely read in 1 pass and every subsequent non-cached read requests more chunks of the image until it's fully read. (I forgot to save the covers each time they got loaded but their sizes increased on each attempt until no more truncation was observed)

> Related to this cover question, is it possible to disable the covercache generation? (or make it in-memory cache, possibly with configurable size)
> The penalty on mpd doesn't seem too heavy to make it refetch covers on demand.

> ---

> On another note, would you consider enabling IPv6 by default for the devel docker image? This would make it easier for me to test that part of the backend (in light of https://github.com/jcorporation/myMPD/discussions/701)

Covercache can be disabled by setting covercache keep days in settings to zero.

Issue is very strange.

The logs shows following sizes for the image:
- first attempt: 524287 bytes
- second attempt: 1835007 bytes
- further attempts: 3728481 bytes

myMPD loops getting 256kb (binary limit) chunks from mpd until it gets zero bytes or a response that is smaller than the binary limit from mpd.

There is no error in the log for the first and second attempt. This indicates that mpd returns not enough (or zero) bytes. I added more verbose debug logging for the albumart command, please retest again and provide logs.

Covercache is written afterwards.

**Comment by jcorporation** [comment]
I think I found the cause of the issue. MPD does not always return the maximum bytes it could, even in the middle of the picture. myMPD interprets this as eof signature. 

The used albumart and readpictures interface from libmpdclient does not return the full size of the image.

MPD documentation says that MPD can choose a reasonable chunk size. Therefore this is a missimplementation on client side.

mpc does not suffer from this issue, because it uses the binary command natively and not the readpicture and albumart wrappers.

**Comment by jcorporation** [comment]
Commit 049580c should fix this issue, please test devel again.

**Comment by dgcampea** [comment]
Seems fixed with mympd-devel `sha256:928c7f5999d7964e408d62e6af02b8ebf28aa3f4eca62ee455989eab34be8f8e`.
Thanks for going through all the trouble to find and fix this bug :)
