### ISSUE TITLE
Albums are broken since v9.2.0

### ISSUE THREAD

**Issue by edhelas** [jcorporation/myMPD#704]
myMPD version: v9.2.0

Lots of albums are broken and doesn't have their album name.

![image](https://user-images.githubusercontent.com/3726886/157418636-ef805118-d98b-46ea-ada1-d6edb78ed15f.png)

When opening a broken album I have

```
ERROR: Can not parse response to json object:{"jsonrpc":"2.0","id":0,"result":{"method":"MYMPD_API_DATABASE_TAG_ALBUM_TITLE_LIST","data":[],"images":[],"bookletPath":"","totalEntities":0,"returnedEntities":0,"Album":"-","AlbumArtist":,"Discs":1,"totalTime":0}} combined.js:8:96578
ERROR: JavaScript error: TypeError: obj is undefined (https://edhelas.movim.eu/mympd/js/combined.js: 8) combined.js:8:96578
```

In the javascript console.

The issue appeared with the 9.2.0 upgrade.

**Comment by jcorporation** [comment]
I can not reproduce your issue, but I found two other bugs. Commit ae324fc could fix your issue. Please test the devel branch.

**Comment by jcorporation** [comment]
There are many cue sheet related errors in the logs.

But the issue appears for embedded images in flac files? Can you provide such a file?

**Comment by edhelas** [comment]
v9.2.1 fixes the issue :) Thanks !
