### ISSUE TITLE
Bogus IP Adress in "About"

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#712]
myMPD 9.2.2 mpd 0.24

I´m currently testing mpd 0.24 in combination with myMPD 9.2.2 (both git checkout from yesterday). The test machine has 192.168.0.9 and no other IPs or interfaces configured.
When accessing it from my Laptop the "About" section shows 192.168.0.194 (which is the address of the Laptop itself) - see screenshot (addressbar with 192.168.0.9). When accessing it from my Tablet, the same myMPD instance (192.168.0.9) shows "192.168.0.3", which is another machine.
So, while these IPs do exist on the network, they are definitely not those myMPD is running on.
![bogus_ip_address](https://user-images.githubusercontent.com/75694230/159868190-2a07afca-08cd-495c-84ca-9f402a014ee2.jpg)

**Comment by jcorporation** [comment]
It displays the peer address not the local one. This was a copy&paste error.

**Comment by dgcampea** [comment]
mympd-devel (image sha256:68ea86af65bb8da66151aad6a8257461e1d1b1cb1d35045e9f5841fb4d83aa6d)
With mympd listening on `[::]` and nginx reverse proxy configured (proxy_pass to `http://localhost:<mympd port>/`):
![image](https://user-images.githubusercontent.com/59268455/161038077-01a0dd04-0a1f-402e-b1e3-0e265ecfc13a.png)

`::` doesn't seem correct, it should be displaying other valid addresses it has learned. (according to https://www.apnic.net/get-ip/faqs/what-is-an-ip-address/ipv6-address-types/, https://www.rfc-editor.org/rfc/rfc4291.html#section-2.5.2)
