### ISSUE TITLE
Incorrect Filename link for CUE virtual tracks

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#714]
myMPD version: 9.2.2 (devel image: `sha256:6d3a3ccb709c88fff4f21f0702035bbee05b4a3fd8f7a2f8d893ab11f1385775`)

**Describe the bug**

Under  `Song details` for a cuesheet virtual track, `Filename` field has value `track0028` which is not incorrect but the link directs to 
`http://localhost/browse/<path to album>.cue/track0028` which does not exist, since `track0028` is a virtual track.

**To Reproduce**

1. Go to 'Song details' for a cuesheet virtual track
2. Click on 'Filename' value

**Expected behavior**

Link to cuesheet instead and have
> Filename: [cuesheet.cue](example.com/...../cuesheet.cue) (track0028)

**Alternative 2**:

Link to cuesheet 'FILE' value. This gives the whole audio file and aligns with the behavior of non virtual tracks.
It could also be cropped to better match the expectation that you're getting a link to the specified audio track (and not other unrelated tracks within the cuesheet) but this is probably overkill.

> Filename: [CDImage.flac](example.com/...../CDImage.flac)  (track0028)

or

> Filename: [cropped.flac](example.com/...../cropped.flac)  //link generated on-click

**Comment by jcorporation** [comment]
MPD does not return the `FILE` value of the cuesheet and myMPD has no parsing logic for cuesheets. Best what we can do is to calculate the link of the cuesheet.

I open a issue for this in the MPD repo, getting the FILE value with `lsinfo` would be a great protocol enhancement.

I noticed also that the fingerprint command does not work for virtual cuesheet tracks.

**Comment by jcorporation** [comment]
getfingerprint: https://github.com/MusicPlayerDaemon/MPD/issues/1494
lsinfo: https://github.com/MusicPlayerDaemon/MPD/issues/1495
