### ISSUE TITLE
Missing AF_NETLINK in RestrictAddressFamilies

### ISSUE THREAD

**Issue by lbschenkel** [jcorporation/myMPD#716]
myMPD version: 9.2.2

**Cannot queue radio playlists.**

The problem is because in my system (Debian testing) the following call fails:
https://github.com/jcorporation/myMPD/blob/0b2a55f9b6452f9fa0ea50af201448c03291259d/src/mympd_api/mympd_api_utility.c#L56
with `errno`=`EAFNOSUPPORT` (Address family not supported by protocol), and then:
1. `get_local_ip()` returns an empy string to the caller
2. the URL of the playlist is generated with an empty host: https://github.com/jcorporation/myMPD/blob/0b2a55f9b6452f9fa0ea50af201448c03291259d/src/mympd_api/mympd_api_utility.c#L168
3. MPD fails to resolve the URL: 
   ```
   mpd[140]: client: [18] process command "load "http://:80/browse/webradios/...""
   mpd[140]: exception: CURL failed: URL using bad/illegal format or missing URL
   mpd[140]: exception: No such playlist
   ```
5. The following is logged by myMPD:
   ```
   mympd[2129]: ERROR    mympdapi  Can not get list of inteface ip addresses
   mympd[2129]: ERROR    mympdapi  Address family not supported by protocol
   mympd[2129]: ERROR    mympdapi  MPD error: No such playlist (9)
   mympd[2129]: ERROR    mympdapi  Error in response to command mpd_run_load
   ```

The reason for `getifaddrs` failing with `EAFNOSUPPORT` is because the systemd unit file does not include `AF_NETLINK` in `RestrictAddressFamilies`: https://github.com/jcorporation/myMPD/blob/0b2a55f9b6452f9fa0ea50af201448c03291259d/contrib/initscripts/mympd.service.in#L22

 Apparently [this is necessary to enumerate interfaces](https://github.com/NLnetLabs/unbound/issues/350#issuecomment-731577025). Once it is included:
```
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_NETLINK
```
then the problem goes away and myMPD can auto-detect its own IP and generate well-formed URLs with its own IP in the host field.

**Comment by jcorporation** [comment]
A bug report with a fix included - great!

**Comment by lbschenkel** [comment]
Thanks. I would like to add that I found out about myMPD just yesterday and I wish I knew about it sooner, it is exactly what I was looking for. Great project.
