### ISSUE TITLE
UI - Navbar icons not always entirely visible/accessible

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#728]
myMPD version: 9.2.3
Browser used: {Firefox Nightly / Google Chrome} on Android 11

**Describe the bug**
Depending on
- the number of navbar icons (in my case 8),
- the screen size & DPI of your mobile device,

all icons of the navbar might not always be visible/accessible

**To Reproduce**
Configure more navbar icons than there is space available to display icons on your mobile device.
Observe you can't access the last icons.

**Expected behavior**
One should be able to scroll the navbar icons laterally when there are more of them than screen estate available.

**Screenshots**
![signal-2022-04-15-082142](https://user-images.githubusercontent.com/4215150/163530078-8d6a0e83-fcd0-44ca-80f0-1d29436c3822.jpeg)
In this screenshot, the mostright search icon is not visible/accessible.

 
**Configuration**
```
# cat navbar_icons
[
  {
    "ligature": "home",
    "title": "Home",
    "options": ["Home"],
    "badge":""
  },
  {
    "ligature": "play_arrow",
    "title": "Playback",
    "options": ["Playback"],
    "badge": ""
  },
  {
    "ligature": "queue_music",
    "title":"Queue",
    "options": ["Queue"],
    "badge":"<span id=\"badgeQueueItems\" class=\"badge badge-secondary\"></span>"
  },
  {
    "ligature": "library_music",
    "title":"Database",
    "options": ["Browse", "Database"],
    "badge":""
  },
  {
    "ligature": "folder",
    "title":"Folders",
    "options": ["Browse", "Filesystem"],
    "badge":""
  },
  {
    "ligature": "radio",
    "title":"WebRadios",
    "options": ["Browse", "Radio"],
    "badge":""
  },
  {
    "ligature": "list",
    "title":"Playlists",
    "options": ["Browse", "Playlists"],
    "badge":""
  },
  {
    "ligature": "search",
    "title": "Search",
    "options": ["Search"],
    "badge": ""
  }
]
```

**Comment by jcorporation** [comment]
I am unsure what is better:

- scrolling: needs a scrollbar 
- dynamic height of top bar and icons in two rows 
- dropdown menu with the cutoff icons

**Comment by Emilot** [comment]
"dropdown menu with the cutoff icons"

my vote

**Comment by tsunulukai** [comment]
Would definitely prefer the scrollable div id...

Something like this maybe ?
```
#navbar-main {
    overflow: auto;
}

```

Or without scrollbars for a more refined look (but lacks any indicator for the users there are more icons there...)
```
/* Hide scrollbar for IE, Edge and Firefox */
#navbar-main {
    overflow: auto;
    -ms-overflow-style: none; /* for Internet Explorer, Edge */
    scrollbar-width: none; /* for Firefox */
}

/* Hide scrollbar for Chrome, Safari and Opera */
#navbar-main::-webkit-scrollbar {
    display: none;
}
```

![image](https://user-images.githubusercontent.com/4215150/164085312-c9d7eb71-9fc9-4034-b32e-93170fe42858.png)

**Comment by jcorporation** [comment]
I prefer also the scrollable solution for its simplicity. Hidding the scrollbar without any other indicator is not userfriendly. Leaving the scrollbar is not the most beautiful solution but also the simplest.

**Comment by tsunulukai** [comment]
Thanks for the heads up ! That state files got carried over for many updates :)
