### ISSUE TITLE
On album und queue view the search field is automatically selected which pops up the tablet keyboard

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#752]
### Discussed in https://github.com/jcorporation/myMPD/discussions/751

<div type='discussions-op-text'>

<sup>Originally posted by **GK-774** May  5, 2022</sup>
On todays (May 5th) devel version when changing to the album view or the queue view, the cursor automatically is in the search field and this activates the keyboard on mobile devices (the keyboard pops up and hides half of the screen).
Is this intentional and/or can one deactivate it? It´s a bit unpractical when browsing through albums and on each page the keyboard pops up.</div>

**Comment by jcorporation** [comment]
Strange, commit 3d22f209c479a4b66dee54db44ac71d755c18e30 should exactly prevent this for all views.

Could be a issue with mobile browser detection. Is there a "Scale ratio" in your settings (Appearance -> Theme)? This should be there if myMPD detects a mobile browser.

**Comment by GK-774** [comment]
On my phone (Android) I have the scale ratio setting (1.0) on my Tablet (iPad) there is none. The browser is Firefox in both cases. Just have tried devel from May 2nd which I still had available, and this version does not pop up the keyboard in the album view but in queue view it does it too.

**Comment by jcorporation** [comment]
Appears this issue only on your iPad (without scale ratio setting) or also on Android (with scale ratio setting)?

**Comment by GK-774** [comment]
It appears on both. On a normal PC the cursor is in the search field automatically as well (but of no consequence of course).

**Comment by jcorporation** [comment]
For desktop’s this is the intended behavior.

Desktops: autofocus 
Mobile: no focus

**Comment by jcorporation** [comment]
I could not reproduce your issue with Firefox on my iPhone. Do you requested the desktop version of the site?

**Comment by GK-774** [comment]
It apparently uses the desktop version per default, if I request the mobile site on the iPad nothing changes. (iPad 12 inch display).

The version from May 2nd only pops up the keyboard in the queue view, later version (from yesterday) does this on the album view as well. This is consistent for the following mobile devices tried: iPhone 6 with Safari, iPad with Firefox, Android Phone with Firefox, Android Tablet with Firefox.

**Comment by GK-774** [comment]
> For desktop’s this is the intended behavior.
> 
> Desktops: autofocus Mobile: no focus

If this does not work reliable, would a default of "no focus" not be a better solution?

**Comment by jcorporation** [comment]
The autofocus for all views is intended for 9.3.0. This behavior is more consistent.

It should be disabled on mobile devices. myMPD detects mobile devices by parsing the UserAgent string. Can you please post the useragent strings, use e.g. http://useragentstring.com/

**Comment by GK-774** [comment]
User agent strings from mobile devices:

Android Phone: Mozilla/5.0 (Android 11; Mobile; rv:100.0) Gecko/100.0 Firefox/100.0
Android Tablet: Mozilla/5.0 (Android 6.0.1; Mobile; rv:100.0) Gecko/100.0 Firefox/100.0

iPad pro 12" - Firefox: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
iPad pro 12" - Safari: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
(no typo, useragentstring.com really reports the same user agent for both browsers)

iPhone - Safari: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148

**Comment by dgcampea** [comment]
I've tested with mympd-devel`sha256:98d7ee3f3cfeddbcf0c493864d89174a7167afa8884fc1fb05421c25a406b920` under Firefox for Android (`User-Agent: Mozilla/5.0 (Android 9; Mobile; rv:99.0) Gecko/99.0 Firefox/99.0`) and it's working as intended (no keyboard popup in either view).

**Comment by GK-774** [comment]
The iPad does apparently not report "mobile" at all, so I assume this would always result in autofocus on the iPad unfortunately.

**Comment by jcorporation** [comment]
Thanks for your tests. Best option would be a browser specific setting to override the mobile detection, like a "Enforce mobile view"?

**Comment by GK-774** [comment]
Well, unlike what dgcampea said above, I have "autofocus" on all four mobile devices tried so far (and the two Phones and the Android tablet have "mobile" in their user agent string.

**Comment by GK-774** [comment]
Personally I would prefer a possibility to disable "autofocus" altogether.

**Comment by GK-774** [comment]
Android and iPhone works now as expected out of the box, iPad needs the "Enforce mobile view", works ok as well. Looks good :-)

**Comment by jcorporation** [comment]
Great, exactly as it should be!
