### ISSUE TITLE
Decompression of brotli compressed assets fails

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#753]
Windows 10 Enterprise 21H2 OS build 19044.1645

Microsoft Edge
Version 101.0.1210.39 (Official build) (64-bit)

Firefox 100.0 (64-bit)

with brotli enabled ("Compressing assets with brotli" message) I get a page full of "�rFF!Y��`Y`3��" symbols on Firefox and a "ERR_CONTENT_DECODING_FAILED" on Edge. Rebuilt with brotli disabled it works as expected on both browsers.

What is the correct way to disable it? In my spec file I placed "export USE_BROTLI="OFF"" before the ./build.sh createassets command and used -DUSE_BROTLI=OFF for cmake, this worked but I´m courious what the "official" way would be.

_Originally posted by @GK-774 in https://github.com/jcorporation/myMPD/issues/750#issuecomment-1119619569_

**Comment by jcorporation** [comment]
> In my spec file I placed "export USE_BROTLI="OFF"" before the ./build.sh createassets command and used -DUSE_BROTLI=OFF for cmake, this worked but I´m courious what the "official" way would be.

That is correct, the `build.sh` script handles this the same way.

Your browser versions should definitively support brotli. Is there a proxy or anything else between myMPD and the browser?

**Comment by GK-774** [comment]
No proxy and on the local LAN (same subnet).

**Comment by jcorporation** [comment]
Very strange! 
BTW: I renamed the USE_BROTLI option to ENABLE_BROTLI.

- Do you know  / check if other sites with brotli compression works?
- Can you grab the request and response headers for ERR_CONTENT_DECODING_FAILED?

I have tested again and changed the server side to latest DietPi on armv7l and it works also. Preceding test was with 64bit x86 serverside.

**Comment by GK-774** [comment]
Does the compression/decompression make sense at all for the use case we have here? It´s of benefit when content is large and the transmission is slow. Both is not the case here with the client typically on the same subnet with the server which is only a few meters away. I doubt it results in a speed improvement.

**Comment by jcorporation** [comment]
Compression is in both cases only done at compile time.

I also tend to revert the patch.

**Comment by jcorporation** [comment]
Brotli patch is now removed. myMPD should now work as before.

**Comment by dgcampea** [comment]
Strange, I did test it with plain HTTP mympd under Firefox (both Desktop and Android) and didn't catch any issues with it.
about:config also shows `br` being available under `.secure`.

**Comment by dgcampea** [comment]
Firefox is marking localhost as secure domain (notice the padlock icon next to Domain), even though it's using HTTP.  This probably explains the differences we're seeing with the tests.

![image](https://user-images.githubusercontent.com/59268455/167250375-302498dd-6841-4f09-9882-bc825e446f87.png)

**Comment by dgcampea** [comment]
Brotli does work with HTTP (non reverse proxied) with Firefox for both Desktop and Android.

Were the browser settings changed (due to user action or some experimental study) ? Can you test with a fresh install/profile?
What are the response headers? Can you try with the cache cleared?

May 6, 2022 5:15:45 PM Jürgen Mang ***@***.***>:

> Very strange!
> BTW: I renamed the USE_BROTLI option to ENABLE_BROTLI.
> 
* > Do you know / check if other sites with brotli compression works?
* > Can you grab the request and response headers for ERR_CONTENT_DECODING_FAILED?
> 
> I have tested again and changed the server side to latest DietPi on armv7l and it works also. Preceding test was with 64bit x86 serverside.
> 
> 
> *Edit:*
> 
> Disabling SSL let me reproduce your error. Searching around I found: https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/
> 
> *Firefox about:config*
> 
* > network.http.accept-encoding is set to gzip, deflate
* > network.http.accept-encoding.secure is set to gzip, deflate, br
> 
> It really seems that brotli is not supported to compress plain http responses.
> 
> I think there are two options:
> 
* > remove the brotli option and use gzip compression as before
* > respect the accept-encoding header and inflate the asset before serving but this adds an extra runtime dependency

**Comment by jcorporation** [comment]
> Brotli does work with HTTP (non reverse proxied) with Firefox for both Desktop and Android.

> Were the browser settings changed (due to user action or some experimental study) ? Can you test with a fresh install/profile?
What are the response headers? Can you try with the cache cleared?

I checked recent Firefox settings on two another systems Linux / Windows: network.http.accept-encoding: gzip, deflate

**Comment by dgcampea** [comment]
![image](https://user-images.githubusercontent.com/59268455/195066099-2c550957-b274-415b-9394-411becb7ed9e.png)
???

This reply (via email) was sent way back in May, looks like it only arrived now?
