### ISSUE TITLE
Filesystem do not return to previous posistion state

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#754]
myMPD version: [e.g. 8.1.0]

**Describe the bug**

When i am at the third page for example, i open a folder and then press "Back" or the "..." to go to the upper level, then i am at the first page and i have to go all that through again.

**To Reproduce**

1. Go to Filesystem 
2. Click on a folder
3. Go back(back mouse button) or with the ".."
4. Go to the top of the page and not to the folder

**Expected behavior**

To go to the folder i was

**Comment by jcorporation** [comment]
It seems it was broken since the introduction of the sticky header for desktops (v9.0.0). Should now be fixed, please test.

**Comment by Emilot** [comment]
Case closed JC. Thank you!
