### ISSUE TITLE
Local playback - Bad Gateway connecting to MPD streaming output

### ISSUE THREAD

**Issue by tobru** [jcorporation/myMPD#757]
myMPD version: 9.3.1

**Describe the bug**

The proxy connection on `/stream/` leads into a "Bad Gateway" response, whereas with manual testing the connection works.

**To Reproduce**

Run myMPD with the [recommended configuration](https://jcorporation.github.io/myMPD/references/local-playback) and try local playback.

**Expected behavior**

`/stream/` proxies to the MPD HTTP streaming output.

**Server plattform:**
 - OS: Alpine Linux
 - OS version: edge
 - Plattform: arm64
 - MPD version: 0.23.7

**Client plattform:**
 - Device: Laptop
 - OS: Arch Linux
 - Browser: Firefox
 - Browser versio: 100

**Debug logs**

```
curl https://mympd.example.com/stream/ -v
[...]
< HTTP/2 502 
< content-type: text/plain; charset=utf-8
< content-length: 11
< date: Wed, 11 May 2022 19:03:38 GMT
< 
Bad Gateway
```

```
INFO     webserver HTTP request (15): GET /stream/
INFO     webserver Creating new tcp backend connection to "http://mpd:8000"
INFO     webserver Forwarding client connection "15" to tcp backend connection "16"
INFO     webserver Backend HTTP connection 16 closed
INFO     webserver HTTP connection 15 closed
INFO     webserver HTTP request (14): GET /stream/
INFO     webserver Creating new tcp backend connection to "http://mpd:8000"
INFO     webserver Forwarding client connection "14" to tcp backend connection "17"
INFO     webserver Backend HTTP connection 17 closed
INFO     webserver HTTP connection 14 closed
```
 
**Configuration**

```
[...]
audio_output {
    type "pulse"
    name "Local Music"
}
audio_output {
        type      "httpd"
        name      "HTTP Stream"
        encoder   "lame" #to support safari on ios
        port      "8000"
        bind_to_address "0.0.0.0"
        bitrate   "128"
        format    "44100:16:1"
        always_on "yes"
        tags      "yes"
}
```
![Screenshot_20220511_210554](https://user-images.githubusercontent.com/1695957/167926637-72a83132-0e97-4b54-89ee-a9d335466335.png)

**Additional context**

Running a `curl http://mpd:8000` from the same location where myMPD is running leads into a successful connection. Also, directly connecting to mpd port 8000 from e.g. vlc lets me successfully stream music.

**Comment by jcorporation** [comment]
> curl https://mympd.example.com/stream/ -v
[...]
< HTTP/2 502 
< content-type: text/plain; charset=utf-8
< content-length: 11
< date: Wed, 11 May 2022 19:03:38 GMT
< 
Bad Gateway

This is strange. myMPD does not support HTTP/2 is in your setup a reverse proxy involved?

**Comment by tobru** [comment]
Yes. The connection is Browser -> Traefik -> myMPD and therefore myMPD is configured with `MYMPD_SSL=false`

**Comment by jcorporation** [comment]
It seems that Traefik reports this error. Can you test without?

**Comment by tobru** [comment]
You're right, that might be an issue with Traefik. Connecting directly to myMPD leads into this:

```
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /stream/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.83.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

and the myMPD log says:

```
DEBUG    webserver New connection id "113" from 127.0.0.1, connections: 8
INFO     webserver HTTP request (113): GET /stream/
INFO     webserver Creating new tcp backend connection to "http://mpd:8000"
INFO     webserver Forwarding client connection "113" to tcp backend connection "114"
INFO     webserver Backend HTTP connection 114 closed
INFO     webserver HTTP connection 113 closed
```

**Comment by jcorporation** [comment]
curl output should look like:
```
curl -v http://localhost/stream/
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /stream/ HTTP/1.1
> Host: localhost
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: audio/mpeg
< Connection: close
< Pragma: no-cache
< Cache-Control: no-cache, no-store
< Access-Control-Allow-Origin: *
```

**Comment by tobru** [comment]
I'll do more debugging soon and let you know.

**Comment by tobru** [comment]
It seems to be an issue with my network configuration - unrelated to myMPD
