### ISSUE TITLE
Open folder/download buttons on song details modal do not work

### ISSUE THREAD

**Issue by sevmonster** [jcorporation/myMPD#758]
myMPD version: 9.3.1

**Describe the bug**

The newly added "open folder" and "download" buttons on the song details tab on song modal do not trigger anything on the `onClick` event. They are set as `button`s in the HTML, but [the code checks for anchors](https://github.com/jcorporation/myMPD/blob/e80eebd8de1a119d4d63fefc48e81da17c4299cd/htdocs/js/song.js#L8).

Don't know if it would be preferable to change the element to an anchor or move the code handling it below to conditional that handles `button`s. They work great with either change.

**Comment by jcorporation** [comment]
I redesigned the modal after implementing the new functionality and forgot to test again…

**Comment by jcorporation** [comment]
Fixed in devel.
