### ISSUE TITLE
PKGBUILD not working for v4.6.1

### ISSUE THREAD

**Issue by GeorgeHJ** [jcorporation/myMPD#76]
Hello,

I am experiencing error 404 when attempting to download the source tarball.

![screenshot_2018-11-25_19-14-57](https://user-images.githubusercontent.com/30212436/48983431-9bb0ce00-f0e6-11e8-8491-00859e19f2c8.png)

**Comment by jcorporation** [comment]
Hi,

the 4.6.1 version is not released yet.

**Comment by GeorgeHJ** [comment]
Well that explains it!

Sorry. I'll revert to a previous change with git and try again.
