### ISSUE TITLE
Too many outputs on phone:  can't get to volume!

### ISSUE THREAD

**Issue by MiM-TMassey** [jcorporation/myMPD#775]
myMPD version: myMPD 9.3.4

**Describe the bug**

On iPhone, I cannot change the volume.  I have 12 (update: 14) outputs, which makes the interface longer than my screen, and there's no way to scroll the list.

**To Reproduce**
  - Create 14 outputs
  - Open interface on iPhone
  - Click the speaker (volume) icon.  You will get a list that shows the bottom of the list of outputs, with the top of the list (with the very critical volume slider!) off the top of the screen.  You cannot scroll this layer.

**Expected behavior**
At the very least, the list should be scrollable so I can get to the top that's off the screen.

In the past, the volume *was* at the top and the list built down.  I couldn't get to the bottom three outputs, which fortunately were not often used (and I'd have to use a different tool to enable or disable).  But now, with it being built from the bottom up, the critical volume slider is inaccessible as well as my most-used outputs.

I would suggest that if the volume button is going to be at the bottom of the screen, it would make sense to put the slider on the bottom of the list (your finger or mouse is already there!).  And if you're doing that, put the "first" oputput at the bottom, again near the volume.

**Screenshots**
The first shot shows the default way the volume/outputs come up.  By default the URL is at the bottom, and on many screens (like the play screen) you can't scroll down, so you can't make the URL chrome go away,  The volume slider is off the screen

<img width=400 src="https://user-images.githubusercontent.com/35174197/173113282-a6ae1646-b0dd-41e8-a548-1b92024147fe.png">

The second shot shows even when you've been able to make the URL chrome go away, if you have enough outputs it still won't show up.  And there's no way to scroll that layer.  So no volume control.

<img width=400 src="https://user-images.githubusercontent.com/35174197/173112172-d7ba40ef-b997-41c8-af5b-284b51cfba25.png">

**Server plattform (please complete the following information):**
 - OS: Fedroa
 - OS: 36
 - Plattform: armv7l
 - MPD version: Music Player Daemon 0.23.6

**Client plattform (please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: iOS 15.2
 - Browser Safari
 - Browser version 15.2

**Debug logs (please attach if it can be usefull)**
None:  error in GUI

Thank you very much for your help and consideration!

**Comment by MiM-TMassey** [comment]
Just tested on Firefox (Windows, 100.0):  Same issue:  can't scroll, and if the window is too small (and it has to be *completely* maximized to fit 12 outputs), it won't show the volume slider.

**Comment by MiM-TMassey** [comment]
Sorry, I just counted my ouptuts:  I have 14, not 12.  And yes, these are all real, live outputs, not a debug kind of thing.

**Comment by jcorporation** [comment]
A fix is in the v9.4.0 branch. I moved the volume slider to the bottom as suggested and the output buttons area is now scrollable.

**Comment by MiM-TMassey** [comment]
Wow! That was fast.

I admit I am lazy (I prefer conservative) and I’m using an RPM. As soon as it shows up in the build infrastructure, I’ll test it. Thank you so very much.
