### ISSUE TITLE
Chinese Translation 9.3.4fix and Chinese file for 9.4.0

### ISSUE THREAD

**Issue by dream7180** [jcorporation/myMPD#779]
- One fix for 9.3.4
- New file for 9.4.0
Thanks.
[cn-CHS-940.txt](https://github.com/jcorporation/myMPD/files/8891322/cn-CHS-940.txt)
[cn-CHS-934fix.txt](https://github.com/jcorporation/myMPD/files/8891324/cn-CHS-934fix.txt)

**Comment by jcorporation** [comment]
Thanks for updating your translation!
