### ISSUE TITLE
Only using cover.jpg, ignoring folder.jpg

### ISSUE THREAD

**Issue by bonelifer** [jcorporation/myMPD#782]
myMPD version: 9.3.3

**Describe the bug**

It's only picking up cover.jpg, ignoring folder.jpg. If I make a copy of the file and name it cover.jpg, it picks it up, so it's not a corrupt file issue. I have this in the config page:
`folder,cover,Folder,Cover`

**Server plattform (please complete the following information):**
 - OS: Xubuntu
 - OS version 20.04.4
 - Plattform: x86_64
 -  MPD version:  0.23.7

**Comment by jcorporation** [comment]
I tested locally and can not reproduce your issue.

**Comment by jcorporation** [comment]
Closing, you can reopen the issue if you can provide debug logs.
