### ISSUE TITLE
Quick Play/Remove button creates another row

### ISSUE THREAD

**Issue by sevmonster** [jcorporation/myMPD#783]
myMPD version: 9.3.4

**Describe the bug**
The new buttons appear above the menu buttons instead of beside it (as I would imagine they should). If this is by design, could there be an option to move them to the side instead? They make tables much less readable due to the extra vertical space.

**To Reproduce**

1. Enable quick play/remove buttons
2. Navigate to a table where the buttons will appear
3. Observe the added line-sized height added to each table row

**Screenshots**

![image](https://user-images.githubusercontent.com/16788697/174433132-b4ecdc81-5b95-4c9d-ac73-b5f2225220d8.png) ![image](https://user-images.githubusercontent.com/16788697/174433324-8a628bde-3eb8-4422-88fa-56110faadb2c.png)

**Server plattform (please complete the following information):**
 - OS: Alpine Linux
 - OS version edge
 - Plattform: x86_64
 - MPD version: 0.23.7

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Artix Linux
 - Browser: Ungoogled Chromium
 - Browser version: 102.0.5005.61

**Comment by jcorporation** [comment]
This is unintended and differently rendered dependent on browser, settings or screen resolution.

Buttons side by side is the best for wider screens and vertical for small screens.

**Comment by sevmonster** [comment]
> Buttons side by side is the best for wider screens and vertical for small screens.

I agree. I thought it might be related to resolution, but no matter the size it would always appear like that.

**Comment by jcorporation** [comment]
I tested quickly:
-Firefox: the buttons are side by side
- Chromium: the buttons are vertical
