### ISSUE TITLE
navbar_icons state file is ignored

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#793]
myMPD version: 9.4.0 - Debian build (both from https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/arm64/  and self-compiled )

**Describe the bug**

Content of /var/lib/mympd/state/navbar_icons is ignored

**To Reproduce**

Edit navbar file as follows (I deleted the search button and added a few direct links to different browsing views)
```
┌──[root@nas]──[/var/lib/mympd/state]────────
# cat navbar_icons
[
        {
                "ligature":"home",
                "title":"Home",
                "options":["Home"]
        },
        {
                "ligature":"equalizer",
                "title":"Playback",
                "options":["Playback"]
        },
        {
                "ligature":"queue_music",
                "title":"Queue",
                "options":["Queue"]
        },
        {
                "ligature":"library_music",
                "title":"Browse",
                "options":["Browse"]
        },
        {
                "ligature":"cloud",
                "title":"DataBase",
                "options":["Browse", "Database"]
        },
        {
                "ligature":"folder",
                "title":"FileSystem",
                "options":["Browse", "Filesystem"]
        },
        {
                "ligature":"list",
                "title":"Playlists",
                "options":["Browse", "Playlists"]
        },
]
```
Start mympd and observe the navbar content which is the one offered in a default install
![image](https://user-images.githubusercontent.com/4215150/179180876-0d967e3f-dd2c-426f-8674-04caeac39d14.png)

**Expected behavior**

Navbar icons should match the content of the navbar_icons state file.

**Additional context**

Verbose logging does not return any message related to the navbar_icon file.
Rolling back to v9.3.4 solves the issue.

**Comment by jcorporation** [comment]
json validation of the navbar_icons failed because v9.4.0 reads only the first line of a state file.

Above commit changes this behavior. 

P.S. the last comma in your json file should be removed.

**Comment by tsunulukai** [comment]
Thanks for the quick fix :)
