### ISSUE TITLE
el.textContent.appendChild is not a function since v9.4.0

### ISSUE THREAD

**Issue by edhelas** [jcorporation/myMPD#795]
myMPD version: the issue appeared since 9.4.0

**Describe the bug**

When opening an album I see the following error.
    
    TypeError: el.textContent.appendChild is not a function (https://.../js/combined.js: 8)

The track list of the album is not shown.

This happens for all the albums.

**Expected behavior**

Don't have this Javascript error anymore and see the tracks of the albums.

**Screenshots**

![image](https://user-images.githubusercontent.com/3726886/179723412-bce8b5f5-1bee-4c99-93b2-a5086d0e5117.png)

**Comment by jcorporation** [comment]
Commit ea70b70316809879a26370f8a788e86857f7a562 introduces this error. Will be fixed soon for devel. Workaround could be to add genre tag to the browse tags.
