### ISSUE TITLE
Invalid homescreen button:  JavaScript error

### ISSUE THREAD

**Issue by MiM-TMassey** [jcorporation/myMPD#798]
myMPD version: 9.3.4

**Describe the bug**
While viewing Browse/Filesystem, I created a homescreen icon.  However, when I use that homescreen Icon, I get the following error:

TypeError: document.getElementById(...) is null (https://172.28.16.48:8042/js/combined.js: 8)

**To Reproduce**

From new session:
Browse/Filesystem/Add view to homescreen
    Name:  Filesystem
Save (Leaving the rest as defaults).

Go to Home and click your new icon: you get the above error.

**Expected behavior**

That I not get the error!  :)

**Screenshots**
Here is the contents of the icon before I put the name in:

![image](https://user-images.githubusercontent.com/35174197/180612100-b51e5040-348b-4c37-8871-b05033a89ee9.png)

**Server plattform (please complete the following information):**
 - OS: Fedora
 - OS 36
 - Plattform: Armv71
 - MPD version: 0.23.6

**Client plattform (please complete the following information):**
 - Device: iPhone, iPad, Firefox
 - OS: iOS 14, iPadOS 15, Windows 10
 - Browse:  Safari, Firefox
 - Browser version as per OS, 102.0.1

**Debug logs (please attach if it can be usefull)**

None.  Let me know if you need it.

**Configuration (please attach if it can be usefull)**

Again, let me know if you need it.

**Additional context**

ETA:  While I'm bugging you, is there a way to set the default view for Browse?  If there is, I've missed it.  I never use Album view, I always use Filesystem view, and it would be nice to make that the default.

**Comment by jcorporation** [comment]
Please update to 9.4.1 and test again.

**Comment by fts-tmassey** [comment]
Upgraded to 9.4.1 and it seems to have fixed it.  Sorry for the noise.

**Comment by MiM-TMassey** [comment]
Seems to be fixed in 9.4.1.  Sorry for the noise.
