### ISSUE TITLE
Volume GUI does not work properly when using partitions

### ISSUE THREAD

**Issue by MiM-TMassey** [jcorporation/myMPD#799]
myMPD version: 9.4.1

MyMPD with partitions enabled.  Volume slider in partitions is at a fixed number (the same number as used by the default partition), no matter what you do to it.

**To Reproduce**

1. In default partition:  set the volume at some specific level.  In my case, it was set to 93%
2. Select a different partition.
3. Click the speaker icon (volume) in bottom right.  The Output/Partitions/Volume popup will appear.
4. Click on the volume slider (not the scrollbar thumb).
5. The playback volume will change, but the scrollbar thumb or % display will not move.

Clicking on the slider does not seem to change MyMPD's internal representation, though it *does* change MPD's volume.  Partition volume always shows the default partition volume.

You will see similar behavior with other elements:
1. Click the + at the far right of the volume end.
2. The volume will leap to slightly louder than where MyMPD shows the volume is, not where MPD has the volume.

See screenshot below.  I'm listening to an output at a low volume (because I clicked on the slider bar in the 10% or so range), but MyMPD shows 93%.  When I click on the +, the volume will jump to 98% (and anger everyone in my house right now).

You also see this with the slidebar thumb:  if I drag it, the actual MPD volume will change to what I drag it to, but the thumb will snap immediately back to where MyMPD thinks it should be (the same number it was before).

This happens with both single and multiple outputs selected.  AFAICT, this only happens when a non-default partition is selected.

After further testing:  if I unselect *all* outputs on the default partition, the non-default partition seems to work correctly:  the GUI shows the proper volume, and the +/- and thumb all work correctly.  As soon as I go back into default and enable an output (even with nothing playing), the non-default partitions volume acts as described above (i.e. broken).

**Expected behavior**
The MyMPD GUI would update its internal volume representation to match what I told it to via the slidebar, regardless of the status of the default partition.

**Screenshots**

In this screenshot, I'm listening at a low volume (approximately 10% here at nearly 11PM), but MyMPD thinks I'm trying to simulate a rock concert at 93%, and it won't budge from that 

![image](https://user-images.githubusercontent.com/35174197/180911789-d88b55d1-dddb-4105-9e35-a294f0794edd.png)

**Server plattform (please complete the following information):**
 - OS: Fedora
 - OS version 36
 - Plattform: armv7
 - MPD version: 0.23.6 (until someone adds separate volume control!!!)

**Client plattform (please complete the following information):**
 - Device: iPhone, iPad, Windows PC
 - OS: iOS 15, iPadOS 15, Windows 10
 - Browser:  Safari , Firefox 
 - Browser version:  As per iOS/iPadOS above, 102.0.1

**Debug logs (please attach if it can be usefull)**

None; let me know if it would help and I would be happy to provide.
 
**Configuration (please attach if it can be usefull)**

None:  again, happy to provide if needed

**Additional context**

Nothing, other than thank you again for your time and effort in making such a great tool.

**Comment by jcorporation** [comment]
I tried to reproduce your issue with no success. In my setup all works as it should. Each partition shows and changes his own volume level.

I tested with:
- MPD 0.24 (latest master)
- MPD 0.23.x branch
- MPD 0.23.5 (from ubuntu)
- myMPD 9.4.1

It seems to be a problem in your setup. Why do you stick on mpd 0.23.6? Debugging at MPD protocol level could be interesting.
In my setup it looks like:
```
OK MPD 0.23.5
newpartition test
OK
moveoutput "My Null Output 1"
OK
setvol 10
OK
getvol 
volume: 10
OK
partition default
OK
getvol
volume: 20
OK
setvol 80
OK
getvol
volume: 80
OK
partition test
OK
getvol
volume: 10
OK

```

**Comment by MiM-TMassey** [comment]
I can solidly reproduce the situation.  When the default partition has an output added to its list and active (green), the volume number and slider is locked to the volume of the default partition for all other partitions, and relative changes (using the +/-) are relative to that default volume level.  Once I disable all outputs on the default partition (not remove, just make grey instead of green), the volume works correctly.

I'm happy to perform whatever logging or testing you would like to see:  just point me in the right direction.

It's not as urgent as it was:  I was forced to use the default partition before you fixed the partition/output move/select logic in 9.4.  Sometimes it was the only partition that could actually see a particular output.  Now that this is resolved, I can simply ignore the default partition.  Having said that, still happy to help if it's worth it.

As for why I stay at 0.23.6:  to allow independent volume control of outputs playing at the same time.  I can have a volume playing loud in my garage (where the speakers are small and the space is big) and in the kitchen (where the speakers are large and the space is small) at the same time.  *VERY* useful -- but MPD 0.23.7 changes the way things work and breaks that for me, without a way to achieve it differently.  If you want more info, details here:  https://github.com/MusicPlayerDaemon/MPD/issues/1423

I cannot lose the ability to set separate volumes for separate outputs.  If that means that I stay at MPD 0.23.6, so be it.  Individual volume control is too integral to the way we use our whole-house audio system at this point.

**Comment by jcorporation** [comment]
myMPD and MPD debug logs could be useful.

Additionally change and get the volume at protocol level with above commands.

Another test could be to assign only dummy outputs with software mixers and retest.

**Comment by MiM-TMassey** [comment]
Here are the debug files.  Unfortunately, I did them as two different runs, but in each case I selected the default partition, made sure an output was selected *and* active, switched to the named partition (Tim), made sure an output was selected and active, then changed the volume.  In each case, the volume GUI did not change as it should have.

Testing with dummy outputs will take a little longer:  I'll work on that next.


[20220726-issue799-run01-mpd.log](https://github.com/jcorporation/myMPD/files/9192403/20220726-issue799-run01-mpd.log)
[20220726-issue799-run01-mymppd.log](https://github.com/jcorporation/myMPD/files/9192405/20220726-issue799-run01-mymppd.log)

**Comment by jcorporation** [comment]
myMPD gets a volume of 36 from MPD. Is it the volume of the tim partition or from the default partition. myMPD does not track the volume internal, it requests it each time from mpd.

**Comment by MiM-TMassey** [comment]
I don't remember what the volumes were actually at, and that's like 3 service restarts ago...  :)

So I redid them.  And everything worked fine!  But I did things a bit differently (I didn't do *all* the steps I normally do to set up MPD/MyMPD after a bounce), so I went back and did them *exactly* as I did before and it failed again.  In the end, there were two items I skipped, so I redid it a few times and found out exactly what elements are necessary to make it fail.  Log files of failing run attached below.

I have a detailed process below, but the part that was left out was having two MyMPD's running at the same time.  I have that in place because of the way multiple partitions are handled in MyMPD (at least as of 9.3) which makes two people using separate partitions effectively impossible:  *all* Web users get switched to the same partition whenever one person switches partitions.  Therefore, I run two MyMPD's, so that I can select my partition, and my wife can select hers, and everyone is kept separate.  (Additional details:  https://github.com/jcorporation/myMPD/issues/440#issuecomment-1152921674 )

In my case, MyMPD is started by a systemd template with two instances (mympd@tim and mympd@leah) that looks *just* like the normal systemd service file except it specifies a different ExecStart:

ExecStart=/usr/bin/mympd -u mpd -w /data/mpd/tools/mympd/partitions/%i/data -a /data/mpd/tools/mympd/partitions/%i/cache

The configuration files in /data/mpd/tools/mympd/partitions/<name> are created simply by using "mympd -u mpd -c" in each partition path and literally the only changes I make is to change port numbers in http_port and ssl_port.  If you want exact config files, etc. I'm happy to provide, but they are 100% standard except changing port numbers.

Here is the exact process I used to create the failure:

Process:
1. systemctl stop mpd
2. systemctl stop mympd@tim
3. systemctl stop mympd@leah
4. nano mpd.conf
5. <Enable verbose logging, save and exit>
6. rm mpd.log
7. systemctl start mpd
8. systemctl start mympd@leah  # If I skip this, everything works.
9. export MYMPD_LOGLEVEL=7
10. mympd -u mpd -w <path to tim> -a <path to tim> | tee 20220726-issue799-run02-mympd.log

Now, in MyMPD GUI:  https://172.28.16.48:8042
(Current partition is Default, all outputs selected, Living Room active, volume at 10%)
1. Volume/Current Partition/New Partition:  Tim/Save/Tim (To select the partition)
2. Volume/Move an output/Dining Room/Move
3. Volume/Dining Room (To make it green)
4. Browse/Filesystem/<Grab a song, append and play>
5. Volume/Change volume:  Volume changes, but slider/numbers do not.

[20220726-issue799-run02-mympd.log](https://github.com/jcorporation/myMPD/files/9192918/20220726-issue799-run02-mympd.log)
[20220726-issue799-run02-mpd.log](https://github.com/jcorporation/myMPD/files/9192919/20220726-issue799-run02-mpd.log)

**Comment by jcorporation** [comment]
This is very weird. I have actually no idea how a second myMPD instance could affect a other instance...

**Comment by MiM-TMassey** [comment]
I know just enough to be dangerous; I certainly might be missing something.  But I can reproduce the failure, those steps get me there, and the two log files were generated at the same time, from the start of the MPD and MyMPD daemons through those steps and through the failure.  That's all that I *actually* can say.  But I'm more than happy to collect whatever information that I can that would help you.

And again, thank you very much for your help.  Like I said, it seems I can avoid the issue by simply ignoring the default partition.  But I wanted to make sure you were aware of the issue.

**Comment by jcorporation** [comment]
I did some tests and I can reproduce your issue with two myMPD instances, but I think this is not a specific problem of two myMPD instances.

The same issue occurs if I connect ncmpc to the default partition and connect myMPD to an other partition. As soon I disconnect ncmpc the volume control works.

**Comment by MiM-TMassey** [comment]
Yay!  I'm glad I'm not crazy!  :)  I'm glad you can reproduce it on your end, but please let me know if I can provide additional information.

**Comment by jcorporation** [comment]
The same issue appears with two ncmpc instances. Volume could not be changed, even not in the default partition. I think this is a mpd bug.

**Comment by MiM-TMassey** [comment]
Well, then I'm glad I can bypass it:  I've had little (read: zero) success in communicating with MPD on my own.  If you prefer, I will create an issue with MPD linking to this, but I'm not enthusiastic.

**Comment by jcorporation** [comment]
I think we should report the bug, this gives us the chance that max fixes it. Its a bummer that max is the almost only MPD developer.

https://github.com/MusicPlayerDaemon/MPD/issues/1583

**Comment by jcorporation** [comment]
Bug is now fixed in MPD.
