### ISSUE TITLE
Page navigation is not functional in Database tab of Browse section

### ISSUE THREAD

**Issue by archphile** [jcorporation/myMPD#8]
Hi jcorp,

I am currently testing your latest master and found the following:

Page navigation is not functional  in Database tab of Browse section. I can see that my library is 8 pages, but apart from the first page I cant go to any other.

I tested with latest Firefox and Chromium under Archlinux on my desktop PC and the behaviour is the same in both browsers

Last but not least, I don't know If I should add here a small note on a feature request:

It would be really nice that "<<Page 1/X>>" is replaced with the standard filter of file system tab. This way, artist navigation will be easier than ever.

Thank you in advance,

Mike

**Comment by archphile** [comment]
Just tested after your fix and everything is fine.

Thanks!

**Comment by jcorporation** [comment]
You are to fast for me ;)

**Comment by archphile** [comment]
wow! you 're right, should have been more patient.

I just rebuilt and saw that apart from the fix, you included my feature request.

Thanks!
