### ISSUE TITLE
Missing "Disc 2" separator for multidisc albums for disc 2.

### ISSUE THREAD

**Issue by hrast01** [jcorporation/myMPD#800]
myMPD version: 9.4.1

**Describe the bug**

In a multidisc album in the details view of the Album, there's a "Disc 1" separator before the songs from Disc 1, there is no "Disc 2" separator before the songs from Disc 2.

**To Reproduce**

1. From the Grid view sorted by Album, Click on the Multidisc album
2. Before the first track from the first disc, there will be separator with the image of a CD and text saying "Disc 1"
3. Before the first track from subsequent discs, there is no separator for "Disc X"

**Expected behavior**

I would expect each disc in the album (that has appropriate Disc tags), to have a separator with the Disc number before the songs from that disc.

**Screenshots**

![multidisc-songs](https://user-images.githubusercontent.com/1563141/181311923-eea5f929-7031-4134-a512-fb22c3752506.png)

**Server plattform (please complete the following information):**
 - OS: DietPI
 - OS version: 8.6.1
 - Plattform: aarch64
 - MPD version: 0.22.6-1+b1

**Client plattform (please complete the following information):**
 - Device: Macbook Pro
 - OS: Monterrey
 - Browser: Firefox
 - Browser version: 103

**Comment by jcorporation** [comment]
myMPD expects the disc tag as a string that contains only one decimal value. Thats why the disc numbering is not working.

From the MPD protocol documentation:
- disc: the decimal disc number in a multi-disc album.

From id3v2 documentation:
TPOS
The 'Part of a set' frame is a numeric string that describes which part of a set the audio came from. This frame is used if the source described in the "TALB" frame is divided into several mediums, e.g. a double CD. The value may be extended with a "/" character and a numeric string containing the total number of parts in the set. E.g. "1/2". 

Quickly testing with my MPD instance on DietPi
- TPOS tag displayed by mid3v2: 1/2
- lsinfo response from MPD: 1

You should tag your files correctly with TPOS as 1/2 not 1,2.

**Comment by hrast01** [comment]
There was a "Disc Number" tag on the flacs I'm seeing the issues with.  I removed the Disc Number tag and now it shows up correctly.  Thanks for the nudge in the right direction!
