### ISSUE TITLE
Database doesn't index all the albums

### ISSUE THREAD

**Issue by edhelas** [jcorporation/myMPD#804]
myMPD version: 9.4.1

**Describe the bug**

The myMPD database doesn't show up all the albums, I tried downgrading but still haven't found why only a small part of the albums are shown. 

**To Reproduce**

![image](https://user-images.githubusercontent.com/3726886/182705517-59d64212-3198-4233-9a0a-0adfed6dd867.png)
When searching or going to "Supertramp" I only see one album.

![image](https://user-images.githubusercontent.com/3726886/182705633-9093bb95-66a2-4d16-a00e-c29e33fb6f15.png)
The filesystem view actually shows many more albums.

MPD indexed properly the albums, they are showing up correctly on other MPD clients, here on ncmcpp

![image](https://user-images.githubusercontent.com/3726886/182705962-55a73957-93f6-4db3-8470-a72bf57c2b03.png)

I was maybe thinking of a database corruption issue, if you need some logs do not hesitate to ask

Thanks for the awesome work by the way, myMPD is my daily MPD client :) !

**Comment by jcorporation** [comment]
This is usually a problem with the AlbumArtist tag enabled but some files are not tagged with this tag. myMPD creates the album view only from songs with AlbumArtist and Album tag. In previous versions myMPD implicitly falls back to the Artist tag, but this is not the case for newer myMPD versions.

Try to disable the AlbumArtist tag or add the tag to all your files.

#791 is a similar issue.

**Comment by edhelas** [comment]
I've answered in #791 as it is the same issue.
