### ISSUE TITLE
Issue with myMPD 0.9.5 behind a reverse proxy under a proxy-defined subfolder.

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#808]
myMPD version: 0.9.5

**Describe the bug**

With the latest release, myMPD fails to work properly when used behind a reverse proxy that publishes myMPD under a specific subfolder.

In my case, I run mympd behind a nginx reverse proxy under https://nas/myMPD/
When loading any page, I get the following errors in the browser's developper console.

From the output, one cas see that myMPD tries to load some resources from `https://nas/myMPDassets` instead of `https://nas/myMPD/assets`

Reverting to myMPD 9.4.1 fixes the issue.
```
XHR GET https://nas/myMPDassets/i18n/en-US.json
[HTTP/1.1 404 Not Found 0ms]

ERROR: Can not parse response to json object:<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>

combined.js:8:19143
ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data combined.js:8:19143
XHRGEThttps://nas/myMPDassets/ligatures.json
[HTTP/1.1 404 Not Found 0ms]

XHRGEThttps://nas/myMPDassets/i18n/en-US.json
[HTTP/1.1 404 Not Found 0ms]

ERROR: Can not parse response to json object:<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>

combined.js:8:19143
ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data combined.js:8:19143
ERROR: Can not parse response to json object:<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>

combined.js:8:19143
ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data combined.js:8:19143
XHRGEThttps://nas/myMPDassets/i18n/en-US.json
[HTTP/1.1 404 Not Found 0ms]

ERROR: Can not parse response to json object:<html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>nginx</center>

</body>

</html>

combined.js:8:19143
ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Expected behavior**

Have myMPD append the missing "/" in the URL for loaded resources.

**Screenshots**

![image](https://user-images.githubusercontent.com/4215150/184509924-fce5d31c-d7bd-48e2-b19d-12d1d07dd435.png)

**Server plattform (please complete the following information):**
 - OS: Debian
 - OS version 11
 - Plattform: x86_64

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Browser Firefox
 - Browser version 103.0.2

**Configuration (please attach if it can be usefull)**

nginx config snippet:
```
cat /etc/nginx/sites-enabled/nas
server {
    listen 0.0.0.0:443 ssl http2;
    listen [::]:443 ssl http2;
    server_name nas;

    # myMPD
    location /myMPD/ {
      proxy_pass http://127.0.0.1:880/;
      include conf.d/params/proxy.conf;
    }
}

# cat /etc/nginx/conf.d/params/proxy.conf
proxy_redirect          off;
proxy_set_header        Host                            $http_host;
proxy_set_header        X-Real-IP                       $remote_addr;
proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto       $scheme;
```

**Comment by jcorporation** [comment]
Fixed in devel. Please test.

**Comment by tsunulukai** [comment]
Fix in Devel solves the issue. Kudos for the usual quick reaction !

**Comment by Emilot** [comment]
Thank you JC

**Comment by tsunulukai** [comment]
There are still two files that myMPD try to load from an incorrect location when run behind a proxy in the described scenario:
![image](https://user-images.githubusercontent.com/4215150/184549468-6e7e9791-b41a-4b76-acf2-0df938daaea8.png)

This doesn't seem to prevent the application from working find though...

**Comment by jcorporation** [comment]
There was indeed two other occurrences of the erroneous assets path. Fixed with above commit in devel.

**Comment by tsunulukai** [comment]
Rebuilt from above commit and the errors are now gone.
Thanks !
