### ISSUE TITLE
Editing home icons with scripts requires refreshing the webpage

### ISSUE THREAD

**Issue by furtarball** [jcorporation/myMPD#814]
myMPD version: 9.5.1

**Describe the bug**

I'd like to make a power indicator on the home screen and I've figured out everything I need, but any update to homescreen icons made by scripts requires refreshing the webpage. I expected it not to, because editing home icons manually doesn't.

**To Reproduce**

1. Create a new script
2. Insert an API call that edits home screen icons in it, for example MYMPD_API_HOME_ICON_SAVE
3. Click save and execute the script

**Expected behavior**
New or changed home icon visible immediately.

**Server plattform (please complete the following information):**
 - OS: Alpine
 - OS version: edge
 - Plattform: aarch64
 - MPD version: 0.23.9

**Client plattform (please complete the following information):**
 - Device: phone, PC
 - OS: Android, Fedora
 - Browser: Firefox 103, Epiphany 42.3

**Comment by jcorporation** [comment]
There is no trigger from the backend to refresh home icons after a change. The frontend initiates this refresh.

Cool idea with the power indicator. It would be great if you can publish your code.

**Comment by jcorporation** [comment]
In devel is now a new API method `MYMPD_API_HOME_ICON_REFRESH` that triggers a refresh event `update_home`. Please test.

**Comment by jcorporation** [comment]
There is now a `update_home` event that should resolve this.
