### ISSUE TITLE
Bugs while using Chinese

### ISSUE THREAD

**Issue by dream7180** [jcorporation/myMPD#820]
Please see attached picture, 2 bugs when open the main menu with Chinese in use.
1. Java script err message about incorrect locale.
2. Blank information list.

![image](https://user-images.githubusercontent.com/18242221/186400107-f0aefdc6-508a-4510-a6f9-77dd32dc9410.png)

**Comment by jcorporation** [comment]
Error is thrown by `.toLocaleString("cn-CHS");
It seems this locale string is invalid for this prototype. Can you tell me the right locale string?
