### ISSUE TITLE
MYMPD_HTTP_PORT environment variable doesn't work on latest docker container image

### ISSUE THREAD

**Issue by utylee** [jcorporation/myMPD#821]
On latest docker container, only http port 80 is available.

But on tag 9.4.1, I confirmed no problem was there.

** My executed command was:

docker run -d \
  --name=mympd \
  --net="host" \
  -e TZ=Europe/London \
  -e UMASK_SET=022 \
  -e MYMPD_SSL=false \
  -e MYMPD_HTTP_PORT=88 \
  --restart unless-stopped \
  ghcr.io/jcorporation/mympd/mympd

**Comment by jcorporation** [comment]
Fixed in devel.
