### ISSUE TITLE
9.5.3 failed to change locale

### ISSUE THREAD

**Issue by dream7180** [jcorporation/myMPD#830]
Whatever language, except default. When apply, Err of "Invalid filename".
![image](https://user-images.githubusercontent.com/18242221/188156451-6c7cdc64-5e39-491c-9ff9-384295111502.png)

When open the "setting" dialog, err message pop as below:
![image](https://user-images.githubusercontent.com/18242221/188157326-6bf68c13-3232-4579-8955-963a950ba052.png)

**Comment by jcorporation** [comment]
I can not reproduce your issue. The error message points to an outdated javascript resource. Try cleaning up the browsers cache or a different browser.

**Comment by dream7180** [comment]
I try with Chrome and Edge, I clean the cache and the Javascrpit error dispear. But change language still failed with "Invalid filename". When I change that three filename setting values and apply, get below error message:
![image](https://user-images.githubusercontent.com/18242221/188277767-803df84c-24c5-4202-8c67-fc3039df0512.png)

**Comment by jcorporation** [comment]
Latest screenshot shows a bug. An empty smart playlist prefix value should be allowed. Fixed with commit 01871a6 and is in devel branch.

**Comment by dream7180** [comment]
Today the whole interface get into a mass (English):
![image](https://user-images.githubusercontent.com/18242221/188909417-a509e3d0-6733-4559-a422-5324b8aa13dd.png)

![image](https://user-images.githubusercontent.com/18242221/188909574-86f63757-e085-44d6-9acd-62607d9cc9b9.png)

**Comment by jcorporation** [comment]
Please provide debug logs, browser logs and an archive of the /var/lib/mympd/state directory.

**Comment by dream7180** [comment]
/var/lib/mympd/state directory.
[state.zip](https://github.com/jcorporation/myMPD/files/9527468/state.zip)

**Comment by jcorporation** [comment]
Logs?

**Comment by jcorporation** [comment]
Found a locale related bug fixed with above commits. It could fix your problem, please test the devel branch. If it does not work, compile a debug build and provide logs.

**Comment by dream7180** [comment]
I have complied devel branch but the problem seems remained.  Below is the running log:
`[dream@diynas ~]$ sudo mympd
04:56:08 NOTICE   mympd     Work dir: "/var/lib/mympd"
04:56:08 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
04:56:08 NOTICE   mympd     Cache dir: "/var/cache/mympd"
04:56:08 NOTICE   mympd     Setting loglevel to NOTICE
04:56:08 NOTICE   mympd     Starting myMPD 9.5.4
04:56:08 NOTICE   mympd     Listening on http://0.0.0.0:8001
04:56:08 NOTICE   mympd     Serving files from "/var/lib/mympd/empty"
04:56:08 NOTICE   mympd     Droping privileges to user "mympd"
04:56:08 NOTICE   mympd     Empty dir: "/var/lib/mympd/empty"
04:56:08 NOTICE   mympd     Pics dir: "/var/lib/mympd/pics"
04:56:08 NOTICE   mympd     Backgrounds dir: "/var/lib/mympd/pics/backgrounds"
04:56:08 NOTICE   mympd     Thumbnails dir: "/var/lib/mympd/pics/thumbs"
04:56:08 NOTICE   mympd     Scripts dir: "/var/lib/mympd/scripts"
04:56:08 NOTICE   mympd     Smartpls dir: "/var/lib/mympd/smartpls"
04:56:08 NOTICE   mympd     State dir: "/var/lib/mympd/state"
04:56:08 NOTICE   mympd     Webradio dir: "/var/lib/mympd/webradios"
04:56:08 NOTICE   mympd     Covercache dir: "/var/cache/mympd/covercache"
04:56:08 NOTICE   mympd     Webradiodb cache dir: "/var/cache/mympd/webradiodb"
04:56:08 NOTICE   mympd     Starting mympd api thread
04:56:08 NOTICE   mympd     Starting webserver thread
04:56:08 NOTICE   mympdapi  Reading states
04:56:08 NOTICE   mympdapi  Connecting to "localhost:6600"
04:56:08 NOTICE   mympdapi  Connected to MPD
04:56:08 NOTICE   mympdapi  MPD protocol version: 0.23.5
04:56:08 ERROR    mympdapi  Invalid music_directory value: "auto"
04:56:08 WARN     mympdapi  Disabling library feature, music directory not defined
04:56:08 NOTICE   mympdapi  MPD supported tags: Artist ArtistSort Album AlbumSort AlbumArtist AlbumArtistSort Title Track Name Genre Date OriginalDate Composer ComposerSort Performer Conductor Work Movement MovementNumber Ensemble Location Grouping Disc Label MUSICBRAINZ_ARTISTID MUSICBRAINZ_ALBUMID MUSICBRAINZ_ALBUMARTISTID MUSICBRAINZ_TRACKID MUSICBRAINZ_RELEASETRACKID MUSICBRAINZ_WORKID 
04:56:08 NOTICE   mympdapi  Enabled tag_list: Album AlbumArtist Artist Disc Genre Name Title Track 
04:56:08 NOTICE   mympdapi  Enabled tag_list_search: Album AlbumArtist Artist Genre Title 
04:56:08 NOTICE   mympdapi  Enabled tag_list_browse: Album AlbumArtist Artist Genre 
04:56:08 NOTICE   mympdapi  Enabled smartpls_generate_tag_list: Genre 
04:56:08 NOTICE   mympdapi  Enabling partitions feature
04:56:08 NOTICE   mympdapi  Enabling binarylimit feature
04:56:08 NOTICE   mympdapi  Enabling delete playlist range feature
04:56:08 NOTICE   mympdapi  Enabling position whence feature
04:56:08 WARN     mympdapi  Disabling advanced queue feature, depends on mpd >= 0.24.0
04:56:09 ERROR    webserver HTTP 404: Embedded asset "/assets/i18n/zh-CN.json" not found
04:56:10 ERROR    webserver HTTP 404: Embedded asset "/assets/i18n/zh-CN.json" not found
04:56:10 ERROR    webserver HTTP 404: Embedded asset "/assets/i18n/zh-CN.json" not found
04:56:10 NOTICE   mympdapi  Starting mpd_worker thread for INTERNAL_API_CACHES_CREATE
04:56:10 NOTICE   mpdworker Connecting to "localhost:6600"
04:56:10 NOTICE   mpdworker Connected to MPD`

**Comment by jcorporation** [comment]
Error: 04:56:09 ERROR webserver HTTP 404: Embedded asset "/assets/i18n/zh-CN.json" not found

Please provide build logs.

**Comment by jcorporation** [comment]
Found another zh-cn related bug. Please try again with updated devel branch.

**Comment by dream7180** [comment]
It is fixed with the update, now app can recognize proper default locale zh-CN. No err so far. Thank you!!
