### ISSUE TITLE
Some album art images not displaying

### ISSUE THREAD

**Issue by aereaux** [jcorporation/myMPD#832]
myMPD version: 9.5.3

**Describe the bug**

I am missing album art for some albums in my collection, even though there is a cover.png file and mpc reads the albumart fine.

**To Reproduce**

1. Have https://beta.musicbrainz.org/release/39df442e-f48b-4f76-bbfe-3df2bc6d772d in your library
2. Search for that album
3. Album art does not appear, instead seeing "not available" placeholder

**Expected behavior**

Album art appears

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: Arch Linux
 - OS version: Most recent rolling
 - Plattform: x86_64
 - MPD version: 0.23.9

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Arch Linux
 - Browser: Firefox
 - Browser version: 104.0.2

**Debug logs (please attach if it can be usefull)**

I see this in the logs when I try to get albumart:
```
Sep 09 11:21:06 hostname mympd[652037]: WARN     mympdapi  Retrieved binary data is too large, discarding
```
 
**Configuration (please attach if it can be usefull)**

**Additional context**
Let me know if any other info would be helpful

**Comment by tsunulukai** [comment]
How big is the cover.png file for that album ? In the log file line you underline, them problem clearly seems to be that file is too large. Can you try to resize it to lower dimensions and see if the problem persist ?

**Comment by jcorporation** [comment]
Reading the error message helps ;)

The limit is 5 MB.

**Comment by aereaux** [comment]
Thanks for the information.  Is there a technical reason for the limit or is it configurable?

**Comment by jcorporation** [comment]
There is no specific reason. I could raise the limit for 9.5.4 to 10 mb, but so large images slows down the ui rendering.

**Comment by jcorporation** [comment]
Limit is set at compile time:

https://github.com/jcorporation/myMPD/blob/master/src/compile_time.h.in:
`#define MPD_BINARY_SIZE_MAX 5242880 //5 MB`

**Comment by aereaux** [comment]
That's true.  I guess one other solution would be to resize images appropriately on the backend, but I don't know if I need to have a 15MB cover art image so I'll probably resize them as well

Also, for some reason some of the cover images that are over 5MB do appear.  Any idea why that could be?

**Comment by jcorporation** [comment]
The limit restricts only the images read from mpd. If myMPD reads the file directly from the music directory no limit is enforced.

**Comment by aereaux** [comment]
OK, I added the library location to the mpd connection settings, but it seems that now the albumart api url is returning 404 (instead of the not available svg).  Any idea what might be wrong now?

**Comment by jcorporation** [comment]
Please provide debug logs.

**Comment by aereaux** [comment]
This should be the relevant part of the logs (I'm `curl`ing the albumart api endpoint):
```
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver New connection id "8" from [0:0:0:0:0:0:0:0]:39620, connections: 3
Sep 10 11:48:54 adesktop mympd[3911660]: INFO     webserver HTTP request (8): GET /albumart
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Connection: close header found (8)
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Handle albumart for uri "Billy Joel/The Hits/01 Everybody Loves You Now.flac", offset 0
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Searching image file for basename "/var/cache/mympd/covercache/bab95f366658c05c5783a9a51135a937d82f8090-0"
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver No covercache file found
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Absolut media_file: /data/music/beets/Billy Joel/The Hits/01 Everybody Loves You Now.flac
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Searching image file for basename "/data/music/beets/Billy Joel/The Hits/folder"
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Searching image file for basename "/data/music/beets/Billy Joel/The Hits/cover"
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Serving file /data/music/beets/Billy Joel/The Hits/cover.png (image/png)
Sep 10 11:48:54 adesktop mympd[3911660]: DEBUG    webserver Set connection 8 to is_draining
Sep 10 11:48:54 adesktop mympd[3911660]: INFO     webserver HTTP connection 8 closed
```

**Comment by jcorporation** [comment]
Strange, the log shows no errors and the webserver should deliver `/data/music/beets/Billy Joel/The Hits/cover.png`. Can you confirm that the filepath is correct and myMPD has permissions to read this file?

**Comment by aereaux** [comment]
Good catch, thanks!  The files were 600.  I changed the permissions and it's working again now.
