### ISSUE TITLE
Some strings not localized in the interface

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#834]
myMPD version: 10.0.0 devel c1928e13a7580844b68819d9e0c11cc355a633aa

**Describe the bug**

Some strings are not localized although the translations are present in the language file.
The same strings are localized in defferent parts of the interface, so the issue is not related to the json lang file.

N.B.: I used the latest available json file from POEditor in french to illustrate this.

Dropdown list under settings/general/startup
![image](https://user-images.githubusercontent.com/4215150/190923169-519dd333-b7d4-43fe-8375-5e3e50209708.png)

Dropdown list under settings/advanced

![image](https://user-images.githubusercontent.com/4215150/190922872-d6c81bb3-2224-4a14-9e92-575b4ea6527a.png)

Dropdown list under settings/appearance/footer
![image](https://user-images.githubusercontent.com/4215150/190922958-07135d0d-2806-4b1e-932d-7fd0215c22d3.png)

**Comment by jcorporation** [comment]
Thanks for reporting this. All automatically populated selects in the settings modal are not translated. This is fixed with above commit.

P.S:
There are two phrases missing in the NL translation, FR is complete:
```
Phrase "OverridesStreamPort" for nl-NL not found
Phrase "Reset" for nl-NL not found
```

**Comment by tsunulukai** [comment]
> Thanks for reporting this. All automatically populated selects in the settings modal are not translated. This is fixed with above commit.
> 
> P.S: There are two phrases missing in the NL translation, FR is complete:
> 
> ```
> Phrase "OverridesStreamPort" for nl-NL not found
> Phrase "Reset" for nl-NL not found
> ```

I've added the two missing NL translations
