### ISSUE TITLE
Sorting queue by position returns error

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#835]
myMPD version: 10.0.0 devel c1928e13a7580844b68819d9e0c11cc355a633aa

**Describe the bug**

Sorting the queue by track position in the queue returns an error: `Validation of value for JSON path "$.params.sort" has failed`

![image](https://user-images.githubusercontent.com/4215150/190923638-7fbf4096-4962-4be7-ab11-5fe0677e6545.png)

**Comment by jcorporation** [comment]
Pos is invalid for sorting the queue, this must be mapped to Priority. Is now fixed.

**Comment by tsunulukai** [comment]
This one is indeed fixed, but I have the same error with a view that previously worked, but doesn't anymore:

I configured a shortcut on my home screen to display the latest additions to my collection.
![image](https://user-images.githubusercontent.com/4215150/190924962-41bc46a3-c6ba-4403-82b1-8b787cd262d6.png)

In a previous release, this would work as expected. Now it returns the same error `Validation of value for JSON path "$.params.sort" has failed`

![image](https://user-images.githubusercontent.com/4215150/190924994-9631a20c-e24b-4bb1-8fb9-626c3ffadaeb.png)

**Comment by jcorporation** [comment]
The syntax of the sort tag has changed in one of the previous versions. The new syntax for your case is `{"tag":"LastModified","desc":true}`

**Comment by tsunulukai** [comment]
Thanks for the info !
