### ISSUE TITLE
Support consume oneshot

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#837]
New MPD 0.24 feature
https://github.com/MusicPlayerDaemon/MPD/commit/48a936ef5bd1c362806afcbb0470e8a542a7bc16

libmpdclient support: https://github.com/MusicPlayerDaemon/libmpdclient/pull/91

**Comment by tsunulukai** [comment]
Added FR/NL 3 extra phrases translations in POEditor
