### ISSUE TITLE
Connection Refused after multiple browser launch

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPD#84]
**Connection Refused**
After mutliples mympd launch, the connection to mpd is refused.
I use mympd as a "web app" with a dedicated browser/launcher. It seems that when closing a browser, mympd doesn't close the connection to mpd. The log of mpd show the number of clients increasing, and refuse to connect when it reaches the limit of mpd.conf

**To Reproduce**
1. Use[surf](https://surf.suckless.org/) to connect to mympd
2. Close surf
3. repeat a few times
4. Connection to mpd refused

**Comment by jcorporation** [comment]
myMPD opens the mpd connection on startup and keeps only one connection open till shutdown of myMPD. There should be no browser dependencies.

Please increase the log level of myMPD and start myMPD manually and post the output here.
