### ISSUE TITLE
Javascript errors in Queue View

### ISSUE THREAD

**Issue by radiant-radish** [jcorporation/myMPD#840]
myMPD version: [10.0.0]

Javascript error when using quick remove on queue entry:

"TypeError: can't assign to property "textContent" on "currentTitleEl": not an object (http://192.168.0.201:1333/js/combined.js: 8)"
This error seems to be popping up when in the Queue view on other occasions i.e. not just when removing an entry.

**To Reproduce**
1. Go to Queue (with some tracks present)
2. Click on the Quick Remove button to remove a track
3. Track is removed but error message displayed

**Server plattform **
 - OS: [DietPI]
 - OS version [5.15.61-v7]
 - Plattform: [armv7]
 - MPD version: [0.22.6]

**Client plattform**
 - Device: [PC]
 - OS: [Linux Mint 19.10]
 - Browser [Firefoxi]
 - Browser version [104.0.2]

**Comment by jcorporation** [comment]
This is already fixed for devel: https://github.com/jcorporation/myMPD/commit/8859b86680d5732cc55fe4aa0a7107178a466b53
