### ISSUE TITLE
The sort by date is not working

### ISSUE THREAD

**Issue by Ezka77** [jcorporation/myMPD#845]
myMPD version: devel githash 0dd31440

**Describe the bug**

The sort by date is not sorting by `date`. Yet the `last modified` sort is working as expected. The album tags are from MBZ eg Date: 2004-01-21

The `last modified` date is localized by the UI but not the `date`.

NB: the sort by date was working like 1 or 2 month ago.

**To Reproduce**

1. Go to Browse
2. Click on "Sort by"
3. Select Date
4. Error: the albums list is not sorted by date

**Expected behavior**

To sort albums by date

**Screenshots**

Here screenshots with the UI in Fr (I've tested it with the Us locale same issue), the first one is the sort by `albumartist`, and the second one by `date`.

![2022-09-25 162743](https://user-images.githubusercontent.com/1818604/193399798-2543bd26-d6ea-4d3a-b923-4721ad528c48.jpg)

![2022-09-25 162834](https://user-images.githubusercontent.com/1818604/193399806-ee902d4b-ceee-4005-9e8d-883ed7775b77.jpg)

**Server plattform (please complete the following information):**
 - OS: Alpine Linux
 - OS version 3.16
 - Plattform: x86_64
 - MPD version: 0.23.7

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser Firefox
 - Browser version [e.g. 22]

**Debug logs (please attach if it can be usefull)**

Let me know if you need logs

**Comment by jcorporation** [comment]
The album cache have used only the default tags for mympd and not the enabled tag types list. This should be fixed with commit 28db447. Can you test again?

**Comment by Ezka77** [comment]
Yes and It works now ! 👏
