### ISSUE TITLE
ListenBrainz Feedback trigger script errors with 10.0.0

### ISSUE THREAD

**Issue by aereaux** [jcorporation/myMPD#846]
myMPD version: [e.g. 8.1.0]

**Describe the bug**

With the upgrade to v10.0.0, my Listenbrainz feedback script now errors with:
```
Error executing script LB Feedback: Runtime error: /var/lib/mympd/scripts/LB Feedback.lua:7: attempt to sub a 'string' with a 'number'
```
It looks like the "vote" argument is not getting populated.

**To Reproduce**

1. Install the Listenbrainz Feeback trigger and script as normal
2. Click on the thumbs up button
3. See error

**Expected behavior**

Script completes successfully and result appears in listenbrainz

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: Arch Linux
 - OS version: Rolling, latest as of this posting
 - Plattform: x86_64
 - MPD version: 0.23.9

**Client plattform (please complete the following information):**
 - Device: Phone
 - OS: Android
 - Browser: Firefox
 - Browser version: 105.1.0

**Debug logs (please attach if it can be usefull)**

Can attach these if needed.
 
**Configuration (please attach if it can be usefull)**

Can attach these if needed

**Additional context**

I looked at the code a bit, and it seems like the problem was probably caused with [this change](https://github.com/jcorporation/myMPD/commit/4e2d4a3acdd2db4b2ac4abcb4930ea4a4590c7bd#diff-1bfaba3134ae3baf000a1230060ed6a5fffbe0790241febee34300ff49fe9281R154).  It looks like it now ignores the `script_arguments` `t_list`, instead passing in `&trigger_data->arguments`, which probably doesn't include the vote (or uri).  I was trying to understand the code here in order to write up a patch, but it's been a while since I've written a lot of C.  Does some merging need to go on between the two lists, or can the `script_arguments` list just be passed in as is (like it was before)?

**Comment by jcorporation** [comment]
Thanks for reporting and analyzing this bug.

> Does some merging need to go on between the two lists, or can the script_arguments list just be passed in as is (like it was before)?

Just like before.

**Comment by jcorporation** [comment]
Bug should be fixed with above commit, can you test?

**Comment by aereaux** [comment]
Yeah, I noticed the bug in the script and fixed it earlier.

Great, it works now with this change!
