### ISSUE TITLE
Interface items not translated in interface although translation exists.

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#849]
I found a few other occurrences of elements for which a translation exists in the language files, but is not applied in the interface:

![image](https://user-images.githubusercontent.com/4215150/193449573-38b0964a-f7bb-4581-8f20-a1c5a2787668.png)

![image](https://user-images.githubusercontent.com/4215150/193449517-b6c14636-7b20-4126-811a-e1a9b0d4a8ec.png)

![image](https://user-images.githubusercontent.com/4215150/193449622-49b7c47e-669b-4bbb-ba7a-79c9e637918a.png)

![image](https://user-images.githubusercontent.com/4215150/193449637-d1d6f62e-8e1f-4245-85fd-add6fea2b6b1.png)

![image](https://user-images.githubusercontent.com/4215150/193449664-29dff499-d128-4354-aad7-e502a5785b9f.png)

![image](https://user-images.githubusercontent.com/4215150/193449731-40239ad2-ded7-404f-a149-95ddc8ee8a4e.png)

![image](https://user-images.githubusercontent.com/4215150/193449769-953a19f9-970a-473e-83d9-cd1b5ad869d0.png)

**Comment by jcorporation** [comment]
Fixed with above commit. I found some additional places where the javascript does not insert a data-phrase attribute in created elements. This bugs are coming  to light because of the asynchronous fetch of the translation files since 9.5.0.

**Comment by tsunulukai** [comment]
Great !
FYI, I updated existing french translations on POEditor again... a few fixes for items which were not easy to understand from a non-geek user perscpective :)

**Comment by jcorporation** [comment]
Thanks! Fetched into devel.
