### ISSUE TITLE
When using ffmpeg as mp3 decoder an odd bit value (224 instead of 24) is displayed

### ISSUE THREAD

**Issue by GK-774** [jcorporation/myMPD#855]
myMPD version: 10.0.3

It´s not really something important, but I thought I report it nevertheless. When I disable mad and mpg123 in mpd.conf, ffmpeg will be used for mp3 decoding.

MyMPD now shows "224bits" instead of "24bits" (see screenshot).

ncmpc reports: Format:    48000:f:2
and hw_params is:
format: S32_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)

Might be that ffmpeg just reports a bogus number, no idea what the "f" stands for in ncmpcs output.

![mp3_224_bits](https://user-images.githubusercontent.com/75694230/195870772-308865eb-4f39-42b8-9ed0-f98bc699771c.jpg)

**Comment by jcorporation** [comment]
Strange, can you grab the jsonrpc response?

**Comment by GK-774** [comment]
If you tell me how to do that, yes.

**Comment by GK-774** [comment]
Log, when starting a mp3 stream and changing to the playback view.
[log.zip](https://github.com/jcorporation/myMPD/files/9787632/log.zip)

**Comment by jcorporation** [comment]
Responses can be inspected with the web developer tools of your browser. You can use the network tab, alternatively myOlogs all responses in the js console if it is in debug mode.

**Comment by GK-774** [comment]
You mean this?

jsonrpc	"2.0"
id	0
result	Object { method: "MYMPD_API_PLAYER_STATE", state: "play", volume: -1, … }
method	"MYMPD_API_PLAYER_STATE"
state	"play"
volume	-1
songPos	0
elapsedTime	248
totalTime	0
currentSongId	1
kbitrate	192
queueLength	1
queueVersion	18
nextSongPos	-1
nextSongId	-1
lastSongId	-1
partition	"default"
AudioFormat	Object { sampleRate: 48000, bits: 224, channels: 2 }
sampleRate	48000
bits	224
channels	2
lastError	""

Raw:

{"jsonrpc":"2.0","id":0,"result":{"method":"MYMPD_API_PLAYER_STATE","state":"play","volume":-1,"songPos":0,"elapsedTime":248,"totalTime":0,"currentSongId":1,"kbitrate":192,"queueLength":1,"queueVersion":18,"nextSongPos":-1,"nextSongId":-1,"lastSongId":-1,"partition":"default","AudioFormat":{"sampleRate":48000,"bits":224,"channels":2},"lastError":""}}

**Comment by jcorporation** [comment]
Exactly this. Can you get the MPD response to the "status" command?
Example:
```
socat - UNIX-CONNECT:/run/mpd/socket 
status
```

**Comment by GK-774** [comment]
socat - UNIX-CONNECT:/run/mpd/socket
OK MPD 0.23.5
status
repeat: 0
random: 0
single: 0
consume: 1
partition: default
playlist: 2
playlistlength: 1
mixrampdb: 0
state: play
song: 0
songid: 1
time: 267:0
elapsed: 267.484
bitrate: 0
audio: 48000:f:2
OK

**Comment by GK-774** [comment]
Nice!
