### ISSUE TITLE
Folder Shortcuts

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPD#86]
**Context**
I often find myself browsing through the filesystem, to find a podcasts or a web radio I want to listen to. It can be a long a tedious process to find the right folder

**Solution**
Perhaps you could add a "Folders Shortcuts" parameter in the conf file, wich would allow to add folder shortcuts to the top bar for example ?
Anywhere which would make some folders easy to reach would be really nice

Thanks

**Comment by jcorporation** [comment]
Folder Shortcuts or general shortscuts are a good idea. I think they should be manageable in the gui.

**Comment by jcorporation** [comment]
Feature is now implemented in master.
