### ISSUE TITLE
Display issue of Queue card in mobile

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#868]
myMPD version: [latest]

**Describe the bug**

**To Reproduce**

1. Two(or more) pages in Queue card
2. Click on icon to go to next page
3. The half of the image is gone and a white space appears
4. look at screenshot

**Expected behavior**

To be responsive in mobile

**Screenshots**

![Screenshot_2022-10-23-16-24-15-282_org mozilla focus](https://user-images.githubusercontent.com/18086896/197404015-99e2a202-4720-49ba-b2ed-ae2dce192b28.jpg)

**Client plattform (please complete the following information):**
Firefox on mobile

**Comment by jcorporation** [comment]
It seems the view does not always scroll to top if the mobile view is active. Can you scroll manually to top after going to the second page?

**Comment by jcorporation** [comment]
Above fix worked for me, can you test the devel branch?

**Comment by Emilot** [comment]
Hi JC. I think you misunderstand my post(but you solve another problem :) 

I menat the issue with the buttons to go to the next page or choose a page, etc...that goes beyond(extend) the mobile screen to the right. It is not responsive i think or something like that. Look at the screen:

![Screenshot_2022-10-24-14-53-26-487_org mozilla focus](https://user-images.githubusercontent.com/18086896/197520027-b979a3f0-4d8f-4d02-832d-5d145d257678.jpg)

It would be great if it "centers" like when i press the Volume for example.

**Comment by jcorporation** [comment]
It seems that the dropup was to big for your relatively small screen. I set now a max width of 80% of the full width. This should fix this issue. Please test devel.

**Comment by Emilot** [comment]
Thank you JC. It is fine now! :)
