### ISSUE TITLE
Thumbs up/down broken

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#870]
myMPD version: 10.1.0 (container devel: `sha256:c5db57eb4dba62a73be4fe032d3ee4dbed8fb2f9d8b59538e8c6bf1efae53e9f`)

**Describe the bug**

Thumbs up/down (Love/Hate song) is broken.

**To Reproduce**

1. Go to 'Playback'
2. Click on 'Love/Hate song'
3. See error: `TypeError: aEl is null (https://localhost/js/combined.js: 8)`

**Server plattform (please complete the following information):**
 - OS: Fedora
 - OS version 36
 - Plattform: x86_64
 - MPD version: 0.23.9

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Fedora
 - OS version 36
 - Browser: Firefox
 - Browser version: 106.0.1

**Comment by jcorporation** [comment]
Thanks for testing devel, bug is fixed with above commit.
