### ISSUE TITLE
Improve build requirements for downstream packaging

### ISSUE THREAD

**Issue by dvzrv** [jcorporation/myMPD#871]
myMPD version: 10.0.3 (applies to earlier)

**Describe the bug**

Hi! I would like to package this project for Arch Linux. However, I have run into a lot of issues with the build system, that I will try to outline below, as they will also affect other packager's willingness to package this project.

The build.sh script bundles *a lot* of functionality, that will never be used by downstream packagers and yet is completely intertwined with what the cmake setup relies upon.

* the cmake options are not correctly [documented](https://jcorporation.github.io/myMPD/installation/compiling) and do not match (e.g. MANPAGES does not exist as a cmake option, MYMPD_INSTALL_PREFIX should be CMAKE_INSTALL_PREFIX) but should be provided as an environment variable(?!)
* the build.sh script does not check for availability of tooling (e.g. it will fail if perl is not available) -> all of that is cmake's job!
* the build.sh script prevents distribution aligned use of cmake (e.g. using `CMAKE_BUILD_TYPE=None` so that distribution wide build flags apply).
* the build.sh script prevents out of tree builds (see repro steps below), without additional steps (e.g. moving files around).
* the build.sh script (if run for a full build) would download and install dependencies on a target system. This is an absolute no-go from a packager perspective (the build systems define the dependencies as input, during build time the system user building the software doesn't even have the privileges to install more software) and is also a huge intervention into any end user's system (if they were to run build.sh). 
* out-of-tree build with cmake (running e.g. `cmake -S myMPD-10.0.3 -B build ..` one level above the project) is broken, because of hardcoded paths (e.g. `#include "../dist/rax/rax.h"`) and not relying on cmake's functionality (see logs)

All in all, the above actively prevents packagers to package this project for downstream distributions. Please only use cmake.

**To Reproduce**

1. `cd myMPD-10.0.3`
2. `./build.sh createassets`
3. `cd ..`
4. `cmake -B build -S myMPD-10.0.3 -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev` 
5. build fails because of hardcoded paths and assumptions (see logs)

**Expected behavior**

Only cmake is required for building, default options are used. Project specific options are ideally prefixed.

**Screenshots**

n/a

**Server plattform (please complete the following information):**
 - OS: Arch Linux
 - OS version n/a
 - Plattform: x86_64
 - MPD version: n/a

**Client plattform (please complete the following information):**
 - Device: n/a
 - OS: Arch Linux
 - Browser n/a
 - Browser version n/a

**Debug logs (please attach if it can be usefull)**
[mympd-10.0.3-1-x86_64-build.log](https://github.com/jcorporation/myMPD/files/9893285/mympd-10.0.3-1-x86_64-build.log)
[mympd-10.0.3-1-x86_64-prepare.log](https://github.com/jcorporation/myMPD/files/9893286/mympd-10.0.3-1-x86_64-prepare.log)

 
**Configuration (please attach if it can be usefull)**
n/a

**Additional context**

All downstream distributions have their own build infrastructure and specific packaging guidelines that must be met (e.g. build in a clean chroot, build scripts/metadata in a distribution hosted repository).
Using a wrapper around cmake (which is a fully fledged build system for nearly all intends and purposes) is not a good idea and will actually prevent downstreams from packaging this instead of picking it up, as it is more hassle to deal with (and prevents/breaks a lot of assumptions).

I understand why build.sh exists (from a developer perspective), but all of its functionality should reside in the cmake setup instead. From a packager perspective, having to jump through hoops to package a project greatly reduces the likelyhood of it actually being packaged. Scripts such as build.sh will never be used by downstream packagers.

That all being said: You will be able to cut down on *a lot* of complexity by transferring build.sh's prepare and build functionality into the cmake setup and only document that.
Furthermore, building distribution specific packages can then be done based upon the distribution specific tooling (e.g. devtools on Arch Linux) on e.g. tagged releases in github CI (or whatever is your preferred CI).

**Comment by jcorporation** [comment]
Do you think it’s better that cmake calls build.sh to create the assets? build.sh is mostly created for me to automate some steps.

**Comment by dvzrv** [comment]
Yes, creating the assets (if they should be bundled) should be part of what cmake does.

The creation of the assets could be a separate script, if that is easier, but cmake should be the top-most entry point to building the project (anything else gets very intransparent and hard to change for downstreams unfortunately).

**Comment by jcorporation** [comment]
Moving functions out of build.sh could be a good idea.

**Comment by dvzrv** [comment]
btw, you can remove all of the Arch Linux package integration now (unless you specifically still want to make use of that).
By extension, myMPD will end up on all the sister projects of Arch Linux by me packaging it.

**Comment by jcorporation** [comment]
I will keep the arch package integration for now.

**Comment by jcorporation** [comment]
I implemented some improvements for the build process:

- Added MANPAGES option to cmake
- Replaced MYMPD_INSTALL_DIR with CMAKE_INSTALL_DIR
- Fixed includes to support out-of-tree builds
- cmake calls now `./build.sh createassets`
- Build script checks for perl executable
- updated documentation

`cmake -B build -S myMPD -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev` should now work.

All the options to download and install packages in the `build.sh` script are not designed for packagers.

I hope this changes makes the life for packagers easier.

**Comment by jcorporation** [comment]
@dvzrv: could you test my changes if they fixes your packaging issues?

**Comment by jcorporation** [comment]
I reworked the cmake infrastructrue completely. CMAKE_BUILD_TYPE=None do not touch any compile and linker options, only Release and Debug sets myMPD default values.
