### ISSUE TITLE
DIsplay issue - Green lines in Queue card

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#881]
myMPD version: [latest]

**Describe the bug**

When a song ends the green bar doesn't disappear like it should and continues to the next song, etc...

**To Reproduce**

1. Play a song
2. Wait to end
3. Green line continue to the next

**Expected behavior**

To disappear and start to the next song

**Screenshots**

![Untitled-1](https://user-images.githubusercontent.com/18086896/200184625-e4fdb8c7-2d86-4b31-9f96-2aee2a26b0a8.jpg)

Desktop Firefox (latest)

**Comment by jcorporation** [comment]
Fixed in devel.
