### ISSUE TITLE
.ape files showing as Playlists

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#883]
myMPD version: [latest]

**Describe the bug**

.ape files are showing like Playlists

**To Reproduce**

1. Go to an .ape audio file
2. Click on it
3. See error

**Expected behavior**

To play the files

**Screenshots**

![ape](https://user-images.githubusercontent.com/18086896/200193936-0bbe0fc0-beb0-40e6-9230-c47b29c2eecc.jpg)

**Comment by jcorporation** [comment]
Type is determined by MPD not by myMPD. Are this single APE files or an APE file with a cuesheet?

A native `lsinfo` response from MPD for this directory could points in the right direction.

e.g.
```
telnet localhost 6600
lsinfo Testfiles
```

**Comment by Emilot** [comment]
APE files are as single files, not a .cue.

lsinfo respond with "access denied" message in every directory i tried.

**Comment by jcorporation** [comment]
MPD thinks this is a playlist, compare it with none-ape files, line should begin with file:

**Comment by jcorporation** [comment]
https://github.com/MusicPlayerDaemon/MPD/issues/1663
