### ISSUE TITLE
Building myMPD on Fedora 36 fails

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/myMPD#886]
### Discussed in https://github.com/jcorporation/myMPD/discussions/885

<div type='discussions-op-text'>

<sup>Originally posted by **avalx** November  7, 2022</sup>
I'm trying to build a rpm package for the dev version but I got an error. When I run `build.sh pkgrpm` it immediately fails with error:

error: line 43: %package debuginfo
: package mympd-debuginfo already exists

My system is Fedora 36 with all the latest updates. Some time ago this process was working without problems, so I'm wondering what has changed to cause this error. Any ideas?</div>

**Comment by jcorporation** [comment]
@avalx: can you please test devel?

**Comment by avalx** [comment]
I still get the same error!

**Comment by jcorporation** [comment]
Can you attach the complete build log?

**Comment by avalx** [comment]
Well I only get this message when trying to build the package:

# ./build.sh pkgrpm
error: line 46: %package debuginfo
: package mympd-debuginfo already exists

Any other way to get the log?

**Comment by jcorporation** [comment]
I pulled a fedora docker image and tried it myself. Should now work.

**Comment by avalx** [comment]
Yes, it does 👍 
Thanks for yout quick solution!
