### ISSUE TITLE
'Goto playing song' button broken

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#892]
myMPD version: v10.1.2 (container devel: `sha256:5d75dcfa6b99b4e9ed2bdbe617d7377c3da24891e060ea3f4b2e84220c3b3ad5`)

**Describe the bug**

Pressing 'Goto playing song' results in `Javascript Error`.

**To Reproduce**

1. Go to 'Queue'
2. Click on 'Goto playing song' (with a track already playing)
4. See error: `TypeError: document.querySelector(...) is null`

**Server plattform (please complete the following information):**
 - OS: Fedora
 - OS version: 36
 - Plattform: x86_64
 - MPD version: 0.23.9

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Fedora
 - Browser: Firefox
 - Browser version: 106.0.3

**Additional context**

Unrelated to the bug itself but it should be (audio/music) 'track' rather than 'song' as the audio track can be comprised only of instrumentals.

**Comment by jcorporation** [comment]
Fixed in the devel.
