### ISSUE TITLE
Erratic playback progress tracking

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#893]
myMPD version: v10.1.2 (container devel: `sha256:5d75dcfa6b99b4e9ed2bdbe617d7377c3da24891e060ea3f4b2e84220c3b3ad5`)

**Describe the bug**

Switching an already playing track by clicking in another track results in erratic playback progress tracking.

**To Reproduce**

1. Go to 'Queue'
2. Start playing a track
3. Switch to another track by clicking
4. See erratic progress tracking.

**Screenshots**

![image](https://user-images.githubusercontent.com/59268455/202254562-44527143-f7fc-4fe2-9a16-76239b5fb7ea.png)

**Server plattform (please complete the following information):**
 - OS: Fedora
 - OS version: 36
 - Plattform: x86_64
 - MPD version: 0.23.9

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Fedora
 - Browser: Firefox
 - Browser version: 106.0.3

**Additional context**

This erratic progress is cleared when an audio track manages to finish without interruption.

**Comment by jcorporation** [comment]
I could not reproduce your issue with current devel version ([a01fa27](https://github.com/jcorporation/myMPD/commit/a01fa270286477e5e9acccd3c6e48d9e756b5f8d)).

**Comment by dgcampea** [comment]
> Are there any javascript errors in the browser console?

None.

Might be worth to mention but I did tweak 'Playback settings' under Queue:
![image](https://user-images.githubusercontent.com/59268455/202478266-3a24c0be-064c-4014-a3f5-a5ac1abd081b.png)

**Comment by dgcampea** [comment]
Interesting, I've just pulled the latest devel container (sha256:fadcdc8649979efd7596e63009a636fdc979c193e3cadbaee146722d659be7e0) and it doesn't seem to happen anymore.

Either it's something depending on state or it was recently fixed in the meantime.
