### ISSUE TITLE
I can't set mixramp values from settings

### ISSUE THREAD

**Issue by archphile** [jcorporation/myMPD#9]
Hi Jcorporation,

I am trying to understand how mixramp works, mainly in order to be able to disable it (finding values that do not affect music reproduction).

For some reason on the web interface settings, both Mixramp DB and Mixramp delay have the value of **3168124928** (the number changes from time to time). I am trying to set ex. -17dB and 2sec delay (I don't know if these settings make sense btw )and nothing happens (When I revisit settings I get the same 316... value), while setting these commands via mpc commands, I get the job done, confirming it with the mpd.log.

Just to clarify, I can't understand from the documentation if mixramp package has to be installed or if MPD does the job itself:
https://www.musicpd.org/doc/protocol/playback_option_commands.html

I need to find a value for DB and a value for delay to set so that I ensure it does not affect anything.. 

The reason I need these values, is because whenever I go to settings and exit by saving, myMPD always sends replaygain, crossfade and mixramp and all the other commands found there, even If anything is changed.

**Example:**

I go to mympd settings and having everything else disabled, I just set mixramp at -17dB and 2 sec delay. The mpd output is the following:

```
Jun 04 16:00 : client: [4] process command "consume "0""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "random "0""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "single "0""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "repeat "0""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "replay_gain_mode "off""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "crossfade "0""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "mixrampdb "3894939648.""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "mixrampdelay "3894939648.""
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "status"
Jun 04 16:00 : client: [4] command returned 0
Jun 04 16:00 : client: [4] process command "outputs"
Jun 04 16:00 : client: [4] command returned 0
```

FYI, I tested with both latest Firefox and Chromium under Archlinux.

Regards,

Michael

**Comment by jcorporation** [comment]
I found a bug in setting this two values. This can also be the issue for your strange numbers.

I dont think that you must install anything to use mixramp. Only the files must be appropiate taged with the mixramp tools. But I not tried these.

**Comment by archphile** [comment]
With latest code, I can put different values, but I noticed that when I set mixrampdelay value to 0, although it sends the correct command, it stores value -1 on the setting cell.

Last but not least, based on the documentation:

**mixrampdelay {SECONDS}**

Additional time subtracted from the overlap calculated by mixrampdb. A **value of "nan"** disables MixRamp overlapping and falls back to crossfading. 

I tested with mpc and it accepts the **mpc mixrampdelay nan** command, so I believe that the web interface should accept **nan** entry and in addition this value to be the default when someone is visiting the settings for the first time.

Regards,
Mike

**Comment by jcorporation** [comment]
I tested it with my mpd and a positive value for mixrampdelay is set and displayed correctly (with myMPD and mpc). A value of 0 sets mixrampdelay to -1 (with myMPD and mpc), which is equivalent to "nan".

I looked in the code of mpc and the header files of mpd:
/**
 * Returns mixrampdelay setting in seconds.  Negative means mixramp is
 * disabled.
 */

**Comment by archphile** [comment]
With your latest code, I still can't give a mixrampdelay 0 using MPD 0.20.20 and mpc 0.30 via myMPD, while via terminal and mpc commands it can accept the value of 0.

Again, it's not that I want to set it to 0!  I was just investigating for a possible bug

If you can confirm that 0dB and -1 disables mixramp then it's totally fine by me and issue is resolved for me.

Thanks!
