### ISSUE TITLE
Context menu appears offscreen on mobile

### ISSUE THREAD

**Issue by mirutoyoshi** [jcorporation/myMPD#907]
myMPD version: 10.1.3

On mobile, clicking to open the context menu in the track listing view results in the context menu appearing offscreen (towards the top of the page). Tested on Andorid in both Firefox and Chrome.

**To Reproduce**

1. Select an album
2. In the tracklist, click on 'hamburger'
3. Context menu appears above track/title/duration etc headers
4. When scrolled-down the page, the menu is offscreen

**Expected behavior**

Context menu should always appear onscreen.

**Screenshots**
Sorry for the blury webcam!
![context_menu_issue](https://user-images.githubusercontent.com/39650740/204133135-4ce00bbe-5d6c-47ea-9c58-cd4c058f474e.jpg)

**Server plattform (please complete the following information):**
 - OS: Arch ARM
 - OS version: rolling, current
 - Plattform: Raspberry Pi
 - MPD version: 0.23.10

**Client plattform (please complete the following information):**
 - Device: Android phones
 - OS: Android
 - Browser: Both Chrome and Firefox
 - Browser version: Unknown

**Debug logs (please attach if it can be useful)**
None relevant?
 
**Configuration (please attach if it can be useful)**
[mympd_config.tar.gz](https://github.com/jcorporation/myMPD/files/10098179/mympd_config.tar.gz)
[mympd_state.tar.gz](https://github.com/jcorporation/myMPD/files/10098183/mympd_state.tar.gz)

**Additional context**

**Comment by jcorporation** [comment]
Fixed in the devel branch.
