### ISSUE TITLE
myMPD cannot start anymore

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#91]
**Describe the bug**
myMPD cannot start. Neither as a service or through terminal command

**To Reproduce**
1. Build myMPD with ./mkrelease.sh
2. try to start it.
3. See error

**API request (3): {"cmd":"MPD_API_PLAYER_CURRENT_SONG"}
Segmentation fault (core dumped)**

**Expected behavior**
Start normally

**Screenshots**

![mympd](https://user-images.githubusercontent.com/18086896/52170024-9a38fd00-274a-11e9-84f2-811996cb4545.jpg)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser  Firefox
 - Version latest

**Additional context**
Everything played fine until this commit:

https://github.com/jcorporation/myMPD/commit/26eeffb3aece6fb824aecc1fb9a4a2ff6e777a69

after that you fix the memory leaks and from this commit:

https://github.com/jcorporation/myMPD/commit/d1959e841895a26cda8f6807809c8332186b479c

i cannot start myMPD.

**Comment by Emilot** [comment]
I nailed it down :)

If i change back these lines:

        **_char *value = mpd_client_get_tag(song, mpd_tag_name_parse(current_tag->data)); \
        len += json_printf(&out, "%Q: %Q", current_tag->data, value); \
        if (strncmp(value, "-", 1) == 0) { free(value); } \_**

with this(the previous one):

         **_len += json_printf(&out, "%Q: %Q", current_tag->data, mpd_client_get_tag(song, mpd_tag_name_parse(current_tag->data))); \_**

at mpd_client.c file

from this commit (it is the first change)...

https://github.com/jcorporation/myMPD/commit/d1959e841895a26cda8f6807809c8332186b479c

everything is build perfect!

**Comment by jcorporation** [comment]
You are playing from a stream?

**Comment by Emilot** [comment]
I am playing a radio station, yes.

**Comment by jcorporation** [comment]
Commit  4a0315b should fix this issue

**Comment by Emilot** [comment]
Perfect!

Thank you JC :)
