### ISSUE TITLE
Ability to disable listening on plain HTTP

### ISSUE THREAD

**Issue by MichaIng** [jcorporation/myMPD#914]
#### Is your feature request related to a problem? Please describe:

- In case a custom port is used, with SSL enabled, listening on plain HTTP is basically obsolete. One must define the port explicitly anyway and hence the default port 80 => 443 redirect which still has some point with older browsers (which do not attempt HTTPS connections first OOTB), doesn't give any benefit.
- The plain HTTP port remains unused, but blocks a code to be used by other applications. Currently, using any invalid setting, the default `80` is used.

#### Describe the solution you'd like:

- The ability to disable listening on plain HTTP, e.g. with a special value `0` of the http_port setting.

**Comment by jcorporation** [comment]
Implemented for the v10.2.0 release. Set `http_port` to `0` to disable listening for plain http requests.

**Comment by MichaIng** [comment]
Awesome, many thanks for the quick implementation 🚀.

**Comment by jcorporation** [comment]
Worth a note:
If http_port is disabled: The MPD curl plugin must trust the myMPD CA or certificate checking must be disabled. MPD fetches webradio playlist with http(s) from myMPD webserver.

**Comment by MichaIng** [comment]
Good hint. I guess that is not inherently true for the self-signed certificates created by myMPD itself if no cert is present.

**Comment by jcorporation** [comment]
Right, the user must import the `/var/lib/mympd/ssl/ca.pem` file in the trust store for MPD.

**Comment by MichaIng** [comment]
Just in case anyone lands here:
```sh
mkdir -p /usr/local/share/ca-certificates
ln -sf /var/lib/mympd/ssl/ca.pem /usr/local/share/ca-certificates/myMPD_CA.crt
update-ca-certificates
```
To revert:
```sh
rm /usr/local/share/ca-certificates/myMPD_CA.crt
update-ca-certificates -f
```

**Comment by MichaIng** [comment]
@jcorporation 
There is no way to have `/var/lib/mympd/ssl/ca.pem` pre-created without actually starting myMPD, is it? I'm thinking about how to automate this best.

**Comment by jcorporation** [comment]
Right, at the moment there is no way. myMPD v10.2.0 will create the certificates with `mympd -c`. 

It would be cool enhancement for dietpi if it maintains an own local ca and certificates and installs this for all services with ssl support. So that a user must import only one additional ca certificate.

**Comment by MichaIng** [comment]
Ah great. Yeah I was thinking about configuring HTTPS more consequently by default on DietPi provided web applications and then ship a self-signed cert or use the one obtained from Let's Encrypt, if present. But I need to think through it a little and at best add some new tool to manage the certificate. Thought about `dietpi-https` to merge self-signed cert generation/install with web apps, with what `dietpi-letsencrypt` currently does, at best with `acme.sh` (something lighter) instead of `certbot`.

**Comment by dgcampea** [comment]
> Implemented for the v10.2.0 release. Set `http_port` to `0` to disable listening for plain http requests.

I don't like this idea of using `0` to indicate http as disabled since that is a valid port number[^1], though its a reserved one and many implementations like to assume it's an illegal one or use it for other purposes[^2].

IMO this should be controlled in the same way as it's done with https, through a `http_enabled` = `true|false`.

[^1]: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
[^2]: https://daniel.haxx.se/blog/2014/10/25/pretending-port-zero-is-a-normal-one/

**Comment by MichaIng** [comment]
What about `-1`? However, if `0` is reserved and hence cannot/should not be applied to any application, practically it is fine (doesn't make a difference) to use it as disable flag, and it is more a documentation question than a problem.

Redis server btw does the same, just to show that it is not something totally uncommon myMPD does:
> ```
> # If port 0 is specified Redis will not listen on a TCP socket.
> ```

**Comment by dgcampea** [comment]
> Redis server btw does the same, just to show that it is not something totally uncommon myMPD does:
> 
> > ```
> > # If port 0 is specified Redis will not listen on a TCP socket.
> > ```

The second link talks about this.

I still think doing things "outside of spec" unnecessarily is a source for future headaches.

**Comment by MichaIng** [comment]
> What about `-1`?

Just as an alternative to your suggestion which does not require a new config key.

**Comment by jcorporation** [comment]
For consistency reasons it will be better to add a http = true|false config key.
