### ISSUE TITLE
debian package error 

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#917]
myMPD version: 10.1.5 devel 4e378d0a3cab01732f98ff432cbe89221c518e9a

**Describe the bug**

```
Preparing to unpack mympd_10.1.5-1_armel.deb ...
Unpacking mympd (10.1.5-1) over (10.1.3-1) ...
Setting up mympd (10.1.5-1) ...
Removing obsolet mympd user and group
groupdel: cannot remove the primary group of user 'mympd'
dpkg: error processing package mympd (--install):
 installed mympd package post-installation script subprocess returned error exit status 8
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
 mympd
```

I expect the issue to be in the postint file, on line 12.
The reason it fails is because it tries to delete the mympd group before the mympd user, which would leave the user without primary group, which is not allowed.
Putting line 13 before line 12 should fix the error.

```
# grep groupdel * -nrC 2
contrib/packaging/debian/postinst-10-else
contrib/packaging/debian/postinst-11-    echo "Removing obsolet mympd user and group"
contrib/packaging/debian/postinst:12:    ! getent group mympd > /dev/null || groupdel mympd
contrib/packaging/debian/postinst-13-    ! getent passwd mympd > /dev/null || userdel mympd
contrib/packaging/debian/postinst-14-fi

```

nb: why try to remove "obsolete mympd user & group" when they are still used in the systemd init script for the daemon ?
Which user/group should the daemon run as ?

**Comment by jcorporation** [comment]
myMPD uses a DynamicUser an do not need an explizit mympd user and group anymore: https://github.com/jcorporation/myMPD/pull/875

Removing the user is the best way to enforce this: https://github.com/jcorporation/myMPD/issues/912

**Comment by tsunulukai** [comment]
After this update, it now fails because it can't remove the user while the mympd service is running with that user's identity (which will most likely always be the case).

```
# dpkg -i builds/bullseye-amd64/mympd_10.1.5-1_amd64.deb
(Reading database ... 164312 files and directories currently installed.)
Preparing to unpack .../mympd_10.1.5-1_amd64.deb ...
Unpacking mympd (10.1.5-1) over (10.1.5-1) ...
Setting up mympd (10.1.5-1) ...
Removing obsolet mympd user and group
userdel: user mympd is currently used by process 3403680
dpkg: error processing package mympd (--install):
 installed mympd package post-installation script subprocess returned error exit status 8
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
 mympd


# systemctl stop mympd

# dpkg -i builds/bullseye-amd64/mympd_10.1.5-1_amd64.deb
(Reading database ... 164312 files and directories currently installed.)
Preparing to unpack .../mympd_10.1.5-1_amd64.deb ...
Unpacking mympd (10.1.5-1) over (10.1.5-1) ...
Setting up mympd (10.1.5-1) ...
Removing obsolet mympd user and group
Processing triggers for man-db (2.9.4-2) ...
```

So the script could either kill all processes running as mympd before trying to remove the user (probably a BAD idea), or just attempt to stop the mympd service before removing the mympd user.

**Comment by jcorporation** [comment]
Should be fixed with above commit (devel branch).

**Comment by tsunulukai** [comment]
Yep, that did it !
nb: one would probably expect the service to be restarted after the installation, but if the systemd unit file had been changed, systemctl must be reloaded first.

```
systemctl daemon-reload
systemctl mympd restart
```
