### ISSUE TITLE
musl + buildroot = problem

### ISSUE THREAD

**Issue by mistepien** [jcorporation/myMPD#92]
Hello, I try co compilie mympd in buildroot with musl (using ympd template).
This is what I got:

> >>> mympd v1.3.0 Building
PATH="/root/buildroot-2019/buildroot/output/host/bin:/root/buildroot-2019/buildroot/output/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin"  /usr/bin/make -j2  -C /root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/
make[1]: Entering directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make[2]: Entering directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make[3]: Entering directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
Scanning dependencies of target mympd
make[3]: Leaving directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make[3]: Entering directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
[ 18%] Building C object CMakeFiles/mympd.dir/src/main.c.o
[ 18%] Building C object CMakeFiles/mympd.dir/src/global.c.o
In file included from /root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/global.c:32:
/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/tiny_queue.h:32:5: error: unknown type name ‘pthread_mutex_t’
     pthread_mutex_t mutex;
     ^~~~~~~~~~~~~~~
/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/tiny_queue.h:33:5: error: unknown type name ‘pthread_cond_t’
     pthread_cond_t wakeup;
     ^~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/mympd.dir/build.make:76: CMakeFiles/mympd.dir/src/global.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/mympd.dir/all] Error 2
make[2]: Leaving directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make[1]: *** [Makefile:130: all] Error 2
make[1]: Leaving directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make: *** [package/pkg-generic.mk:233: /root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/.stamp_built] Error 2

**Comment by jcorporation** [comment]
It seems thats the pthreads library is missing in your build environment.

**Comment by mistepien** [comment]
Could you try out to compile MyMPD on musl-based system like alpine?

https://wiki.musl-libc.org/faq.html
https://wiki.musl-libc.org/design-concepts.html

I'm not sure is there separate pthreads library available at all.

**Comment by jcorporation** [comment]
Unfortunately I have no access to a musl-based system.

What do you mean with 
> using ympd template

Can you try to comment out line 22 in src/main.c `#define _GNU_SOURCE`?

**Comment by mistepien** [comment]
I think that nothing has changed:

> [  9%] Building C object CMakeFiles/mympd.dir/src/global.c.o
[ 18%] Building C object CMakeFiles/mympd.dir/src/main.c.o
In file included from /root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/global.c:32:
/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/tiny_queue.h:32:5: error: unknown type name ‘pthread_mutex_t’
     pthread_mutex_t mutex;
     ^~~~~~~~~~~~~~~
/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/tiny_queue.h:33:5: error: unknown type name ‘pthread_cond_t’
     pthread_cond_t wakeup;
     ^~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/mympd.dir/build.make:76: CMakeFiles/mympd.dir/src/global.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/main.c: In function ‘main’:
/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/main.c:387:9: warning: implicit declaration of function ‘pthread_setname_np’; did you mean ‘pthread_setcanceltype’? [-Wimplicit-function-declaration]
         pthread_setname_np(mpd_client_thread, "mympd_mpdclient");
         ^~~~~~~~~~~~~~~~~~
         pthread_setcanceltype
/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/src/main.c:387:9: warning: nested extern declaration of ‘pthread_setname_np’ [-Wnested-externs]
make[3]: Leaving directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/mympd.dir/all] Error 2
make[2]: Leaving directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make[1]: *** [Makefile:130: all] Error 2
make[1]: Leaving directory '/root/buildroot-2019/buildroot/output/build/mympd-v1.3.0'
make: *** [package/pkg-generic.mk:233: /root/buildroot-2019/buildroot/output/build/mympd-v1.3.0/.stamp_built] Error 2

Alpine is available as ready-to-use system:
http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86/alpine-minirootfs-3.9.0-x86.tar.gz
http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-minirootfs-3.9.0-x86_64.tar.gz

this tailored for chroot. All you have to do is set nameserver in /etc/resolv.conf and you can install packages.

apk update
apk search libc
apk search gcc
apk add gcc
apk add mc

and so on.

Musl is not some experiment, this libc is used on many embedded systems like eg. OpenWRT. MPD+MyMPD is made for embedded systems because they do not need a lot of resources.

**Comment by jcorporation** [comment]
Thanks for your hint. I figured out the problem and fixed it in the devel branch. I had to include the pthread header in all source files that include tiny_queue.h.

Can you give it a try?

Needed dependencies:
```
apk add gcc cmake libmpdclient make libmpdclient-dev musl-dev openssl-dev openssl linux-headers
```

**Comment by jcorporation** [comment]
Fixe is now in master. I am closing this issue. Don't hesitate to reopen it, if it don't works for you.
