### ISSUE TITLE
LUA script regression

### ISSUE THREAD

**Issue by pgzh** [jcorporation/myMPD#925]
myMPD version: 10.1.5

**Describe the bug**

Since v10.1 my LUA script to shut down the machine running mympd does no longer work.

**To Reproduce**

1. Create LUA script /var/lib/mympd/scripts/poweroff.lua:
-- {"order":1,"arguments":[]}
output = mympd.os_capture("sudo /usr/sbin/shutdown -h now")
return output

2. Modify /etc/sudoers to include
mympd   ALL=NOPASSWD: /usr/sbin/shutdown

2. Execute the script

**Expected behavior**

Machine shutting down.

**Screenshots**

N/A

**Server plattform (please complete the following information):**
 - OS: Raspbian
 - OS version 11.5
 - Plattform: arm64 / Raspberry Pi 3 B
 - MPD version: 0.22.4

**Client plattform (please complete the following information):**
Not relevant

**Debug logs (please attach if it can be useful)**

Dec 07 20:36:54 jukebox mympd[868]: sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges
 
**Configuration (please attach if it can be useful)**

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 

Please request if required.

**Additional context**

This probably is caused by the removal of the mympd user and relying on systemd for running mympd 'userless'.
So this isn't really a bug but rather a regression (it worked before, now it doesn't) by design.

How could I work around this and get the machine to power off from the mympd menu?

I don't expect any kind of fix or change in mympd for this, but I just can't figure out how to achieve this "poweroff" menu item that was so useful. Maybe you can give me a tip / suggest a possible solution or workaround.
I also know there is a mympd distro based on Alpine Linux that runs in RAM and can be powered off without risking filesystem corruption. But since I have rotary encoders, buttons and a touch display attached to the GPIO/Pi with custom software, I actually am hesitant to change from a Debian based distro to an Arch based distro.
Further I would understand if you would decide to close this bug report without further action, but still hope to get a hint to making this work (again).

**Comment by jcorporation** [comment]
This is discussed already: https://github.com/jcorporation/myMPD/discussions/916
