### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#926]
10.1 and onwards (i think that is where i started).

Good day, Jürgen - i am having some trouble with the changes to the build script.

DESTDIR="/usr/local" ./build.sh

Before, i had a local installation in /usr/local/bin - now it puts mympd in /usr/local/usr/bin and gives me error messages about /var not being writable.

Notice, i run it as local user with /usr/local writable the old Debian way, but it always used to work, so - what am i doing wrong?

Thank you in advance, of course!

Bo

**Comment by jcorporation** [comment]
Sure you did it in the past with `DESTDIR`? You must set `CMAKE_INSTALL_PREFIX` to `/usr/local`. This was not changed.

```
cmake -B release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_BUILD_TYPE=Release .
make -C release
make -C release install
```
