### ISSUE TITLE
Startup error after upgrading from v10 to v10.1.6

### ISSUE THREAD

**Issue by john-** [jcorporation/myMPD#929]
myMPD version: v10.1.6

myMPD builds and install without error.  However, at startup this error occurs:

```
Dec 14 13:20:05 frontaudio systemd[1]: Started myMPD server daemon.
Dec 14 13:20:06 frontaudio mympd[1062]: NOTICE   mympd     Cache dir: "/var/cache/mympd"
Dec 14 13:20:06 frontaudio mympd[1062]: NOTICE   mympd     Work dir: "/var/lib/mympd"
Dec 14 13:20:06 frontaudio mympd[1062]: ERROR    mympd     Config dir: creating "/var/lib/mympd/config" failed
Dec 14 13:20:06 frontaudio mympd[1062]: ERROR    mympd     File exists
Dec 14 13:20:06 frontaudio mympd[1062]: Exiting erroneous, thank you for using myMPD
Dec 14 13:20:06 frontaudio systemd[1]: mympd.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 13:20:06 frontaudio systemd[1]: mympd.service: Failed with result 'exit-code'.
```

**To Reproduce**

1. Installed reference version of mymPD
2. execute "systemctl start mympd"

**Expected behavior**

myMPD retains my courrent configuration and starts without error.

I would like to retain my configuration so I am hesitant to delete the "config" directory.

**Client plattform (please complete the following information):**
 - Device:Ocdroid C2
 - OS: Ubuntu 18.04
 - Browser: Not applicable
 - Browser: Not applicable

**Comment by jcorporation** [comment]
This is a known issue, that is triggered by the new systemd unit. Simply remove the static myMPD user or run `chown -R mympd /var/lib/mympd`.

#912
