### ISSUE TITLE
Wiki: Add section for nginx & apache reverse proxy

### ISSUE THREAD

**Issue by CultofRobots** [jcorporation/myMPD#93]
**Wiki: Add section for nginx & apache reverse proxy**

Should include the following:
* Basic examples with proxypass / proxypassreverse
* Example with Basic auth:
```   
      AuthName "mympd user"
      AuthUserFile /etc/apache2/.passwds/mympd
      Require valid-user
```

Could also include example with limiting access to local network. For example, in apache
`Require ip 192.168.1.0/24`

Nothing fancy, just the basic "This is the minimal needed to make it work".

Related: #29

**Comment by jcorporation** [comment]
If you like, you can provide here the details for nginx and apache configuration. I will gladly integrate this in the wiki.

**Comment by CultofRobots** [comment]
Except I haven't gotten it to work properly, though I only spent about 2 minutes on it and haven't had a chance to get back to it yet. Positive I had websocket proxypass wrong. If I do get around to it this weekend I'll be more than happy to post the details for at least apache.

**Comment by CultofRobots** [comment]
Here's an entry for subdomain (mympd.example.com) on apache2. It's a lot more complicated to do it on example.com/mympd. I'll do one for nginx when I get around to setting it up on another system. Attachedtext file with the markdown:
[mympd_proxy.txt](https://github.com/jcorporation/myMPD/files/2897104/mympd_proxy.txt)


## Proxy through Apache2

To access mympd behind apache2 enable mod_proxy if not already enabled:
`a2enmod mod_proxy`

Create a virtual host and add the following:
```
ProxyRequests Off 
ProxyPreserveHost on
ProxyVia On

<Location "/">
  ProxyPass http://127.0.0.1:8080/
  ProxyPassReverse http://127.0.0.1:8080/
</Location>

<LocationMatch "/ws/?">
  ProxyPass ws://127.0.0.1:8080
  ProxyPassReverse ws://127.0.0.1:8080
</LocationMatch>
```

## Basic Password Authentication

To add basic password authentication create a new htpasswd file 
`sudo htpasswd -c <path/to/htpasswd/file> <username to access mympd>`

Or append an existing htpasswd file
`sudo htpasswd <path/to/htpasswd/file> <username to access mympd>`

for example:
`sudo htpasswd -c  /etc/apache2/.htpasswds mympd`

Then add the following to your mympd Location in your apache virtualhost configuration file

```
AuthType Basic
AuthName "Authentication Required" # or add any type of identifier you prefer
AuthUserFile <path/to/htpasswd/file> # for example /etc/apache2/.htpasswds
Require valid-user
```

for example:
```
<Location "/">
  AuthType Basic
  AuthName "Authentication Required" # or add any type of identifier you prefer
  AuthUserFile <path/to/htpasswd/file> # for example /etc/apache2/.htpasswds
  Require valid-user

  ProxyPass http://127.0.0.1:8080/
  ProxyPassReverse http://127.0.0.1:8080/
  </Location>
```
See https://wiki.apache.org/httpd/PasswordBasicAuth for more information

## Simple Access Control
To limit acces to mympd  to the local network, add the following to the location directive adjusting for your own network:

```
Require host localhost 
Require ip <ipaddress>
Require ip <ip range/netmask> # ex 192.168.1.0/24
```
See https://httpd.apache.org/docs/2.4/howto/access.html for more information

## Full Example Config
```
<VirtualHost *:80>
  ServerName mympd.example.com

  ProxyRequests Off
  ProxyPreserveHost on
  ProxyVia On

  <Location "/">
    Require host localhost
	Require ip 192.168.1.0/24
	AuthType Basic
	AuthName "Authentication Required"
	AuthUserFile /etc/apache2/.passwds/mympd
	Require valid-user

    ProxyPass http://127.0.0.1:8080/
	ProxyPassReverse http://127.0.0.1:8080/
  </Location>

  <LocationMatch "/ws/?">
     ProxyPass ws://127.0.0.1:8080
	 ProxyPassReverse ws://127.0.0.1:8080
  </LocationMatch>
</VirtualHost>
```

**Comment by jcorporation** [comment]
Many thanks for this documentation. I created a wiki page: https://github.com/jcorporation/myMPD/wiki/Accessing-myMPD-through-Apache2

**Comment by Serede** [comment]
@jcorporation Please allow me to praise your job with this project, it's awesome!

Also, here's my nginx reverse proxy config for myMPD, in case it helps:
``` nginx
location /mympd/ {
    [...]
    proxy_set_header Accept-Encoding "";
    sub_filter_types text/html text/css text/javascript text/xml application/x-javascript;
    sub_filter_once off;
    sub_filter '/css/' '/mympd/css/';
    sub_filter '/js/' '/mympd/js/';
    sub_filter '/assets' '/mympd/assets';
    sub_filter '/api' '/mympd/api';
    sub_filter '/ws' '/mympd/ws';
    sub_filter '/player.html' '/mympd/player.html';
    sub_filter 'href="/' 'href="/mympd/';
}
```

**Comment by jcorporation** [comment]
Thanks a lot. I added your configuration to a new wiki site: https://github.com/jcorporation/myMPD/wiki/Accessing-myMPD-through-Nginx

**Comment by laclaro** [comment]
I could not make it run.

My configuration is as follows
```
upstream mympd {
  server    localhost:8082;
  keepalive 512;
}
...
location /mympd/ {
    proxy_pass http://mympd;
    proxy_set_header Accept-Encoding "";
    sub_filter_types text/html text/css text/javascript text/xml application/x-javascript;
    sub_filter_once off;
    sub_filter '/css/' '/mympd/css/';
    sub_filter '/js/' '/mympd/js/';
    sub_filter '/assets' '/mympd/assets';
    sub_filter '/api' '/mympd/api';
    sub_filter '/ws' '/mympd/ws';
    sub_filter '/player.html' '/mympd/player.html';
    sub_filter 'href="/' 'href="/mympd/';
}
```

It results in
```
myMPD error

Embedded asset /mympd/css not found
```

Could we setup a small working configuration in the wiki?

Best,

Henning
