### ISSUE TITLE
Validation of value for JSON path "$.params.codec" has failed

### ISSUE THREAD

**Issue by pirateradiohack** [jcorporation/myMPD#933]
While trying to save a webradio in my favorites the modal returned this error:

`Validation of value for JSON path "$.params.codec" has failed`

the codec is `AAC+`.

I thought this codec was supported by MPD, but I can't say I'm 100% certain. So if it's supported it means it's "just" a matter of validation.
But if not supported then maybe improving the error message to communicate that would help.

**Comment by jcorporation** [comment]
This is a myMPD issue, not a myMPDos issue.

This seems to be a validation issue only. Leave out the `+` and should work. Will be fixed for the next version.

**Comment by pirateradiohack** [comment]
Great, your workaround works! Thanks.

**Comment by pirateradiohack** [comment]
Regarding your mention of webradiodb, I am curious about the goal of this project.

I see in the README that it aims to be a curated list of radios for myMPD. Nice goal, but wouldn't that be achievable thanks to the great radio-browser.info project? I can see it is even integrated in myMPD.

I think I am missing something here, what would be the purpose of rebuilding another database instead of using and contributing to radio-browser.info?

**Comment by jcorporation** [comment]
The radio-browser.info project has a big quality problem, because of this: https://github.com/segler-alex/radiobrowser-api-rust/issues/49

If you want discuss this further, please open a new discussion.
