### ISSUE TITLE
Upgrade from 10.0 to 10.1 introduce a user setup issue on Debian

### ISSUE THREAD

**Issue by edhelas** [jcorporation/myMPD#939]
myMPD version: 10.1.6

**Describe the bug**

When upgrating from 10.0.3 it seems that the user changes introduced in the new 10.1 were not properly applied

**To Reproduce**

Using raspbian testing. Install mympd_10.0.3-1_armhf.deb then upgrade to mympd_10.1.6-1_armhf.deb

**Expected behavior**

That the package setup properly the new user/group introduced in myMPD 10.1

**Debug logs**

root@edhelas-pi:/home/pi# mympd
11:00:23 WARN     mympd     User "mympd" does not exist
11:00:23 NOTICE   mympd     Cache dir: "/var/cache/mympd"
11:00:23 NOTICE   mympd     Work dir: "/var/lib/mympd"
11:00:23 NOTICE   mympd     Config dir: "/var/lib/mympd/config"
11:00:23 NOTICE   mympd     Setting loglevel to NOTICE
11:00:23 NOTICE   mympd     Starting myMPD 10.1.6
11:00:23 NOTICE   mympd     Listening on http://0.0.0.0:8081
11:00:23 NOTICE   mympd     Serving files from "/var/lib/mympd/empty"
11:00:23 NOTICE   mympd     Droping privileges to user "mympd"
11:00:23 ERROR    mympd     User "mympd" does not exist
11:00:23 ERROR    mympd     Success
Exiting erroneous, thank you for using myMPD

**Comment by jcorporation** [comment]
With systemd myMPD runs with a dynamic user, there is no static `mympd` user anymore.

Try this, to run myMPD as this dynamic user from console:

```
systemd-run -p DynamicUser=yes -p User=mympd -p Group=mympd -p StateDirectory=mympd -p CacheDirectory=mympd /usr/bin/mympd
```

**Comment by MichaIng** [comment]
Is it actually still required to name the user (and group) `mympd`? Outside of the process environment the name has no meaning, so generally I'd assume it being possible and easier to simply skip it.

**Comment by jcorporation** [comment]
This is correct, we can omit `User=` and `Group=`, not only in this command, but also in the service file.

```
systemd-run -p DynamicUser=yes -p StateDirectory=mympd -p CacheDirectory=mympd /usr/bin/mympd
```

**Comment by edhelas** [comment]
This was fixed on my side by adding User= and Group= manually in the systemd file.

**Comment by jcorporation** [comment]
User= and Group= directives and a static mympd user are not needed. If you want to start myMPD manually in a console session you should use systemd-run. All other setups are likely to break with each future update.
