### ISSUE TITLE
mympd -c does not store MYMPD_LOGLEVEL env var

### ISSUE THREAD

**Issue by MichaIng** [jcorporation/myMPD#940]
myMPD version: 10.1.7

**Describe the bug**

While all other environment variables are applied correctly, the log level seems to be ignored and the default `5` is used instead.
```
root@VM-Bullseye:~# export MYMPD_LOGLEVEL=4
root@VM-Bullseye:~# mympd -c
04:00:17 WARN     mympd     User "mympd" does not exist
04:00:17 NOTICE   mympd     Cache dir: "/var/cache/mympd"
04:00:17 NOTICE   mympd     Work dir: "/var/lib/mympd" created
04:00:17 NOTICE   mympd     Config dir: "/var/lib/mympd/config" created
Created myMPD config and exit
Exiting gracefully, thank you for using myMPD
root@VM-Bullseye:~# cat /var/lib/mympd/config/loglevel
5
```

**To Reproduce**

1. `export MYMPD_LOGLEVEL=4`
2. `mympd -c`
3. `cat /var/lib/mympd/config/loglevel`

**Expected behavior**

Loglevel 4 should be applied according to exported `MYMPD_LOGLEVEL=4`.

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: DietPi
 - OS version 8.13 (development version)
 - Plattform: x86_64
 - MPD version: 0.22.6

**Debug logs (please attach if it can be useful)**

**Additional context**

**Comment by jcorporation** [comment]
Fixed in the v10.2.0 branch.

**Comment by jcorporation** [comment]
For v10.2.0 the behavior changed back to old behavior if the user does not exist. 

You should use `systemd-run` to create the initial configuration. This should also work with current v10.1.x versions.

```
systemd-run -t -p DynamicUser=yes -p StateDirectory=mympd -p CacheDirectory=mympd debug/bin/mympd -c
```

**Comment by MichaIng** [comment]
Okay great, will implement the `systemd-run mympd -c` with next DietPi release on 14. January. If you want to release myMPD v10.2.0 earlier, it would be great if you could give me a ping a day before, so I can implement a live patch to adjust the code line for our users between releases 🙂.
