### ISSUE TITLE
Overly restrictive CSP header when used with Stream URI

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#943]
myMPD version: 10.1.6

**Describe the bug**

Streaming from a different domain than mympd fails due to getting blocked by CSP.

**To Reproduce**

1. Go to Settings, Features.
2. Enable Local Playback.
3. Set Stream URI to a domain different from the one running mympd, e.g. have mympd serve over `example.tld` and stream URI as `streams-mympd.example.tld`.
4. See error in console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://streams-mympd.example.tld/flac (“media-src”).
```

**Expected behavior**

CSP header is adjusted to accommodate Stream URI. 

**Server plattform (please complete the following information):**
 - OS: GuixSD
 - OS version: 7c476873e0300711bf92668cf01abd28f7295ead
 - Plattform: x86_64
 - MPD version: 0.23.11

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Fedora Linux
 - Browser: Firefox
 - Browser version: 108.0.1

**Comment by dgcampea** [comment]
I'm getting inconsistent results on this across multiple devices, I suspect this might be caused by some stale browser cache or reverse proxy issues. Leaving it closed for now until I get more confirmation on this.

**Comment by jcorporation** [comment]
`media-src` is set to `*`
