### ISSUE TITLE
Songs are not playing 

### ISSUE THREAD

**Issue by sChUhBiDu** [jcorporation/myMPD#95]
**Describe the bug**
Installed myMPD via DietPi-Software menu. Everything went fine, I can access the webpage and I can see/add mp3 files to queue, BUT when I press play nothing happens. Is there a log file that I can sent to you guys? 

**To Reproduce**
see text above

**Desktop (please complete the following information):**
 - OS: dietpi v6.21.1
 - Browser firefox
 - Version 65.0.1

**Comment by jcorporation** [comment]
Please set loglevel to debug and start mympd in the terminal. The log is printed to stdout/stderr. Please also provide the output of the javascript console of your browser.

**Comment by CultofRobots** [comment]
Does mpd play from command line? `mpc play` If not check `/var/log/mpd/mpd.log` (or wherever your log file is set in /etc/mpd.conf) for any errors.

**Comment by sChUhBiDu** [comment]
Log File says:

Feb 23 11:37 : exception: Failed to open "DietPi Alsa" [alsa]
Feb 23 11:37 : exception: nested: Failed to open ALSA device "default": Permission denied

**Comment by jcorporation** [comment]
It seems it is a problem with mpd, that can't open your alsa device. You should open a bug report for dietpi.
I'm closing this issue now. Feel free to reopen it, if it is really a myMPD problem.
