### ISSUE TITLE
Uncaught TypeError when synced lyric timestamp is reached 

### ISSUE THREAD

**Issue by Hajuskin** [jcorporation/myMPD#951]
myMPD version: 10.2.0 (latest devel-branch docker image, but happens with older versions too)

**Describe the bug**

The first time a song with synced lyrics reaches a timestamp I get this error: 
`Uncaught TypeError: Cannot read properties of null (reading 'classList') (https://192.168.1.3:8084/js/combined.js: 19391)`
It doesn't matter if the synced lyric or the unsynced lyric is displayed. 
Beside that message the display (progress bar, time, synced lyrics) will not update anymore until the next song or you manually advanced the track, but that may rather be caused by displaying the error message then the error itself.

**Comment by jcorporation** [comment]
Above commit should fix this bug.

**Comment by Hajuskin** [comment]
After deleting websites cookies no more error messsages, thank you :)
