### ISSUE TITLE
Latest Debian packages do not contain systemd unit

### ISSUE THREAD

**Issue by MichaIng** [jcorporation/myMPD#955]
myMPD version: 10.2.0

**Describe the bug**

**To Reproduce**

1. Install repo + key: https://download.opensuse.org/repositories/home:/jcorporation/Debian_11/ or https://download.opensuse.org/repositories/home:/jcorporation/Raspbian_11/
2. `apt install mympd`
3. `dpkg -L mympd`

**Expected behavior**

`/lib/systemd/system/mympd.service` exists

**Screenshots**

```console
# dpkg -L mympd
/.
/etc
/etc/init.d
/etc/init.d/mympd
/usr
/usr/bin
/usr/bin/mympd
/usr/bin/mympd-script
/usr/share
/usr/share/doc
/usr/share/doc/mympd
/usr/share/doc/mympd/changelog.Debian.gz
/usr/share/doc/mympd/changelog.gz
/usr/share/doc/mympd/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/mympd-script.1.gz
/usr/share/man/man1/mympd.1.gz
```

**Server plattform (please complete the following information):**
 - OS: DietPi
 - OS version 8.13/8.14 (dev)
 - Plattform: armv6l/x86_64
 - MPD version: 0.22.6

**Debug logs (please attach if it can be useful)**

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
 - Browser network console
 
**Configuration (please attach if it can be useful)**

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 

**Additional context**

The init.d service is installed and hence started by the automatically wrapped systemd unit, but it fails since it required the `mympd` user which does not exist on systemd systems.

**Comment by radiant-radish** [comment]
I have this issue as well on my Raspberry Pi OS build . Prior to my apt update/upgrade everything had been running fine (i.e. myMPD running as a SystemD service, etc). After the upgrade to myMPD 10.2.0 I would appear to have an init.d setup!

**Comment by jcorporation** [comment]
It seems `/usr/lib/systemd/system` does not exist in the OBS build system. The 10.2.0 release removed the fallback check of `/lib/systemd/system`. I readd this check for v10.2.1 and merge it in master also.

**Comment by MichaIng** [comment]
Even on Bookworm (where usr-merged systems are now officially required), the vast majority of packages, including `systemd` itself, use the `/lib` path for systemd units, instead of `/usr/lib`. The first is assured to exist and be backwards compatible via symlink on usr-merged systemd, so it is probably easiest follow that for now:
```console
# cat /etc/debian_version
bookworm/sid
# dpkg -S /usr/lib/systemd/system
grafana, libpam-modules-bin, fail2ban: /usr/lib/systemd/system
# dpkg -S /lib/systemd/system
mariadb-server-10.6, ifupdown, haveged, openssh-server, sudo, systemd-timesyncd, acpid, docker-ce, php8.2-fpm, dpkg, e2fsprogs, php-common, apt, apache2, util-linux, udev, rsync, systemd, containerd.io, cron: /lib/systemd/system
```

**Comment by jcorporation** [comment]
If `/lib/systemd/system` myMPD should install the systemd unit also in this location and not in `/usr/lib/systemd/system`.

**Comment by MichaIng** [comment]
debhelper uses this, so at least default on Debian where packagers are encouraged to use debhelper: https://github.com/Debian/debhelper/blob/master/dh_installsystemd

**Comment by dvzrv** [comment]
@jcorporation `/lib/systemd/system` is *not* the default everywhere.

Distributions such as Arch Linux (also Fedora, etc.) follow a [/usr merge](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/) approach, which means that /lib is a symlink to /usr/lib. Installing files to /lib is an invalid packaging action there.

Please derive the correct location for each distribution using pkg-config (i.e. the output of `pkg-config --variable systemd_system_unit_dir systemd`) using the [pkg_get_variable](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_get_variable) function to not hardcode this value.

**Comment by MichaIng** [comment]
Debian images are btw also usr-merged, and it is enforced/required since Bookworm. No idea why debhelper (the official toolkit used to generate DEB packages for the official Debian repo) still has `/lib` for systemd units (matching also `pkg-config` output), which seems conflicting/inconsistent. Good solution with `pkg-config` 👍.

**Comment by jcorporation** [comment]
Seems /usr/lib/systemd/system will be the better default / fallback if the pkg-config method does not work.

**Comment by MichaIng** [comment]
Well, the reason for this issue was that this directory did not exist on your OBS build system. And even on usr-merged systems, `/lib` always exists. That is what the symlinks are for. So in this regards `/lib/systemd/system` is the better/more compatible default.

Of course the directory could simply be created, if missing.
