### ISSUE TITLE
Extend docs to cover env vars for systemd-run mympd -c

### ISSUE THREAD

**Issue by MichaIng** [jcorporation/myMPD#956]
I recognised that in DietPi, our exported pre-config variables do not apply, as well as the pre-generated `state` directory for setting the playlist and music directories is not writable to the dynamic systemd service.

1. Exported variables are not passed through `systemd-run`, hence they need to be set via `Environment` property:
    ```sh
    systemd-run -p DynamicUser=yes -p StateDirectory=mympd -p CacheDirectory=mympd -p Environment='MYMPD_LOGLEVEL=4 MYMPD_MPD_HOST=/run/mpd/socket MYMPD_HTTP_PORT=0 MYMPD_SSL_PORT=1333' mympd -c
    ```
2. The systemd unit changes the owner of files and directories within `/var/lib/mympd` as long as it is not a symlink yet, but not when it is a symlink already. So creating `/var/lib/mympd/state` after running `systemd-run` isn't usable by myMPD. Either it needs to be created first, or it needs to be `chown`ed to the exact UID of the dynamic service user:
    ```sh
    systemd-run ...
    uid=$(stat -c '%u' /var/lib/mympd/config)
    mkdir -p /var/lib/mympd/state
    ...
    chown -R "$uid" /var/lib/mympd/state
    ```
    Easier of course is to create it before `systemd-run` is executed, i.e. when `/var/lib/mympd` doesn't exist at all.

Point 2 is an edge case, but since the docs mentioned that variables can be used for first start and `mympd -c`, point 1 might be a good addition: https://jcorporation.github.io/myMPD/configuration/configuration-files

**Comment by jcorporation** [comment]
Another issue which is caused by the DynamicUser option of systemd. I am beginning to think about changing it back to a normal system user for simplicity.

**Comment by MichaIng** [comment]
> Another issue which is caused by the DynamicUser option of systemd. I am beginning to think about changing it back to a normal system user for simplicity.

I was thinking the same, or the other way round, I am dropping the idea of moving DietPi software options where we create systemd units ourselves to dynamic user.

On the other hand, this is quite a nice learning curve. There are some implications, but nothing was a deal-breaker so far.

> systemd-run has a `-E` option

Ah nice, I didn't see that. The result is the same, but that one is a little shorter.

> You could also use systemd-run to prepopulate the state directory.

But it would need to be in the same `systemd-run` call to have a matching UID, i.e. needs a shell wrapper then:
```sh
systemd-run -p DynamicUser=yes -p StateDirectory=mympd -p CacheDirectory=mympd -E MYMPD_LOGLEVEL=4 -E MYMPD_HTTP_PORT=0 -E MYMPD_SSL_PORT=1333 bash -c 'mympd -c; mkdir -pm 0700 /var/lib/mympd/state; echo "value" > ...'
```
This the goal is actually to create the states files inside, in a one-liner this becomes unreadable 😄.

> Another possibility would be to enhance myMPD that it can prepoluate the state directory as it does it for the config directory.

I think it would only make sense in combination with new env vars being handled my `mympd [-c]` to pre-set music and playlist dirs, and other web GUI settings. For use (DietPi) it would be nice, but in general it is probably not of so much value as all these can be controlled via web UI.

**Comment by jcorporation** [comment]
> I think it would only make sense in combination with new env vars being handled my mympd [-c] to pre-set music and playlist dirs, and other web GUI settings. For use (DietPi) it would be nice, but in general it is probably not of so much value as all these can be controlled via web UI.

Correct. On the other hand: myMPD reads the music and playlist directory from MPD if it is connected via the mpd socket. Reading the playlist directory requires MPD 0.24 (not yet released). Hence this, the prepopulation of this values will be obsolete in the future.

**Comment by MichaIng** [comment]
Ah good to know. So setting the music directory isn't even required now, if it is set in MPD?

Means, let's forget about point 2. I know now how to do it and changed it in our code accordingly, but will let it fading out when dropping old Debian version with pre-v0.24 MPD in the future.

**Comment by jcorporation** [comment]
> Ah good to know. So setting the music directory isn't even required now, if it is set in MPD?

correct

**Comment by MichaIng** [comment]
I just tested it and the music directory is obtained automatically while the playlists dir is not, showing "None" in MPD connection settings and greyed out the default `/var/lib/mpd/playlists`, just as expected.

However, when I go "Browse" and select "Playlists", it shows them correctly regardless. Also creating/changing a playlist works and creates them in the music=playlist dir. Or does it search playlists in the music dir as well (as those match in DietPi), or as fallback when not defined, or blindly letting MPD manage it?

The only difference I could find so far is that `playlists/` is missing when browsing `https://<ip>:<port>/browse/` or selecting "Browse directories" from collapsing side panel. Not worth the hassle of pre-creating the state dir, IMO. Or are there other downsides when leaving the playlists dir undefined?

**Comment by jcorporation** [comment]
> The only difference I could find so far is that playlists/ is missing when browsing https://<ip>:<port>/browse

Correct, the playlist directory definition is only used for that. All the playlist management is done through the mpd protocol.
