### ISSUE TITLE
Missing Bookmark file

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPD#96]
**Describe the bug**
When trying to add a bookmark mympd complain about "Can't read bookmarks file"

**To Reproduce**
1. Pull latest from github
2. run mkdebian.sh
3. Install the package created
4. Run updated mympd
5. Try to add a bookmark

 - OS: Raspbian

**Additional context**
After manually creating the bookmark file, everything works as expected

ps: thanks for 5.0.0 by the way

**Comment by jcorporation** [comment]
Indeed I forgotten to create this file through the postinstall script. Fixed in devel, through commit ed61951c435226b7ecdf7a857d2108ce8ba0b753.

Adding the first bookmark creates this file anyway.
