### ISSUE TITLE
About Chinese Languages

### ISSUE THREAD

**Issue by dream7180** [jcorporation/myMPD#961]
Recommend rename them back to zh_CN & zh_TW, so that the web browser can recognize them.

**Comment by jcorporation** [comment]
You mean if the language setting of myMPD is auto?

I can add aliases for this to work.

**Comment by dream7180** [comment]
Yes. Auto.

**Comment by jcorporation** [comment]
Added the alias feature to devel. @dream7180: can you test?

**Comment by dream7180** [comment]
I think it will be OK but sorry that I am not able to test...
