### ISSUE TITLE
Volume changes reset Browse page

### ISSUE THREAD

**Issue by dgcampea** [jcorporation/myMPD#969]
myMPD version: 10.2.1

**Describe the bug**

When browsing albums under Browse, performing a volume change (using hardware keys) triggers a refresh and resets the page back to 1.

**To Reproduce**

1. Go to 'Browse'
2. Go to page 2 or higher.
3. Increase/Decrease volume using keyboard volume keys/volume knob.
4. Page refreshes and goes back to page 1.

**Expected behavior**

Volume changes should never affect scrolling or which page is being browsed.

**Client platform (please complete the following information):**
 - Device: Desktop
 - OS: Fedora Linux
 - Browser: Firefox
 - Browser version: 109.0.1

**Comment by jcorporation** [comment]
Is the focus on the search input?

**Comment by dgcampea** [comment]
> Is the focus on the search input?

It is but I've noticed that even if the focus is away from the search input, when you go to the next page the focus is immediately grabbed by the search bar.

**Comment by jcorporation** [comment]
> when you go to the next page the focus is immediately grabbed by the search bar.
This is an intended behavior.

I tested your issue with current devel branch and I can not reproduce it. Refreshes the complete page or only the browse view?

**Comment by dgcampea** [comment]
> I tested your issue with current devel branch and I can not reproduce it. Refreshes the complete page or only the browse view?

Browse view

**Comment by jcorporation** [comment]
Strange, I tested with Linux/Firefox, too.

**Comment by dgcampea** [comment]
Could it be from the `keyup` event listener? VolumeUp/Down triggers it.

**Comment by dgcampea** [comment]
![image](https://user-images.githubusercontent.com/59268455/217334690-e29ae9b5-d675-4aec-9acf-065e5c55fb7b.png)

Breakpoints on `Media` and `Keyboard`. Triggered using the volume knob.

**Comment by jcorporation** [comment]
I added a ignore function for keyup handling for input elements. Can you test it in the devel branch?

**Comment by dgcampea** [comment]
I've tested the devel container image and though not the exact setup I have with the "main instance", it seems to fix it.
