### ISSUE TITLE
Song title not changing at web radio streaming...

### ISSUE THREAD

**Issue by Emilot** [jcorporation/myMPD#97]
**Describe the bug**
Not showing the next song in web radio. 

**To Reproduce**
1. Go to a web radio station
2. Click on station
3. Hit "Play"
4. Wait to change the song. 

**Expected behavior**
Show me the title of the next song and notify me.

PS. In queue the song title change in the normal way, as it should.

Thank you.

**Comment by jcorporation** [comment]
I fixed it quickly in devel.

**Comment by Emilot** [comment]
Thank you JC!

Greetings.
