### ISSUE TITLE
Finishing IME composition with Enter key also clears the search box

### ISSUE THREAD

**Issue by soya-daizu** [jcorporation/myMPD#977]
myMPD version: 10.2.2

**Describe the bug**

Users in CJK regions use IME (Input Method Editor) to input text in their languages. IMEs have their own input state that is separate from the text box, and use Enter key to "exit" the composition and enter the composed text into the text box.

In Firefox, the `keyup` and `keydown` events are also fired during IME composition, meaning that the Enter key that is pressed to finish the composition also triggers myMPD's Enter key behavior in the search box.

This produces undesirable effect that "enters" the filtering condition before user inputs all filtering words if they finish composition in the middle of the text.

This issue does not appear in Chrome as it doesn't fire Enter key events with `keyup` during IME composition.

**To Reproduce**

1. Go to "Browse" or "Search" tab
2. Click on the search box
3. Start typing with IME
4. Enters the composed text with the Enter key
 
**Expected behavior**

It should not clear the search box and enter the filtering condition below the search box. Users should only be able to enter search conditions and clear the search box after the IME composition is ended.

**Server plattform (please complete the following information):**
 - OS: Manjaro Linux
 - OS version: 2023-02-12
 - Plattform: x86_64
 - MPD version: 0.23.12

**Client plattform (please complete the following information):**
 - Device: Laptop
 - OS: Manjaro Linux
 - Browser: Firefox
 - Browser version: 112.0a1

**Additional context**

One solution is to use the [event.isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing) property, but myMPD seems to be using `keyup` instead of `keydown` to detect key presses, and `event.isComposing` with Enter key can only be true in the `keydown` events.

Is using `keyup` instead of `keydown` necessary to produce the current behavior?

If we are sticking with `keyup`, there are events specific to IME composition like [compositionstart](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event) and [compositionend](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionend_event), so maybe we can hold the composition state in the back and ignore the Enter `keyup` while that state is true.

**Comment by jcorporation** [comment]
How can I use the IME input method. I even do not know this.

**Comment by soya-daizu** [comment]
It's straight forward on Windows and macOS but it can be tricky in some Linux distributions. Here are some guides I found about installing Japanese input methods for example:
https://windowsloop.com/type-japanese-in-windows-10/
https://support.apple.com/guide/japanese-input-method/welcome/mac
https://wiki.archlinux.org/title/Input_method

As for installing IMEs on Arch based distributions, I would recommend the `fcitx-mozc` package. There should be similarly named packages in other major distributions as well. Fcitx is like a frontend for different IMEs and Mozc is the actual IME behind it.

If these are too much of work for you and you don't mind not being able to verify the patch, I can try to fix it by myself and make a PR for it.

**Comment by jcorporation** [comment]
> If these are too much of work for you and you don't mind not being able to verify the patch, I can try to fix it and make a PR for it.

That would be great!

**Comment by jcorporation** [comment]
Merges! Many thanks  for the PR.
