### ISSUE TITLE
Fail gracefully if API request fails or is redirected

### ISSUE THREAD

**Issue by sevmonster** [jcorporation/myMPD#984]
myMPD version: 10.1.6

**Describe the bug**

If an API request is redirected or otherwise fails (for example to the `/api/default` endpoint), myMPD does not always seem to handle this gracefully. It would be optimal to always show an error in this event, or try to refresh the page.

In my particular use case, I protect my instance with [authentik](https://goauthentik.io), and when my login session times out, further `POST` requests to the `/api/default` endpoint result in `302` redirects to the outpost URL (i.e. `/outpost.goauthentik.io/start?rd=/api/default`). From there, it attempts to redirect to the login flow on another domain, which causes a CORS error, and the navigation is canceled. myMPD shows no error or other indication that the action has failed. This causes a lot of interesting issues, like progress bars not disappearing on songs after it thinks the next song would have started playing. The whole queue is filled with progress bars of varying lengths. It's quite funny. Unfortunately I don't have an image of it right now.

Rather than just show an error, it would be even more useful to be able to capture if the request was redirected to another location or match some other criteria, and try to reload the page if that happens. This would allow authentik to properly redirect to the login page instead of redirecting the API call. This is not as much of a concern but would be a nice feature to have for people like me with authenticating reverse proxies.

**To Reproduce**

1. Open myMPD
2. Somehow block access to `/api/default` or redirect to another URL
3. Perform an action

**Expected behavior**

Some kind of error message to indicate the API request failed

**Screenshots**

None right now. I will take some next time it happens.

**Server platform:**
 - OS: Alpine Linux
 - OS version edge
 - Platform: x86_64
 - MPD version: 0.23.5

**Client platform:**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Ungoogled Chromium
 - Browser version: 109.0.5414.120

**Comment by jcorporation** [comment]
There should be logged an error in browsers JavaScript console, but right there is notification shown to the user.

**Comment by jcorporation** [comment]
Could you test the v10.3.0 branch?

- 300-399 HTTP response codes should now result on a reload of the whole page
- other error codes should be now notified always to the user

**Comment by sevmonster** [comment]
I just compiled 10.3.0 head, and I am not getting redirected when the API redirects, but I am at least seeing the errors.
![image](https://user-images.githubusercontent.com/16788697/222572682-b311bfd0-411b-4ecf-927e-0e4501c8b230.png)
![image](https://user-images.githubusercontent.com/16788697/222572948-6a36d109-a1de-461d-ac57-c2cdfba1c446.png)

**Comment by jcorporation** [comment]
Strange, the response code in the notification should be the same as in the network log.

**Comment by sevmonster** [comment]
It isn't stopping on the 302 redirect, so perhaps it isn't getting the code and the 0 is because of the CORS error.

**Comment by jcorporation** [comment]
I researched a bit:

302 responses to XHR requests are automatically followed by the browser. This can not be intercepted by JavaScript.

The only way to achieve this is the usage of the newer fetch API.

**Comment by jcorporation** [comment]
Closing this now, migrating to the newer fetch() api is an other topic.
