### ISSUE TITLE
Javascript errors after update

### ISSUE THREAD

**Issue by mirutoyoshi** [jcorporation/myMPD#987]
myMPD version: 10.2.3 (installed from packages with pacman)

After updating, many Javascript errors occur.

**To Reproduce**
1. Open mympd in any browser (Windows Firefox, Chrome & Edge), (Android Firefox & Chrome). 
2. Click button to change view from homescreen - e.g. browse, search, queue
3. Javascript TypeError occurs (various errors)

**Expected behavior**
1. No error ;)

**Screenshots**
On Firefox:
![mympd_firefox](https://user-images.githubusercontent.com/39650740/221380874-3d5d984d-603b-4098-bcfe-135b7166740a.PNG)
On Edge:
![mympd_edge](https://user-images.githubusercontent.com/39650740/221380867-bd914a5e-024f-4763-9490-e58fb593bfa1.PNG)

**Server plattform (please complete the following information):**
 - OS: Arch ARM
 - OS version: Rolling
 - Plattform: ARM (Raspberry Pi 4)
 - MPD version: 0.23.5

**Client plattform (please complete the following information):**
 - Device: Windows PC
 - OS: Windows 10
 - Browser: Firefox / Chrome / Edge
 - Browser version: 110.0 / 110.0.5481.177 / 110.0.1587.56

**Debug logs (please attach if it can be useful)**
[hifi.homenet-1677361559770.log](https://github.com/jcorporation/myMPD/files/10832392/hifi.homenet-1677361559770.log)
[mympd_log.txt](https://github.com/jcorporation/myMPD/files/10832398/mympd_log.txt)
 
**Configuration (please attach if it can be useful)**
[config.tar.gz](https://github.com/jcorporation/myMPD/files/10832402/config.tar.gz)
[state.tar.gz](https://github.com/jcorporation/myMPD/files/10832403/state.tar.gz)
[mpd.conf.tar.gz](https://github.com/jcorporation/myMPD/files/10832406/mpd.conf.tar.gz)

**Additional context**
After rolling back, version 10.1.7 works without errors.

**Comment by jcorporation** [comment]
Occurs this issue only if you click specific home icons or also on the default navigation buttons?

**Comment by mirutoyoshi** [comment]
All the default buttons cause the error to occur. 

I have some home screen shortcuts:
One of them sets up a browse view with some filters - the error does happen with this button. 
The rest just replaces the queue with a webradio - these do not cause any issue (but they do not try to change the view)

![Buttons](https://user-images.githubusercontent.com/39650740/221403974-a8b54d88-7ca0-4770-a20c-7233f8360ae8.PNG)

**Comment by jcorporation** [comment]
> One of them sets up a browse view with some filters - the error does happen with this button.

This is likely the root cause. Some lists are renamed in myMPD 10.2.0. Remove and add this button to solve the issue. Do it from a fresh browser session as myMPD remembers the faulty location for the view.

**Comment by mirutoyoshi** [comment]
Thanks. Looks like that's the casue of the issue. 
Deleting the old home icon has fixed it.
