### ISSUE TITLE
Cover Background

### ISSUE THREAD

**Issue by koflesinge** [jcorporation/myMPD#99]
**Adding the currently playing cover image as a background of the player**
I dont really like the solid color background of mympd and would like a better alternative

**Blurred currently playing cover in cover**
Maybe the cover of the currently played song can be put in background of the whole ui instead of the solid color. Because covers are often 300px wide or less, and having an image in background can be disturbng, maybe a bit of blur on it would make for a nice ever changing background

**Or maybe a user picked picture**
Other than that, just allowing in the settings a custom background picture would be nice

**Comment by jcorporation** [comment]
This should be easy to implement. At the moment you can change the background color to a solid color defined in mympd.conf. I plan to extend this feature, with your proposals. Do you want a stretched and blured coverimage or a blured and repeated coverimage?

**Comment by koflesinge** [comment]
I think it would look better to stretch (while keeping the ratio) and
blur the cover image. This way, people with High-res covers could enjoy
them a bit more.

One thing came to my mind though, what about when there's no cover ?
(like playng a webradio, missing cover, or not playing )

**Comment by jcorporation** [comment]
Is now configurable with background and backgroundfilter options in the theme section of the configuration file. mympd.conf.dist is updated appropriately.
Falls back to default background color, if no cover is found.
