### ISSUE TITLE
Fedora package not installable on Fedora 38

### ISSUE THREAD

**Issue by Guara92** [jcorporation/myMPD#998]
myMPD version: [latest]

**Describe the bug**

Using the Fedora Rawhide repository the installation fail

**To Reproduce**

1. Enable jcorporation Fedora Rawhide or Fedora 37 repository on Fedora 38
2. Try to install mympd

**Additional context**
`sudo dnf install mympd` -> `Error: GPG check FAILED`
`sudo dnf install mympd --nogpgcheck` -> `Error: Transaction test error:
  package mympd-10.2.5-1.1.x86_64 does not verify: Header V3 RSA/SHA256 Signature, key ID xxxx: NOTTRUSTED`

I think this is related to recent change in crypto policies in Fedora 38 more [here](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings3Forewarning2)

**Comment by jcorporation** [comment]
> This is a rejected Change proposal for Fedora Linux.

Seems you must import the signing key or disable checking?

**Comment by Guara92** [comment]
sorry wrong link, in [this](https://fedoraproject.org/wiki/Changes/RpmSequoia) page 
```
For normal usage, the change is quite invisible. The notable exceptions are

Some old, insecure (MD5/SHA1 based) signatures are rejected (this is in line with the stronger crypto settings proposed elsewhere for F38)
Key import may accept some previously rejected keys, in part due to limitations of old parser etc but in particular, the old implementation verifies self-signatures at import time whereas Sequoia verifies them at time of use.
Key import may reject some previously accepted keys due to better validation.
```

dnf say that I already have the key
```
GPG key at https://download.opensuse.org/repositories/home:/jcorporation/Fedora_Rawhide/repodata/repomd.xml.key (0xE895BD7D) is already installed
The GPG keys listed for the "myMPD and myGPIOd (Fedora_Rawhide)" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: mympd-10.2.5-1.1.x86_64
 GPG Keys are configured as: https://download.opensuse.org/repositories/home:/jcorporation/Fedora_Rawhide/repodata/repomd.xml.key
Error: GPG check FAILED
```

**Comment by jcorporation** [comment]
Tried to delete and reimport the key?

**Comment by Guara92** [comment]
thanks deleting an reimporting the key fix the problem.
`rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'` to find the key
`rpm -e [KEY_ID]` to delete the key
